### ISSUE TITLE
Documentation seems to contain several errors due changes in os and process

### ISSUE THREAD

**Issue by edegraaff** [home-assistant/home-assistant.github.io#11093]
Hi, it tried to use this manual to enable lets encrypt on my pi and home assistant. It is a clean install and it failed. I found out the sudo instructions can't be used but need to be sudo on the pi user. Also stopping the ha services  should be done by pi user. The main issue is the current lets encrypt scripts are failing to pull the right software. the apt-get install certbot
 did do the job. 

Could someone update this manual a bit, i think using https will be used more and more.

**Comment by frenck** [comment]
It all depends on the installation methods used.

Could you provide some more information on how you've installed Home Assistant, and which part of the documentation you are trying to apply? (URL).

Thanks 👍

**Comment by altimmons** [comment]
While I know its a work in progress..., this reads a bit like it once existed then was accidentally deleted.

https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/alarm_control_panel.markdown

home-assistant.io/source/_integrations/alarm_control_panel.markdown

https://www.home-assistant.io/integrations/alarm_control_panel/

**Comment by altimmons** [comment]
The Command line help is wrong in several places.
 
also:

https://www.home-assistant.io/docs/configuration/group_visibility/ 

example at the bottom contains what I have eventually figured out related to the old `/states` UI, which I don't know about.

Further, there is a leap that has to be made in implementing Home Assistant for the new user (like myself).  The docs cover initial set up, and then configuration, but I can't quite put it into words yet, there is this missing gulf of info, stuff that seems obvious to veterans, and over which newbies must pass or give up.  Generally speaking, its how to start editing config...yaml.  Not actually how- but what to put in there.

It took me days to realize that everything is an 'integration' and the docs are under  [Here](https://www.home-assistant.io/integrations/).

Over and over I kept finding myself here - (https://developers.home-assistant.io/docs/en/entity_index.html) thinking this is what I needed, but it never explained what I needed, though I read it through a few times.

The obvious answer is for us to contribute to the docs ourselves as a community, and I am in fact taking notes as I go, which will be adapted as needed.  **Perhaps a Wiki format would be more ideal, allowing quicker editing from the community rather than requiring pull requests.**

**Comment by altimmons** [comment]
Actually, I think the CLI errors were mostly in HassOS.  The distinction between HassOS, HassIO, Home Assistant, and Nabu Casa or an Integration is rather fuzzy to us new comers

**Comment by fabaff** [comment]
> While I know its a work in progress..., this reads a bit like it once existed then was accidentally deleted. https://www.home-assistant.io/integrations/alarm_control_panel/

The integration overview pages are no longer as imported as three years ago. 

> The Command line help is wrong in several places.

Yes, the output of the CLI tool was outdated. But I highly doubt that this was a big issue as the `hass -h` always give the current help and in the docs we simply included the output without context.

> https://www.home-assistant.io/docs/configuration/group_visibility/
>
> example at the bottom contains what I have eventually figured out related to the old /states UI, which I don't know about.

There are still a lot of people who are running with the old UI because of speed and customization. We can't remove those information at the moment.

> Further, there is a leap that has to be made in implementing Home Assistant for the new user (like myself). The docs cover initial set up, and then configuration, but I can't quite put it into words yet, there is this missing gulf of info, stuff that seems obvious to veterans, and over which newbies must pass or give up. Generally speaking, its how to start editing config...yaml. Not actually how- but what to put in there.

The "Docs" section covers configuration/advance configuration, automation and other topic which maybe useful. 

> It took me days to realize that everything is an 'integration' and the docs are under Here.

There is a whole section about the usage of `configuration.yaml` file in the Docs section which covers style and points straight to the Integrations.

> Over and over I kept finding myself here - (https://developers.home-assistant.io/docs/en/entity_index.html) thinking this is what I needed, but it never explained what I needed, though I read it through a few times.

There is the end-user and the developer documentation. The link points to the developer documentation. Please use the Devel docs repos for issues.

> Perhaps a Wiki format would be more ideal, allowing quicker editing from the community rather than requiring pull requests.

"Edit this page on GitHub" makes the the documentation pretty much a Wiki.

>  The distinction between HassOS, HassIO, Home Assistant, and Nabu Casa or an Integration is rather fuzzy to us new comers

There is a glossary and a FAQ. If it's not enough then it needs to be extended.
