### ISSUE TITLE
Configurator try to acces Phishing site - Heimdal report it!

### ISSUE THREAD

**Issue by DKAutomater** [home-assistant/home-assistant.github.io#11229]
Hi then i am using Configurator in Hassio. Heimdal is telling me that ace.c9.io is connecting and this site is reported as a Phishing site, guys please fix this!

![image](https://user-images.githubusercontent.com/52005923/69177548-0503cb00-0b08-11ea-95e4-d110bb461ae2.png)

**Comment by frenck** [comment]
The repository and issue tracker for the Configurator can be found here: <https://github.com/danielperna84/hass-configurator>

Nevertheless, I highly doubt this is correct. It looks like a false positive since that website serves the ace editor, which is the editor the Configurator is based on.

Please report is at the above-listed repository.
