### ISSUE TITLE
Zigbee integration overview

### ISSUE THREAD

**Issue by ulope** [home-assistant/home-assistant.github.io#11569]
There are quite a few ways to integrate zigbee devices.
Off the top of my head:

- Tradfri Hub
- Hue Hub
- deCONZ
  - Conbee / Raspbee
- ZHA
  - XBee
  - ConBee / RaspBee
  - EZSP
  - ZiGate
- Zigbee (why does this still exist?)
  - XBee

Similar to Z-Wave there should be a generic Zigbee overview page that links to the various integration options and also links back to that overview from the individual integration docs.

**Comment by frenck** [comment]
This has been discussed before, see: <https://github.com/home-assistant/home-assistant.io/pull/10585>

We should avoid this in general. Since it can create more confusion than it currently solves.

We should not focus on a single problem (Zigbee information at this point), but on the general structure, which is something we are working on right now (the planning part).

I'm going to close this issue for now because of the above-linked PR and the reasoning given in that PR.

**Comment by ulope** [comment]
Fair enough, I did search for issues but missed the PR.

**Comment by frenck** [comment]
Don't worry m8! That happens 👍
