### ISSUE TITLE
It is possible to set incomfort temperature right?

### ISSUE THREAD

**Issue by tomkuijsten** [home-assistant/home-assistant.github.io#11681]
I have a intergas with the incomfort® Internet Gateway. Via the website it exposes, it is possible to set the thermostat setpoint. In the documentation for the incomfort here:

https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/incomfort.markdown

It states that the gateway does not expose any endpoint to change it, but as far as I tested, it does. Am I missing something?

**Comment by frenck** [comment]
Maybe it didn't at the time created and does right now?

However, this is the GitHub issue tracker for our website, on which we log website issues. Your issue is with a Home Assistant integration itself, please raise an issue on the Home Assistant codebase: <https://github.com/home-assistant/home-assistant/issues>.

Thanks! 👍

**Comment by tomkuijsten** [comment]
@frenck thanks for the info, I'll add an issue in the right code base
