### ISSUE TITLE
Rova invalid dates

### ISSUE THREAD

**Issue by ronniebee** [home-assistant/home-assistant.github.io#11687]
I set up ROVA in config yaml as decribed but onlys Bio shows a date. paper etc says  "Invalid date" . what to do?

![image](https://user-images.githubusercontent.com/7029899/72086591-72adc580-3307-11ea-9e0b-a31fad8b7212.png)

**Comment by klaasnicolaas** [comment]
This is the GitHub issue tracker for our website, on which we log website issues. Your issue is with a Home Assistant integration itself, please raise an issue on the Home Assistant codebase: https://github.com/home-assistant/home-assistant/issues. But you can ask also help on our community forum or Discord server.

Thanks! 👍
