### ISSUE TITLE
Yeelight will not set up

### ISSUE THREAD

**Issue by Ryan911199** [home-assistant/home-assistant.github.io#12182]
## The problem

I am attempting to set up yeelights with home Assistent but they come up as home kit devices. When I try to add them they say enter a paring code which does not exist for yeelight.
![562BBC40-71A1-4FBD-89CD-4A243A0A1927](https://user-images.githubusercontent.com/37816894/75313692-c7a38d80-581a-11ea-8126-67e5d62f7d85.png)

**Comment by frenck** [comment]
Hi there @Ryan911199! 


Thanks for raising an issue, however, this is the issue tracker for our website & documentation, not for Home Assistant (Core) itself.

Please raise your issue here:

<https://github.com/home-assistant/home-assistant/issues>

Please be sure to provide all the information that is asked by the issue template presented. Thanks! 👍
