### ISSUE TITLE
About Hassbian for Raspberry Pi version？

### ISSUE THREAD

**Issue by sonwa** [home-assistant/home-assistant.github.io#1266]
Hi,
 Home Assistant Can only be used in "Raspberry Pi 2" Or "Raspberry Pi 3"?
I'm here "Raspberry Pi 1" Hassbian Image,Enter the system but the Home Assistant Not installed successfully.Because I visit "http: // ip-address-of-pi: 8123" did not respond.

**Comment by Landrash** [comment]
This repository is for the documentation of Home Assistant. If you got any questions about the HASSbian image have a look at the [HASSbian ](https://community.home-assistant.io/c/installation/hassbian)section of our [forum](https://community.home-assistant.io/c/installation/hassbian).

To answer your question. I tested the image on a Raspberry Pi B+, Pi Zero, Pi 2 and a Pi 3.
I'll try it on a first gen Pi B at my earliest convenience. If it works it will most likely take quite a bit longer on first boot before HA is available since the estimated time of ~5 minutes is with a Raspberry Pi 3.
I don't have either of the A models or a compute module available to me so I can't test either of those.
