### ISSUE TITLE
 virtual appliance qcow2 link wrong

### ISSUE THREAD

**Issue by whocarezpt** [home-assistant/home-assistant.github.io#13310]
## The problem

Hi,
The link to qcow2 virtual appliance is wrong on installation page https://www.home-assistant.io/hassio/installation/, is linking to a vdi image:
https://github.com/home-assistant/operating-system/releases/download/4.5/hassos_ova-4.5.vdi.gz

Correct link should be:
https://github.com/home-assistant/operating-system/releases/download/4.5/hassos_ova-4.5.qcow2.gz

**Comment by fabaff** [comment]
Looks like that this was fixed with the update to 4.6

- VDI:https://github.com/home-assistant/operating-system/releases/download/3.13/hassos_ova-3.13.vdi.gz
- QCOW2 (beta): https://github.com/home-assistant/operating-system/releases/download/4.6/hassos_ova-4.6.qcow2.gz
- OVA (Beta): https://github.com/home-assistant/operating-system/releases/download/4.6/hassos_ova-4.6.ova
