### ISSUE TITLE
HomeKit integration documentation title should be `HomeKit Bridge` to match Integration UI

### ISSUE THREAD

**Issue by kocsenc** [home-assistant/home-assistant.github.io#13864]
## The problem

The [HomeKit Bridge](https://www.home-assistant.io/integrations/homekit/) integration page should have the title show as `HomeKit Bridge` instead of just `HomeKit` since the integrations on the HA UI show them distinctly: 

<img width="338" alt="image" src="https://user-images.githubusercontent.com/2752396/85941624-cc677380-b8d8-11ea-8668-778070338eaa.png">

This also hints at the fact that there are two different HomeKit integrations.

**Comment by frenck** [comment]
This is actually not a documentation issue. It is synced from the codebase:

<https://github.com/home-assistant/core/blob/dev/homeassistant/components/homekit/manifest.json#L3>

However, the translations have "HomeKit Bridge", which is why it is shown like that in the interface.

This needs to be fixed in the codebase.
