### ISSUE TITLE
How do I get the uuid of a chromecast device?

### ISSUE THREAD

**Issue by marcus13371337** [home-assistant/home-assistant.github.io#14090]
## The problem
Previously (< 0.113.1), when adding a specific list of cast devices to the cast integration you were supposed to provide the ip-address to the device (by setting the host attribute in the configuration). Now when I booted up 0.113.1, I got the message that the host attribute is deprecated and supposed to be replaced by the uuid. As I have no idea how I can find the uuid of a cast device I went to the documentation for the cast integration, but I couldn't get any information on how I could find such uuid. Would it be possible to add some kind of explanation on how you could find this uuid?

Also, I noticed that the example in the [manual configuration](https://www.home-assistant.io/integrations/cast#manual-configuration) also refers to the deprecated host attribute

**Comment by brandoncorry** [comment]
Also curious how to go about the same. I was initially confused by the example showing the deprecated host attribute as well. Hope someone can update the documentation and include a couple ways/best way to get UUIDs.

**Comment by Smoetzak** [comment]
Any update on this? I am wondering as well.

**Comment by OzGav** [comment]
Me three

**Comment by IQndk** [comment]
Same. My integrations does not discover any of my 3 Chromecasts.
And none of the old configurations are working.

**Comment by wwilsman** [comment]
Hey guys! I took a dive and figured this out! Home Assistant uses a python library, [PyChromecast](https://pypi.org/project/PyChromecast/) to interact with Chromecast devices. You can see in their example that you can query for Chromecasts by friendly name, then print the resulting UUIDs.

I’m no python expert, so I wonder if there is a one-liner we might be able to use to accomplish this. I ended up using the python REPL to print the UUIDs and copied them over to my secrets file. Here are the steps I took:

1. SSH into home assistant. (You can do this on your local machine if you prefer. I used an addon that comes with a terminal and did this all from the web interface)
2. Install PyChromecast: `$ pip install pychromecast`
3. Enter the python REPL: `$ python3`
4. Type the following (replacing the list of friendly names with your actual Chromecast names):

    ```python
    import pychromecast
    print(pychromecast.get_listed_chromecasts(friendly_names=["Living Room TV", "Bedroom TV", "Office Chromecast"]))
    ```

Since PyChromecast comes with HA, I wonder if we can skip step 2 by being in the correct docker container?

In any case, I hope this helps y'all along with anyone else finding this issue!

---

Editing to add: you can execute python inline with the `-c` flag. So you should be able to do something like this in lieu of  steps 3 & 4 above: `$ python3 -c "import pychromecast; print(pychromecast.get_....."`

**Comment by OzGav** [comment]
LEGEND!!! Can't believe the docs don't explain how to do this. 

I can also confirm if you have access to the HA docker container then step 2 is not required.

Thanks for solving this issue.

**Comment by OzGav** [comment]
I have added a pull request to the docs to incorporate this. See if it gets approved...

**Comment by Smoetzak** [comment]
Works like a charm!

Mind the name is case sensitive!

Thanks for figuring this out!
