### ISSUE TITLE
met.no hourly forecast

### ISSUE THREAD

**Issue by knfoo** [home-assistant/home-assistant.github.io#14657]
## Missing configuration information

The release notes states that met.no now supports hourly forecast.
But the documentation a description on how that is achieved. 

And the config ui does not allow me to set it in the integration so I assume that I need to do something in the configuration.yaml file but am not sure about that.

**Comment by frenck** [comment]
There is nothing to achieve?
You can activate the entity in the integration, the hourly forecast is disabled by default. Every UI managed entity can be enabled / disabled in Home Assistant.

**Comment by knfoo** [comment]
OK,
Maybe I am confused, where the problem is.
The Weather Forecast Card Configuration does not allow me to set a `mode: hourly`
And the integration does have such option as well.
and if I put this into my configuration.yaml:

```
weather:
  - platform: met
    mode: hourly
```
the configuration is not valid.

So a little hint in the docs as to where you will need to set the `hourly` flag would be very appreciated.

**Comment by knfoo** [comment]
@frenck; maybe you can be so kind to give me a hint more as it seems I do not understand what I need to do, thanks

**Comment by knfoo** [comment]
I got help in Discord.
I needed to search for the disabled entity in the list - but first enable the filter of the disabled entities

**Comment by rccoleman** [comment]
This is pretty confusing for users, and I had to find a forum thread to remind me of the "disabled" entity filter.  The integration card says "2 Entities", but clicking on that only shows a single entity because disabled entities are automatically filtered.  Other than that indirect indication, the only other way to know that the "hourly" entity is disabled is to comb through the logs at INFO to see it mentioned there during startup or during a reload.  Perhaps it would be a better UX if a) ALL entities are shown when clicking on the "entities" link in the Integration card, disabled or not or b) if the integration created a Device, which more clearly shows the entities that are enabled and disabled.

**Comment by frenck** [comment]
@rccoleman Please report feature requests on our forum. Thanks.

**Comment by rccoleman** [comment]
Done: https://community.home-assistant.io/t/make-disabled-entities-more-obvious-and-easier-to-enable/232360
