### ISSUE TITLE
Tesla integration: Provide more information about wakeup and battery

### ISSUE THREAD

**Issue by mabahj** [home-assistant/home-assistant.github.io#16521]
**Feedback**

I've long been concerned if this integration wakes up my car and drain the battery. Also, I've tried to figure out how to intentionally wake up the car. I've now enabled some debugging, reviewed the logs and also found this thread: https://github.com/zabuldon/teslajsonpy/issues/119

I think there are a couple of battery related topics that could be better addressed in the documentation. I am not *confident* that my proposals are correct, so I won't write it in myself. But here's a proposal. (The English can probably be improved, it is not my first language..)

**URL**

https://www.home-assistant.io/integrations/tesla/

**Version**

2021.2.3

**Proposal:**

# Battery impact
* The `scan_interval` determines when to *check* if the car is awake and new information is available, but the tesla integration will *not* wake up a sleeping car during this polling. **(Open question: Will it ever wake up the car during polling?)**
* The car will, however, be woken up when a command is actively *sent to the car*, such as door unlock or turning on the HVAC. It will then also fetch updated information while the car is awake.
* The car can *intentionally* be woken up to fetch recent information by sending a harmless command, for example a lock command. This can be used in automation to for example ensure that updated information is available every morning. (Note that the command must be valid for that specific car model. So locking the frunk of a Model 3 will not wake up that car.)

**Comment by alandtse** [comment]
Yes, this is generally correct. You may want to explain the wake_on_start option will wake the cars when the integration first begins.

> * (Open question: Will it ever wake up the car during polling?)

No.

Some clarification, please consider how to summarize it for the documentation.
- `scan_interval` is the user setting that controls the interval between successive attempts to read info from an awake car. Based on testing 660 was the amount of seconds needed to allow a vehicle to go to sleep.
- The controller object in teslajsonpy will ping Tesla's servers every 60 seconds to determine the state of all connected vehicles. If it determines a vehicle has become awake that was previously asleep, it will query the car, as dictated by `scan_interval`
- There are cases where `scan_interval` will not be followed and this is when we are doing dynamic updates.
  - While driving, the car will be queried every 60 seconds `DRIVING_INTERVAL` until it's parked.
  - After being parked, it will wait at least 600 seconds `IDLE_INTERVAL` before resuming normal scans. This is intended to let the car sleep immediately after detecting a park event.
    - However, if the car sentry mode is on, climate is on, or is charging, it will not enter `IDLE_INTERVAL` time and will continue scans at `scan_interval`. 

Lastly, the update switch was added in to disable the scan_interval entirely. If update switch is not on, it will not perform any updates. Specifically, the update check still happens every `scan_interval` and will only scan a car if the update_switch is on.

I use it in an automation to disable the update_interval once I'm away from a charger for more than 24 hours. This is useful for parking at an airport.

I have been very conservative on polling the car because it costs people real money if the vehicle doesn't sleep and I don't want to risk stranding someone while they're away from home.

Please see https://github.com/zabuldon/teslajsonpy/blob/dev/teslajsonpy/controller.py#L526-L603 and https://github.com/zabuldon/teslajsonpy/blob/dev/teslajsonpy/const.py for more details.

**Comment by frenck** [comment]
Hehe, @alandtse.. The point of feedback, is so you, as a code owner, can actively improve the documentation for your integration 😉

**Comment by alandtse** [comment]
@frenck I get that point, but given this is an open source community, people can help document stuff if they care about it. I'm spending my time trying to solve the MFA issues preventing users logging in. I'd assume users would prefer I choose that over documentation of how it works under the hood. ;)

**Comment by frenck** [comment]
Its alright, @alandtse! Was just checking if that was clear.

And of course, anybody willing to pick this up, please go ahead 🎉
