### ISSUE TITLE
Nuki Software bridge is not supported anymore

### ISSUE THREAD

**Issue by Thomas55555** [home-assistant/home-assistant.github.io#16533]
**Feedback**

The software bridge is not supported anymore my Nuki and the are no more software updates.
Source:
https://nuki.io/de/blog/nuki-news-de/update-zur-nuki-android-bridge-app-das-ende-einer-aera-ist-auch-immer-ein-neuer-anfang/
The link for the software bridge should be removed.

**URL**

https://www.home-assistant.io/integrations/nuki/

**Version**

2021.2.3

**Comment by Donaldini** [comment]
Here is the English article for the German one listed by OP: https://nuki.io/en/blog/nuki-news/update-on-the-nuki-android-bridge-app-with-the-end-of-every-era-comes-a-new-beginning/

I'm not entirely sure what it means because the Nuki app is still present on Android and iOS App stores with updates the past days/weeks, even though there is a deprecation date of 21/01/2021 in the article. I'm not entirely sure what that is about?

I can also confirm this is occuring for me, might be related: #16768

**Comment by frenck** [comment]
This is the issue/feedback tracker for the documentation, but you are reporting an issue with an integration.

Please report issue for integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍
