### ISSUE TITLE
DSM integration already setup when enabling 2-Step verification

### ISSUE THREAD

**Issue by titiviking** [home-assistant/home-assistant.github.io#16626]
**Feedback**

I've let my DSM run without 2SV for a while to keep things simple. Integration was installed in Home Assistant.

I now enabled the 2SV, but the integration does not offer a way to update the crednetials and update the 2SV settings.

How can I setup the Home Assistant integration to accept the 2SV ?

**URL**

https://www.home-assistant.io/integrations/synology_dsm/

**Version**

2021.2.3

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues without documentation, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places. If it turns out to be lacking in the documentation, please, let us know!

Thanks! 👍
