### ISSUE TITLE
Setting up presence detection page doesn't help to setup presence detection

### ISSUE THREAD

**Issue by kyberias** [home-assistant/home-assistant.github.io#16712]
**Feedback**

The page merely lists what is possible but provides no instructions. Documentation would be much more useful if it would actually give guidance.

**URL**

https://www.home-assistant.io/getting-started/presence-detection/

**Version**

2021.2.3

**Comment by frenck** [comment]
It tells about the need for device trackers, e.g., using a supported router, or using the iOS or android app, which would create device trackers. Additionally, it gives an introduction about zones that can be used in automations.

All those cases are linked in the text for more information. I'm not sure what it is you are missing, could you please clarify or suggest what to add to this page?

**Comment by stresskiller** [comment]
it doesn't tell how you should set things up in a logical way starting from scratch.
where to start and in what order.

**Comment by MickW69** [comment]
The step that was missing for me was the need to go into the HA app and enable Geolocation Sensors.

**Comment by frenck** [comment]
> The step that was missing for me was the need to go into the HA app and enable Geolocation Sensors.

That should not be needed? By default, it sets those up.

**Comment by MickW69** [comment]
OK, then I might be still missing something.  I have got everything set up for notifications from zone activity, but they don't trigger.

**Comment by kyberias** [comment]
I think the text would benefit if it explained how HA detects presence. I'm sure it's obvious to you if you already know it. It never states anything explicitly.

For example: "There are different ways of setting up presence detection. Usually the easiest way to detect presence is by checking which devices are connected to the network. "

It tells that there are different ways to set it up and then says that the easiest way is to "check which devices are connected". Now, should I as a user do that or is that automatic? It is not stated clearly.

It can be automatic but that needs to be said.

After installing the app I realized that it somehow magically works automatically but it was a surprise to me.

I still don't understand why the routers are mentioned and under which circumstances I should have a "compatible" router.

**Comment by kyberias** [comment]
BTW, it never explains that you need "device trackers" or even what a device tracker is.

**Comment by bhaywa1** [comment]
@kyberias, I agree. Unfortunately this is a common problem with HA documentation. Home Assistant is an awesome, and very well implemented system, in most cases, and continues to get better. But the documentation is extremely lacking in regard to configuration information for noobs. People are expected to know and understand WTH the documentation is talking about, and in far too many cases, the necessary background and supporting information is assumed, rather than provided. Examples are indeed plentiful in many cases, though generally lean (only including what is absolutely needed), and frequently missing contextual information that is vital for people who are new to HA. But many times examples are completely missing, and we are left to search YouTube or forums to find out how to do what is needed.
In this particular case, the document in question does not provide any information at all about actually setting up Presence Detection. It briefly describes what it is, and gives a couple of vague examples and a couple of different ways it can be used. But nowhere does it actually indicate HOW to do what is needed to set it up. So the title is misleading, and the document is pretty much useless.
@frenck, please don't take this as negative criticism. I know that Home Assitant is a labor of love for a lot of people. And I am deeply appreciative of the work that so many continue to put into making it better. I would love to help beef up the docs, as technical documentation is something that I have a lot of experience with, and I'm good at it. But unfortunately I'm just learning the system myself, and am nowhere near comfortable with adding to the docs to make it easier for noobs (like myself) to set up their systems, not to mention not having a lot of free time to do so. Hopefully I can lend a hand in the near future if that is acceptable.

**Comment by frenck** [comment]
@bhaywa1 lets keep it on topic, if you want to a general discussion about the documentation, please use the community forums.

On your content, this is an open source project, meaning everybody creates what you see, including you. Please feel free to help improve the documentation by writing some 👍

**Comment by kyberias** [comment]
Look, I also appreciate the effort that all the developers put into Home Assistant and I'm happily using it.

The only reason I opened this issue is because I found the page lacking useful information that I needed and the page in question **literally has a link to "Provide feedback"**. :) There are now four users in this thread complaining about the same page. I don't think anyone expects the developers to fix this immediately and rewrite the page but some kind of acceptance would be appreciated and not this kind of downright dismissal of obvious issues.

If the development team does not want feedback and these issues about documentation are a nuisance, perhaps the feedback-link should be removed? I think you are entitled to do that, you have no obligation to fix anything.

I may consider contributing some documentation myself once I learn more about the subject. The current documentation on this particular subject doesn't help much though.

**Comment by frenck** [comment]
@kyberias And thank you for the feedback. If the feedback wasn't accepted, this issue would have been closed already. But this is an open-source project, things like a "development team" do not exists, as the whole community is part of it.

Feedback is left here, if someone wants to pick it up, well, go ahead! That is the magic of open source. The feedback is here to collect those cases, which someone could decide to work on.

**Comment by LucVanDyck** [comment]
What also isn't mentioned is that, when using the app on your phone for presence detection, that you should register with nabucasa.com and add the remote URL to the settings of the app. Otherwise, you always appear to be at home.

**Comment by stresskiller** [comment]
> 
> 
> What also isn't mentioned is that, when using the app on your phone for presence detection, that you should register with nabucasa.com and add the remote URL to the settings of the app. Otherwise, you always appear to be at home.

not sure if that is true , i managed to get it working here on my pi without nabucasa login information, in lovelace created a map :

type: map
entities:
  - device_tracker.oneplus_a5000
title: Waar is ze ?
hours_to_show: 24
dark_mode: false
default_zoom: 100

the mobile app on the phone send the info to the hassio pi at home, just make sure you forward the port on your firewall / router / switch to the hassio pi.

**Comment by frenck** [comment]
> What also isn't mentioned is that, when using the app on your phone for presence detection, that you should register with nabucasa.com and add the remote URL to the settings of the app. Otherwise, you always appear to be at home.

That information is incorrect. There are many methods to provide access from the outside. This requirement is not correct.

**Comment by LucVanDyck** [comment]
Then let's rephrase it: the app on the phone needs to be able to access your HA at home, from outside the local network. Doing this through nabucasa is one way.
