### ISSUE TITLE
Missing lifx_legacy documentation page

### ISSUE THREAD

**Issue by klaasnicolaas** [home-assistant/home-assistant.github.io#16723]
**Feedback**

In core we have 3 integrations of **lifx**:
- lifx
- lifx_cloud
- lifx_legacy

However, on the website you will only find a web page for the first 2, for `lifx_legacy` it is missing.

**URL**

https://www.home-assistant.io/integrations/lifx_legacy

**Version**

_No response_

**Comment by klaasnicolaas** [comment]
I see that @amelchio was the codeowner for this integration

**Comment by frenck** [comment]
I think we should mark the `lifx_legacy` integration deprecated and pending removal from our codebase.

It seems to be never really listed in our docs, additionally:

<https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+lifx_legacy%22>

0 reports (which could mean it is perfect though 🙈 )

The package used by it has been stale since 2018:
<https://github.com/TangoAlpha/liffylights>

0 usage by code matches on GitHub:
<https://github.com/search?q=%22platform%3A+lifx_legacy%22&type=code>

**Comment by amelchio** [comment]
It was retained back in the day because Windows did not support asyncio UDP, https://github.com/home-assistant/core/issues/6820

However, `create_datagram_endpoint` is allegedly supported on Windows since Python 3.8 so there should be no problem with removing the legacy integration now.

(Even without that support, I would agree with relegating `lifx_legacy` to a custom component)
