### ISSUE TITLE
Automation Templating: Action block of automation 3 in examples does not work

### ISSUE THREAD

**Issue by bitmadao** [home-assistant/home-assistant.github.io#16757]
**Feedback**

Example automation 3's action block shows use of `target: entity_id: "{{ trigger.entity_id }}"` which does not work. data: `entity_id: "{{ trigger.entity_id }}"`.
target throws the following error in logs: 
`2021-02-26 12:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: not a valid value for dictionary value @ data['action'][0]['target']['entity_id']. Got None. (See ?, line ?)`

See the following discord interaction for an enactment of the issue: https://discord.com/channels/330944238910963714/672220450977349653/814822172257419315

Thanks, as almost always to Tinkerer for cracking the case!

**URL**

https://www.home-assistant.io/docs/automation/templating/

**Version**

2021.2.3

**Comment by frenck** [comment]
Yes!

This is, unfortunately, my fault. I was 100% sure this already was shipped in the last release, but support for this will land the next release (upcoming Wednesday). We've found out 2 days ago this was miscommunicated. I've adjusted quite a lot of places already 🤦, therefore, the problem is solved in a couple of days 😬

**Comment by bitmadao** [comment]
Ahh,
Issue solved by way of timey wimey!
Thanks for the reply XD
