### ISSUE TITLE
Fan Speed not working

### ISSUE THREAD

**Issue by JHKQ** [home-assistant/home-assistant.github.io#16756]
**Feedback**

Hi There! 

The Fan speed for both Exhaust and supply isent working or atleast only showing 0...

**URL**

https://www.home-assistant.io/integrations/danfoss_air/

**Version**

2021.2.3

**Comment by frenck** [comment]
Hi there @JHKQ!

Thanks for the feedback, but this is the repository for our documentation. It sounds like you want to report an issue with the integration itself. To report issues with Home Assistant Core integrations, please report your issue here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍
