### ISSUE TITLE
ROOMBA integration broken after restart on FEB 26

### ISSUE THREAD

**Issue by mlhfb** [home-assistant/home-assistant.github.io#16766]
**Feedback**

After a HA restart Roomba entities no longer available.  Remove and reinstall of integration fails.  After IP and BLID entered and home button pressed on Roomba, integration fails and roomba responds with device is all set up press clean to get going... or something to that effect.

**URL**

https://www.home-assistant.io/integrations/roomba/

**Version**

2021.2.3

**Comment by frenck** [comment]
Hi there, thank you for reporting an issue, however, this is the issue tracker/feedback for the documentation. It seems like you want to report an bug with an Home Assistant Core integration. In that case, you should report your issue here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍
