### ISSUE TITLE
Where to set?

### ISSUE THREAD

**Issue by jahbini** [home-assistant/home-assistant.github.io#16838]
### Feedback

I infer that this ID is to be specified in the configfile?  Yes? No? Maybe? Syntax?

### URL

https://www.home-assistant.io/faq/unique_id/

### Version

2021.3.0

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/109940148-0e4f8180-7cd2-11eb-871b-e60fa37d47c5.png)

It's a limitation of the integration specifically; which can only be fixed if integration is adjusted for it (if even possible).

**Comment by spencerthayer** [comment]
How does one delete an entity that does not have a unique ID so we can start over? Or how do we manually assign a `unique_id` or `entity_id` in the `configuration.yaml` to override this error?

If not possible, then perhaps the way entities are done needs to be rethought because editing the `core.entity_registry` shouldn't be the solution.
