### ISSUE TITLE
Verisure introduced 2FA, which needs to be disabled for the integration

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant.github.io#16960]
### Feedback

Verisure is currently enabling 2FA on all accounts. Our Verisure integration, unfortunately, cannot handle this yet. 

We need to document, as a prerequisite, that 2FA needs to be disabled and recommend todo so on a seperate (non-administrator) account.

### URL

https://www.home-assistant.io/integrations/verisure/

### Version

2021.3.3

**Comment by saksholm** [comment]
I got this working by creating a new "system" user and disabled 2FA. Not sure is there a bug or not but I have to create an admin account first to able disable 2FA on that account, and then switch back to a normal user.

**Comment by epetwes** [comment]
Please note that swedish letters "ÅÄÖ" does not work in password string in this implementation. It is allowed in "Verisure MyPage" but in Hassio it does not work. I have tried the "https://github.com/persandstrom/python-verisure" and there it worked.
I know that you shall avoid that kind of special characters but as a swede it is quite nice to use.

**Comment by frenck** [comment]
The documentation has been updated already to take care of 2FA. Closing the issue on this end.

**Comment by epetwes** [comment]
@frenck I agree that the documentation has taken care of 2FA issue but my opinion is still that there is an error in implementation of swedish letter in the password. Please mention this in documentation so other people do not need to have the same trouble as I had until I found out the root cause why Verisure implementation failed.

I'm newbie in github, the issue should maybe be raised in some other part of github? Sorry for this reply. //Peter

**Comment by frenck** [comment]
The letters/encoding was not related to this documentation issue. Please raise an issue in the core if you think there is a bug with the Verisure integration.
