### ISSUE TITLE
Add a filters in search bar

### ISSUE THREAD

**Issue by AalianKhan** [home-assistant/home-assistant.github.io#16996]
### Feedback

Hello,
I really like how there is a quality scale to see how good this integration is with home assistant. I often see people on forums asking what is the best fans, air conditioners, etc that work well with home assistant. A possible solution to this might be to make a filter in the search bar to see all the components with platinums, golds, etc to see which products/brands work well with home assistant which can influence mine and other people's buying decisions. I think some people will like a filter for IoT class too.

I think it would be best if it works how filters work for platforms. Such as when you click alarm you see all the alarm platforms
### URL

https://www.home-assistant.io/docs

### Version

2021.3.4

![Screen Shot 2021-03-14 at 1 00 20 AM](https://user-images.githubusercontent.com/39784853/111059073-c3b3cf00-8460-11eb-81a3-13ed4ad721ce.png)

**Comment by AalianKhan** [comment]
Maybe a better implementation might be to have a sort button where a person clicks on the platform on the sidebar he/she is looking for and sorts it by quality

**Comment by frenck** [comment]
This has been discussed a couple of time before, hacking it into a "category" list is a bit off. It would be better if we added an actual filter option.

**Comment by MichaelAldrich** [comment]
Please do this. I'm someone excited about home assistant who is about to purchase their first ever smart home products. For me being able to choose the most well integrated products is a big priority. I woud like filters for IOT class as well, so I can quickly find the local push options.

**Comment by AalianKhan** [comment]
This will be still highly useful today

**Comment by ludeeus** [comment]
I made a concept to add filters yesterday <https://deploy-preview-18512--home-assistant-docs.netlify.app/integrations/>.
If anyone want to continue on that approach [here are the source](https://github.com/home-assistant/home-assistant.io/pull/18512/files)

It was fast thrown together so it's far from ready but should give a starting point, it would need at least:
- Better styling at least for desktop (mobile looks "fine" as IMO better than the current view)
- IOT Class and quality scale should be multi-select
- It should be possible to combine filters
- Maybe an easy way to reset filters
- The filter functions needs adjustments (this concept har misusing the search and that will not work with combining and multi-select)
- The filter needs to be backward compatible since there are links out there directly to searches/categories.
