### ISSUE TITLE
The options mentioned to say are unclearly specified and not discoverable

### ISSUE THREAD

**Issue by thomasvs** [home-assistant/home-assistant.github.io#17069]
### Feedback

Re: The say service support language and on some platforms also options for set, i.e., voice, motion, speed, etc.

 * it's not clear whether this means that 'options' is a key in the service data or something else.  If it is the former, it's not clear how you then specify a hash of options.
 * it would help to see an example below that includes voice, motion, speed options
 * it would help to link to an example or the documentation of a tts platform that allows you to specify those options

There is also something about the wording that doesn't read right, but I can't suggest a better wording without understanding how this is supposed to work.  I can revisit when there's a clearer example.

### URL

https://www.home-assistant.io/integrations/tts/

### Version

2021.3.4

**Comment by frenck** [comment]
The TTS entity-component options are documented? And has examples?
Integration specific should go into the pages for those specific integrations.

So, things like voice, motion, speed and such, are not provided by the integration you provided this feedback on.

**Comment by kyberias** [comment]
For the purpose of getting HA to speak, I tried to understand the page but didn't really understand much of it. It's as if the documentation tries very hard to save words and document only the absolute minimum.

**Comment by frenck** [comment]
This page will not make Home Assistant speak...

**Comment by kyberias** [comment]
> This page will not make Home Assistant speak...

Huh? I really don't understand what you're trying but this behavior won't make HA documentation better.

**Comment by frenck** [comment]
> but this behavior won't make HA documentation better.

I'm sorry, I'm not here for support. However, I'm not trying to be unfriendly at any time.

The problem here is that the TTS documentation is not about TTS implementations. For example, Google Translate is one of the integrations that provides TTS. More can be found here: <https://www.home-assistant.io/integrations/#text-to-speech>

The integration page you provided feedback for (https://www.home-assistant.io/integrations/tts/) provides a basic entity platform that other integrations can use. By itself, it is not capable of anything.

Hence, none of the provided feedback bullet points provided in this feedback can be added to that page, simply because it doesn't apply or isn't known at this level.
