### ISSUE TITLE
Documentation doesn't specify which platform configuration options are global

### ISSUE THREAD

**Issue by thomasvs** [home-assistant/home-assistant.github.io#17068]
### Feedback

The page says this:

"However, the TTS integration will only look for global settings under the configuration of the first configured platform:"

It's not clear which of the configuration parameters below are global and which aren't.  For example, service_name clearly is not a global setting, because you can specify a different one for each tts platform entry.

### URL

https://www.home-assistant.io/integrations/tts/

### Version

2021.3.4

**Comment by frenck** [comment]
You opened up a PR for that already? Why are you making a feedback item for it?

**Comment by MMaciocia** [comment]
Maybe, just maybe, the feedback mechanism directed him here - as it did me!
Now, what does that suggest to you?
Clue, it is something to do with the way the installation and configuration pages are written!

**Comment by frenck** [comment]
@MMaciocia I think you are missing the point in your last comment. @thomasvs opened a PR here:

<https://github.com/home-assistant/home-assistant.io/pull/17067>

There is no need to open issues/feedback in order to open a PR. So I'm not getting the creation of this, if he opened a PR as well.

> Clue, it is something to do with the way the installation and configuration pages are written!

Clue, this is an open source project. Please feel free to improve our documentation by opening a PR. Thanks 👍
