### ISSUE TITLE
integration does not work

### ISSUE THREAD

**Issue by tiagodiaf** [home-assistant/home-assistant.github.io#17116]
### Feedback

the integration doesn't work, i try to login with my tesla account data and it doesn't work. I've used it for a while and everything worked, I can't currently integrate, the only change I know of was Tesla using 2-factor authentication.
Can you please check the situation?

### URL

https://www.home-assistant.io/integrations/tesla/

### Version

2021.3.4

the integration doesn't work, i try to login with my tesla account data and it doesn't work. I've used it for a while and everything worked, I can't currently integrate, the only change I know of was Tesla using 2-factor authentication.
Can you please check the situation?

**Comment by frenck** [comment]
Hi there,

I think you want to report an issue with an integration, however, this is the feedback/issues tracker for the documentation. There is no amount of documentation I can adjust to fix integration code...

Please report your issue here:

<https://github.com/home-assistant/core/issues>

Thanks 👍
