### ISSUE TITLE
not  working hive integration

### ISSUE THREAD

**Issue by treforparr** [home-assistant/home-assistant.github.io#17217]
### Feedback

Not working anymore tried it several ways problem is the two-step verification as Hive has changed a lot of his settings due to the security cameras with a hive view

### URL

https://www.home-assistant.io/integrations/hive/

### Version

2021.3.4

**Comment by frenck** [comment]
Hi there @treforparr 👍 

It seems like you want to report an issue/bug with an integration. However, you left documentation feedback. There is no amount of documentation that I can adjust to fix an integration.

Please report your issue here:

<https://github.com/home-assistant/core/issues>


Thanks 👍

**Comment by treforparr** [comment]
I didn’t know how to fill out the document as I’m suffer with dyslexic
