### ISSUE TITLE
Underlying problem

### ISSUE THREAD

**Issue by O-Palda** [home-assistant/home-assistant.github.io#17489]
### Feedback

It might be a good idea to provide a warning that for some types of sensors (especially 3 phase energy meters) can provide bogus values while underlying sensors goes from unknown / unavailable states under | float = 0 to real values after a while, especially during restart of hass.io.

To prevent this issue it is best to use template_availability in the sensor to prevent the sensor to be evaluated for very not good example:

        availability_template: >
          {% if is_state("sensor.shelly_3em_shelly_3em_hlavni_meter_total_0", "unavailable") %}
            false
          {% elif is_state("sensor.shelly_3em_shelly_3em_hlavni_meter_total_1", "unknown") %}
            false
          {% elif is_state("sensor.shelly_3em_shelly_3em_hlavni_meter_total_1", "unavailable") %}
            false
          {% elif is_state("sensor.shelly_3em_shelly_3em_hlavni_meter_total_1", "unknown") %}
            false
          {% elif is_state("sensor.shelly_3em_shelly_3em_hlavni_meter_total_2", "unavailable") %}
            false
          {% elif is_state("sensor.shelly_3em_shelly_3em_hlavni_meter_total_2", "unknown") %}
            false
          {% else %}
            true
          {%- endif %} 

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2021.4.4

**Comment by frenck** [comment]
This isn't a general rule of thumb, as it depends on the integration used how that behavior of being unavailable or unknown works.

IMHO, unknown/unavailable should not be processed by this integration. Maybe file a bug instead?

PS: The term hass.io isn't used anymore, neither should you. It is ambiguous.

**Comment by dgomes** [comment]
integration sensor handles UNKNOWN and UNAVAILABLE because it needs to skip those states, and it does it rightly so.

The issue @O-Palda is documenting is related to templates that cast the UNKNOWN and UNAVAILABLE to 0 (and this is the real issue!). When that happens **integration** sensor treats those states as an actual 0 causing erroneous values. If instead of casting to 0, **integration** sensor knows that any of the sources is unavailable/unknown, then all is processed correctly.

**Comment by O-Palda** [comment]
Dear all, I am not suggesting that something is wrong with the internal logic of HA, I am merely suggesting to put some warning into Utility meter documentation that such situation might happen and offer example or suggestion how to deal with it correctly, thank you for your consideration

**Comment by frenck** [comment]
>  that cast the UNKNOWN and UNAVAILABLE to 0 

They don't actually, as a template always results in a string (unless AST evaluated, however, that would still not result in those strings being casted to 0). Thus this must be a bug with integration.

**Comment by dgomes** [comment]
If there is a bug, it's with template...

{{ states.sensor.im_still_loading | float }}

this template will render 0 and not UNAVAILABLE

**Comment by frenck** [comment]
Right, but that is the given example:

![image](https://user-images.githubusercontent.com/195327/115137720-e9b42c80-a027-11eb-86f6-3d58be7063ed.png)

**Comment by dgomes** [comment]
and should work for sensors that don't have have "unavailable"/"unknown" state, since that entry was proposed by DMSR users...

From the point of view of the integration, I have no control on what sort of things the user types in the template :(
on the integration I only get 0 and act accordingly...
