### ISSUE TITLE
Stream page documentation

### ISSUE THREAD

**Issue by craigtappin** [home-assistant/home-assistant.github.io#17505]
### Feedback

- Include an actual example of the entire configuration of "stream".
- Include an actual example of a lovelace card utilizing the stream.
- What is "camera.quintal" in reference to? Does each camera need to exist under "camera" in configuration.yaml? If so include in documentation.

### URL

https://www.home-assistant.io/integrations/stream/

### Version

2021.4.4

**Comment by craigtappin** [comment]
Just noticed closed issue https://github.com/home-assistant/home-assistant.io/issues/17246.

The code example only has the stream: config. It would be good to have all the attributes in a YAML code snippet (I know they are listed underneath, but for people that are new to a language, it's easier to see a code block that can be copied).

Also as above, should mention that a camera entity is required.

Also it appears the "action" section is completely separate from the "stream"?

**Comment by allenporter** [comment]
My initial thought would be to remove all the docs and make it look similar to something like https://www.home-assistant.io/integrations/auth/ basically saying: This is internal, go look at camera.  We can remove all references to the services, since they are gone now, completely internal to camera.

Is `stream:` even needed in `configuration.yaml`? I've never used it directly or found a need to...

**Comment by allenporter** [comment]
@craigtappin From that issue you referenced " The example on the page is a complete example. There isn't more to configure" -- what configuration options are you expecting?  I'd like to clarify the documentation to understand why it is expected there are more options.

**Comment by allenporter** [comment]
We took a pass on cleaning up the documentation (mostly removing stuff) to clarify things. Thanks for the report!
