### ISSUE TITLE
Yandex Transport not work.

### ISSUE THREAD

**Issue by AirKing555** [home-assistant/home-assistant.github.io#17534]
### Feedback

https://yandex.ru/maps/10668/murom/stops/1543201926/?ll=42.036894%2C55.577853&utm_source=main_stripe_big&z=17.04

stops with the specified format do not work in the yandex.transport integration. The name of the bus stop is received, but the list of routes is not.

### URL

https://www.home-assistant.io/integrations/yandex_transport/

### Version

2021.4.6

**Comment by frenck** [comment]
Hi there @AirKing555!

It seems like you want to report an issue with an integration, but you provided documentation feedback instead. There is no amount of documentation I can change in order to fix an integration 😄 

Please report a bug at the Home Assistant Core issue tracker:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck 🚂
