### ISSUE TITLE
Still not integrating

### ISSUE THREAD

**Issue by treforparr** [home-assistant/home-assistant.github.io#17538]
### Feedback

Constant problems with integration it says aborted Or it won’t integrate I’ve tried everything

### URL

https://www.home-assistant.io/integrations/hive/

### Version

2021.4.6

### Additional information

Or it won’t integrate I’ve tried everything is there any news of when this will be fixed so I can integrate it into him assistance again it has a two-step verification problem

**Comment by SeanPM5** [comment]
As KJonline mentioned in the previous feedback you opened https://github.com/home-assistant/home-assistant.io/issues/17372 the fix for this will be included in the 2021.5 release. That is scheduled for Wednesday May 5th.

You can get access to it a week earlier (April 28th) by joining the beta channel (Supervisor -> System tab).
