### ISSUE TITLE
Tasmota Integration

### ISSUE THREAD

**Issue by spoolr** [home-assistant/home-assistant.github.io#17679]
### Feedback

I'm having some issues with Tasmota Integration, mainly my devices become "Unavailable" after a few days of uptime.  I recognize this isn't the place for that, however, while trying to track down why this is, I've noticed Tasmota and Home Assistant say different things regarding a custom fulltopic (which I have)

Tasmota docs regarding Home Assistant Integration says:

> Do not change the FullTopic in order to use this feature. Leave it as default

Home Assistant docs say:

> Although the Tasmota integration supports custom fulltopic it is strongly suggested to leave fulltopic at its default, Tasmota does not prevent setting an invalid or non-unique fulltopic, for example a fulltopic without the %prefix% or %topic% tokens.

You could argue they both say the same thing, but Home Assistant seems to give more info on why you wouldn't want to mess with it.  In my case, I use a custom full topic using the %prefix% and %topic% tokens as recommended  (I reversed the order, so it's device/tele instead of tele/device)) and things work for the first few days but ultimately fall apart.  I don't want to adjust the fulltopic across my many devices only to discover my problem ultimately lies elsewhere.

.

### URL

https://www.home-assistant.io/integrations/tasmota/

### Additional information

Quote from Tasmota docs comes from here:

https://tasmota.github.io/docs/Home-Assistant/#tasmota-integration

**Comment by emontnemery** [comment]
The wording in the Tasmota docs is very strict, and the reason is to not encourage configuring the `fulltopic` as it's very easy to get it wrong, but if the devices are discovered and can be controlled the configuration is sane.

Reversing the order of `%prefix%` and `%topic%` should be perfectly fine.

I'd suggest to:
- Open a PR (if that's how it works) to adjust the Tasmota docs to explain why `fulltopic` is tricky
- Open an issue here: https://github.com/home-assistant/core/issues/new/choose if you want some help to debug your unavailable Tasmota devices
