### ISSUE TITLE
Openhardwaremonitor not working

### ISSUE THREAD

**Issue by jatgm1** [home-assistant/home-assistant.github.io#17816]
### Feedback

Openhardwaremonitor does not work when included in configuration yaml.

### URL

https://www.home-assistant.io/integrations/openhardwaremonitor/

### Version

2021.5.3

**Comment by frenck** [comment]
Hi there @jatgm1!

It seems like you want to report a bug with an integration, instead, you have provided documentation feedback. There is no amount of documentation that I can adjust to get an integration fixed.

Please report your issue here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
