### ISSUE TITLE
Aqara E1 switch can’t add a to HA by aqara m1

### ISSUE THREAD

**Issue by percy10442** [home-assistant/home-assistant.github.io#18205]
### Feedback

Aqara E1 switch can’t add a to HA by aqara m1.

### URL

https://www.home-assistant.io/integrations/homekit_controller/

### Version

2021.6.4

**Comment by Jc2k** [comment]
Hi

You have filed this as a documentation issue. I think you meant to file this in https://github.com/home-assistant/core ([here](https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml))? There is a form there you need to fill in to help us figure out what is wrong. Right now you haven't told us enough to be able to help you.

When you fill in the form in the core repository, please provide as much detail as possible. I do not have an Aqara E1. I do not have any Aqara devices. But I know some of their products have worked for other users. Be sure to tell us how you tried to add it, what you thought would happen, what actually happened. Was there an error message in the UI? Was there an error message in the logs? Etc.

I'm going to close this because it's the wrong place for the issue and there is not enough information to help, but please do file one in the other repository [here](https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml).
