### ISSUE TITLE
We need a top level warming or PSA letting people know this will have a recurring payment needed to work

### ISSUE THREAD

**Issue by AlxSZP** [home-assistant/home-assistant.github.io#18242]
### Feedback

I spent hours following up all the integration process, paid the 5USD dev fee, and it all ended up being useless, because the only way to expose my home assistant is to subscribe to nabucasa that has a monthly cost of 5 dollars.

I wish I knew this upfront to avoid spending my time doing this

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2021.6.5

**Comment by allenporter** [comment]
Hi, that isn't totally accurate though nabu casa is great.

Google recently changed the rules to require ssl a few days ago and I wrote up this short guide in the community forum for options:
https://community.home-assistant.io/t/google-nest-offical-device-access-console-finally-released/229146/1444?u=allenporter

In particular you need to use SSL -- just happens that nabu casa is the easiest way to get it.

Definitely makes sense to update the top to explain this new rule since I agree it can be extra work.

Just want to clarify that nabu casa is not required.
