### ISSUE TITLE
Some yaml sample 

### ISSUE THREAD

**Issue by denisjoshua** [home-assistant/home-assistant.github.io#18266]
### Feedback

Maybe will be a good idea to write some yaml sample on the integration page
Thanks in advance

### URL

https://www.home-assistant.io/integrations/philips_js/

### Version

2021.6.6

**Comment by frenck** [comment]
Could you clarify "Some yaml sample"?

I can write a bunch of YAML, but what are you suggestion/looking for?

**Comment by elupus** [comment]
There should be none. Yaml config is deprecated.

**Comment by frenck** [comment]
@elupus Unless he is looking for a non-"integration setup" example...

**Comment by denisjoshua** [comment]
Thanks a lot fot the quick answer. 
Obviously I'm not a programmer, and also I don't know yaml language,
but usually on some Home Assistant plugin/integration pages is some yaml samples

For example I installed the integration and I think it's work :-) 
Now I want to make a switch that power on/off my Philips TV ..and maybe select the source. 

A sample of yaml script for power on/off can be put on the integration page... 
usually I so a lot of Hass page that let there a yaml sample code. 

Thanks a lot again 
Denis

**Comment by elupus** [comment]
That would be a standard automation that you can do inside the gui. No yaml needed.

**Comment by frenck** [comment]
The YAML examples shown, are generally for either manual configuration setup (which is being phased out, so PhilipsTV actually works fully via the UI as you have already noticed), or are documented because they are advanced things that are not standard.

In this case, it involves controlling a media player. Media players are standardized components and general work similar for all integrations. If you are new to Home Assistant (and not a programmer 😉 ) I would advise you to use the automation editor in the UI first. That way you can get comfortable with the terminology and how stuff works. Allowing you to go into tougher subjects later on.

[![Open your Home Assistant instance and show your automations.](https://my.home-assistant.io/badges/automations.svg)](https://my.home-assistant.io/redirect/automations/)

Fun/helpful fact. All automation made via the UI can be viewed as YAML to see the output of what the automation editor created. This can be really helpful for the future.

Good luck!

../Frenck

**Comment by denisjoshua** [comment]
Thanks a lot Frenck, 
I have try in the automation page but also there, I don't know how to create a switch.
I want to create a switch that have name: TV and use it in the google home assistant routine 
in order to power on/off the TV. 
I'll try to find some switch sources on web and personalize for my propouse :-) 

Thanks a lot again 
Denis

**Comment by frenck** [comment]
You do not need to created switches for those :)
Media players already have turn on/off functionality.

**Comment by denisjoshua** [comment]
Yes, but even if I synchronized devices in my google home assistant, I can't find my Philips TV on the APP.
I also unlink and relink the HassOS in my ghome assistant and my TV is not there... 
So I want to create a new switch in my HassOS... that switch wil turn on/off my TV 
and I'll use that switch in the ghome assistant. 
Thanks a lot again
Denis

**Comment by frenck** [comment]
@denisjoshua That is kinda unrelated to this documentation, thus you won't find a specific example for that in this integration documentation.

You could take a look at the documentation of a switch template. A template allows you to create a "virtual" switch that controls something else. This does require working with things like YAML.

If you are in need of getting help with that, I would highly recommend joining our community forum or Discord chat. You are likely to get more guidance and an answer to your question in those places.

👍 

../Frenck

**Comment by denisjoshua** [comment]
Ok thanks a lot Frenck :-)
