### ISSUE TITLE
Modern Forms Integration

### ISSUE THREAD

**Issue by kdbulldog** [home-assistant/home-assistant.github.io#18449]
### Feedback

I am not sure what it is asking form when it asks for a host in the configuration of the integration.  The documentation does not address this.  

### URL

https://www.home-assistant.io/integrations/modern_forms/

### Version

2021.7.1

**Comment by wonderslug** [comment]
This is the network Hostname or IP address for the Fan in this case.

**Comment by stxph-n** [comment]
It appears that this integration is for the setup of a single fan only and not multiple, correct?

**Comment by stxph-n** [comment]
Update: To add multiple fans, just repeat the integration process, using each individual IP as the host name. Also, the easiest way to get the IP is to go to Settings > Devices (in the MF Form app) and it will show the IP. I'd also suggest reserving the IP on your router because the Wi-Fi on these things are finicky.  I already had one IP change on me (before I reserved it) due to a fan reboot.
