### ISSUE TITLE
Adding multiple shelly integrations is not clear from the documentation

### ISSUE THREAD

**Issue by fredvd** [home-assistant/home-assistant.github.io#18533]
### Feedback

The shelly integration works different from many other integrations when you want to add multiple device through the UI.  I was already a bit confused after reading the integration page that during adding the shelly integration I had to provide a Host/Device IP when the documentation says the integration can work by local push: I configure the homeassistant server it's AIP and CoiOP port on the device itself. Why does Homeassistant need the device IP?

What surprised me more after trying: I should add a second and third Shelly integration for each new device. Then it sometimes gets auto discovered and after setup the devices 'fold' into a single integration.  So on setup there's a concept of 'each device is added by adding a new integration'.

But this is completely different from how other integrations/devices work: You have one integration. And once it is set up it has found one ore more devices.  With new devices, you configure devices IN the integration UI. 

It is possible to change the integration UI to support adding devices in the Shelly integration itself, and not be depended on triggering new device detection by adding the same integration multiple times? This is very confusing.

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2021.7.3

**Comment by thecode** [comment]
Hi @fredvd,
Shell devices supports using authentication to connect to them, a user may set different credentials to each shelly and in that case using a single integration as suggested above will not work.

This issue was discussed between Shelly integration developers, and although it has some impact on the user experience vs one integration entry, this is the only way to support different credentials so that each device has it's own entry, the frontend groups them together as you noticed.

Home assistant does not need the device IP from the user, it should discover Shelly devices automatically and show them on the integrations page for you to approve adding them. The discovery is based on mDNS, if you added a device when HA is not connected to the network it may take some time until the device advertises itself (you can speed it up by rebooting the device). 

However if HA is running and you don't see new devices automatically discovered it means that either mDNS is blocked or the Shelly device is not on the same network as HA which also means local push will not work.

**Comment by fredvd** [comment]
Thank you for your feed back.  Now I understand the motivation for using the multiple integrations. But my point is this is not mentionned at all in the integration documentation or the setup screen of the integration. And it works contrary to the other integrations. Would it be ok to add this more explicit to the documentation and the integration setup page?

> However if HA is running and you don't see new devices automatically discovered it means that either mDNS is blocked or the Shelly device is not on the same network as HA which also means local push will not work.

This is not what I experienced when adding multiple Shelly Plug S.  I have no user/passwords set up on the plugs, all on the same network. 

* I added the first device by adding the integration. I fully configured it including CoIoT.  

* Then I set up the second device, also configured CoIoT on the plug to point to the HA instance. 
* The already active integration did not pick up the second device. 
* I restarted the integrattion, I restarted Home Assistance Core, I ever reset the whole OS. 

When I however added a new shelly integration, auto discovery picked up the second device without prompting me for a host IP and folded it into the first integration after finishing the setup in HA.

**Comment by thecode** [comment]
Since you are describing a problem here and not a documentation error, please open a case on the core repo, devices should be discovered without any need to add the integration for the first time

**Comment by klaasnicolaas** [comment]
Hi there @fredvd 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. At this point there is no reason to change the documentation.

Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

Klaas
