### ISSUE TITLE
Innova HP12 ELEC

### ISSUE THREAD

**Issue by bLackCat-79** [home-assistant/home-assistant.github.io#18624]
### Feedback

Hi!

Can you please give some examples on how to set it up with an innova AC?
I see that on innova the following ports are open, but I don't know what one to use:

80/tcp    open     http
1117/tcp  filtered ardus-mtrns
2738/tcp  filtered ndl-tcp-ois-gw
2956/tcp  filtered ovrimosdbman
3287/tcp  filtered directvdata
3953/tcp  filtered xmlink-connect

### URL

https://www.home-assistant.io/integrations/gree/

### Version

2021.7.4

**Comment by cmroche** [comment]
Hi @bLackCat-79 

Gree's protocol works using connectionless sockets, UDP on port 7000.

To discover the device, the integration sends a broadcast to your LAN, ie: 192.168.1.255 port 7000 and waits for a response on the same port number.

When it receives a response it will send UDP packets to the device's specific IP address again on port 7000, and responses will come back to the integration on the randomly bound source port.

Make sure your firewalls is configured to pass traffic on this port, as well as allow broadcast, and for best results make sure the device and HA server are on the same subnet.

**Comment by bLackCat-79** [comment]
Well @cmroche 
 and what if  your device is not listening on poort 7000 like it is the case with the INNOVA

**Comment by cmroche** [comment]
If the device is compatible with Gree+ then it has to work on port 7000. Is there some documentation that says it doesn't use 7000? Because I don't see any other way you would be able to know.

**Comment by bLackCat-79** [comment]
Technical  requirements  for  the  proper  functioning  of  the  cloud  connection  TCP  port  80,  443,  19009,  18321,  18009

https://www.innovaenergie.com/site/assets/files/2792/n273027e_manuale_utente_rev03_en-1.pdf

@cmroche 

Also if I nmap the device on udp, port 7000 is not open.

nmap -p 7000 -sU -v -T4 192.168.1.102
Starting Nmap 7.70 ( https://nmap.org ) at 2021-07-27 16:58 CEST
Initiating ARP Ping Scan at 16:58
Scanning 192.168.1.102 [1 port]
Completed ARP Ping Scan at 16:58, 0.43s elapsed (1 total hosts)
Initiating Parallel DNS resolution of 1 host. at 16:58
Completed Parallel DNS resolution of 1 host. at 16:58, 0.00s elapsed
Initiating UDP Scan at 16:58
Scanning 192.168.1.102 [1 port]
Completed UDP Scan at 16:58, 0.21s elapsed (1 total ports)
Nmap scan report for 192.168.1.102
Host is up (0.056s latency).

PORT     STATE  SERVICE
7000/udp closed afs3-fileserver
MAC Address: A4:E5:7C:01:E9:D9 (Unknown)

Read data files from: /usr/bin/../share/nmap
Nmap done: 1 IP address (1 host up) scanned in 0.80 seconds
           Raw packets sent: 3 (84B) | Rcvd: 2 (84B)

**Comment by cmroche** [comment]
I checked the *GreeRemote* project's issue board on GitHub (not related to the integration, but has info on device compatibility in general with the Gree+ protocol)--reading what I found here: https://github.com/tomikaa87/gree-remote/issues/32 it seems that your device may not easily work, and could require registration and connection to the cloud service before it will work locally. You might even need to emulate the cloud server and use MQTT instead of this integration.

The port-scan though suggests that your specific model isn't going to work at all (unless a wifi connection is first needed before it listens locally on port 7000), or there is another UDP port number it is using. The PDF you sent me only refers to ports for traffic to the cloud, not for local connectivity, FYI.

The best way to test, IMHO, is to try binding the device using the Gree+ app, and if that works and the integration still doesn't work, then use a network capture of traffic between the app and device so we can try and understand what it might be doing.

**Comment by bLackCat-79** [comment]
@cmroche thanks allready for spending effort in this!

The problem is that when I try to configure it with the gree+ app, that app doesn't reconizes the innova wifi. (Tried it boht on android and IOS). The app hangs on accessing the setup wifi network. It wants that its named ac_xxxx and has a password. The innova setup wifi has no password and is called clima_xxx.

I think therefor that innova is **not** compatible with gree+. (it is mentioned that it is compatible in the gree+ documentation)

**Comment by bLackCat-79** [comment]
Ok, I talked with the manufactoror, NO API, NO integration with any kind of platform and NO plans to do it,... it seems its just a crap product.
