### ISSUE TITLE
Integration not working anymore since months. Remove?

### ISSUE THREAD

**Issue by HA-TB303** [home-assistant/home-assistant.github.io#18794]
### Feedback

This integration is not working for months and the author seems to have abandoned the project. Remove it from the integrations? or the HA team fixes it maybe?

### URL

https://www.home-assistant.io/integrations/nissan_leaf/

### Version

2021.8.2

**Comment by frenck** [comment]
There has been ongoing maintenance on this integration and currently 76 Home Assistant instances report this integration as in-use.

You have now submitted documentation feedback, if you have issues with an integration, please report the issue here: 

<https://github.com/home-assistant/core/issues>


Thanks 👍 

../Frenck
