### ISSUE TITLE
Sensores integración Energy

### ISSUE THREAD

**Issue by kata685** [home-assistant/home-assistant.github.io#18839]
### Feedback

Hello,

When trying to select the energy sensors created by myself, they do not appear in the list, I do not know what the reason is.

  - platform: template
    sensors:
       consumo_casa:
        friendly_name: "consumo total casa"
        unit_of_measurement: "w"
        value_template: "{{ (states('sensor.shellyem_054356_channel_1_power')|float + states('sensor.shellyem_054356_channel_2_power')|float) |round(1) }}"

  - platform: integration
    source: sensor.consumo_casa
    name: energia_consumida
    unit_prefix: k
    round: 2
    method: left

Could you help me?

Thanks

### URL

https://www.home-assistant.io/docs/energy/

### Version

2021.8.4

**Comment by klaasnicolaas** [comment]
Hi there @kata685 👋

It seems like you want to report an issue with an Home Assistant integration, hower, this repository is for documentation feedback.

Please raise an issue in the Home Assistant core issue tracker instead (and check if your question has been asked before):
https://github.com/home-assistant/core/issues

But to answer your question, template sensors do not work with the energy dashboard because there is no support for this (this has to do with the `last_rest` option)

Thanks! 👍

Klaas
