### ISSUE TITLE
Warning for users to check where solar forecast doesn't work

### ISSUE THREAD

**Issue by Urbanhunter-hassio** [home-assistant/home-assistant.github.io#18853]
### Feedback

With the new energy dashboard and solar production shows, I have found the forecaster does not work for most of my country Australia.

Maybe a warning to check if your location is covered on the PGIS website so you can stop most of the questions about why it is not working.

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2021.8.3

### Additional information

What is shown on the solar forecaster website
![asdsadasd](https://user-images.githubusercontent.com/60960602/128647740-91bc083d-abb5-4f26-8ac8-dcd7b98beb75.PNG)
THen following the link to PGIS we get the below map.
![dsafasf](https://user-images.githubusercontent.com/60960602/128647758-ed2c4a53-5651-4879-bece-3fda50471544.PNG)
also the full map
![sedfasdfasdf](https://user-images.githubusercontent.com/60960602/128647763-029d05e0-e025-4926-8c08-9121b57669c4.PNG)

**Comment by klaasnicolaas** [comment]
We already did a lot more error handling for this integration before the last core release, because we noticed that many people were running into this problem since the integration was launched in 2021.7

If the integration does not work, you will find in the logs why, in case of a location for which no data is available:
![image](https://user-images.githubusercontent.com/20448157/128647937-8c20ee2c-f74d-4148-b694-889b586c989f.png)

And there is already a PR open (#18801) that gives more information about this in the docs.
