### ISSUE TITLE
great to finally have a Flipr integration

### ISSUE THREAD

**Issue by francodutch** [home-assistant/home-assistant.github.io#18874]
### Feedback

awesome to have this! Is there a way the latest data can be polled? The data on my app is much more recent than on the HA sensors.

### URL

https://www.home-assistant.io/integrations/flipr/

### Version

2021.8.5

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by francodutch** [comment]
Fair enough but it was created from the feedback button on the honeasssistant.io integration landing page - as documentation feedback.

**Comment by frenck** [comment]
I know, it states it pretty clear:

![image](https://user-images.githubusercontent.com/195327/129019415-93e89568-2b83-4c49-ba93-cbfe97afee72.png)

**Comment by cnico** [comment]
Hi @francodutch,

I received a notification for this by the robot as I worked on creation of the flipr integration.
As stated by frenck, do not hesitate to create a ticket on the community forum (I personnaly do not go in discord).

I have posted an exemple of usage here : https://community.home-assistant.io/t/flipr-pool-maintenance-integration/196435

As of your question, the flipr integration only polls the latest (most recent value) that the Flipr API returns. I have never seen the behavior you mention of recent data not received...

So do not hesitate to create a question in the forum so that we can investigate deeper if necessary.
