### ISSUE TITLE
SUpport for extended statistic for TED5000

### ISSUE THREAD

**Issue by Johan-Arens** [home-assistant/home-assistant.github.io#18907]
### Feedback

Hi, do you have any plan to update the integration to support the extended statistic feature ? 
In reference : https://www.home-assistant.io/more-info/statistics/

That would allow us, TED5000 users, to take advantage of the new energy tracking feature in HA. 

I'm willing to use beta versions and to give access to a HA instance to allow you to debug / experiment with my TED5000 unit. 
Thanks ! 

Johan 

### URL

https://www.home-assistant.io/integrations/ted5000/

### Version

2021.8.6

**Comment by frenck** [comment]
Hi there @Johan-Arens 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. This can not be fixed by adjusting the documentation.

Please report issues with Home Assistant Core integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍

**Comment by Johan-Arens** [comment]
Thanks for reporting this to my attention. 

I have open an enhancement request in the forum. 

Cheers, 

Johan Arens
***@***.***
