### ISSUE TITLE
Explain: Leave binary_sensor.flipr_[fliprid]_ph_status and binary_sensor.flipr_[fliprid]_chlorine_status as badges.

### ISSUE THREAD

**Issue by tmenguy** [home-assistant/home-assistant.github.io#19065]
### Feedback

Would be interesting to add a way to understand this:

“ Leave binary_sensor.flipr_[fliprid]_ph_status and binary_sensor.flipr_[fliprid]_chlorine_status as badges.”

A link to a way to use badges would be a good idea. (I have actually no clue on how to use use those two binary sensor and map it to homekit)

### URL

https://www.home-assistant.io/integrations/flipr/

### Version

2021.8.8

**Comment by cnico** [comment]
Hi @tmenguy, 
It is normal you do not find them because they are at the moment not on the official flipr integration.
The community dev rules for home assistant requires to send many small modifications to the core instead of large ones. That's why the two binary sensor are not present in the flipr integration by now. 
They are in the document by error since for the 1st version of the pull request in the code, they were present.
You can follow the pull request evolution asking the HA community to add it to the product here : 
https://github.com/home-assistant/core/pull/53525

Regards,

**Comment by tmenguy** [comment]
Thanks a lot @cnico !
