### ISSUE TITLE
Public sensors`?

### ISSUE THREAD

**Issue by pacc** [home-assistant/home-assistant.github.io#19159]
### Feedback

What is an area, what is even a weather area?
Cant you just log in and have your favourite public stations included as sensors?

### URL

https://www.home-assistant.io/integrations/netatmo/

### Version

2021.8.8

### Additional information

Did it use to work in '19 : https://community.home-assistant.io/t/netatmo-public-gone-forever/179690/91

TLDR; ?

**Comment by cgtobi** [comment]
> What is an area, what is even a weather area?

An area is the amount of space a two dimensional surface takes up. A weather area in this context is the realm between coordinates that you want to retrieve weather information for. 

> Cant you just log in and have your favourite public stations included as sensors?

No, as there is no such API.

**Comment by GiZMoSK1221** [comment]
> No, as there is no such API.

yes, there is. You can use getstationsdata with get_favorites=true. device_id can be "anything"
https://api.netatmo.com/api/getstationsdata?device_id=70%3Aee%3A50%3A58%3Af0%3A34&get_favorites=true
This command returns your favourite stations with all values (json format is different).

there is a problem with getpublicdata. Even when you enter exact coordinates of a station, you get all surroundings stations :( in my case even without the one station I need, which has wind data (it seems to be a "bug" at netatmo api). That's why i cannot use this integration and i have my own script running in background calling getstationdata.

@cgtobi please think about implementing getstationdata method. thank you

**Comment by cgtobi** [comment]
I have indeed overlooked that parameter. I'll put it on my list.

**Comment by cgtobi** [comment]
This will be implemented in an upcoming release.

**Comment by GiZMoSK1221** [comment]
@cgtobi "upcoming release" means HA 2022.04? How do I get entities from my favourite stations?

**Comment by cgtobi** [comment]
No, it has not been released yet. And since recent tests don't provide satisfying results I don't know yet whether I want to release that feature at all.
