### ISSUE TITLE
This page makes no mention of self configured entities.

### ISSUE THREAD

**Issue by horriblenoises** [home-assistant/home-assistant.github.io#19349]
### Feedback

What do I, the user, have to do to get my manually configured entities consuption entities to show up? MQTT? Rest? This page is a bit of a dead end and offers no helpful resources.

### URL

https://www.home-assistant.io/more-info/statistics/

### Version

2021.9.5

**Comment by frenck** [comment]
Please consult the documentation of the integration providing the entities. For example, the MQTT documentation.

**Comment by rct** [comment]
> Please consult the documentation of the integration providing the entities. For example, the MQTT documentation.

That implies there is usable information about long term statistics in the MQTT documentation.  Maybe I'm just blind, but so far I can't locate any.  For example https://www.home-assistant.io/integrations/sensor.mqtt/ doesn't include any mention of statistics.  (The word doesn't appear on the page.)

The total text under `state_class` is "The state_class of the sensor."   

The approach of pushing all of the information to the integration pages, means each MQTT, REST, Template, etc. documentation page should provide some possibly guidance that is possibly redundant and needs to be maintained to be kept current. 

Judging by what's on the developer page, https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics, it seems this page should offer some high level advice about the requirement for `state_class` and `last_reset` in order to track long term statistics.

**Comment by horriblenoises** [comment]
Agreed. I’m afraid I gave the impression that I needed help with these things when my post is really a critique of the information provided by the first stop everyone will see when they can’t add their devices in the GUI.
