### ISSUE TITLE
myq homekit local access is unclear

### ISSUE THREAD

**Issue by gdt** [home-assistant/home-assistant.github.io#19374]
### Feedback

In reading this page, it seems pretty  likely must have the myq app and the cloud set up first, but then after using the homekit bridges it should "work locally".   What is unclear is if one were to firewall the openers from the cloud entirely, and perhaps even deprive them of wifi, will HA be able to control the doors?    For me, the point is to avoid not only the unreliability of cloud in the loop, but to avoid data leakage to the cloud.  So many things fail if they don't phone home, and this isn't in my view clear enough.

### URL

https://www.home-assistant.io/integrations/myq/

### Version

2021.9.7

**Comment by bdraco** [comment]
Please open a PR to adjust the documentation.  Thanks 👍

**Comment by gdt** [comment]
Hey @github-actions this issue is still valid. I spent an hour or so reading code, and I can't figure out if the homekit controller will work if the opener can't phone home.  i'm trying to  prepare PRs to improve the docs.

**Comment by bdraco** [comment]
They work fine when my internet is down so I assume it will work without phoning home.  If you want to know for sure, I suggest setting up firewall rules to test. 

We use GitHub for tracking issues, and since there isn't a clear issue here, I'm going to close this out. If you find a problem, please do open a PR to adjust the docs.
