### ISSUE TITLE
Netgear Integration Not Allowing Me To Login

### ISSUE THREAD

**Issue by kksligh** [home-assistant/home-assistant.github.io#19648]
### Feedback

I have an Orbi Pro with 2 satellites.  I've tried several different ways to login via the new Netgear integration to no avail.  No matter what I do, it throws the same error:

"Connection or login error: please check your configuration".  

I know the username and password are correct as I've even reset the router/changed passwords just to be safe.  I've tried changing the port to 80 and also a different default username and host as well.  

The only netgear reference that I see in the logs is the following:

"2021-10-07 08:09:11 ERROR (SyncWorker_3) [pynetgear] Invalid response
2021-10-07 08:09:12 ERROR (SyncWorker_3) [pynetgear] Invalid response
2021-10-07 08:09:16 ERROR (SyncWorker_6) [pynetgear] Invalid response
2021-10-07 08:09:16 ERROR (SyncWorker_6) [pynetgear] Invalid response"

Anyone else having issues with this?

### URL

https://www.home-assistant.io/integrations/netgear/

### Version

2021.10.0

**Comment by ToaSD** [comment]
I have the Netgear Nighthawk MR60 and am having the same issue.  It auto discovers fine with default values:

Default host: (my router internal ip)
Default port: 5000
Default username: admin

Connection or login error: please check your configuration
---------------------------------------------------------------------

Log Details:

Logger: pynetgear
Source: /usr/local/lib/python3.9/site-packages/pynetgear/__init__.py:498
First occurred: 8:07:21 PM (4 occurrences)
Last logged: 8:07:35 PM

Invalid response

Logger: pynetgear
Source: /usr/local/lib/python3.9/site-packages/pynetgear/__init__.py:488
First occurred: 8:07:21 PM (4 occurrences)
Last logged: 8:07:34 PM

Unauthorized response, let's login and retry...

**Comment by kksligh** [comment]
in the latest update, I was able to login with no issues.

**Comment by starkillerOG** [comment]
@kksligh I made some fixes specifically for Orbi routers, glad to hear that it fixed your problem and that you are now able to use the integration.

**Comment by starkillerOG** [comment]
@ToaSD you don't have an Orbi router so those fixes might not work for you.
Please update to the latest version of HomeAssistant (2021.10.4) and remove any configuration in the YAML files that has to do with Netgear, please also do not use any custom components related to netgear while testing.
If it still does not work, please open a new issue.

What you could try is ignoring the auto-discovered integration and hit the + icon on the bottom right, search for Netgear and add it manually, you schould then be able to specify the port yourself.
You can try port 80 instead of 5000 and see if that works.
(If it does work with port 80 and does not with port 5000, please let me know so I can make a fix to use the correct port for your model).

**Comment by ToaSD** [comment]
No test seems to work for me and give a "Connection or login error: please check your configuration" error, however, if I use my local IP rather than routerlogin.net and port 80 I get the additional error (not a different error as the prior persists as well) "Unknown error occurred".  I don't know if it makes any difference but  (Gateway) UPnP/IGD integration is successful. I'm guessing that has no bearing on this issue however.

**Comment by starkillerOG** [comment]
@ToaSD do you have the trace log of the "Unknown error occurred"
Are you sure you are using the correct username and password for the router?
Did you have the netgear integration setup earlier or is this the first time you try it?
