### ISSUE TITLE
Minimum

### ISSUE THREAD

**Issue by matteocorti** [home-assistant/home-assistant.github.io#19787]
### Feedback

The minimum days to show is not 1 (as documented). I use it with 0.1 (2 hours) and it's working fine.

### URL

https://www.home-assistant.io/lovelace/statistics-graph/

### Version

2021.10.4

**Comment by frenck** [comment]
@bramkragten Could you clarify this?

**Comment by dannytsang** [comment]
@frenck I think @matteocorti is referring to this:
![image](https://user-images.githubusercontent.com/567982/151446165-bf843ea9-4d1c-4c35-afd9-23db294767ac.png)

The days to show can be set to less than 1 day. To do this, you have to do something like this:
![image](https://user-images.githubusercontent.com/567982/151446638-f2b7f00b-11ab-4eea-addd-7a9167894585.png)

and then delete the leading number (3 in the above example) otherwise it will default anything less than 1 to 30 days so is this more of a UI than a documentation feedback?
