### ISSUE TITLE
KNX states in case of GroupValueRead failure

### ISSUE THREAD

**Issue by nanosonde** [home-assistant/home-assistant.github.io#19861]
### Feedback

The sync_state option is a bit unclear. What exactly happens if "expire" is used, but the KNX group address could not be read due to KNX device failure.
Will the state show something like "unavailable"?

### URL

https://www.home-assistant.io/integrations/knx/

### Version

2021.10.6

**Comment by farmio** [comment]
The timer is reset on sending the read request. It will be tried again after it expired again. A warning will be logged. 

As these issues are very unlikely to happen (unless it's a configuration issue, which should be fixed by the user) it is not very throughly covered. 

> Will the state show something like "unavailable"?

That depends on the entity type and feature the state_address is for. 
Eg. a sensor would keep its value if it already had one. If not it will be "unknown" I think, but not 100% sure - you can just try it out with an unused GA. 

Feel free to update the documentation with clearer wording.
