### ISSUE TITLE
Yale doorman L3

### ISSUE THREAD

**Issue by Sredna17** [home-assistant/home-assistant.github.io#19882]
### Feedback

Hi!
I just want to feedback that i can control my Yale Doorman L3 so it seems that the August integration supports this lock.
I can connect to my Yale doorman L3 with the August integration and get the possibility to lock and unlock my door. Get battery status, if the door is closed or opened and who was the last user.

Best regards
Anders Sandmark

### URL

https://www.home-assistant.io/integrations/august/

### Version

2021.10.6

**Comment by bdraco** [comment]
We have issues opened against this device that are still outstanding before we can move it to a supported state:

https://github.com/home-assistant/core/issues/54722
https://github.com/home-assistant/core/issues/54348

Its unlikely to reach supported state since none of the codeowners for this integration have access to this device.

**Comment by isabellaalstrom** [comment]
@bdraco I would love to help with debug logs etc.

**Comment by bdraco** [comment]
To add support for this I'd need one of the following (and some luck that the api isn't difficult to decipher):

1. The vendor to send a test device (unlikely to happen here since the api usage here is reverse engineered)
2. I purchase one and have it shipped to the USA (unlikely to happen here since the high price point -- I'd rather donate the money to the food bank)
3. A user purchases one and sends it to me
4. Owner access to a lock that is already setup for a few weeks and time to coordinate testing.

**Comment by mattias-arrelid** [comment]
I will try to have a look at the doorbell stuff if I can find some time. Got a new spare phone that can run the latest iOS version (and hence, the latest August app) - just waiting for checkra1n jailbreak to gain support for iOS 15…

**Comment by bdraco** [comment]
Please see my comment here :

https://github.com/home-assistant/core/issues/54722#issuecomment-1021832847
