### ISSUE TITLE
Correct sensors to use when configuring the (native) Energy dashboard in HA ?

### ISSUE THREAD

**Issue by nelgmo** [home-assistant/home-assistant.github.io#19911]
### Feedback

I would like to know what are the correct sensors to use when configuring "Grid consumption" and "Return to grid" in the Energy dashboard. 

It is not clear to me what sensors to use when configuring the costs and money back.
Since you have the following sensors:
- sensor.accumulated_consumption_<name>_cost
- sensor.accumulated_production_<name>_compensation

I would expect to be able to use them for the option "Use an entity tracking the total costs" as these are the "real" (already calculated) costs/compensations. But when I try I get errors thrown. 

So instead I have to set "Use an entity with current rate" and sensor "sensor.electricity_price_<name>" to be able to calculate the cost/money back. But this does not seem the correct way since I assume everything is not included in this price.

Please advice.

### URL

https://www.home-assistant.io/integrations/tibber/

### Version

2021.10.6

**Comment by olofbokedal** [comment]
@nelgmo did you manage to figure out what sensors to use?

I don't have any production but would simply like to add correct sensors for the consumption and price. My first idea was to use the sensor.power_HOME_NAME entity since the value reflects what my Tibber Pulse says, but that sensor isn't available when configuring energy within HA. Been trying with different sensors for consumption but none of them seems to reflect what Tibber Pulse says.

I might just be misinterpreting the values though, but some clear instructions would be great.

@Danielhiversen not sure if I can remove the stale label so I'm just throwing in a mention here in case you'll miss it otherwise.
