### ISSUE TITLE
Home Assistant Cloud

### ISSUE THREAD

**Issue by dpawson** [home-assistant/home-assistant.github.io#19918]
### Feedback

There is nothing on this page about setting up HA cloud?
Links to features / pricing
and 
HA setup?

Where is the HA cloud setup documentation please?
   

### URL

https://www.home-assistant.io/cloud/

### Version

2021.10.6

**Comment by frenck** [comment]
The page writes and links:

![image](https://user-images.githubusercontent.com/195327/138550875-22bf13fd-536e-4dbb-b787-3bf50e28cd44.png)

All of your suggestions and questions are answered on these linked pages.

**Comment by dpawson** [comment]
Usual response. "It's good enough for Frank"?
All it does it link to advertising and the general HA documentation?

**Comment by frenck** [comment]
> "It's good enough for Frank"?

It's not about being good enough for me, all information is on the linked pages.

We don't add pricing information for other products or services in the Home Assistant documentation either.

As a matter of fact, this was changed in the past because of maintenance reasons. So you are actually looking at something that was changed from what you are suggested for other reasons.

Hence, we are ok with the current situation. Sorry to hear you don't agree.
