### ISSUE TITLE
Casting local media to Google Devices

### ISSUE THREAD

**Issue by borpin** [home-assistant/home-assistant.github.io#20147]
### Feedback

The page states that Google Cast can only be done via HTTPS then shows examples of HTTP URLs.

The note should be amended to add this (only HTTPS) and remove any reference to HTTP URLs as they will not work.

I suggest these steps are added as part of the solution to cast local media.

1.  Open Home Assistant Media browser.
1.  Choose Player → Select Web Browser.
1.  Open Dev Console on the browser, go to Network tab.
1.  Select the media you want to play. Once it starts playing Check the Network tab. Copy the request URL with auth key.
2.  Add your Nabu Casa (or DuckDNS etc) domain to that and use it as the “media_content_id”
3.  Add the content type such as audio/mp3

![image](https://user-images.githubusercontent.com/1322749/140303961-3085e045-73a1-4ca8-b0fb-aa54585f0416.png)

### URL

https://www.home-assistant.io/integrations/cast/

### Version

2021.11.0

**Comment by drthanwho** [comment]
As far as I know Google Home, whether it's a mini or a display device, can play media either via https or http.

The requirement for HTTPS is for **Home Assistant** Cast only, not Google Cast. As in you need HTTPS in order to cast your Lovelace through the build in home assistant cast. Playing an audio clip can be anything. HTTP certainly works as I have audio clips that I play to Google Minis over http.

This works just fine `http://192.168.1.250/local/audio/doorbell.mp3`

**Comment by borpin** [comment]
@drthanwho, Sorry I don't understand the difference. 

All I am doing in the integration is...

![image](https://user-images.githubusercontent.com/1322749/140616619-5f21d149-072c-4d6a-8955-81f6a13dc9e9.png)

The 'Home Assistant Cast' appears from the documentation to be part of the 'Google Cast' page.

![image](https://user-images.githubusercontent.com/1322749/140616679-5d438a1f-ff95-4507-b094-2e7e6ed1eb28.png)

When looking for a service to play media, All I get with google cast is..

![image](https://user-images.githubusercontent.com/1322749/140616746-e4bdd736-15ae-4942-9259-2c37fe96e0ad.png)

**Comment by drthanwho** [comment]
Here is an example from one of my automations
```yaml
service: media_player.play_media
data:
  entity_id: media_player.kitchen_display
data:
  media_content_id: "http://192.168.1.250:8123/local/audio/xmas/1.mp3"
  media_content_type: audio/mp3
```

This is stored in the `www` folder (thus /local) which means it's accessible both locally and externally (this is mentioned in the note that it has to be publically accessible). What you are trying to play is stored in /media which is why you can only get it to work by copying the url from the dev console. 
If you want them to play normally you need to move your sounds to the www folder. 

Regarding the Home Assistant Cast that is completely different (which is why it's under its own heading and not part of Playing Media heading). Don't confuse the two.

**Comment by borpin** [comment]
Hi @drthanwho, thanks. I think I understand this now and seem to have got it to work.

So the part re the `www` folder is what needs adding to the documentation as that isn't clear (or a link to where this is explained more fully).

![image](https://user-images.githubusercontent.com/1322749/140756448-f8963445-1261-4a17-93f2-3c1a0d8c82e9.png)

Might I suggest this is added, please?

"To cast media stored in your Home Assistant instance, it needs to be added to the `/config/www` folder which translates to the `/local` folder. e.g. a cast location of `/local/media/audio/test.mp3` is actually stored in `/config/www/local/media/audio/test.mp3`. There is no need to define the host, as Home Assistant works that out for itself" 

The last part needs confirming, but appears to be true.

Perhaps a screenshot of the Automation editor would not go amiss.

![image](https://user-images.githubusercontent.com/1322749/140757233-c8e1e759-09c5-4df5-b5f1-ce9db14250c8.png)

Thanks for your help :)
