### ISSUE TITLE
Fitbit Integration

### ISSUE THREAD

**Issue by Xiondewah** [home-assistant/home-assistant.github.io#20203]
### Feedback

“Go to the frontend. You will see a new entry for configuring Fitbit. Follow the instructions there to complete the setup process.”

I’ve no idea where this new entry for configuring is - can find a new card, but nothing requiring configuration after updating the configuration.yaml file and restarting.

### URL

https://www.home-assistant.io/integrations/fitbit/

### Version

2021.11.1

**Comment by fraulout** [comment]
Check in your configurations -> logs, see if there's an error for fitbit.

**Comment by Xiondewah** [comment]
Nothing in the logs but I now have the configurator.

However:

The app you're trying to connect did not provide valid information to Fitbit. Please report this issue to them.
Developer information: unauthorized_client - Invalid client_id

**Comment by Xiondewah** [comment]
Uninstalled/Reinstalled (having deleted the .conf file) now the configurator doesn't show up I'm afraid.

**Comment by borpin** [comment]
It seems the integration is broken

https://community.home-assistant.io/t/fitbit-unable-to-authorize/80470/74?u=baz123

**Comment by AddMoreLimes** [comment]
@Xiondewah I've attempted to add some steps to the documentation that I found in the comment that @borpin linked. You _must_ have SSL set up on Home Assistant, otherwise the integration will not trigger appropriately when you add the data to your configuration.yaml file. There's no error message in the GUI to tell you that this is the problem.

The steps will appear under "Notifications" telling you to create a Developer account with Fitbit, setting up an OAUTH application with Fitbit, then entering your instance and secret key into fitbit.conf. 

Fitbit has banned non-secure communication, so you can't set it up unless you have SSL.
