### ISSUE TITLE
Small problem

### ISSUE THREAD

**Issue by Struan1207** [home-assistant/home-assistant.github.io#20222]
### Feedback

I had a problem with the virtual environment. it states python3.8, which was unknown. 
Thanks for providing this manual.

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.11.1

**Comment by frenck** [comment]
So, when using the core installation method, in a Python environment, your Python runtime might differ from the examples. This can be caused by using different distributions or personal preferences of managing runtimes.

Anyways, this is an advanced installation method, we expect people that use this, to be aware of how to manage their Python runtime and environment.
