### ISSUE TITLE
Not able to add AppleTV integration

### ISSUE THREAD

**Issue by ondrejremes** [home-assistant/home-assistant.github.io#20500]
### Feedback

After pairing with AppleTV I am receiving error:
Aborted
The configuration for this device is incomplete. Please try adding it again..

### URL

https://www.home-assistant.io/integrations/apple_tv/

### Version

2021.11.5

**Comment by frenck** [comment]
Hi there @ondrejremes 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please submit issues with integrations here:

<https://github.com/home-assistant/core/issues>

Be sure to use the search on the issue tracker to see if your issue is reported already. In this case, I'm pretty sure this has been reported already (as an Apple TV OS 15 issue I think).

Thanks! 👍 

../Frenck
