### ISSUE TITLE
Growatt MOD 8000TL3-X-AU all parameters are zero

### ISSUE THREAD

**Issue by MaoZ1993** [home-assistant/home-assistant.github.io#20510]
### Feedback

I recently installed Growatt MOD 8000TL3-X-AU with new wifi logger Growatt ShineWiFi-X

I can see all data correctly in https://server.growatt.com/, but get all zero in HA. I think the integration is able to talk to the growatt server, but failed to identify the model thus no data is fetched. Please see screenshot below.

![Screen Shot 2021-11-30 at 9 14 51 am](https://user-images.githubusercontent.com/35769176/143951290-59bddb56-b1c1-4175-b935-ac7a76f5f1be.png)
![Screen Shot 2021-11-30 at 9 14 44 am](https://user-images.githubusercontent.com/35769176/143951302-6ce6d529-f0a3-4b9e-a4c0-4d1084044b7b.png)

![Screen Shot 2021-11-30 at 9 16 03 am](https://user-images.githubusercontent.com/35769176/143951370-7a9248bb-2f7a-4824-acab-fa77f874ef63.png)

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2021.11.5

**Comment by muppet3000** [comment]
Hi @MaoZ1993 thanks for the really detailed post. I'm gonna stick my neck on the line and say I'm 99% certain this is a duplicate of this bug: https://github.com/home-assistant/core/issues/51660
I'm guessing you have a "Max/Mid" type system? (It's what's reported on the Dashboard page of the Growatt site above the graph). If so, we haven't implemented that functionality yet (it's on my list I just need to find the time) it lists all the values in HomeAssistant because it thinks it's another type of system we do have support for.
Given how many people have reported this now I'll bump it up my priorities for implementation.

Note: this GitHub is for bugs with the UI, not the integrations, this bug should really have been filed under the "core" repo. Although given that it'll end up closed as a duplicate there's no need to do anything.

Can you please confirm that you're experiencing the same issue as listed above and, of you are, continue the discussion over on the other ticket?

Thanks.

**Comment by MaoZ1993** [comment]
Hi @muppet3000 . Thanks for your reply.

Yes I confirm my inverter is shown as a "Max/Mid" type. Apologies I only searched by the model so I missed that post #51660. It's dup and you can close this ticket now.

If you need any assistant on debug/logs/testing of MOD 8000TL3-X-AU model pls let me know. Thanks for your great works

**Comment by muppet3000** [comment]
No problem @MaoZ1993 - Would you mind just commenting on that other ticket so I've got a track of you having this issue. It would be nice for everyone to get a notification when we finally fix it.
