### ISSUE TITLE
Forgot 'subscriber_id:' in code snippet yaml

### ISSUE THREAD

**Issue by bregtvandenbergh** [home-assistant/home-assistant.github.io#20669]
### Feedback

Hi, please could you adjust the code snippet for yaml, you need to add 'subscriber_id:' at the bottom.

Kind Regards,

B

![image](https://user-images.githubusercontent.com/31744864/145716228-810092c9-31de-4a88-a7f4-33cb8466529a.png)

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2021.12.0

**Comment by allenporter** [comment]
As of `2021.12`, I removed `subscriber_id` intentionally because it is no longer needed when setting up the integration for the first time. As you was through the setup, pubsub subscriptions are now automatically created by the integration.

Note it says in the configuration text:
```
subscriber_id string (optional):
Recommended to leave blank, and let the integration manage this for you. If you want to use your subscription, enter the full path for the Pub/sub Subscription name.
```

@bregtvandenbergh can you confirm that makes sense? Let me know if you have more context for why you think it is needed.

**Comment by bregtvandenbergh** [comment]
Dear Allen, my home assistant on rpi b+ was stuck in a reboot loop. As i couldn't find the cause I decided tot completely  reinstall. I readded the nest integration without the subscriber id and it would work with my old setup in Google cloud. So i made a new one. That wouldnt work too. So i readded the subscriber id and used the old cloud config Then it worked again. Maybe i was doing something wrong? Kind Regards B

Met vriendelijke groet,

Bregt
________________________________

**Comment by allenporter** [comment]
It should not be in the example, since new users should not be specifying it. It is not required.  Since you are an existing user, you can use it, and it is still described in the docs.  Let me know if i misunderstood.
