### ISSUE TITLE
Add automation example for varying tariff start times

### ISSUE THREAD

**Issue by ivanovd** [home-assistant/home-assistant.github.io#20709]
### Feedback

Where I live, from April 1st to November 1st (summer season), the night tariff starts from 23:00 and ends at 07:00 and from November 1st to April 1st (winter season) the night tariff starts from 22:00 and ends at 06:00.

Is there a way to automate this? If yes, then could you provide an example as I believe that is a valid use case in other countries as well?

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2021.12.1

**Comment by dgomes** [comment]
This is complex... I have a similar issue in Portugal and ended up creating a custom component: https://github.com/dgomes/ha_erse because this logic is by no means easy to implement as an automation.

I suggest you follow a similar path (custom_component) or python script that changes the tariff for you
