### ISSUE TITLE
Stiebel Eltron WPF07

### ISSUE THREAD

**Issue by zimmerlis** [home-assistant/home-assistant.github.io#20858]
### Feedback

In need to integrate the Stiebel Eltron Modell WPF07, how is this possible?

### URL

https://www.home-assistant.io/integrations/stiebel_eltron/

### Version

2021.12.5

**Comment by fucm** [comment]
Please look through the following [discussion](https://community.home-assistant.io/t/is-there-any-interest-in-a-stiebel-eltron-climate-platform/65628). In the meantime, there are about three methods to integrate Stiebel Eltron devices:

- your mentioned [stiebel_eltron integration](https://www.home-assistant.io/integrations/stiebel_eltron/). Currently limited to LWZ systems only. The WPF07 does have the WPM 3 integrated and is therefore not supported.
- using the [modbus integration](https://www.home-assistant.io/integrations/modbus/), as described in the linked discussion above. Any type can be integrated (if modbus is supported), but you have to do a lot of manual configuration.
- using Node-RED HTML scrapping (required if Modbus can't be used, because you have the EMI module enabled on the ISG), as well described in the discussion linked above or [here](https://github.com/fucm/node-red)

Please close this ticket, if the answer was helpful. I am looking for maintainers of the stiebel_eltron integration, see [here](https://github.com/fucm/python-stiebel-eltron/issues/4) a request for a WPM extension as well.
