### ISSUE TITLE
Unclear about where to place example snippets

### ISSUE THREAD

**Issue by NdK73** [home-assistant/home-assistant.github.io#20946]
### Feedback

The page documents "everything" except a detail: where should a noob insert the example snippets? Sure, it's obvious to HA experts, but sometimes even the noobs would like to do something :-)
Maybe an example using the GUI editor could be useful.

### URL

https://www.home-assistant.io/integrations/telegram_bot/

### Version

2021.12.7

**Comment by frenck** [comment]
Your title of this issue is maybe somewhat "unclear" ;)

Please use descriptive titles, that helps everyone.

Anyways, I think you are looking for how to use YAML configuration, more information in that can be found here:

https://www.home-assistant.io/docs/configuration/

Even though you suggested to add information about doing this via the UI; This integration cannot be set up via the UI.

**Comment by NdK73** [comment]
Yup. Unclear on purpose :)
The examples on the page refer to setting up automations. And that can (mostly) be done via the GUI, but it requires to split the example code.
I've setup a new automation filling general/name, trigger/{type=event,trigger_type=telegram_text} and then pasted the contents of the action template in the action YAML (just 'cause templates are not editable in GUI mode).

**Comment by frenck** [comment]
I am not sure what you are trying to say, sorry.

This integration is not aimed towards UI use.
