### ISSUE TITLE
Nmap Tracker does not have any documentation of configuration parameters

### ISSUE THREAD

**Issue by hubikj** [home-assistant/home-assistant.github.io#21029]
### Feedback

Nmap Tracker does not have any documentation of configuration parameters. It has a sentence mentioning customization example
> An example of how the Nmap scanner can be customized:

but no example is given.

### URL

https://www.home-assistant.io/integrations/nmap_tracker/

### Version

2021.12.8

**Comment by hubikj** [comment]
👍

**Comment by luckydonald** [comment]
Yeah, apparently `platform: nmap` Is invalid.

![91A9268E-D885-4A5F-B64E-D68967C26EED](https://user-images.githubusercontent.com/2737108/168767049-34d86f2e-1aec-4e97-b136-1a11e46ea7a6.png)

![10630667-8CC3-4D38-ADC7-949836F8575A](https://user-images.githubusercontent.com/2737108/168692043-a1fee3e8-f210-49b1-a0ce-3e86556fbd11.png)

**Comment by luckydonald** [comment]
@frenck 
Ah, that's an improvement, however I am looking for how to integrate it with Device Tracker (which is pretty much the purpose of this plugin).
Can have a section about how to configure it in device tracker?

**Comment by frenck** [comment]
@luckydonald I don't understand your question; the NMap integration provides device tracker entities, so I'm confused about your question.

**Comment by luckydonald** [comment]
@frenck 
Apparently you have to add this plugin to the device tracker with the config file, and the page of device tracker only shows examples for `platform: netgear`

However, trying

```yml
device_tracker:
  platform: nmap
```
results in 

> Configuration invalid!
> Platform error device_tracker.nmap - Integration 'map' not found.

as seen in the screenshot above.

**Comment by frenck** [comment]
```yaml
device_tracker:
  platform: nmap
```

Is not a valid configuration, please consult the nmap tracker documentation for the recent documentation on using the nmap tracker.

**Comment by luckydonald** [comment]
Which unfortunately leads me to no documentation about how to set it up with the config file, hence to this ticket.

**Comment by frenck** [comment]
@luckydonald This issue is about:

> Nmap Tracker does not have any documentation of configuration parameters. It has a sentence mentioning customization example

(See initial opening post); this has been resolved. I'm not following any of your comments and how they are related to that.

This documentation suggestion in this issue is about this page:

[home-assistant.io/integrations/nmap_tracker](https://www.home-assistant.io/integrations/nmap_tracker/)

The Nmap tracker does NOT use YAML configuration at all and is configured via the UI, so your YAML snippets do not make sense to me. Additionally, you are talking about plugins (no idea what those are) and about `platform: netgear`, which has absolutely nothing to do with the NMap tracker.

Sorry, but I'm lost on what you want or what your documentation suggestion is.

**Comment by luckydonald** [comment]
Apologies.
I'll try to explain it better.

im coming from Device Tracker: https://www.home-assistant.io/integrations/device_tracker/#configuring-a-device_tracker-platform

A bit further down it states: "Multiple device trackers can be used in parallel, such as [Owntracks](https://www.home-assistant.io/integrations/owntracks/) and [Nmap](https://www.home-assistant.io/integrations/nmap_tracker/)."

Now I do not own a netgear router, so I was trying to set up `nmap` instead, because I understand that this would be an alternative platform for that?
That's at least what I understand from the documentation page there.

But I'm failing to configure the device tracker properly for this nmap add-on (plugin), it seems.

**Comment by frenck** [comment]
To be honest, I think you are in need of support... you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

The reason is that you have fundamental questions (and misconceptions), not related to this specific integration page: but about Home Assistant itself. This is not the place for that.

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by luckydonald** [comment]
I appreciate your time, and for pointing me into a better direction, even if this wasn't the answer I was hoping for 🤗

from your answer I can gather that, different to what the documentation makes it seems, this module is not a plug-in to the Tracker, but maybe something on it's own?
All I'm looking for is the possible values for that platform parameter 😅
