### ISSUE TITLE
Yale Doorman L3 works, even if listed as "known not to work"

### ISSUE THREAD

**Issue by marcus-sonestedt** [home-assistant/home-assistant.github.io#21362]
### Feedback

Just tested it?   I have the wifi bridge.

Device info
IRCN190916
by August Home Inc.
Firmware: 3.2.1-3.3.0-2.0.8

### URL

https://www.home-assistant.io/integrations/august/

### Version

2021.12.10

**Comment by bdraco** [comment]
Its reported here https://github.com/home-assistant/home-assistant.io/issues/19882 and here https://github.com/home-assistant/core/issues/54722#issuecomment-1021832847 as not working

I don't have one myself so I can't validate either way.

**Comment by marcus-sonestedt** [comment]
Ok. Let me know if you need any assistance from me to validate/test things either way. 

I am a software developer and I have that lock, it works for me in Home Assistant right now, and I am willing to support you with my time if you need me to test/check things out..

**Comment by bdraco** [comment]
To validate we are doing everything correctly in `yalexs` I'll need dumps of all the calls to the `remoteoperate` endpoint when using the iOS or android add while the lock is added to Home Assistant along with debug logging turned on in Home Assistant for `pubnub` since I'll need to see what comes down on the `pubnub` channel during each operation.

The app uses certificate pinning so you'll have to use something like https://httptoolkit.tech/blog/frida-certificate-pinning/ to see the https requests.

If you don't have any luck getting the dumps, in the past I setup a dev account setup to allow people to share owner access to their lock for a brief time for me to take the dumps so we could add support for their lock:

augustdev@koston.org
‪(440) 623-7226‬

**Comment by marcus-sonestedt** [comment]
I'll get back to you. I'm not feeling 100% after having had covid last week.  Also, I need to set up Android dev-env again as I have new computers. :)    Just letting you know.

**Comment by bdraco** [comment]
No worries.  Take your time. Feel better
