### ISSUE TITLE
Wrong entity id in Home Assistant GoodWe example

### ISSUE THREAD

**Issue by dd871** [home-assistant/home-assistant.github.io#21545]
### Feedback

The example for manual polling lists:
```
<...>
        entity_id: sensor.ppv
<...>
```

This seems to be incorrect (at least in my installation). The correct value for me was _entity_id: sensor.goodwe_ppv_

### URL

https://www.home-assistant.io/integrations/goodwe/

### Version

2022.2.3

**Comment by frenck** [comment]
All entity IDs in the documentation generally don't match and can differ. This is not an error, this is because entities are not guaranteed to be the same. As a matter of fact, you can even change entity IDs to your liking from the Home Assistant frontend.

In the documentation, they serve as an example.

../Frenck
