### ISSUE TITLE
Missing essential information on how to use

### ISSUE THREAD

**Issue by Hippe-Lip** [home-assistant/home-assistant.github.io#21557]
### Feedback

I’ve tried to make a statistics graph card but got problems.

When adding a ‘statistics graph card, it says “You must include at least one entity”.
Then I entered one sensor (using the code editor) and got the error message: “Entities need to be an array” and “The provided value for 'entities' is not supported by the visual editor. We support (array) but received ("sensor.wp_nibe_berekende_cop_dag").

The instruction page (https://www.home-assistant.io/lovelace/statistics-graph/)
- doesn’t say what the requirements are for the sensor in this card;
- doesn’t say anything about arrays;
- obviously is missing essential information on how to build up this card;
- is missing several examples of different kinds (formats) and sorts of configuration, along with explanatory text.

Now I’m stuck with a system that knows more then I do (it can tell me I’m wrong) but there is no way for me to find out WHAT is wrong and how I should have done it.

I need a graph of ONE sensor only.

The (unfortunately wrong) code in my card:

type: statistics-graph
title: COP per dag
entities: sensor.wp_nibe_berekende_cop_dag
days_to_show: 30
period: day
chart_type: bar
stat_types:
  - min
  - max
  - mean

thanks,
Philippe

### URL

https://www.home-assistant.io/lovelace/statistics-graph/

### Version

2022.2.3

**Comment by mdegat01** [comment]
> doesn’t say what the requirements are for the sensor in this card;

Which ones are you missing? Did you follow this direction at the top of the doc for that card?

> If your sensor doesn’t work with statistics, check [this](https://www.home-assistant.io/more-info/statistics/).

> doesn’t say anything about arrays;

Well it does say `list` for `entities`
<img width="353" alt="Screen Shot 2022-02-09 at 11 57 37 PM" src="https://user-images.githubusercontent.com/2037026/153340142-0a6c1346-1c1c-4232-8b73-0f8271bfc0c5.png">
Admittedly that is a different word then `array` so perhaps that error should be made consistent with the doc. But both are definitely trying to convey that you can't put just a string in `entities`.

> obviously is missing essential information on how to build up this card;

Not sure I agree. But if you think that consider submitting a PR to update the doc with the info you think is missing. Also have you tried the UI editor for the card? It eliminates these issues since it makes it impossible to configure it incorrectly:
<img width="1005" alt="Screen Shot 2022-02-10 at 12 07 56 AM" src="https://user-images.githubusercontent.com/2037026/153341291-cca51edc-a4f5-4e00-8d91-a9c98c5c0c80.png">

> is missing several examples of different kinds (formats) and sorts of configuration, along with explanatory text.

Again, not sure I agree but here is the example from the documentation:
```yaml
type: statistics-graph
title: 'My Graph'
entities:
  - sensor.outside_temperature
  - entity: sensor.inside_temperature
    name: Inside
```
From this example we can infer that what's incorrect about your config is `entities` since you have:
```yaml
entities: sensor.wp_nibe_berekende_cop_dag
```
And it should be like this to match the example:
```yaml
entities:
  - sensor.wp_nibe_berekende_cop_dag
```
