### ISSUE TITLE
As a suggestion

### ISSUE THREAD

**Issue by jmmartinviana** [home-assistant/home-assistant.github.io#21570]
### Feedback

As a suggestion, an example of how to calculate the temporary statistics of a season (from August to February of the following year) could be included.
Thank you.

### URL

https://www.home-assistant.io/integrations/history_stats/

### Version

2022.2.5

**Comment by mdegat01** [comment]
Seasons vary greatly based on location. You're referring to August to February as one season for example, for me that is 3: tail end of summer, all of fall, most of winter.

Assuming you want statistics for the current season you'd need a second integration that provides a `timestamp` sensor for "start of the current season". If you have that then this is trivial, start = that sensor, end = `now()`. The [season integration](https://www.home-assistant.io/integrations/season/) has this information but doesn't make it available currently. It just makes a sensor with the name of the current season and only uses the start datetime of the season internally.

It actually does seem like a nice idea and example but I'm not sure how it could be done without an enhancement. If you know of a way to do it today then please share it (or better yet, make a PR to update the doc with the example). If not then I'd recommend submitting a feature request to enhance `season` (or a PR if you feel comfortable doing that enhancement yourself) so that this can be done.

**Comment by jmmartinviana** [comment]
Thanks for your answer, If the season is from August to August of the following year
I have solved it with a conditional template whose values are:
```
    start: "{{ now().replace(year=now().year-1 if now().month in (1,2,3,4,5,6,7,8) else now().year if now().month in (9,10,11,12) , month=8, day=1, hour=0, minute=0, second=0) }}"
    end: '{{ now() }}'
```
