### ISSUE TITLE
Climate card, doesn't explain possible values of preset mode

### ISSUE THREAD

**Issue by ferreto1978** [home-assistant/home-assistant.github.io#21692]
### Feedback

In the manual it states that there is a "preset mode".
As an explanation, it syas "New value of preset mode." but nowhere can I find what values this can have.
From an example a bit lower on the page, I noticed "eco" is one of them, but it seems to render an error.
From that error I learned I had to use either "none" or "away", so I'm very confused now.
I was hoping it would have presets like "day" (home) and "night" (eco) and I also readd there should be a "vacation" mode?
Please, point me in the right dierction if I'm looking in the wrong place (I did hit the "?" on the card page)

### URL

https://www.home-assistant.io/integrations/climate/

### Version

2022.2.9

**Comment by dannytsang** [comment]
@ferreto1978 I believe different thermostats will support different modes. The best way to see what your one supports would be to go to **Developer Tools > States** and enter the entity ID.

Here's an example from mine and there's a attribute called _preset_modes_
![image](https://user-images.githubusercontent.com/567982/155576841-c1e2d48e-4770-4982-a029-a3917a5774e8.png)

The only way I know to tell say night preset mode is the same as eco mode on your unit is to turn those modes on and use the developer tools from above to see what state home assistant is reporting. Don't forget to press the refresh button at the bottom of the attributes every time you do that because it does not automatically refresh the state of the entity.

If you don't see the developer tools icon I think you need to be in [advanced mode](https://smarthomehobby.com/configure-home-assistant/#activate-advanced-mode)

**Comment by ferreto1978** [comment]
@dannytsang 
It seems that I had to define the preset temperatures first.
Then I can swap between these preset modes:
```
    sleep_temp: 17
    activity_temp: 19
    comfort_temp: 21
```
![image](https://user-images.githubusercontent.com/54818622/155612825-463c615a-5c25-4933-9843-a44f89cfb158.png)
