### ISSUE TITLE
Daily emails because of iCloud integration

### ISSUE THREAD

**Issue by ThaDuhFeez** [home-assistant/home-assistant.github.io#21756]
### Feedback

There has been an issue ([#46308](https://github.com/home-assistant/core/issues/46308)) open for over a year now regarding this integration.  Specifically, users who activate the integration receive daily emails (I get 2 per day) from Apple saying:

> Your Apple ID was used to sign in to iCloud via a web browser.
> --
> Dear XXX XXX,
> Your Apple ID (XXX@XXX) was used to sign in to iCloud via a web browser.
> Date and Time: XXXXXXX XX, 2022, X:00 AM PST
> If the information above looks familiar, you can ignore this message.
> If you have not signed in to iCloud recently and believe someone may have accessed your account, go to Apple ID (https://appleid.apple.com) and change your password as soon as possible.
> Apple Support

I am currently trying a suggested workaround to log into the Apple Id website beforehand ([https://appleid.apple.com/account/manage](https://appleid.apple.com/account/manage)) and generate an "App Specific Password" to be used with the Home Assistant integration.

Whether this works or not.  Users should be warned about the ongoing emails.  Otherwise they might think something has compromised their Home Assistant/Apple ID.

### URL

https://www.home-assistant.io/integrations/icloud/

### Additional information

In the past day 4 other users noted the same issue in a post on the Home Assistant Facebook Group ([https://www.facebook.com/groups/HomeAssistant](https://www.facebook.com/groups/HomeAssistant))
![Facebook](https://user-images.githubusercontent.com/44759269/155349220-dd30216d-ccc4-4edf-9e4b-202f9d46e0d0.jpg)

**Comment by GizmoGoody** [comment]
+1

**Comment by GizmoGoody** [comment]
Robot, this still isn't fixed.

**Comment by LordNex** [comment]
Agreed. I still receive daily emails and push notifications

**Comment by GoState** [comment]
As do I.  Really I think the fix should be for people to create an app specific password for their Apple ID ( appleid.apple.com) and the code needs to be updated so it doesn't prompt for a verification code since the App Password does not provide verification code (in order to enable app specific passcodes you must already have 2FA turned on for your Apple ID, but once in use these passwords don't require the verification code).  This way you don't get notifications about your ID being used either. (I've used this on other apps and it works great).

**Comment by ShadowRep** [comment]
This is not fixed and really should be.

**Comment by ThaDuhFeez** [comment]
This is still VERY MUCH an ongoing issue.

**Comment by frenck** [comment]
So the reason this issue is still open probably (or at least will never be closed), it because this isn't the issue tracker for Core integrations.

This tracker is used to collect documentation feedback, not for handling or reporting issue.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

When report an issue, please make sure your issue isn't reported already (to prevent duplicates).

When in doubt where to go, for now and in the future, please check out: <https://www.home-assistant.io/help>

Closing this one, as there is no documentation we can adjust to fix an integration issue.

../Frenck
