### ISSUE TITLE
Undocumented? Breaking Change 2022.3.0b0 - Requirements for custom components not found

### ISSUE THREAD

**Issue by purcell-lab** [home-assistant/home-assistant.github.io#21766]
### Feedback

Thanks for the new beta to play with!

Looks like maybe an undocumented breaking change, related to custom integrations and the way upstream libraries are referenced in pip.

https://github.com/pypa/pip/issues/10825

I presume each dependent library will need to fix their pip install dependencies, before the custom component can load.

### URL

https://rc.home-assistant.io/blog/2022/02/23/release-20223/

### Version

2022.3.0b0

### Additional information

```
Logger: homeassistant.setup
Source: setup.py:155
First occurred: 9:41:33 AM (2 occurrences)
Last logged: 9:42:09 AM

Setup failed for tesla_custom: Requirements for tesla_custom not found: ['teslajsonpy==1.5.0'].
Setup failed for deebot: Requirements for deebot not found: ['deebotozmo==3.0.1'].
```

```
Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 9:41:11 AM (6 occurrences)
Last logged: 9:42:09 AM

Unable to install package teslajsonpy==1.5.0: warning: missing-index-doctype × The package index page being used does not have a proper HTML doctype declaration. ╰─> Problematic URL: https://wheels.home-assistant.io/alpine-3.14/aarch64/ note: This is an issue with the page at the URL mentioned above. hint: You might need to reach out to the owner of that package index, to get this fixed. See https://github.com/pypa/pip/issues/10825 for context. ERROR: Cannot install teslajsonpy because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
Unable to install package deebotozmo==3.0.1: warning: missing-index-doctype × The package index page being used does not have a proper HTML doctype declaration. ╰─> Problematic URL: https://wheels.home-assistant.io/alpine-3.14/aarch64/ note: This is an issue with the page at the URL mentioned above. hint: You might need to reach out to the owner of that package index, to get this fixed. See https://github.com/pypa/pip/issues/10825 for context. ERROR: Cannot install deebotozmo==3.0.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by frenck** [comment]
Thanks, @purcell-lab 👍 

So, there are two things. 1, is the warning about the HTML doc type, for which you linked the issue. That is not causing problems, just a warning. Going to check if we can fix that on our end.

The dependency conflict show, causing problems installing some custom components, is more a side effect actually. It's caused by Python `pip`s newer resolver.

Those components and packages would have been generating warnings for a long long time already (which have been ignored by custom component authors).

For the latter case I'll see if I can add something to the breaking changes section.

**Comment by purcell-lab** [comment]
This issue looks like another instance:

https://github.com/custom-components/alexa_media_player/issues/1523

**Comment by piio** [comment]
Hi,

I have found in my logs another packages which can't be installed after updating to 2022.3.0b0 due to this issue:

2022-02-24 07:41:04 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package PyP100==0.0.18: warning: missing-index-doctype

× The package index page being used does not have a proper HTML doctype declaration.
╰─> Problematic URL: https://wheels.home-assistant.io/alpine-3.14/amd64/

note: This is an issue with the page at the URL mentioned above.
hint: You might need to reach out to the owner of that package index, to get this fixed. See https://github.com/pypa/pip/issues/10825 for context.
ERROR: Cannot install pyp100==0.0.18 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

2022-02-24 07:42:45 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package glocaltokens==0.6.2: warning: missing-index-doctype

× The package index page being used does not have a proper HTML doctype declaration.
╰─> Problematic URL: https://wheels.home-assistant.io/alpine-3.14/amd64/

note: This is an issue with the page at the URL mentioned above.
hint: You might need to reach out to the owner of that package index, to get this fixed. See https://github.com/pypa/pip/issues/10825 for context.
ERROR: Cannot install glocaltokens==0.6.2 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

2022-02-24 07:42:17 ERROR (MainThread) [homeassistant.config] Platform error: light - Requirements for tapo_p100_control not found: ['PyP100==0.0.18'].
homeassistant.requirements.RequirementsNotFound: Requirements for google_home not found: ['glocaltokens==0.6.2'].

**Comment by frenck** [comment]
> ERROR: Cannot install pyp100==0.0.18 because these package versions have conflicting dependencies.

Please report that with the author of that custom integration. Thanks! 👍

**Comment by purcell-lab** [comment]
tesla_custom dependencies have been fixed. 
debot is a bit unmaintained at the moment and has been removed from HACS.

**Comment by frenck** [comment]
Small update, I've added a breaking change note to the beta release notes for custom integration developers on the effects of the new Python pip may have on their custom integration.

Thanks for bringing it to my attention @purcell-lab 👍
