### ISSUE TITLE
DLNA Digital Media Server Playlist

### ISSUE THREAD

**Issue by aquavass** [home-assistant/home-assistant.github.io#21884]
### Feedback

Fantastic integration, is it possible to play the playlist which automatically plays all the songs in the list. Currently it only allows the choice to select and play one song play within the playlist?

### URL

https://www.home-assistant.io/integrations/dlna_dms/

### Version

2022.3.0

### Additional information

If this was to be updated and resolved would be great to have an option to shuffle the songs. Many Thanks keep up the great work!!!!!

**Comment by chishm** [comment]
Thanks, it's nice to get some positive feedback :smiley: 

I would love to have playlists too, but it's not easy to add support at the moment. HA [media players](https://www.home-assistant.io/integrations/media_player/) don't have a generic concept of play lists (other than enqueue next item and clear all items), so that would have to be added. Also the front end doesn't have a way of showing the play list information. This will require some HA architecture discussion and in-depth planning to get implemented properly.

If your DLNA server can serve playlist files (.m3u or .pls) and your DLNA media player can play them, and the server doesn't try to expand the contents of the play list (so that HA shows the items inside instead), then it might be possible to do it now without any changes. But you won't be able to change or view the playlist contents from HA.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
