### ISSUE TITLE
Some radios cannot play but, somehow it's just a HA issue

### ISSUE THREAD

**Issue by joaquinvacas** [home-assistant/home-assistant.github.io#21881]
### Feedback

Running Home Assistant 2022.3 on a Docker, tried also on latest HomeAssistantOS on a VM from another PC and another network.
Also tried from a personal VPN.

Radio-browser looks good, but when I try to play "Cadena SER Mallorca" which is a Spanish radio, it's stuck keep loading.

Also, if I try to cast the radio it shows this on the logs:

"2022-03-03 12:26:14 ERROR (Thread-12) [homeassistant.components.cast.media_player] Failed to cast media http://provisioning.streamtheworld.com/pls/SER_MALLORCA.pls. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address"

Actually, I can access from the docker container if I use wget, for example, so there's no connection issue or anything else.

Also, I can play some other radios.

The URL works fine, it's just the integration that cannot play from HA.

Maybe it's the way the playlist is made, using PLS instead of m3u. Because I can use this pls playlist on VLC for example.

### URL

https://www.home-assistant.io/integrations/radio_browser/

### Version

2022.3.0

**Comment by frenck** [comment]
This, unfortunately, is not a Home Assistant issue.


![CleanShot 2022-03-04 at 13 16 37@2x](https://user-images.githubusercontent.com/195327/156762073-6b355a2d-4fce-4040-913c-aedf7258cc4b.png)

This particular station is listed twice, both are `.pls`, which is not an issue.
The issue is that the stream marked with `1` seems not to be available right now, the second one marked with `2` is.

../Frenck
