### ISSUE TITLE
Updater deprecation: why and alternative?

### ISSUE THREAD

**Issue by stephanvierkant** [home-assistant/home-assistant.github.io#22018]
### Feedback

Is says it's deprecated, but further explanation is given. Some background information and an alternative would be great.

### URL

https://www.home-assistant.io/integrations/updater/

### Version

2022.3.4

**Comment by frenck** [comment]
> Is says it's deprecated, but further explanation is given. Some background information and an alternative would be great.

<https://www.home-assistant.io/blog/2022/03/02/release-20223/#breaking-changes>

![image](https://user-images.githubusercontent.com/195327/158207045-4a1832ce-9c6f-4aef-9d9f-3f1344c43bf8.png)

**Comment by frenck** [comment]
I believe all are in there?

**Comment by stephanvierkant** [comment]
Thanks, that makes sense! I think it's a good idea to put the information on that page, so users don't have to look for blog posts to get this information. I can create a PR?

**Comment by frenck** [comment]
Sure! But it won't be up for long, as it will be removed soon

**Comment by skipishere** [comment]
Got to agree with @stephanvierkant on this. It was only today when wondering why my dashboard wasn't telling me there was an update that I found the sensor in the 'Unavailable' state since the start of the month. Would be handy to have deprecation stuff on those pages (esp as that's where a quick web search will send you) as not all users will know to look in a release note / on GitHub (& if you haven't taken/read March's updates you'd be none the wiser when you next update).

**Comment by frenck** [comment]
> It was only today when wondering why my dashboard wasn't telling me there was an update that I found the sensor in the 'Unavailable' state since the start of the month.

Please actually READ release notes... really... especially the breaking changes, where this is listed. We can't stress that enough for every update.

**Comment by skipishere** [comment]
> > It was only today when wondering why my dashboard wasn't telling me there was an update that I found the sensor in the 'Unavailable' state since the start of the month.
> 
> Please actually READ release notes... really... especially the breaking changes, where this is listed. We can't stress that enough for every update.

I do, but like a lot of things, there is a large amount to take in and trying to remember what integrations I have on my instance.
Please take my feedback as constructive rather than as a complaint and knowing that users are unlikely to see a particular release note telling you what/why vs the documentation page.

**Comment by frenck** [comment]
> Please take my feedback as constructive rather than as a complaint and knowing that users are unlikely to see a particular release note telling you what/why vs the documentation page.

I do consider it constructive, and do not see it as a complaint at all?  I'm a user too.
Feel free to contribute by opening a PR to amend the documentation.

**Comment by Rbroughton007** [comment]
Frenck, I seen your comment to just "Read release notes". I don't mean this as a complaint or anything, but my setup has about 150 different states and over 200 services. Plus with an update occurring ever few days, I am just not going to spend my time seeing if 1 of the 350 different labels in the states and services match the variety of constant changes in the release notes every few days. 

I somehow doubt that any typical user will be any different then how I approach it. If you are going to deprecate something and modify it with something else, you should just link your blog response to the appropriate HA page so people can find it easier instead of making it more difficult. As far as your 'Open a PR to amend the documentation' to make it easier to follow, that doesn't work either as one of the few times I did that in the past, you changed it back and blew off the reason. I think you forget that most people don't work on this software project day in/day out and after a short while, they just aren't familiar with it anymore. 

I am just trying to be constructive, because when I used to do a lot of programming in the past on projects, I would sometimes lose sight that others (like the typical users) just don't see a program the same way as an in-depth programmer would see it.

**Comment by frenck** [comment]
> Plus with an update occurring ever few days

Those won't have breaking changes. Breaking changes only happen on major releases, which are happening every first Wednesday of the month, once a month.

> If you are going to deprecate something and modify it with something else

We generally remove it completely from the documentation. This is one of the exceptions that has been handled differently (as there is a note during deprecation), and now raises questions. Anyways, I'm not against amending the documentation, feel free to do so by opening a PR (as I said above already).

But yes, it is in the release notes and yes, one should read those. That is a side comment; I do not state or mean we can't adjust the documentation to point to it. Which I already pointed out and clarified in an earlier reply.

> As far as your 'Open a PR to amend the documentation' to make it easier to follow, that doesn't work either as one of the few times I did that in the past, you changed it back and blew off the reason.

OK, then don't open a PR 🤷 If you think everything is handled like that you should indeed not. I think it is complete nonsense to think everything is handled as such. If something is not accepted or reverted that has a reason. Sorry, you had a negative experience at that part; We have merged over 1500PRs a month (on average) the past 12 months, I'm pretty sure a lot of them stick 😉 

In the end, complaining about it won't change a thing; instead, try changing it. Be the change.

>  I think you forget that most people don't work on this software project day in/day out and after a short while, they just aren't familiar with it anymore.

I'm not sure what this side comment has to do with anything.

It seems in general you have other issues with me or the project. Which is sorry to hear, but I don't want to go into endless discussions that are offtopic for the suggestion at hand.

If one wants to edit the existing docs and propose a suggestion via an PR, that is welcomed.

../Frenck
