### ISSUE TITLE
Cannot change IP address

### ISSUE THREAD

**Issue by fplanjer** [home-assistant/home-assistant.github.io#22033]
### Feedback

My home network had some changes and the ip of my brel hub changed. There was no way I could change the configuration of the integration and ended up removing and re-adding it. Please provide a way to change the ip from the settings.

### URL

https://www.home-assistant.io/integrations/motion_blinds/

### Version

2022.3.5

**Comment by frenck** [comment]
Hi there @fplanjer 👋 

It seems like you are requesting a new feature, however, you have submitted documentation feedback instead. There is no amount of documentation I can adjust to implement your feature request 🙈 

Please use our community forums to request new features.

Thanks! 👍 

../Frenck

**Comment by starkillerOG** [comment]
@fplanjer you are right, removing and setting up the integration is currently the only way to change the IP.

@frenck If I implement a re-authentication flow in the integration, is it possible to manually trigger the re-authentication flow from within the UI?
Since I do not have any way to distinguish a network failure/bad wifi for which we would want to try to setup the integration again from a changed IP from which we would want to trigger a re-autentication flow, is a user able to trigger the re-autentication flow manually?

**Comment by frenck** [comment]
The config entry can be updated based on the unique ID. If the new device that is added matches an existing device, the existing config entry can be updated instead (that is how almost all integrations handle it).

**Comment by starkillerOG** [comment]
@frenck that is great, do I need to implement the update in the code or is this done automatically?
If I try it on my setup now I get the error message that the device is already set up.

**Comment by frenck** [comment]
@starkillerOG The abort method accepts fields to update in the existing entry. For example, this could handle something like this in the config flow:

```py
await self.async_set_unique_id(some_mac_address)
self._abort_if_unique_id_configured(updates={CONF_HOST: user_input[CONF_HOST]})
```

This updates the existing config entry for the mac address and reloads the entry.

**Comment by starkillerOG** [comment]
@fplanjer This PR https://github.com/home-assistant/core/pull/68589 will allow you to update connection settings such as IP by simply starting a new config flow withouth removing the integration.

**Comment by starkillerOG** [comment]
@frenck thank you very much for your help and explanation!
