### ISSUE TITLE
Provide information how to disable Home Assistant Cloud

### ISSUE THREAD

**Issue by chrismanivong** [home-assistant/home-assistant.github.io#22096]
### Feedback

Currently there is no documentation how to disable the Home Assistant cloud integration unless removing the line of "default_config:". As this has several impacts, it should be documented how the option to disable cloud should look like.

### URL

https://www.home-assistant.io/integrations/cloud/

### Version

2022.3.5

**Comment by frenck** [comment]
> As this has several impacts, it should be documented how the option to disable cloud should look like.

I'm not sure what you are trying to suggest? Removing the `default_config` is the only way to do that, which is already mentioned?

**Comment by jwshields** [comment]
@chrismanivong If I am reading your question correctly, I believe you're asking what is needed to replace `default_config` in order to remove it and disable things such as `cloud`, is that right?  
I found these two pages which seem to detail the components involved as part of `default_config` - but the two lists differ. I wonder if it's a matter of the documentation lagging behind the code? Not 100% sure.  
I do wish this information was easier to find though, and less of an inverted way to figure out what to remove/keep and how to actually do it.

In any case, take a look here:  
https://github.com/home-assistant/core/blob/dev/homeassistant/components/default_config/manifest.json
https://www.home-assistant.io/integrations/default_config

In my setup, I have commented out `default_config` and only added the components from those lists that I am interested in. Works well and I've not noticed any issues in what I've selected.

**Comment by LordNex** [comment]
Bump

**Comment by jwshields** [comment]
@LordNex Check out the links I posted. They show which components `default_config` enables.  
You can remove `default_config` and pick and choose from the listed components in those links.  
But there's risk you could break HA if you remove the wrong item(s), so tread carefully if you go that route.
