### ISSUE TITLE
Prequesists

### ISSUE THREAD

**Issue by tazginpax-ho** [home-assistant/home-assistant.github.io#22208]
### Feedback

Where can i find the sensors Prerequisites to be shown in dashboard like "last reset" or "device class" and some instructions to add them via customizations? I can only find help in forum, but should here be something?

### URL

https://www.home-assistant.io/docs/energy/faq/

### Version

2022.3.8

**Comment by frenck** [comment]
> Prerequisites to be shown in dashboard like "last reset" or "device class" and some instructions to add them via customizations? 

Nowhere, because customizations are not a solution for such a thing. If an integration doesn't support long-term statistics or the energy dashboard properly, please raise an issue. When it's solved, it benefits everyone.

We do not recommend using customize for resolving this.

Thanks! 👍 

../Frenck
