### ISSUE TITLE
Hass.OS inside Raspberry 4 - Ethernet connection does not work

### ISSUE THREAD

**Issue by jdestefanis** [home-assistant/home-assistant.github.io#22226]
### Feedback

I´ve followed the guide, tried with 32 and 64 bits version and they don't work with the eth0 port. The NetworkManager-wait-online.service fails because something must be wrong with the images for Raspberry 4. I could complete the installation by adding manually the wifi by using nmcli command.
Then I tried to add a static IP address from Supervisor section and it didn.t work either. This is a known issue because all the errors are being commented trough all the home assistant community forum and no one found a solution.
It would be great if any of you can create an image that works fine for everyone. I just went back to my original installation on my raspberry 3.
Tried:
Different cables
Different router
Different SD cards.

Nothing worked.
Thanks

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2022.3.8

**Comment by jdestefanis** [comment]
Is there an SLA for answers?

**Comment by frenck** [comment]
No, there is no SLA. This is an open-source project, created by and for the community. It relies on contributions.

Anyways, this issue is created in an incorrect location. You are trying to report an issue with the operating system, however, you have submitted documentation feedback instead.

Please see: https://www.home-assistant.io/help
for where to report issues with that.

Thanks! 👍 

../Frenck
