### ISSUE TITLE
More detailed information on Tasmota MQTT configuration is needed

### ISSUE THREAD

**Issue by ponuryzrzeda** [home-assistant/home-assistant.github.io#22385]
### Feedback

Documentation does not cover details about which MQTT topic is send with autodiscovery. In case the user does not have an ACL on the Mosquitto broker, it does not matter. But when even simple rules are added, generic/default configuration of this integration won't work. It just doesn't autodiscover anything. Docs should contain information on what topic should be allowed in what direction (HA->device, device->HA) and with what permissions (read or read and write).

### URL

https://www.home-assistant.io/integrations/tasmota/

### Version

2022.4.3

**Comment by emontnemery** [comment]
Because of the extreme configurability of Tasmota it's not possible to list some simple rules for a broker's ACL configuration. Also, such documentation should be here <https://tasmota.github.io/docs/> somewhere, not a part of the Home Assistant documentation. 

We could add a general note stating that ACL should either be disabled, or configured such that the message flow between Home Assistant and the Tasmota devices is not obstructed.
