### ISSUE TITLE
Getting started doesn't work

### ISSUE THREAD

**Issue by biot** [home-assistant/home-assistant.github.io#22432]
### Feedback

In keeping with the Home Assistant theme of never being NOT baffling, the "Getting Started" Automation tutorial falls flat. I'm running the latest stable, up to date, new installation.

- The "sun" integration cannot be added via config -> Add integration. It's simply not in the list.
- Turns out you have to make a custom dashboard, add a card, select entity, and there it is! There's an entity called "sun"! Baffling.
- Once that's there, you can use it in an automation. The tutorial is again wrong: there is no orange button.
- Well, of course there's some popup that asks about a blueprint, also not at all mentioned in the tutorial.
- The "Actions" dialogue looks very different from the tutorial.
- You can add empty triggers, actions etc, for no reason.
- When you click Save, you get a message that says "Message malformed: Integration '' not found".

This is not just a matter of the tutorial being out of date. The workflow and UI are fundamentally messed up.
Home Assistant is an egregious violator of the Principle Of Least Astonishment. It is never NOT baffling.

### URL

https://www.home-assistant.io/getting-started/automation/

### Version

2022.4.5

**Comment by dannytsang** [comment]
Hi @biot 
If I could go down your points in order to see if I can help in some way. I am looking at this from a documentation point rather than the software/bug point of view.

> ### Feedback
> 
> In keeping with the Home Assistant theme of never being NOT baffling, the "Getting Started" Automation tutorial falls flat. I'm running the latest stable, up to date, new installation.
> 
>     * The "sun" integration cannot be added via config -> Add integration. It's simply not in the list.
Is this on the https://www.home-assistant.io/getting-started/automation/ page or somewhere else?

> 
>     * Turns out you have to make a custom dashboard, add a card, select entity, and there it is! There's an entity called "sun"! Baffling.
Does it prevent you from creating the automation using the sun as a trigger until you have done the above step?

> 
>     * Once that's there, you can use it in an automation. The tutorial is again wrong: there is no orange button.
> 
>     * Well, of course there's some popup that asks about a blueprint, also not at all mentioned in the tutorial.
> 
>     * The "Actions" dialogue looks very different from the tutorial.
Agreed and I think the above suffers from being out of date from the current release.

> 
>     * You can add empty triggers, actions etc, for no reason.
Is this related to the https://www.home-assistant.io/getting-started/automation/ page or a general observation?
> 
>     * When you click Save, you get a message that says "Message malformed: Integration '' not found".
Looking at your above points, can you confirm you still don't have the Sun integration added when you created the automation please?

**Comment by dannytsang** [comment]
> > ```
> > * The "sun" integration cannot be added via config -> Add integration. It's simply not in the list.
> > ```
> 
> Is this on the https://www.home-assistant.io/getting-started/automation/ page or somewhere else?
> 

Ignore that. I can see that in the docs and it has been reported in #22345
