### ISSUE TITLE
Errors code of shell_command integration !

### ISSUE THREAD

**Issue by vincegre** [home-assistant/home-assistant.github.io#22827]
### Feedback

Hi

I try to use the shell_command integration but documentation is quite light and no documentation at all on error codes that it can generate ! Right now I have an error 127 on a shell command I kill my head to get running and have no way to know what is the problem as that error code is not documented :(

Thanks for consideration

Vincèn

### URL

https://www.home-assistant.io/integrations/shell_command

### Version

2022.5.5

**Comment by frenck** [comment]
> and no documentation at all on error codes that it can generate

That is because it's not the integration that generates the error codes, but the commands you run.

> Right now I have an error 127 on a shell command I kill my head to get running and have no way to know what is the problem as that error code is not documented :(

So, we cannot document that, as those error codes are different for each command (the command you run/configure yourself). Please consult the documentation of the command you run for information about their exit codes.

As for exit code 127, that is a common code defacto used for things like (sub)command or job not found.
