### ISSUE TITLE
Information lack?

### ISSUE THREAD

**Issue by danlun** [home-assistant/home-assistant.github.io#22918]
### Feedback

Hi, its hard to understand which Renault models that this integration works for. It feels a bit like its only for the electric Megan's not fuel, but that can be a mistake from my side. I have petrol version from 2017 Megane and have a cloud account. I used my credential when setting up the integration via UI but only get sensors with no values.
I personally would appreciate a more detailed explanation around this things in the documentation.
thanks
Dan

### URL

https://www.home-assistant.io/integrations/renault/

### Version

2022.5.5

**Comment by RandyAndy1965** [comment]
I have an Arcana. I see the milage (sometimes) but other sensors are not filled.

**Comment by epenet** [comment]
I think this is the wrong place for this discussion.

If you have correct data in the official renault phone app that is not available in Home Assistant, then you need to open an issue in https://github.com/home-assistant/core or in https://github.com/hacf-fr/renault-api
If you do not have any data in the official renault phone app, then I suggest that you open instead of PR to say that vehicle XXX is not supported

**Comment by epenet** [comment]
There is also a known issue linked to recent Renault updates here: https://github.com/home-assistant/core/issues/73701

**Comment by frenck** [comment]
Closing the feedback suggestion, as per above comments.
