### ISSUE TITLE
Files and file locations

### ISSUE THREAD

**Issue by TangoOversway** [home-assistant/home-assistant.github.io#22981]
### Feedback

This directory specified has a lot of subfolders and configuration files. It would help to have more of an explanation. For instance, if I'm trying to copy my configuration files and copy all of the information unique to this system, do I have to recursively copy all directories here or are there certain areas I need to deal with? (If someone is asking this question, they're very likely to want to be able to get all their information transferred or backed up to create a 2nd system or to restore it.

### URL

https://www.home-assistant.io/faq/sdcard_files/

### Version

2022.6.1

**Comment by dannytsang** [comment]
Hi @TangoOversway 

I believe the FAQ is specifically for finding where your files are stored rather than a detailed guide on the directory and files.

In terms of your example of why you want to know more about the directory structure, does this page help? https://www.home-assistant.io/common-tasks/os/#backups

**Comment by TangoOversway** [comment]
Thank you for responding!

Okay, that helps a lot more than the page I was on!

I’d like to bring up a related point: If someone is trying to find files on a crashed version of HA (like I was - after my backup RAID also had issues), it’d be really helpful if there were some material on which partitions to look on when trying to find files from another system. For instance, I found a lot, probably everything, in /hassos-data/supervisor/ - but since I don’t have it in front of me, I may misremember. I don’t know if there was another folder in there that contained supervisor. It’s a bit confusing to try to mentally relocate from the normal directory tree to sorting through the partitions on the drive.

Again, thank you for responding!


Hal

**Comment by dannytsang** [comment]
@TangoOversway I would recommend using the [backup](https://www.home-assistant.io/common-tasks/os/#backups) feature in Home Assistant. It does a pretty good job of taking a snapshot and allow a full restore of your system from the setup screen of a fresh install. The backup page lists the folders it backups up so if it's good enough for the out of the box backup feature then that's a good list of folders to backup.

The backups will be created and stored on your Home Assistant so you it wouldn't help you in this case because you would still need to go to the file system and to get them.

To get the backups off the device there are several options like the Samba Backup addon to storing it in [Google Drive](https://github.com/sabeechen/hassio-google-drive-backup) (if you're comfortable with storing data with Online/Google)
