### ISSUE TITLE
your chart shows NOTHING. What was it's point?

### ISSUE THREAD

**Issue by Cannonball57** [home-assistant/home-assistant.github.io#23053]
### Feedback

The initial question asked was:  "where is Supervisor and Configuration that is now missing in the Side Bar?"
and the answer was a chart showing it missing, but the chart didn't have any association as to what version of the HAOS it referred to.  what's up with you guys?
You should label yourselves CLOSED SOURCE

### URL

https://www.home-assistant.io/installation/

### Version

2022.6.4

### Additional information

Please add Supervisor and Configuration to the next version and have them functional.

**Comment by frenck** [comment]
Nothing in this feedback provides any constructive feedback for the documentation.

Going to close this issue for that reason. Based on the last sentence in your feedback, it seems you are here to release frustration rather than to provide feedback.

**Comment by Cannonball57** [comment]
Frustration because there is NO feedback nor any answers to peoples frustration as to why Supervisor, Restoration of backups and “Configuration” is missing in the HA sidebar.  If you feel that the answer to my frustration is to just “Close” the ticket, you’re a pretty pathetic moderator, programmer or whatever.  I guess it’s “No soup for me”, I’m now labeled assholic

**Comment by frenck** [comment]
> Frustration because there is NO feedback nor any answers

I think you misunderstood the form you submitted. It's not a support form.

If you are in need of support or have questions, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

>  as to why Supervisor, Restoration of backups and “Configuration” is missing in the HA sidebar.

The "Configuration" menu has been renamed to "Settings", the "Supervisor" menu has been fully merged with the existing "Settings" menu.

This has recently changed, in Home Assistant 2022.5: <https://www.home-assistant.io/blog/2022/05/04/release-20225/#reorganized-settings-menu>

>  If you feel that the answer to my frustration is to just “Close” the ticket, you’re a pretty pathetic moderator, programmer or whatever.

I closed it because of that exact tone and expression of frustration (instead of providing feedback). It's the tone that makes the music 🎶

../Frenck

**Comment by Cannonball57** [comment]
That’s OK, I received my answers elsewhere  and all is fine.

**Comment by Cannonball57** [comment]
Thank you for the “recently changed items for 2022.5” link.  Danny has been very helpful.  My initial frustration may have been a bit too much, but when I Googled for this information, all paths went to your forums.  Then, after seeing all of the other “Unanswered” or even commented on inquiries, something had to be said.  If even one of those other inquiries was answered with “This is not the forum for inquiries, go here….“, I would have followed that.
As, I told Danny, thank you
Tom
