### ISSUE TITLE
SQL Sensor

### ISSUE THREAD

**Issue by nickrout** [home-assistant/home-assistant.github.io#23066]
### Feedback

Now that this is moved to the UI, the quotes around the sql query do not work and should be removed from the examples. The examples variously use `"`, `'` and no quotes. Only no quotes works in UI.

Also I think the sentence "The SQL integration will connect to default recorder if Database URL is not specified." should read "The SQL integration will connect to sqlite if Database URL is not specified. If you use a different database recorder (eg MariaDB), you will have to specify the Database URL"

### URL

https://www.home-assistant.io/integrations/sql/

### Version

2022.6.4

**Comment by bcutter** [comment]
> The examples variously use `"`, `'` and no quotes. Only no quotes works in UI.

Can you explain why (**is there a documentation for this?**)? Trying to add a SQL integration via the UI for hours, it consistently refuses to accept the SQL statement. Doesn't matter if ", ' or no quotes are used.
https://community.home-assistant.io/t/sql-integration-not-accepting-sql-statement/441015/2

**Comment by romlisrl** [comment]
Yeah, new SQL integration mentioned as pain in the ass.

**Comment by gjohansson-ST** [comment]
Issue should be closed as PR was merged

**Comment by romlisrl** [comment]
Played around the SQL integration. 
It's possible to create the sensor providing only database address and query (in my case MariaDB), but when is needed to provide unit_of_measurement, the UI will ask you to provide value_template too (it was mentioned as optional), the same happens when you try to edit query in SQL integration. In my situation I not use template, therefore I'm unable to set unit of measurement for the query result.
Thanks and sry 4 trbles.

**Comment by gjohansson-ST** [comment]
> but when is needed to provide unit_of_measurement, the UI will ask you to provide value_template too (it was mentioned as optional),

That should not be the case. Please open a new issue so that it can be tested and corrected.

**Comment by nickrout** [comment]
Resolved in docs now, my pr finally got merged. I think I need to improve me githib-fu.
