### ISSUE TITLE
Home Connect documentation Integration

### ISSUE THREAD

**Issue by Atomiiik** [home-assistant/home-assistant.github.io#23095]
### Feedback

Hello, i was using home Connect integration and i would like to notice 2 things for make it work : 

- Redirect URI in Home Connect Developper Application must be your PUBLIC internet IP address with PORT FORWARDED to your HA ( open access to HA on on your firewall / router)
- for adding the plugin, log in to HA from PUBLIC internet visible address - this is very important step - because can't add plugin from local URL

I think it's import to add this point in the documentation

### URL

https://www.home-assistant.io/integrations/home_connect/

**Comment by wowtor** [comment]
Can't get this plugin to work, even with the instructions above.

* I followed the setup instructions at `https://www.home-assistant.io/integrations/home_connect/`
* Home Connect application setup has redirect uri: `https://MYNAME.duckdns.org/auth/external/callback`
* The `configuration.yaml` has `external_url` set to `https://MYNAME.duckdns.org` and the `internal_url` is `https://homeassistant.local`
* Connect to the Home Assistant gui via the external URL and add the Home Connect integration

The result is the error "client or redirection URI not authorized", and the redirect URL in the browser shows `https://my.home-assistant.io/redirect/oauth`. Whatever I do, the redirect URL keeps pointing to the Nabu Casa URL instead of my own. Am I overlooking something?

*EDIT:* fixed the issue by registering the URL `https://my.home-assistant.io/redirect/oauth` in Home Connect, in addition to the internal URL. (The public URL may have worked as well, did not try that.) HA version is 2022.8.6.
