### ISSUE TITLE
More metadata for components and filter in searches

### ISSUE THREAD

**Issue by Zac-HD** [home-assistant/home-assistant.github.io#2310]
I can't be the only person who has used [the component docs](https://home-assistant.io/components/) as a shopping list - it's a great resource, and you can be confident that supported devices are (a) supported by homeassistant and therefore (b) not locked down to the point of uselessness.

However, it would be even better if components were tagged with and searches could be filtered by a number of attributes (stored in eg a `tags:` dict in the header).

- discoverable: true/false
- requires_internet: always/setup/never
- official_api: true/false
- iot_device_security: ok/weak/broken (if relevant)

These are example properties, but they illustrate the idea.  Thoughts?

**Comment by bdurrer** [comment]
The discoverable components can easily be found on the discovery component page.
For the others... one would need to crawl through those 603 components and add the required metadata.

Personally I don't see all too much value in the _suggested_ properties, but I see your point. A lot of components are assigned to an category but would fit into multiple categories. E.g. an camera being a _sensor_ and, well, a _camera_
... so yeah, tagging in general would help a lot


I would happily extend the search feature, but I'm not the one going to add tags to the components 😄

**Comment by Zac-HD** [comment]
Sounds good!  I agree that there should be some more discussion about what tags we should use (they're just examples).  And if someone else can write the search function, I'm willing to do the tagging.  It would be good to have Travis check that the header is in order though, to ensure that the tags stay up-to-date and new components are tagged too.

**Comment by petersohn** [comment]
I would be happy to be able to search by IoT class.

**Comment by balloob** [comment]
Yeah, we also already fill in the IoT class, so that should be easy.

Another one I would like to see is a url-only search option to search by version. Right now for each release blog post I link to the "released in current version" section, but each new release will have old release blog posts link to the wrong components.

**Comment by bdurrer** [comment]
@balloob I'll add that. Is there any reason to keep the three `#added_in_...` tags, if the overview links to the version hashes instead?

**Comment by balloob** [comment]
No, we can drop those categories if we can just generate links for the last 3 versions.

**Comment by bdurrer** [comment]
So, here is the thing: adding more metadata to the search does not improve it's quality. searching for "polling" looks like garbage, because you can't see _why_ you got those results.

There are two ways I see right now:

1. add grouped items into the sidebar and maybe add some headers (eg versions, categories, IoT class)
2. make the search "smart" with meta tags, eg you can enter `iot: polling` to only filter for iot classes.

Problems:
- the category list is already long, adding more parts does not really make it more beautiful
- I guess nobody will ever discover the meta-search feature.

**Comment by balloob** [comment]
Maybe we can add a 'filter' bar a la Google images?

![image](https://cloud.githubusercontent.com/assets/1444314/26136478/2bb22400-3a71-11e7-9aac-f57243e7f6ef.png)

I agree that the number of categories is huuuge but I don't really think that we should kill any.

**Comment by bdurrer** [comment]
I like that idea! Hm, it might be useful to introduce a gui framework onto the component page ... Any preferences? Maybe Vue? (I think polymer in combination with the current jenkyll build would drive me crazy :innocent:]

Do you think the categories should also just be one of the filter dropdowns? maybe the sidebar isn't required anymore then?

**Comment by balloob** [comment]
I would be down for Vue, never done it myself but would be cool to see how it works. Wouldn't mind Preact either as that's what I just introduced it to the HA frontend too (for the automation editor).

I am not sure if we should hide the categories. It's kinda nice to have them but I guess we might want to go more to an app style structure: show list of categories -> show list of components -> show component info (on a new page). I guess it's something we should experiment with :)

**Comment by bdurrer** [comment]
ok, I'll check out Preact too before I decide.

oh wow there is an automation editor now? I'm almost done with a blockly wysiwyg front-end, I guess I can stop working on that now 😊

**Comment by Landrash** [comment]
Any further that this should be expanded or can we consider it done?

My quick guess is that additional filters for presently available information in the documentation should be done to https://github.com/home-assistant/home-assistant.github.io/blob/next/source/components/index.html

**Comment by bdurrer** [comment]
@Landrash yes, it's the components index page. The release anchor thing is done, but not the main request (searching for additional metadata).

I _did_ start with the suggested filter dropdowns (it's not pushed to anywhere yet). I recently became a father, so the main problem is my lack of free time. I hope to get it done in august.


In the meantime,

**Comment by Landrash** [comment]
Congrats @bdurrer . My turn in mid September :tada: .
If you don't mind I'll ask a friend of me to have a look at it? 

Calling @hampzter . This is the one I was talking about :grin:

**Comment by bdurrer** [comment]
Thanks :)
Sure do. I started with Vue and it's blazing fast, the rendering and
filtering are instant, even on IE. I can push my current state on monday,
if needed. It ecen comes with its own js build, since the docs build is
horribly slow :-)

But doing it in React would probably make sense, because we already use
it...

Am 01.08.2017 15:32 schrieb "Fredrik Lindqvist" <notifications@github.com>:

**Comment by bdurrer** [comment]
I'm looking forward for a PR, @hAmpzter - I'm still trapped in the carry-baby-around endless-loop  😆 and I don't think I'll have time to work on this issue in the next weeks
