### ISSUE TITLE
default port 

### ISSUE THREAD

**Issue by acfnews** [home-assistant/home-assistant.github.io#23186]
### Feedback

Can the default TCP port be mentioned  in the 'configuration / path' section:

According to this topic :  https://www.domoticaforum.eu/viewtopic.php?t=13438&sid=f0c7225c9f97a60dd771088abba3cb90

it should be : socket://192.168.1.138:25238

### URL

https://www.home-assistant.io/integrations/opentherm_gw/

### Version

2022.6.7

**Comment by mvn23** [comment]
The OpenTherm Gateway is designed as a serial device, not as a network device. When using a `socket://`-type url to connect to the gateway, you're essentially connecting to an additional device (in your case an ESP8266) which is taking care of the transfer of network traffic to the serial port and vice versa. This additional device has its own firmware and settings and depending on the firmware in use, the default port will be different (mine defaulted to 23).
Because of this, there is no such thing as a default port for the OpenTherm Gateway. There are only default ports for each firmware that may be in use to translate between the serial and network connections. Therefore, the correct place for this information is in the documentation of the specific firmware in use. For Robert's ESP8266 OTGW-firmware it is clearly stated [here](https://github.com/rvdbreemen/OTGW-firmware/wiki/How-to-use-it-with-Home-Assistant-or-Domoticz-or-others#serial-2-network) which port should be used.

**Comment by frenck** [comment]
Closing this feedback, as there is no "standard" or default port for this integration.
