### ISSUE TITLE
Recommend 32 bit Raspbian

### ISSUE THREAD

**Issue by markolbert** [home-assistant/home-assistant.github.io#23244]
### Feedback

I encountered quite a few problems getting scripts and what not to work while configuring a Pi to use HA via a docker container. 

They all appeared to be related to my having initially chosen to use the 64 bit version of Raspbian (this was on a Pi4). All the problems went away when I switched to 32 bit Raspbian.

If there is a basic dependency on the 32 bit version I think that should be highlighted in the installation instructions.

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2022.6.7

**Comment by frenck** [comment]
We actually recommend 64 bits, for everything and work with that everywhere as well.
32 bit is slowly going away in this world (see for example Ubuntu, they don't ship 32 bits in their last release even).

If you experience an issue, please file an issue with 64 bits setups (and if the requirements otherwise are met), please file an issue. in our Core issue tracker 👍 

../Frenck

**Comment by markolbert** [comment]
Do you know of documentation/setup instructions on installing HA via a docker container for 64 bit environments? Because following the existing instructions on the HA site simply do not work for the docker approach. And I'm not sure the HA team would appreciate a bug report that simply says "hey, those instructions you've posted don't work" :).

**Comment by frenck** [comment]
The instructions work actually, and are verified regularly. If it doesn't work, please provide the exact steps for reproduction.

**Comment by markolbert** [comment]
:) clearly not the case -- unless you want to argue I'm hallucinating :) -- but I don't want to argue the point. I'll invest some time documenting what I ran into and submitting the reports.
