### ISSUE TITLE
Docker instructions /explanation what it is is poor.

### ISSUE THREAD

**Issue by blairthornton** [home-assistant/home-assistant.github.io#23257]
### Feedback

Your guide says: This guide assumes that you already have an operating system setup and a container runtime installed (like Docker)." =- when it is indeed NOT obvious as you think for new users. I have NO Supervisor Icon under developer tools and have no clue how to get it. Documentation is very lacking and I am stuck.

### URL

https://www.home-assistant.io/installation/raspberrypi

### Version

2022.6.7

### Additional information

so frustrating, your documentation sucks IMHO.

**Comment by klaasnicolaas** [comment]
At which step do you run into problems?

btw this is not the place for support questions, just documentation feedback. For further support I would like to refer you to the community forum or the Discord server.

**Comment by blairthornton** [comment]
How do you get Supervisor into your menu between settings and Developer Tools. It's NOT obvious from your documentation.

Blair Thornton
DIT/DOP/Editor - [Experience Nova Scotia](http://www.visitingnovascotia.com/?page_id=4393)
***@***.***
(416) 917-9740

**Comment by klaasnicolaas** [comment]
That is not possible, in recent updates the supervisor has been removed from that location and placed under **settings** -> **system**, which is why it is not in the documentation either. If you really want the supervisor back in the sidebar you could try something like this: https://community.home-assistant.io/t/supervisor-2021-12-2-is-missing-on-side-panel/373502/6

If there are no further suggestions for concrete changes to the documentation, I will gladly close this issue.

**Comment by blairthornton** [comment]
Supervisor is also MISSING in settings -> system

Your documentation and instructions TOTALLY SUCK. Using HA OS image.

Blair Thornton
DIT/DOP/Editor - [Experience Nova Scotia](http://www.visitingnovascotia.com/?page_id=4393)
***@***.***
(416) 917-9740

**Comment by klaasnicolaas** [comment]
With this tone I kindly refer you to the community forum or discord server for help. I'm not extracting any documentation feedback from this, so I'm closing the issue.
