### ISSUE TITLE
General remark on Integrations to be set up via the interface

### ISSUE THREAD

**Issue by Spiffo** [home-assistant/home-assistant.github.io#23301]
### Feedback

For integrations that can be set up via the user interface, it would be useful to have an explanation of the fields that need to be entered. I am trying to add the Notifications for Android TV / Fire TV integration to my system, but don't know what to fill in for Host (ip address of tv does not work, name of device also does not work).
This information should be shown on the documentation page, and if possible also on the configuration popup when you add the integration.
since this is for both the documentation and for core, I wasn't sure where to enter this ticket

### URL

https://www.home-assistant.io/integrations/

### Version

2022.7.0

**Comment by frenck** [comment]
> ip address of tv does not work

The host can be a (m)DNS name or indeed an IP address.
So, that you have correct.

IP address should work. So you are either looking at setting it up incorrectly, or a bug.

../Frenck

**Comment by Spiffo** [comment]
That's a quick reply :)
Got IP from the States tab. Will try again later today. Thx.
General remark does stand though :)

**Comment by frenck** [comment]
> That's a quick reply :)

<img src="https://media2.giphy.com/media/S6BLhq4ZOvIdN0WVEQ/giphy.gif"/>

> General remark does stand though :)

:)
We are aware and have been adding these things to the UI itself. Very recently we introduced the possibility for integrations to add descriptions to the fields in the UI. Which is IMHO even better.

However, "Host" is a very generic and commonly accept term (since the dawn of networking and computer long long long time ago) that I would doubt that anyone would actually provide a description for 🤷

**Comment by Spiffo** [comment]
thanks !
