### ISSUE TITLE
Minor point - Rust missing on Ubuntu 22.04 LTS server

### ISSUE THREAD

**Issue by znac049** [home-assistant/home-assistant.github.io#23358]
### Feedback

Just installed a clean Ubuntu 22.04 LTS on a Raspberry Pi 4 and followed the instructions from the URL below. The following command failed initially:

**pip3 install homeassistant**

With an error indicating that the encryption (module?) couldn't be built due to not being able to find a Rust compiler. I ran the following command:

**apt install rust-all**

Now when I rerun the pip3 install homeassistant command, everything ran fine.

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2022.7.3

**Comment by frenck** [comment]
As per documentation, depending on your installation/setup, things might work different a bit:

![CleanShot 2022-07-11 at 15 56 29](https://user-images.githubusercontent.com/195327/178280775-f1d73436-4b81-4037-9667-8f0a00a53d48.png)

We assume one is able to handle those differences, otherwise, we recommend not using this installation method.

../Frenck
