### ISSUE TITLE
No Documentation on how to fix issue on Raspberry Pi without GRUB

### ISSUE THREAD

**Issue by NightBlackCat** [home-assistant/home-assistant.github.io#23639]
### Feedback

Documentation requires GRUB to fix unsupported error.  

Since Raspberry Pi doesn't use the GRUB bootloader, the documentation doesn't help you fix the issue on a Raspberry Pi.

At the bottom of the page it says:

"Perfect to run on a Raspberry Pi or a local server"

So I think it should be covered.

### URL

https://www.home-assistant.io/more-info/unsupported/docker_configuration/

### Version

2022.8.0

**Comment by frenck** [comment]
There are many systems out there, most use grub. If you use other setups, we expect a user to be able to handle that. Please note, that the system you are running is your choice and your responsibility in that case.

The reason you end up on this page is that you run an unsupported setup caused by external factors for Home Assistant. Factors are created by you, not us.

If you are able to manage such a system, we recommend considering a different installation method (e.g., using Home Assistant Operating System that takes away the need to take care of things like this).

../Frenck
