### ISSUE TITLE
developer tool - service won't run for google calendar create_event.

### ISSUE THREAD

**Issue by robertfgoodworth** [home-assistant/home-assistant.github.io#23642]
### Feedback

Developer tools - Services, when using "Google Calendars: Create event" does not allow you to select the calendar entity-id, therefore you can't call the service. I had multi calendars so may be different if you only have one.

To address this go into "yaml" mode and add your calendar entity id after "service:" and before "data:" as follows.
this is sample data: change this to your needs.

service: google.create_event
entity_id: calendar.<replace with your calendar entity name here>
data:
  summary: Bowling
  description: Birthday bowling
  start_date_time: 2022-08-06T09:00:00.000Z
  end_date_time: 2022-08-07T12:00:00.000Z
 
Now you can call the service
Hope this helps others

### URL

https://www.home-assistant.io/integrations/google/

### Version

2022.8.0

**Comment by robertfgoodworth** [comment]
should be

service: google.create_event
entity_id: calendar.replace with your calendar entity name here
data:
  summary: Bowling
  description: Birthday bowling
  start_date_time: 2022-08-06T09:00:00.000Z
  end_date_time: 2022-08-07T12:00:00.000Z

**Comment by allenporter** [comment]
I tested this on a dev build and I was able to use the UI to select an entity and create a calendar event :

<img width="1153" alt="Screen Shot 2022-09-04 at 11 28 32 AM" src="https://user-images.githubusercontent.com/6026418/188328258-505ce452-f28d-4be7-ab05-aaacf242d023.png">

I think I may have seen there was an issue in the frontend with the selector when using an integration so that may explain why it now works if it didn't before.
