### ISSUE TITLE
For containers check SELinux

### ISSUE THREAD

**Issue by arifNIH** [home-assistant/home-assistant.github.io#23672]
### Feedback

For containers running on Red Hat type system (eg CentOS, ALma, Rocky, etc) please check SELinux if your container cannot talk to bluetooth devices.

I had to create a new SELinux policy to get this to work.

### URL

https://www.home-assistant.io/integrations/bluetooth/

### Version

2022.8.1

**Comment by f-zappa** [comment]
I'm running docker on ubuntu and have a comparable issue, but with AppArmor instead of SELinux. Unfortunately I have no idea how to allow the access. Hope someone can give me a hint.

Config entry 'Bluetooth' for bluetooth integration not ready yet: Failed to start Bluetooth: [org.freedesktop.DBus.Error.AccessDenied] An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender="(null)" (inactive) interface="org.freedesktop.DBus" member="AddMatch" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus); Retrying in background
