### ISSUE TITLE
The provided bindkey did not work

### ISSUE THREAD

**Issue by dennisleussink** [home-assistant/home-assistant.github.io#23764]
### Feedback

I'm trying to connect my LYWSD03MMC device to Home Assistant using the new Bluetooth integration.

I already connected my Switchbot devices using the ASUS Bluetooth 5.0 USB-adapter.

When I try to add the LYWSD03MMC by entering the bindkey using https://atc1441.github.io/TelinkFlasher.html I get the following error: 

The provided bindkey did not work, sensor data could not be decrypted. Please check it and try again.

Any idea what this issue can be? The device is running stock firmware.

Thanks,
Dennis

### URL

https://www.home-assistant.io/integrations/xiaomi_ble/

### Version

2022.8.4

**Comment by Jc2k** [comment]
Hi - this is the wrong place to ask for help. This is where we manage the documentation. I'm going to close this now.

But I will say: Please make sure you generate the bindkey before you start. Some of these devices don't broadcast very often, so you then need to wait to make sure home assistant has seen a broadcast with the new bindkey, otherwise it might be checking against the old one. Minimum 10 minutes, ideally longer.

I'm hoping to integrate the bindkey generator into the config flow in a future release so most users won't even see what a key looks like. Hopefully that will make this a lot easier.
