### ISSUE TITLE
Clearification about Mains Configuration

### ISSUE THREAD

**Issue by nicknickalive** [home-assistant/home-assistant.github.io#23975]
### Feedback

Would it be helpful to detail how the mains should be configured? i.e. should they be "Allow negative power value" or not? Should they read positive or negative when feeding back to the grid for the math to work out for home assistant ? 

### URL

https://www.home-assistant.io/integrations/iotawatt/

### Version

2022.8.7

**Comment by tvl9ops** [comment]
What I did was to allow for negative values, otherwise it shows the absolute value, which is not correct. Since HA expects only positive values I created special outputs with the `max()` function for GridReturn and GridComsumption to show always zero when it goes negative. If you reload the iotawatt integration, you'll see the new outputs as new sensors in HA.

**Comment by tvl9ops** [comment]
Actually HA should be much more configurable what concerns negative and positive values, because now there needs to be double transformations to please the rigid energy model of HA.
