### ISSUE TITLE
Torque integration been broken for years.

### ISSUE THREAD

**Issue by TRusselo** [home-assistant/home-assistant.github.io#24615]
### Feedback

https://github.com/home-assistant/core/issues/44241
https://github.com/home-assistant/core/issues/31166
https://github.com/home-assistant/core/issues/28836
https://github.com/home-assistant/core/issues/1515

https://community.home-assistant.io/t/wth-why-is-it-so-difficult-to-setup-torque-obdii-in-ha/470697/4

@dshokouhi 

### URL

https://www.home-assistant.io/integrations/torque/

**Comment by dshokouhi** [comment]
The torque integration is separate from the companion app so I will not be able to help with that. My comment was based on how ot use the companion app to leverage the torque intent system.  We should not be updating this documentation with companion app specific things as those are already documented on the companion site as mentioned in the WTH linked.

**Comment by skyborgff** [comment]
What do you mean by broken?
Check if this change helpes you get it working https://github.com/home-assistant/home-assistant.io/pull/24472 .
I can confirm that the torque integration works, although it needs some love. I'm working on a new improved one.

**Comment by nathan-curtis** [comment]
In addition to the endpoint being jacked, it still uses old auth, does not group its sensors by name or integration and dumps all the sensors on restart so you can't rely on them. So yeah. Completely broken

**Comment by frenck** [comment]
This is the issue tracker for documentation feedback, however, it seems like you want to report issues with an integration. This issue is therefore reported in an incorrect issue tracker.

../Frenck

**Comment by nathan-curtis** [comment]
happy to Frenck, have no clue where to do that and the only other issue Ive seen for the integration was closed as stale with no owner ever assigned?  Pointer is welcomed, please?

**Comment by frenck** [comment]
If you are unsure where to go, please check

https://www.home-assistant.io/help

Reporting issue for integrations go into the core issue tracker:

<https://github.com/home-assistant/core/issues>

../Frenck

**Comment by skyborgff** [comment]
@nathan-curtis The endpoint issue is not something we can change in home assistant. it is due to the internal logic of the torque app that normally discards ports.
Would it be ok if i ping you when i do my pr of the new torque integration so you help test it?
`uses old auth` - Do you mean the token we have to put in the torque app? if so, what would you suggest as an improvement?
`does not group its sensors by name or integration` - Fixed (if i understood your point)
![image](https://user-images.githubusercontent.com/19365140/199478645-e5ca6e39-7de5-4eb8-8d07-fe6a049b8fab.png)
![image](https://user-images.githubusercontent.com/19365140/199478710-553156ad-a573-4419-9350-bb0d9bb927f8.png)
`dumps all the sensors on restart so you can't rely on them` - Fixed.
I hit a wall trying to flag the old integration as deprecated so people would configure the new one in the ui, so i didn't bother more with it, but seeing the interest i'll create the pr this week

**Comment by vmonkey** [comment]
@skyborgff Are there any news on this? I am also happy to test/help otherwise

**Comment by skyborgff** [comment]
> @skyborgff Are there any news on this? I am also happy to test/help otherwise

i really just forgot, i'll try to upload this week, I would indeed likesome help with the migration, to see if it smooth enough, although i havent managed to make the ui flag the old one as deprecated yet

**Comment by marcelodavanzo** [comment]
Happy to help test this too

**Comment by skyborgff** [comment]
I have been without my vehicle for a couple months now, I should get it back in a few weeks. Thus, I haven't been able to test the changes, but it is not abandoned

**Comment by sondreen** [comment]
> I have been without my vehicle for a couple months now, I should get it back in a few weeks. Thus, I haven't been able to test the changes, but it is not abandoned

Hi! Will you comment here or similar when/if you push any changes? Thanks! :)

**Comment by skyborgff** [comment]
> > I have been without my vehicle for a couple months now, I should get it back in a few weeks. Thus, I haven't been able to test the changes, but it is not abandoned
> 
> Hi! Will you comment here or similar when/if you push any changes? Thanks! :)

https://github.com/home-assistant/core/pull/86756#issuecomment-1405768459

You can follow it here, i'm still without my car tho
