### ISSUE TITLE
Trouble integrating into energy configuration

### ISSUE THREAD

**Issue by calenkennett** [home-assistant/home-assistant.github.io#24672]
### Feedback

When I try to add my solar panels into the energy configuration, the entities for current power consumption and production don't show up in the list, just the aggregates, like today or 7 day energy production. It says to point the developer to https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

Thanks so much for making this!!! It's amazing! 

### URL

http://192.168.86.65:8123/config/energy

**Comment by klaasnicolaas** [comment]
Power and energy are two different things, [as described here](https://www.home-assistant.io/docs/energy/faq/#energy-vs-power). That's why you can't choose your power production and consumption entities. So for your solar panels you need the entities that keep track of a day or total energy production.
