### ISSUE TITLE
efibootmgr command line is wrong

### ISSUE THREAD

**Issue by HorizonKane** [home-assistant/home-assistant.github.io#24919]
### Feedback

When the efibootmgr command line is copied from the site:

`efibootmgr --create --disk /dev/<drivename> --part 1 --label "HAOS" \
   --loader '\EFI\BOOT\bootx64.efi'`

it will create an invalid UEFI boot entry. The backslash after "HAOS" breaks everything.

It should look like:

`efibootmgr --create --disk /dev/<drivename> --part 1 --label "HAOS"   --loader "\EFI\BOOT\bootx64.efi"`

I had a hard time and had to learn a lot about efibootmgr until I was able to figure out that this was the problem. Yeah learned something again, but for others (as the guy who came to me with his device) it might be impossible to figure out.

Device was a Thinkpad M92p.

### URL

https://www.home-assistant.io/installation/generic-x86-64/

**Comment by HorizonKane** [comment]
The mistake is still on that page.

**Comment by DonKracho** [comment]
The \ without anything behind it means that the command line continues in the next line. But when concatinating these two lines indeed the \ has to be removed.

But I agree, in the documentation the command should be written in one line to avoid these obstacles. Also in some linux distributions, e. g. Ubuntu, it requires a **sudo** in front of it in order to be allowed to execute priviledged comands.

**Comment by Tontze** [comment]
very much misleading indeed
