### ISSUE TITLE
Twinkly devices can also be added using the HomeKit Controller integration

### ISSUE THREAD

**Issue by codyc1515** [home-assistant/home-assistant.github.io#25063]
### Feedback

There is no mention on the page that Twinkly devices can also be added using the HomeKit Controller integration.

### URL

https://www.home-assistant.io/integrations/twinkly/

**Comment by GizmoGoody** [comment]
> ### Feedback
> 
> There is no mention on the page that Twinkly devices can also be added using the HomeKit Controller integration.
> 
> ### URL
> 
> https://www.home-assistant.io/integrations/twinkly/
> 
> ### Version
> 
> _No response_
> 
> ### Additional information
> 
> _No response_

@codyc1515 I just came across this post while searching for help with another issue.

But, you could propose a change to the documentation yourself. Look for this section at the link you posted:

![image](https://user-images.githubusercontent.com/46235745/215629685-a8ec5d3d-df1d-4994-bdfe-fe776d1122e6.jpeg)

The LIFX documentation page has a section similar to what you're proposing. You could probably just copy/paste/edit/submit.

Since I hardly know anything about coding, that's how I try to contribute.

**Comment by codyc1515** [comment]
Still current
