### ISSUE TITLE
What is "fire_event"

### ISSUE THREAD

**Issue by SkyLined** [home-assistant/home-assistant.github.io#25117]
### Feedback

I am looking to respond to a button being pressed on a remote. I've added a device that corresponds to the remote's on/off button. I want to trigger an action every time the on or off button is pressed, even if either button is pressed repeatedly. The documentation states:
> Events
> 
> The RFXtrx integration will signal an event on the reception of messages from and RFXtrx device on the following form [sic]. For the signal to be available, the `fire_event` parameter must be set on the device in configuration.

That first sentence is not correct, can you please fix it so it makes sense?
That second sentence mentions a `fire_event` parameter but does not provide enough information to understand what a user is supposed to do. Searching online for that does not return useful results.

Can you please provide more details?

### URL

https://www.home-assistant.io/integrations/rfxtrx/

**Comment by SkyLined** [comment]
Also, the documentation goes on:
> You can set up automations to react to these events. When you do, don’t include more fields than needed. Always include the device identifying fields, `packet_type`, `sub_type` and `id_string`.

However, it does not tell me how I can find out what their value is for a specific device. I assume I should be able to find this information somewhere in HA; please explain how I can get it for my remote's buttons.

**Comment by dannytsang** [comment]
@SkyLined I'm not familiar with this integration so hopefully what I am going to say will help. In terms the first sentence, you can "listen" for events that have been fired/signalled from the [developer tools](https://www.home-assistant.io/docs/tools/dev-tools/#events).

Mine has a list of **Active listeners** so I hope your integration / device is listed otherwise you will have to know what to event type is to "subscribe" (listen) to.

For the second sentence, I'm afraid I have no clue so good luck.

**Comment by SkyLined** [comment]
This issue has not been addressed: the documentation has not been improved.
