### ISSUE TITLE
How to find product id

### ISSUE THREAD

**Issue by Nazahim** [home-assistant/home-assistant.github.io#25197]
### Feedback

How to find the picnic product id of the item you want to add to your cart? I can't find it in the app itself and it's not described how to find it in the documentation either. Adding a product by id would be preferable so you know exactly what you will be adding.

### URL

https://www.home-assistant.io/integrations/picnic/

### Version

2022.12

### Additional information

Thanks for adding this feature to the picnic integration! It opens up a lot of cool new automations :-)

**Comment by GitUpAah** [comment]
Yes I would also really like to know. I already contacted Picnic and asked them if I could receive a list of product IDs but they would not give it :-)

**Comment by Nazahim** [comment]
I have tried to use the EAN code as product id, but this didn't work. The QR codes on the picnic products use the EAN code so i thought maybe this would also be the product id :-)

**Comment by corneyl** [comment]
@GitUpAah I don't think it's very wise to contact Picnic about this, they might reconsider and make their API private. 🤔 

To only ways to get the product IDs is by running the dependency library directly, see https://github.com/MikeBrink/python-picnic-api. Initially I wanted to add a `search` service which would return a list of products, but a service returning data didn't fit the HA architecture.

It might be an idea to add a sensor with the products that are currently in the cart, including their product ID, but I don't know how this would fit into the HA architecture since it can be quite some data.

@vb-git What would you exactly like to have added to the docs? Pointing to a python package is a bit too technical maybe...

**Comment by Nazahim** [comment]
Thanks! According to your reply i now understand that it's hard to explain how to do this as there is no easy way. But people will keep wondering how to use it as it is currently because it doesn't give any info they could go by.

One way it could work is that if the search service would return the found products/id's in the HA log. Then you could look it up over there because once you know an id you're done for that product. If it worked like this the docs could read "Search for the product you want and look up the desired ID in the Home Assistant log."

Maybe it's a good idea to at least add some kind of extra info to the docs of Product Id "ID as used in (link to python api). Recommended to use product_name for ease of use"
