### ISSUE TITLE
DB integration has been disabled in HA 22.11

### ISSUE THREAD

**Issue by Villa-Buenavista** [home-assistant/home-assistant.github.io#25336]
### Feedback

Hi,

this integration shows as "pending removal in HA 22.11". It already has been disbled, or has it?

br

Gunnar

### URL

https://www.home-assistant.io/integrations/deutsche_bahn/

### Version

22.12

**Comment by frenck** [comment]
That is my bad, I simply forgot to remove it.
Will ensure it is gone for the 2023.1 release.

**Comment by Villa-Buenavista** [comment]
ah, it's still there? And I already removed it... 😀
You, it actually works flawless... I understand you guys don't want 
scaping, but there is no replacement integration for Germany. ☹️

Am 19. Dezember 2022 13:46:56 schrieb Franck Nijhof ***@***.***>:

**Comment by frenck** [comment]
> but there is no replacement integration for Germany. 

Anyone is free to run/make it a custom integration. We just don't want to maintain such integration as an official one in our Core repositories.

../Frenck

**Comment by Villa-Buenavista** [comment]
Yeah I know. Fair enough. But why not remove the existing one  when and if 
it breaks?

Am 19. Dezember 2022 16:09:28 schrieb Franck Nijhof ***@***.***>:

**Comment by frenck** [comment]
> But why not remove the existing one  when and if
it breaks?

Three reasons:
1. It currently violates our design rules.
2. We can now phase it out in a controlled way (instead of when it breaks down and cases issues).
3. We have to draw a line somewhere. Someone wanting to add a new integration that does webscraping is likely to point at some that are in core. It is hard/unfair to say no at that point.
