### ISSUE TITLE
Statistics: specify info on max_age & sampling_size

### ISSUE THREAD

**Issue by nathan-gs** [home-assistant/home-assistant.github.io#25506]
### Feedback

It would be great if we can highlight the importance of setting `sampling_size` even when using `max_age` for the `statistics` integration. See more info at: https://community.home-assistant.io/t/statistics-max-age-and-sampling-size/424166

### URL

https://www.home-assistant.io/integrations/statistics

**Comment by nathan-gs** [comment]
I'll write a PR with some improvements.

**Comment by ThomDietrich** [comment]
Hey @nathan-gs,
thanks for your contribution! Sorry to say, but the info in your PR is outdated (as of HA 2022.12), see: https://github.com/home-assistant/core/pull/80999 - The implicit `sampling_size` of 20 was deprecated because of issues like yours :)

That said, I agree that we would benefit from a short paragraph explaining the relation between "samples" and time, especially addressing the fact that unchanged measurements are not considered. Would you like to try another PR or shall I propose something for your review? Cheers!

**Comment by nathan-gs** [comment]
@ThomDietrich good to know! Happy to review
