### ISSUE TITLE
Information missing: Host

### ISSUE THREAD

**Issue by R999UK** [home-assistant/home-assistant.github.io#25607]
### Feedback

On the Roku page (https://www.home-assistant.io/integrations/roku) page click 'Add integration' 
On the Integrations page there is a message box: "Do you want to set up Roku?"
Click 'Yes'
Another message box box asks "Enter your Roku information"....."Host".
There is a question mark which, when clicked, returns you to the Roku page. 
The word "Host" does not appear anywhere on this page. 
Please help idiots like me by providing answers to simple issues like this. 
What do I enter in the Host field? If it's an IP address then please say so, Also say which IP address - is it the IP address of the Roku device or the IP address of the router to which the Roku is connected?
Thank you

### URL

https://www.home-assistant.io/integrations/roku

### Version

2023.1.1

**Comment by frenck** [comment]
> The word "Host" does not appear anywhere on this page.

The host is a very generic term in computing. It refers to the machine running the subject talked about. Combined with networking, that is either the IP address, hostname, or even FQDN of the device running the referred service (in this case, Roku).

This term has been generally used since the 80s and is by no means technical. IP-address, however, would be a more technical (and too specific as it rules out hostname and FQDNs) term to use.

../Frenck
