### ISSUE TITLE
iOS Remote Widget Does Not Support WatchOS

### ISSUE THREAD

**Issue by daredoes** [home-assistant/home-assistant.github.io#25610]
### Feedback

The event `homekit_tv_remote_key_pressed` is exposed, allowing control of the remote buttons from an iOS device.

When using an Apple Watch Remote app, no event is emitted/exposed, and so no remote created in HomeAssistant can be controlled via WatchOS.

### URL

https://www.home-assistant.io/integrations/homekit/#ios-remote-widget

**Comment by fireRoads** [comment]
Same problem here. It probably sends different events compared to the phone. Hope this can be fixed.

**Comment by frenck** [comment]
Hi there @daredoes 👋 

It seems like you want to report an issue with our Companion app for iOS, however, you have submitted documentation feedback instead.

Please report issues with the iOS app here:

<https://github.com/home-assistant/ios/issues>

Thanks 👍 

../Frenck

**Comment by fireRoads** [comment]
@frenck this has nothing to do with the companion app of HA. It concerns the Homekit integration and the event homekit_tv_remote_key_pressed that does not fire when being triggered from an Apple Watch. It works with an iPhone but not with an Apple Watch. Should work the same since it is a Homekit feature.
