### ISSUE TITLE
Remove Withings Integration Documentation

### ISSUE THREAD

**Issue by smileyhogue** [home-assistant/home-assistant.github.io#25773]
### Feedback

The Withings integration has been broken for a long time now, based on open issues here. I am suggesting the documentation gets removed from https://www.home-assistant.io/integrations/withings/ or at least a warning displayed that the integration is broken and that there is no development on the integration.

Reason for the request being that people are still buying this sensor (including myself) and finding that there is no way to set it up even though it is shown to be supported on home assistant. 

### URL

https://www.home-assistant.io/integrations/withings/

**Comment by frenck** [comment]
> The Withings integration has been broken for a long time now

Works fine for my personal use case, so that sounds like a bad plan. Sorry to hear it doesn't work for you.

This is not the place for discussing issues with integrations, use Core issue tracker for that instead.

>  finding that there is no way to set it up even though it is shown to be supported on home assistant.

Setting up the integration works. I've done it myself lately (as it was questioned before), and helped another person recently too (with success).

../Frenck
