### ISSUE TITLE
Don't see the rate limiting anymore when using Hue accessories

### ISSUE THREAD

**Issue by AddMoreLimes** [home-assistant/home-assistant.github.io#25817]
### Feedback

The "Warning" about rate-limiting under the "Hue remotes and switches" section doesn't appear to be limited on my instance. I see multiple firings on the hue_event listener. I can press the button at least 5 times within a second and get the matching number of "initial_press" and "short_release" events. I also get several "repeat" events when holding button within a second.

I have a Hue Hub, a Hue Button and a new model Hue Dimmer Switch.

If other people can confirm that there isn't rate-limiting anymore, the warning can be removed.

### URL

https://www.home-assistant.io/integrations/hue/

### Version

2023.1.5

**Comment by marcelveldt** [comment]
Yes, you will get the matching 5 events (because events will not be lost) but they'll be sent in one burst. The limit is that it will only send events once a second. Signify said it will be adjusted at some point to remove/shorten that throttler but so far I have not seen any confirmation that it is removed. 

Just tested myself on a Hue dimmer switch and the limit/throttle is still there.
