### ISSUE TITLE
link to github folder

### ISSUE THREAD

**Issue by su-Koch** [home-assistant/home-assistant.github.io#25811]
### Feedback

would be really cool if one could get directly from the documentation to the github repository of the component.
can anyone tell where the code of this component can be found in the repository?

### URL

https://www.home-assistant.io/dashboards/picture-glance/

### Version

2023.1.5

### Additional information

would like to watch the code to implement some custom card (expect this to be normal developer behaviour)

_No response_

**Comment by frenck** [comment]
> would be really cool if one could get directly from the documentation to the github repository of the component.

It isn't a component, otherwise it would be linked like others.

In this case, it is part of the Home Assistant frontend, for which the repository can be found here:

<https://github.com/home-assistant/frontend>

For more information, check out our developers website on: https://developers.home-assistant.io

../Frenck
