### ISSUE TITLE
The time is shown in hours instead of minutes

### ISSUE THREAD

**Issue by Bart-van-Gorp** [home-assistant/home-assistant.github.io#25959]
### Feedback

Dear,

When I use the sensor cards, the time is showed in minutes. But when I use the sensor to display the information as an entity, it shows us that it's shown in hours. How can I solve this issue, since we'd like to have a clean and small person card with enough information about ourselfs with the correct minutes. 

![image](https://user-images.githubusercontent.com/6367588/214825496-85db6bd0-2c53-4bd1-8c61-fdab7fb09b20.png)

### URL

https://www.home-assistant.io/integrations/waze_travel_time/

### Version

2023.1.7

**Comment by eifinger** [comment]
HI @Bart-van-Gorp I am not quite sure what exactly your problem is could you please describe it a bit more in detail showing your lovelace configuration etc?
Moreover please do so in the forum or other support channels listed here https://www.home-assistant.io/help
We use Github Issues to track actual bugs only.

Also please check if your issue is already discussed here https://github.com/home-assistant/frontend/issues/15103 or join in and contribute =)

**Comment by eifinger** [comment]
@home-assistant close
