### ISSUE TITLE
Tankerkoenig different stations not more supported

### ISSUE THREAD

**Issue by inreinbek** [home-assistant/home-assistant.github.io#25999]
### Feedback

I used Tankerkoenig to compare 2 gas stations about 130 km apart ... since the inclusion as an instance in Homeassistant, this unfortunately no longer works. How can I reconnect 2 stations that are so far apart?

### URL

https://www.home-assistant.io/integrations/tankerkoenig/

### Version

2023.1.7

### Additional information

1st station: 6ffce2a8-04da-475c-ac49-8acecc711eec
2nd station: 2f432c0c-9052-466d-9030-c78ab8c4149d

**Comment by guillempages** [comment]
@inreinbek you can add two separate instances of the tankerkönig integration, each with a different station.
Instead of adding the station by id, you can add the first station by location (i.e. looking for it in the map with a 1km radius), and once this is added, you can add another station by adding a "new" tankerkoenig integration with the second station (also via the map)

**Comment by inreinbek** [comment]
@guillempages thanks a lot ... thant's an idea i've had not in my focus ;-)
