### ISSUE TITLE
Controller ZB-CL01 eWeLight

### ISSUE THREAD

**Issue by suchkovdu** [home-assistant/home-assistant.github.io#26046]
### Feedback

Can`t use on/off button
Pushing button i only can changing color
My device:
https://aliexpress.ru/item/1005001629650377.html?spm=a2g2w.orderdetail.0.0.2e7a4aa6AcTRTo&sku_id=12000016891633159

### URL

https://www.home-assistant.io/integrations/zha/

### Version

2023.1.7

**Comment by Hedda** [comment]
@suchkovdu first undrstand that  https://github.com/home-assistant/home-assistant.io/issues is not for support, see https://www.home-assistant.io/help/ which in summery explain that you should post to the forum first and then if looks like a bug post an issue to Home Assistant core, however for Zigbee devices issues like that you might as well post a device support request to https://github.com/zigpy/zha-device-handlers/issue

Zigbee devices that do not use standard configuration and parameters (standard ZCL clusters and attributes) will need a custom handler/converter/translator as Python script code in "[ZHA Device Handlers](https://github.com/zigpy/zha-device-handlers/)" repository to extend custom support for specific non-standard devices (which the ZHA integration then makes use of).

If you can not code that Python script code yourself to write the needed custom handler/converter/translator for adding that specific device to the "ZHA Device Handlers" repository/library then suggest submitting a "device support request" as new issues -> [https://github.com/zigpy/zha-device-handlers/issues](https://github.com/zigpy/zha-device-handlers/issues)

Without a "device support request" as a new issue posted to the "ZHA Device Handlers" repository/library requesting support for an unsupported device or device feature with Device signature and Diagnostic information the ZHA integration developers will not even know about the device unless they by random chance happened to have bought it themselves.

The reason is why non-standard devices need a custom handler/converter/translator is explained in ZHA integration documentation here -> [https://www.home-assistant.io/integrations/zha#zha-exception-and-deviation-handling](https://www.home-assistant.io/integrations/zha#zha-exception-and-deviation-handling)

Zigbee devices that use clusters and attributes that are standard in the official ZCL (Zigbee Cluster Library) do not need custom handlers/converters/translators as explained in the ZHA integration documentation here -> [https://www.home-assistant.io/integrations/zha#knowing-which-devices-are-supported](https://www.home-assistant.io/integrations/zha#knowing-which-devices-are-supported)

PS: Off-topic but FYI, this also works kind of similar for Zigbee2MQTT which also requires a custom handler/converter/translator for specific devices -> [https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html)
