### ISSUE TITLE
Why are some devices supported but "not recommended"?

### ISSUE THREAD

**Issue by mikehughesc** [home-assistant/home-assistant.github.io#26052]
### Feedback

It would really help if you could explain why you have listed some devices as recommended, and others as supported but not recommended.  Why are they not recommended? - are they badly made? unreliable? too expensive?

I've just taken delivery of a new Zigate Wifi hub, and it's a bit galling to see it listed as "not recommended" without any explanation of exactly what is wrong with it!  Should I send it back and get something else?  I chose it because it claimed compatibility with most of the devices I own - but is it more important that it should be "recommended" by HA?  I just don't know!

### URL

https://www.home-assistant.io/integrations/zha/

### Version

2023.1.7

**Comment by dmulcahey** [comment]
It’s not recommended because it’s WiFi connected and the latency of that connection can significantly degrade the functionality of the Zigbee network. It’s very much impacted by your network setup and mix of things in your environment and not deterministic in any way. EZSP (the Zigbee stack) is sensitive to latency and the latency added from connecting to that coordinator over WiFi generally leads to issues. YMMV but that’s the reason for this particular device. 

Edit: It very well could work fine for you. I don’t want to speak for everyone that contributes to ZHA but if you experience issues you are unlikely to get a ton of help with that coordinator as it is known to have these issues and we have to manage what we spend our time on.

**Comment by mikehughesc** [comment]
OK, thanks very much for such a quick reply!

 

But if it’s the Wifi connection that causes the problem, then why are the ZiGate USB and even the PiZiGate also not recommended?  Seeing all the ZiGate modules listed there I assumed there was something wrong with the whole Zigate range.

 

Mike

**Comment by puddly** [comment]
> why are the ZiGate USB and even the PiZiGate also not recommended?

The ZiGate firmware has bugs that cause network issues. The firmware also does not allow you to read settings to make backups.

**Comment by mikehughesc** [comment]
Ah OK - thanks!
