### ISSUE TITLE
Dokumentation missleading for PJlink variable

### ISSUE THREAD

**Issue by rudihm** [home-assistant/home-assistant.github.io#26073]
### Feedback

Dear home assistant community,
there is a small error in the documentation that took me some time to figure out why the PJLink integration wasn't working.
The host: string variable must be enclosed in double quotes "". e.g. 
host: "192.168.2.1"

### URL

https://www.home-assistant.io/integrations/pjlink/

### Version

2023.1.7

### Additional information

media_player:
  - platform: pjlink
     host: "192.168.2.1"
     port: 4352
     name: "Home Cinema Projector"

**Comment by frenck** [comment]
Sorry, but it doesn't have to be quoted.

Your suggested change is not correct (and your issue was probably not related to this change).

Both with and without will result in a string type in YAML, and even if that wasn't the case, the host field for this integration has been set to convert any value to a string anyways.

../Frenck
