### ISSUE TITLE
Bridge mode

### ISSUE THREAD

**Issue by bodawui** [home-assistant/home-assistant.github.io#26098]
### Feedback

How is it possible to reach out thru bridge mode? that means I do not have IP of that device

### URL

https://www.home-assistant.io/integrations/starlink/

### Version

2023.2.1

**Comment by boswelja** [comment]
Do you mean bypass mode? As far as we can tell, bypass mode shuts down the internal server, so it's impossible to connect to it

**Comment by LordNex** [comment]
You’ll need to set a static route in your router to send all traffic destined for 192.168.100.0/24 to use your WAN interface. Once you have that setup you can verify it’s working by seeing if you can get to 
[http://dishy.starlink.com/](http://dishy.starlink.com/). After that just use 192.168.100.1 when adding the integration and your should be good to go.

**Comment by LordNex** [comment]
> Do you mean bypass mode? As far as we can tell, bypass mode shuts down the internal server, so it's impossible to connect to it

Actually the main connection computer is in the Dish itself. The “Router” they give you is just a glorified PoE injector with wifi. So all of the stats your getting from the app or http://dishy.starlink.com/ is all coming from a small web server inside the dish on the roof. Bypass mode just basically shuts everything on the “router” off and just turns it into a PoE injector. You then have a separate adapter that just changes their proprietary CAT5 cable into a normal one you can plug into your own Firewall/Router. If would highly suggest Firewalla Gold. Best firewall out there and no subscription fees

**Comment by boswelja** [comment]
Thanks @LordNex! I managed to get a static route set up, which seems to work fine with bypass mode and should when bridging (though my network before was a bridge and didn't have any extra setup needed).

I think this issue can be closed. We can't provide comprehensive documentation on how to set up static routes since it varies by router (for example, my Orbi didn't net me specify the full range `192.168.100.0/24`, but it seems like specifying just `192.168.100.1` worked fine.

**Comment by boswelja** [comment]
@home-assistant close
