### ISSUE TITLE
Water integration documentation doesn't tell you how to integrate water

### ISSUE THREAD

**Issue by bdonohoe** [home-assistant/home-assistant.github.io#26113]
### Feedback

The documentation for how to integrate water into your energy dashboard basically says only "you need a device to measure your water consumption". It has lots of pointers to devices you can buy or build, but it doesn't actually say how to get them to appear on your energy dashboard. At the bottom of the page, there are notes about manual integration of sensors, which advises you to "make sure you set and provide the device_class, state_class, and unit_of_measurement for those sensors", but declines to state what those parameters should be set to.

I have a device already (a Flume). What sensor should I pick? Do I need to create a virtual sensor to transform the data it provides? What kind of data is the energy dashboard looking for? Even that little bit of information would be helpful in figuring out how to get from A to B. I'm scouring the forums now, of course, but it seems like this kind of basic information should be part of the documentation.

### URL

https://www.home-assistant.io/docs/energy/water/

### Version

2023.2.1

**Comment by frenck** [comment]
Hi there @bdonohoe 👋 

> At the bottom of the page, there are notes about manual integration of sensors, which advises you to "make sure you set and provide the device_class, state_class, and unit_of_measurement for those sensors", but declines to state what those parameters should be set to.

Every sensor should set those values to match the device. Please note, that one doesn't adjust a device to be compatible with our energy dashboard... as in, if a device doesn't measure water volume, but still force those parameters in a way the dashboard would swallow: That would be wrong. There are many factors and combinations.

In general, an integration should provide all this data for the end user. No manual setup is needed for that. If an integration doesn't provide the capabilities to be used on the energy dashboard (but you think it should) an issue should be raised.

If these are manual provided sensors, please follow the documentation for that manual  sensor and provide data that matches the manual sensor you are integrating.

> I have a device already (a Flume). What sensor should I pick?

Flume is a built-in integration and should just work. Nothing is needed for that.
The energy dashboard will allow you to pick any sensor that has been found to work (otherwise it will not be selectable).

../Frenck

**Comment by bdonohoe** [comment]
Hi Frenck!

Thanks for the reply. I did manage to get the Flume to show up by picking the daily water usage measurement. The thing I wasn't clear on—and what I thought the documentation would benefit from—is some explanation of what kind of measurement would cause a sensor to show up. The Flume has a bunch of sensors, for instance, but only daily, weekly, and monthly show up. I wasn't sure if the dashboard would work better with a constant stream of usage or with a value that sums it up over a given period (and if the latter, then whether it matters what period I pick).

For the manual sensor instructions at the bottom, I was hoping that would give a clue that might inform the answer to the above questions. Like, what kind of device_class, state_class, and unit_of_measurement would cause it to appear in the list of available sensors. That'd help a less savvy user find their way to an answer, even if the documentation can't tell you exactly what to do in every situation.

Anyway, just a suggestion. I would offer to write an update myself, but I don't have the depth of knowledge to do it right. :)
