### ISSUE TITLE
Stookwijzer status (homeassistant integration) not updated occassionally?

### ISSUE THREAD

**Issue by JarichSpliethoff** [home-assistant/home-assistant.github.io#26233]
### Feedback

@fwestenberg 

I'm using the Stookwijzer integration in HA and really like it.

However, it seems that the status (blue/orange/red) is not updated regularly. 
If I check the stookwijzer website the status is often different than the status provided by the HA integration. 

I tried reloading and uninstalling/installing the integration, but at this moment it still shows the state of Yesterday ("red") rather than current state ("blue") according to the stookwijzer website.

I'm running HA 2023.2.3 on a x86_64 system.

[config_entry-stookwijzer-836a22dc2cd5437e15b0dc93e8570b5a.json (1).txt](https://github.com/home-assistant/home-assistant.io/files/10721232/config_entry-stookwijzer-836a22dc2cd5437e15b0dc93e8570b5a.json.1.txt)

### URL

https://www.home-assistant.io/integrations/stookwijzer/

### Version

2023.2.3

### Additional information

![stookalert](https://user-images.githubusercontent.com/22955519/218434271-b5aaa290-a6e5-4ef5-8477-d66314f64636.PNG)

**Comment by fwestenberg** [comment]
Hi Jarich, 

This issue is something I'm aware of. The problem is not the update, but the actual source. 
Stookwijzer.nu fetches data from OpenWeatherMap, while this integration gets the windspeed from Open-Meteo. The reason for this is, the website does expose the weather data from on the website's API, but in not in m/s but in Beaufort. This is not precise enough, so I have to get the data from another source. Now OpenWeatherMap would work, but this needs an API-key. I expect the Air Quality Index to be from the same source, so only windspeed is the problem here. 

Right now I'm trying to get in touch with someone from Stookwijzer, to see if we can work this out together. But it seems to be very hard to find the right organisation/person. 

Perhaps you can go to your HA integrations page, press the 3 dots of the Stookwijzer integration and download the Diagnostics. This can help me verify this problem. Thanks!

**Comment by JarichSpliethoff** [comment]
thanks for the very rapid response!
Indeed I just noticed that wind speed according to the diagnostics log (1.65) is indeed  different than the one reported on the Stookwijzer website and just below the threshold of 2m/sec to switch from code blue to code red. 

![Stookalert-Rood](https://user-images.githubusercontent.com/22955519/218437684-622f03c5-f0f5-49d8-9358-86db96cc1670.PNG)

As long as we know it's not a bug, but due to practical choices in implementation, this works fine! Thanks
