### ISSUE TITLE
Documentation of Visualization Card Missing

### ISSUE THREAD

**Issue by Ventusfahrer** [home-assistant/home-assistant.github.io#26300]
### Feedback

the graphical visualization card for the zigbee topology is very interesting. 

I would like to understand the details on the card in order to figure out reasons for possible issues in my zigbee insdtallation, but was not able to find any information on it.

It would be very nice to find information on the elements shown in the card:

- different node types (meaning of the shapes)
- the lines (meaning, colors)
- the numbers assotiated to the lines

If the documentation can be find anywhere in the Web, please put link into the zha documentation.

Without proper documentation the visualization card is a cute picture but a very blunt _Swiss Army Knife_ which generates more questions than it is answering.

Thanks!

### URL

https://www.home-assistant.io/integrations/zha/

### Version

2023.2.5

**Comment by Hedda** [comment]
FYI, posted a PR for ZHA documentation with basic info on the visualization window/tab as a seed for what is requested -> https://github.com/home-assistant/home-assistant.io/pull/26848

Please note that PR only provides some initial basic information that probably needs to be fleshed out further by ZHA developers.

> Without proper documentation the visualization card is a cute picture but a very blunt _Swiss Army Knife_ which generates more questions than it is answering.

IMHO, while the visualization looks awesome I still believe that even with proper documentation it currently at it stands today it can today only give a very rough indication of bad, good, and great connections between your devices, so right now it will at best indicate which devices could probably get a better link if adding additional Zigee Router devices.

PS: Off-topic but would be great if the ZHA integration could also calculate + estimate and let the end-user know in laymen's terms via clear indicators which devices are probably getting too much interference or are in need of more Zigee Router devices.

**Comment by Hedda** [comment]
> I would like to understand the details on the card in order to figure out reasons for possible issues in my zigbee insdtallation, but was not able to find any information on it.
> 
> It would be very nice to find information on the elements shown in the card:
> 
> * different node types (meaning of the shapes)
> * the lines (meaning, colors)
> * the numbers assotiated to the lines
> 
> If the documentation can be find anywhere in the Web, please put link into the zha documentation.
> 
> Without proper documentation the visualization card is a cute picture but a very blunt _Swiss Army Knife_ which generates more questions than it is answering.

@Ventusfahrer maybe after https://github.com/home-assistant/home-assistant.io/pull/26848 is merged then perhaps you would be willing to volunteer to edit and extend that section?

> _Originally posted by @Hedda in https://github.com/home-assistant/home-assistant.io/issues/26848_
> 
> **_Please note that this only provides some initial basic information that probably needs to be fleshed out further by ZHA developers._**
> 
> **_That is, I do not think that the initial commit in this PR alone currently provides all the information that is asked for in #26300_**

**Comment by Hedda** [comment]
Still relevant as per https://github.com/home-assistant/home-assistant.io/pull/26848

**Comment by Hedda** [comment]
FYI, https://github.com/home-assistant/home-assistant.io/pull/26848 has now been merged to at least bring some basic information about the visualizarion map and how to interpret RSSI/ LQI, but note that this new ZHA integration documentation section on this still need to be improved so please feel free to modify and/or provide feedback on what needs to be added or changed, same as for the rest of the ZHA integration documentation-> https://www.home-assistant.io/integrations/zha/#zigbee-network-visualization-in-zha-ui

Again, please note that initial only provides some basic information that probably needs to be fleshed out further by ZHA developers and more advanced Zigbee users. That is, I do not think that the initial commit in that first PR alone currently provides all the information that is asked for by many users here, still, I hope that it can be good enough for some now so that it can later be fleshed out by others.
