### ISSUE TITLE
Please, bridge the gap.

### ISSUE THREAD

**Issue by davidbicho** [home-assistant/home-assistant.github.io#26362]
### Feedback

Your Getting Started-page 3 (Automation) gives a warning before going on to further reading, stating:
"Please note, these pages require a bit more experience with Home Assistant than you probably have at this point of this tutorial."

How about filling this gap between "this point" and "these pages"?

The community is filled with tutorials before "this gap" and after "these pages". No one out there seems to have the educational skills to bridge the gap. It's all too basic, or yummy Yaml-code on Git hub. The whole learning journey from basic UI-clicked automations, to knowing what the hell one should do with a gray mass of yaml-code is no where to find. The whole Home Assistant philosophy is to learn by spending hours and hours of constant trial and error, investigation, and experimentation. That's are great for people who have and want to spend the time. I guess this creates a secret brotherhood bound between Home Assistantiers - those who have gone through the initial phase of horror. Done the dirty work. Got the shit under their nails, and so on. I get it.

Instead of getting my nails ruined, I write this text to call for a pedagogical description of the bigger picture, the fundamental syntax skeleton of actions, triggers, scripts, helpers and so on, the terminology, how everything is supposed to work together and so on. I'd bet you could earn quite some bucks on making it into a online course! Oh, sorry. That would be blasphemy to the codex of Dirty Nails Brotherhood... Information Must Be Free and so on.

Just my two cents.

Now, I'm off experimenting.

### URL

https://www.home-assistant.io/getting-started/automation/

### Version

2023.2.5

**Comment by riemers** [comment]
I think there are plenty of people out there that make a living off making video's with home assistant tutorials and frankly that is what most people do to learn too. Home assistant is just so big that you cannot make everyone happy. At some point you have to decide to focus on new stuff or to make the documentation so great that everybody can use it. But when writing documentation the 'coders' could say, but what if we change this and that.. then the user has less issues with this and it becomes more easier for them. So should they then focus on that or still on the documentation that they know will be outdated by the time they make that new feature? If you want something simple you can always go for Fibaro or something no coding involved. Problem is, most people are beyond that and want to do more, they step over to Home Assistant and yes it takes some more time then the usual click Apple/Google experience. Mostly to it being open source and by the love of the community they have some resources that they have people working on it full time. 

Anyway just my 2 cents since i didn't want to state the 'if you don't like the docs put in a pull request reply'

**Comment by dannytsang** [comment]
I would like to remind you to please be respectful in your feedback. Home Assistant is based around a community of people who contribute their effort for free.

To address your point, there is a balance of video / screenshot based material and then the up keep of those v.s. text which are easier to maintain.

I hope some of that can be bridge by a higher level run through of Home Assistant concepts which is waiting for review https://github.com/home-assistant/home-assistant.io/pull/23127 (nudge @frenck 😉 )

If there are any more specifics about those gaps, by all means raise them with more detail to help understand what they are or maybe help contribute by updating the documentation.
