### ISSUE TITLE
Home Assistant image is compressed & Etcher does not decompress.

### ISSUE THREAD

**Issue by brendandixon** [home-assistant/home-assistant.github.io#26532]
### Feedback

The page should be updated to explain downloading and de-compressing the Home Assistant IMG file. Etcher cannot handle compressed (.xz) files.

### URL

https://www.home-assistant.io/installation/generic-x86-64/

### Version

2023.3.3

**Comment by fabaff** [comment]
Etcher has support to decompress xz (https://github.com/balena-io/etcher/pull/376) for many years. Auto decompression works for me with balenaEtcher-1.7.9-x64.AppImage.

The issue seems more that https://github.com/home-assistant/operating-system/releases/download/9.5/haos_generic-x86-64-9.5.img.xz gives a HTTP 404 error from time to time which makes the download fail.

**Comment by brendandixon** [comment]
@fabaff Hmm, that does correspond to the behavior I'm seeing. However, Etcher may have failed to de-compress because my Ubuntu was a limited version running off a USB stick. It may not have had the xz tools installed.

**Comment by c0ffeeca7** [comment]
closed by #27330.
