### ISSUE TITLE
Energy distribution unclear

### ISSUE THREAD

**Issue by indyjason79** [home-assistant/home-assistant.github.io#26531]
### Feedback

It's unclear if the energy distribution card is showing the current energy production or the energy produced for today as a whole and should be spelled out clearly. 

### URL

https://www.home-assistant.io/dashboards/energy/

### Version

2023.3.3

**Comment by frenck** [comment]
Current energy production is not something that exists.

I think you are mixing up the difference between power and energy. Because if you talk about what one is currently producing, that would be power, not energy. Power is expressed in W or kW.

This is an energy graph, which shows the produced energy. Energy produced (or consumed) is power produced (or consumed over time) and expressed in kWh or Wh.

Since this card is an energy card )not a power card) and showing kWh, I am not sure how that is confusing from power in W?
