### ISSUE TITLE
Verisure has changed its APIs - Component no longer working

### ISSUE THREAD

**Issue by plastfuglen** [home-assistant/home-assistant.github.io#26784]
### Feedback

Haven't been in contact with Verisure, bur i get this error message: 
_Invalid response, status code: 404 - Data: {"errorGroup":"NOT_IMPLEMENTED","errorCode":"VAL_01797","errorMessage":"This API is not supported anymore "}_

I presume Verisure has changed some services and switched APIs...

### URL

https://www.home-assistant.io/integrations/verisure/

### Version

2023.3.6

**Comment by frenck** [comment]
Hi there @plastfuglen 👋 

First of all, you are in the wrong place. You are trying to report an issue with an Home Assistant integration, but have submitted documentation feedback instead. Please, report issues with integrations here:

<https://github.com/home-assistant/core/issues>

As for Verisure, this is a known issue that has been fixed in development. It is expected to be part of the next release of Home Assistant.

../Frenck

**Comment by plastfuglen** [comment]
Sorry for reporting in the wrong place.
Thanks for the update!
