### ISSUE TITLE
Device compatibilities.

### ISSUE THREAD

**Issue by Fonsos** [home-assistant/home-assistant.github.io#26880]
### Feedback

There are only a few devices compatible with this integration. The devices have to be compatible with the Local API, and the only compatible devices are:

Aidoo Pro Control Wi-Fi, with codes: AZAI6WSPXXX, where XXX are the letters or numbers that identifies a model.
Aidoo Pro Control Fancoil, with code: AZAI6WSPFAN.
Webserver Hub Airzone Cloud Dual 2.4-5 GHz Ethernet, with code: AZX6WSPHUB.
Webserver Airzone Cloud Ethernet, with code: AZX6WEBSCLOUDC.
And Webserver Airzone Cloud Wi-Fi Dual 2.4-5G, with code: AZX6WSC5GER.

If this information can be added to the description, it may help the users.

### URL

https://www.home-assistant.io/integrations/airzone/

### Version

2023.3.6

**Comment by Noltari** [comment]
> ### Feedback
> There are only a few devices compatible with this integration. The devices have to be compatible with the Local API, and the only compatible devices are:
> 
> Aidoo Pro Control Wi-Fi, with codes: AZAI6WSPXXX, where XXX are the letters or numbers that identifies a model. Aidoo Pro Control Fancoil, with code: AZAI6WSPFAN. Webserver Hub Airzone Cloud Dual 2.4-5 GHz Ethernet, with code: AZX6WSPHUB. Webserver Airzone Cloud Ethernet, with code: AZX6WEBSCLOUDC. And Webserver Airzone Cloud Wi-Fi Dual 2.4-5G, with code: AZX6WSC5GER.
> 
> If this information can be added to the description, it may help the users.
> 
> ### URL
> https://www.home-assistant.io/integrations/airzone/
> 
> ### Version
> 2023.3.6
> 
> ### Additional information
> _No response_

Hi @Fonsos,

The first sentence in the [integration documentation](https://www.home-assistant.io/integrations/airzone/) is "This integration interacts with the **Local API** of Airzone HVAC zoning systems".
I think it's implicit that the device needs to support the **Local API** in order to be compatible with the integration, but feel free to submit a PR which makes it more clear for the users.
I know that the Local API is only supported in recent devices and that older devices are only compatible with the Cloud API, but there's no official integration for the Cloud API yet, so those older devices won't be supported until an official integration for the Cloud API is submitted and accepted. However, newer devices would be compatible with both integrations.

**Comment by Noltari** [comment]
@home-assistant close
