### ISSUE TITLE
Replying IP/NVR Integration

### ISSUE THREAD

**Issue by akalderon** [home-assistant/home-assistant.github.io#26951]
### Feedback

E1 Pro model works fine - documentation needs to be updated as per write up below. 

Suggest removing the section that states these models do not work with the integration as it is no longer relevant. 

Thanks for all your hard work. 

### URL

https://www.home-assistant.io/integrations/reolink/

### Additional information

Documentation page states:
The following models are lacking the HTTP webserver API and can therfore not work with this integration:

E1 Pro
E1

However the integration works perfectly fine with E1 Pro cameras as per multiple on our deployment. I would venture that E1 probably works fine as well by now. 

Suggest removing this section as it is no longer relevant. 

Thanks for all your hard work.

**Comment by starkillerOG** [comment]
@akalderon thank you for your feedback!
However I do need some more information because previous users have confirmed to me the E1 Pro was lacking the HTTP API:
- How did you connect the E1 Pro, directly to Home Assistant or did you add it to a NVR and the NVR to Home Assistant?
- Which hardware model of the E1 Pro are you using, and how old is the camera (purchesed very recently or already older than a year)
- Which firmware version are you using on the E1 Pro?
- Is the E1 Pro now accesible by going to the IP adress in a webbrowser?
- In the Reolink windows client under settings->network->Advanced->Server Settings which ports are visible there?

**Comment by starkillerOG** [comment]
If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library.

**Comment by akalderon** [comment]
Connected directly to HomeAssistant via local IP(s) - I have several of them on my network
They were purchased almost 1.5 years ago
Device Type: E1 Pro Outdoor
Hardware Ver: IPC_523SD8
Firmware: v3.0.0.460_21071406
Details: IPC_523SD8S10E1W31100000001
Fully accessible via web browser - reolink web server version: v1.0.273
Available ports: 
Media: 9000 
Http: 80 
Https: 443
Rtmp: 1935
Rtsp: 554
Onvif: 8000
Use P2P is checked / Use UPNP is unchecked

**Comment by starkillerOG** [comment]
@akalderon "E1 Pro Outdoor" does not exist according to the reolink site and my knowladge.
Reolink has 4 models in the E1 series:
- E1 (3MP budget model)
- E1 Pro (4MP)
- E1 Zoom (5MP + optical zoom)
- E1 Outdoor (8MP + optical zoom + water tight)

If your camera is water thight and for outdoor use, you have a E1 Outdoor, not a E1 Pro.
The E1 Zoom and E1 Outdoor do support the HTTP API and are listed as supported in the documentation.
The E1 And E1 Pro are lacking the HTTP API and are not supported.

**Comment by akalderon** [comment]
Got it. My bad. Thanks
