### ISSUE TITLE
IP change of fritzbox 

### ISSUE THREAD

**Issue by t3chie** [home-assistant/home-assistant.github.io#27063]
### Feedback

After changing the IP of my fritzbox, I realize there is no way in the WebUI to update the changed IP.
Is there a commandline option to tell HA what the changed IP is?

### URL

https://www.home-assistant.io/integrations/fritzbox/

### Version

2023.4.5

**Comment by jwluiten** [comment]
I ran into the same problem. My old Fritz!Box died. The new one got a different ip-address and HA has no way to change it.

**Comment by mib1185** [comment]
@t3chie as soon as the same(!) Fritz!Box can be discovered by HA, it will automatically update to the new IP address.

@jwluiten there is no manual way to change the used ip address in HA, further because it is an new Fritz!Box the automatic update via discovery will not work. Either you configure the new Fritz!Box to have the same IP as the old one, or you remove the old configuration from HA and add the new Fritz!Box (_which will NOT preserve the historical data_)

---

If you are still in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://www.home-assistant.io/join-chat).
We use GitHub for tracking issues with Home Assistant Core itself, not for providing support.

Thanks! 👍
