### ISSUE TITLE
add HAs VoIP  Address

### ISSUE THREAD

**Issue by renarena** [home-assistant/home-assistant.github.io#27224]
### Feedback

Please add, which address/url to use to reach Home Assistant.
Currently there is only the tutorial with the adapter, but no hint how to use f.e. an android VoIP client.
People not used to VoIP may have no clue, what to use.

### URL

https://www.home-assistant.io/integrations/voip/

### Version

2023.5.0

**Comment by databoy2k** [comment]
I completely agree. I think there's three changes that need to be made:

1) Clarify that the VOIP Integration _does not create a VOIP Server_ and instead only acts as a VOIP receiver. This means that calls into it requires your VOIP system to have local, direct access or you can access the SIP listener from your existing VOIP server. 

2) Confirm how to use the integration, namely by placing a SIP call to sip:[host]:[port].

3) Maybe have some tips for different softwares - codecs, "use local account" in the case of MicroSIP, etc.

**Comment by frenck** [comment]
The page links the tutorial with detailed instructions:

<https://www.home-assistant.io/projects/worlds-most-private-voice-assistant>

> Maybe have some tips for different softwares - codecs, "use local account" in the case of MicroSIP, etc

As the text on the page says, only the Grandstream listed is supported.

**Comment by databoy2k** [comment]
> The page links the tutorial with detailed instructions:
> 
> https://www.home-assistant.io/projects/worlds-most-private-voice-assistant
> 
> > Maybe have some tips for different softwares - codecs, "use local account" in the case of MicroSIP, etc
> 
> As the text on the page says, only the Grandstream listed is supported.

Why wouldn't the integration page explain how to actually use the integration? I can tell you that as of now I have a shortcut on my desktop that with one click gives me access to HA's voice recognition. I'll have something similar on my Android phone soon. 

I appreciate that only the Grandstream is supported, but that's like saying that the Roomba integration only supports the 980 - it doesn't, and very similar setup instructions apply for the i3 etc.

**Comment by frenck** [comment]
> Why wouldn't the integration page explain how to actually use the integration? 

It links to a more specific tutorial to provide that context. The integration by itself doesn't do much.

>  I can tell you that as of now I have a shortcut on my desktop that with one click gives me access to HA's voice recognition. I'll have something similar on my Android phone soon.

That has nothing to do with this integration. This is for the Grandstream as listed in this page.

> I appreciate that only the Grandstream is supported, but that's like saying that the Roomba integration only supports the 980 - it doesn't, and very similar setup instructions apply for the i3 etc.

Not sure what you mean by this comment or how the roomba is related to this.

**Comment by databoy2k** [comment]
I'm sorry frenck; clearly I'm not communicating clearly. I'll do my best to clarify.

Yes, the VOIP integration is currently for the Grandstream, to have a physical phone be used to communicate with the assistant. However, even though that is the current use for it, that isn't the _only_ use for it.

I'd like to use the exact same system on my cell phone, which is always in my pocket rather than having to walk to the old-style phone in one room. I'd like to pick up my phone, tap a shortcut, and have Home Assistant activate a scene or trigger an automation by voice. 

...and I can! This VOIP Integration does that! It was obviously coded to be more than just a receiver for a Grandstream - it also allows us to use our phones to control the system. And for those of us (renarena, as well as a few others commenting in the blog) that have got it working, we realize that it's not complicated if the instructions were just better.

Rather than have the instructions limit the integration to one single supported device, why not have the instructions describe the use of the integration with all supported devices: anything that can make an SIP call to the server. 

Here's the roomba analogy: The iRobot integration relies on the dorita980 suite, which was designed for an iRobot Roomba 980. However, the suite works just as well across a wide range of Roombas, and only a slight change in the setup applies (pressing a different button combination on some different Roombas to pair). The integration works with many more hardwares than the software initially targeted. The VOIP integration does too, and renarena and I are arguing that the integration's page should identify that fact so that others can enjoy these same tools.

**Comment by frenck** [comment]
> that isn't the only use for it.

Other use cases you come up with yourself are fine, but don't expect us to document those. Right now, only the Grandstream is tested and supported, others are not.

The documentation has been specifically adjusted for this during the beta period as well. The limitation is an explicit choice by the project. If you wish to use it differently, feel free to do so on your own.

../Frenck

**Comment by databoy2k** [comment]
Alright. Thanks frenck for getting back to us on this so quickly.

**Comment by frenck** [comment]
No problem, going to close this feedback for now, as the documentation covers the supported cases.

**Comment by renarena** [comment]
I dont understand why its a problem to include the address you have to use to call HA per VoIP, which is a protocoll not tied to a single hardware.

**Comment by frenck** [comment]
> I dont understand why its a problem to include the address you have to use to call HA per VoIP,

It your HA address, which is also explained in the linked tutorial on the first paragraph.

**Comment by databoy2k** [comment]
I've started a post in the Share your Projects section that can act as an unofficial support thread. https://community.home-assistant.io/t/voice-over-ip-integration-call-from-any-sip-client/567762 

I implicitly referenced this issue when suggesting that we not keep bugging devs ;)

**Comment by frenck** [comment]
🤷

**Comment by renarena** [comment]
`*47192*168*1*100*5060` isnt exactly an IP address and doesnt tell me the meaning of 47. 
Countrycode, direct dialing number, ...?  

In any case its working with anything@192.168.x.x:5060 on mizudroid.

**Comment by lebeno** [comment]
> `*47192*168*1*100*5060` isnt exactly an IP address and doesnt tell me the meaning of 47. Countrycode, direct dialing number, ...?

`*47` is the Grandstream prefix for Direct IP calling. Reference: https://documentation.grandstream.com/knowledge-base/ht801-quick-user-guide/
