### ISSUE TITLE
EMail unknown

### ISSUE THREAD

**Issue by BraVo75** [home-assistant/home-assistant.github.io#27275]
### Feedback

I am running a Roborock S6 via the Xiaomi integration where my Xiaomi Mi Account is used.
There is no description but since the Roborock integration tells me, that there is no account with my EMail address, I assume, that it must be possible to create a Roborock account outside of Xiaomi somewhere.
There is a Roborock Website, where US citizens can create an account and maybe connect their device. On the german Roborock Website it is not possible.

My question: How can I use this plugin?

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2023.5.1

**Comment by Lash-L** [comment]
You download the official Roborock app and create an account. 

I need to change the docs because you are not the only one who is confused by this.

Roborock used to not have their own app - and you were supposed to just use Mi Home. But now they've developed their own app with better support for their own vacuums. But you have to make a new account there and link your robot to that account instead.

**Comment by BraVo75** [comment]
Thank you for you fast response. It somehow worked. I downloaded the app and created a new account. I had to reconnect the device which is now no longer available in my Xiaomi app (offline).
As a result in Home Assistant I've got the Roborock integration running, which shows me 1 device with only 3 entities. The Xiaomi integration, which is now no longer working, showed me 1 device with 18 entities. Very disappointing.
I don't really see the "more complete integration" which is mentioned for this integration.
Do I miss something?

**Comment by Lash-L** [comment]
As of right now - the majority of the extra functionality comes from being able to use the app. As the roborock app unlocks extra features for some of their vacuums compared to the Mi Home app - and because of that, as time goes on this integration will be able to better support Roborock features. 

With that being said, there is a limit with how much functionality a integration can have when being added. I added as much as I could before the original release. The rest of the functionality will come in future updates. We currently have 31 entities in the main branch of the  custom component version https://github.com/Lash-L/homeassistant-roborock

Those will come over here, but adding features into core takes time

**Comment by BraVo75** [comment]
Ok, I see. Thank you for your help!
