### ISSUE TITLE
There's no information about securing HA with a self signed SSL cert

### ISSUE THREAD

**Issue by Bugsbane** [home-assistant/home-assistant.github.io#27300]
### Feedback

From 2023.05 SSL is required to use all of the new voice features. For anyone using a local network only setup, this means needing to use a self signed certificate, but all of the information on the page is about either using Nabu Casa Cloud, or using DuckDNS which requires Home Assistant being accessible to the open internet.

Please add, or at least link to a page which explains how to secure HA with a self signed cert so the voice features of HA are available.

### URL

https://www.home-assistant.io/docs/configuration/securing/

### Version

2023.5.0

**Comment by frenck** [comment]
> From 2023.05 SSL is required to use all of the new voice features

There are many options out there, you can find many off them in our community guides sections on the forums. We deliberately choose not to provide a definitive guide on this, simply because there is no right or wrong and the many options out there.

We used to have many guides, most outdated and unmaintained yet people kept adding new ones. It was a mess. Hence we decided to remove them.

You could use Nabu Casa Cloud, route traffic trough CloudFlare, install the NGINX proxy add-on from core, use a Docker container like SWAG, use a stunnel, set up Tailscale and leverage their internal SSL capabilities, or even expose it via their funnel feature, use the NGINX Proxy Manager add-on (or Docker container), Trafik might be an option, just as Caddy is a good candidate, etc...

I'm not even getting starting a list of possibilities that are out there... In the end, in all those cases, Home Assistant itself just runs on `http`, those external apps will add the SSL termination on top of it. So, from that perspective, Home Assistant won't do SSL.

> SSL is required to use all of the new voice features

We don't require it, that is your browser.
 
../Frenck
