### ISSUE TITLE
Include download link in installation instructions

### ISSUE THREAD

**Issue by jonbosche** [home-assistant/home-assistant.github.io#27347]
### Feedback

I'm not seeing the installation link for the operating system in the RBpi instructions

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2023.5.2

**Comment by c0ffeeca7** [comment]
The download link is in the first step:
https://www.raspberrypi.com/software/
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/ffa8a892-6dad-43e9-b620-8bd0673bf512)

You click on this, it will take you here:
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/6c6494b2-c219-410c-92e0-86c2e9f0cc1e)

I could change the screenshot so that the download section is visible. 
Would this solve the issue for you?
