### ISSUE TITLE
Add exact port numbers

### ISSUE THREAD

**Issue by andmcg1** [home-assistant/home-assistant.github.io#27417]
### Feedback

Based on my testing, I believe only the following port is required to be open on a firewall/router between HA and the Roborock device (if they are not on the same network/VLAN):
TCP 58867

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2023.5.3

**Comment by Lash-L** [comment]
I've created the change. In the future, for small changes like a port number, it is very helpful if instead of creating an issue, you go ahead and create the PR. Documentation takes no coding experience, so anyone can do it, and it helps out the developers a lot if they don't have to read the issue, make the change, and then create a PR, they can just review the PR.

Thank you for the suggestion though!
