### ISSUE TITLE
What to enter in the "host" field?

### ISSUE THREAD

**Issue by curtmgray** [home-assistant/home-assistant.github.io#27442]
### Feedback

What do I need to enter into the host field during the setup? Is it my local IP for the device or is it some external address to Enphase?

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2023.5.3

**Comment by bigmach23** [comment]
> ### Feedback
> What do I need to enter into the host field during the setup? Is it my local IP for the device or is it some external address to Enphase?
> 
> ### URL
> https://www.home-assistant.io/integrations/enphase_envoy/
> 
> ### Version
> 2023.5.3
Host: enter your envoy ip address
User: I used my app username (it's my email)
Password: use your app email
Serial: find it in your envoy app (open envoy app-> system->devices->gateway->serial shown as "sn:xxxxxxxxxx"
Make the box "enlighten"

Good luck. 
I am able to load it about it does not load data since the last hassio update- broken since hassio version 4.6

**Comment by klaasnicolaas** [comment]
Host is the device you want to connect to, in this case the Envoy on your network. This can be both an ip address or hostname. 

Side note: currently the core integration works up to firmware version D5.x of your gateway, new installations are often already on D7.x. A team (of community members) is currently working on a new python package and adjusting the integration so that it works well for everyone again.
