### ISSUE TITLE
Integration requires API token

### ISSUE THREAD

**Issue by stephanschn** [home-assistant/home-assistant.github.io#27519]
### Feedback

Hi, access to enphase has change to token based API authentication as here: https://github.com/briancmpbll/home_assistant_custom_envoy
The password based access is not working anymore so the Home Assistant setup needs to be changed. 
thanks, Stephan 

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2023.5.4

**Comment by klaasnicolaas** [comment]
Hi there @stephanschn 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

But to get into this anyway, it is known that the integration in its current form only works on gateway firmware version D5.x or lower. A team is working on a new python library so that everything will work again in the future.

Thanks! 👍

./Klaas

**Comment by stephanschn** [comment]
Hi Klaas, thank you for the follow-up and apologies for the unqualified ticket. Looking forward to the new library. Thanks, Stephan
