### ISSUE TITLE
Soma Connect - any update?

### ISSUE THREAD

**Issue by musickgm** [home-assistant/home-assistant.github.io#27557]
### Feedback

Any update for these instructions? I do not know what to put for Host* or Port* for connecting my SOMA connect to home assistant. 

### URL

https://www.home-assistant.io/integrations/soma/

### Version

2023.5.4

**Comment by ratsept** [comment]
Hi @musickgm,
You can leave the port at the default 3000. The IP address needs to match whatever your Connect has in your network. The easiest way to find that is to use the SOMA app. But you can also just check from your routers DHCP leases or you can query the MDNS responder.

**Comment by musickgm** [comment]
Thank you.
I updated the values to 3000 and what I found in the app for the IP
address. However I'm still getting the error message "Failed to connect".
After looking at this thread
<https://github.com/home-assistant/home-assistant.io/issues/25067>, I
believe it might be because I have the new hardware (the USB stick) instead
of the raspberry pi version of SOMA Connect. If this is the case (if this
hardware is still not supported), perhaps we could update the documentation
to reflect that certain hardware is not supported?

**Comment by ratsept** [comment]
Hi,
Have you looked at the SOMA helpcenter documents (https://support.somasmarthome.com/hc/en-us/articles/360026064234-HTTP-API)? You can see the API description for the USB hardware at the end of the page.

To start debugging this first make sure that the Connect is connected to your WiFi (green light steady on and SOMA app showing IP that matches your network settings). Then use a browser on any device in the same network and navigate to somaconnect.local:3000/list_devices or if that doesn't work just use the IP address from the app directly in the browser ( replace the "somaconnect.local" part with the IP address). That should give you a JSON formatted list of motors the Connect can see. Let me know if you can get that far.

**Comment by musickgm** [comment]
Hello,
Thank you for your response.
I have viewed the SOMA help center documentation.
For the debugging steps - I can get to that step using both methods
(somaconnec.local or using the IP address from the app). Both
successfully list the devices and their state.

**Comment by ratsept** [comment]
Is your HA instance in the same network as the SOMA Connect? This seems very much like a network issue. Also - what version of HA (or more specifically the SOMA integration) do you have? The USB Connect uses a slightly different API (as you can see from the documentation pages) and older versions of the pysoma library do not support that. I'm not really sure how to check library versions in HA but I'm sure there are ways. If the API from the browser works the issue has to be either in the network or the HA configuration because what the pysoma library (used in the integration) does is basically call the same API. If you have desktop access to the machine running HA you can try a browser on that and see if the API is reachable from there. Or if you have SSH access then maybe try the same thing with wget or curl.

**Comment by musickgm** [comment]
HA and SOMA Connect are on the same network.
HA Version is 2023.5.4.
I do not have the version of the SOMA integration because I have never been
able to successfully integrate it.
In HA, I go Settings > Devices & Services (Integrations) > Add Integration
> SOMA Connect (I enter the Host (IP Address from the SOMA Connect app) and
Port (3000)) > and then I get the error pop up:
[image: image.png]
So I'm not sure which version of the SOMA integration "I have" since I do
not have it.

**Comment by ratsept** [comment]
I'm not sure what you mean when you say you don't have the SOMA integration. As far as I know HA will download all the required libraries for any integration when you try to add it. So inside your HA instance somewhere there is a Python library called pysoma - that is what actually makes the API calls to the Connect.

But I had an idea what you can try now. Since the SOMA Connect API is basically just a REST API you can set up a REST integration/sensor to access the same API. This should tell us if HA has network access to the Connect. For example this is something I have in my own home right now:
```
sensor:
  - platform: rest
    name: Livingroom 2 Shades Battery
    resource: "http://192.168.1.130:3000/get_battery_level?mac=c4:5b:8f:bb:be:c7"
    value_template: '{{value_json.battery_battery_percentage}}'
    unit_of_measurement: '%'
    scan_interval: 300
  - platform: rest
    name: Bedroom Shades Battery
    resource: "http://192.168.1.130:3000/get_battery_level?mac=eb:b5:d4:c8:1f:0a"
    value_template: '{{value_json.battery_level}}'
    unit_of_measurement: mV
    scan_interval: 300
```
This will have t be adjusted for your network and you will need to fill in the MAC addresses for the motors (I think you can get those from the app). You probably want to first test the API calls in a browser to make sure the MAC address are correct and see if you get sensible battery readings. Then add this into your configuration, reload and see if the sensors appear or if you get errors.

**Comment by musickgm** [comment]
What I meant by "I don't have the SOMA integration" was that I can't add
the integration - it gives me the error message shown in the picture from
the last response.

I really appreciate your help. But unfortunately I do not know how to
follow these instructions regarding the REST API.
I thought I remembered someone having an issue connecting to the SOMA
Connect USB version. I thought this might have been the case. I was wanting
to report a bug and hopefully get a fix. But I don't have the knowledge to
do a deep dive into troubleshooting (of this nature at least).

**Comment by ratsept** [comment]
I will be working on the SOMA integration next week as we are releasing the updated motors that will also have to be supported now. To do that I will install a fresh copy of HA and I will go through all the steps of adding the integration as well. I hope I remember to come back here and let you know how that goes. Our internal support staff has not heard of any major issues with the HA integration though. My guess is still that this is a network issue. It would be hard to debug this remotely though. How certain are you that HA and the Connect are on the same network? What I mean is - do you know how to get the HA IP address and the Connect IP address? The IP addresses should match largely (same subnet segment) for this to work in most cases.

Since this is most likely not a HA integration issue I suggest we continue this in the SOMA support system. You can contact our support through the app. Let the support people know that you have been talking to me and add a link to this issue so I can reference the conversation here. I'm sorry I've not been able to help more but I'm sure we can find a way to solve this.

**Comment by musickgm** [comment]
I appreciate it! Thanks for all your work on this.
So I was fairly confident but after your comments I'm unsure. The SOMA
connect is connected to our wifi. The HA is connected to the router
directly with an ethernet cable (same network?).
However, the IP address for home assistant is a 10 or 12 numbers (IPv4) or
a ton of numbers IPv6. I'm assuming I have the right IP information? But
the IP address for SOMA Connect is simply "espressif.lan". Does this
information help at all?

**Comment by banning4** [comment]
I'd like to add to this thread as well. I've followed all of the steps above (including doing a wget from the HA device) to make sure that the SOMA connect USB is indeed functioning, that I have the right IP address for it, and that the HA device can communicate with the USB connect. I haven't yet tried your suggestion of the rest api call from within HA (working on that now) but wanted to echo what musickgm had said in that I am unsure how to tell what soma connect integration version I am using and/or what version of pysoma is running within HA. 

*Updated: rest sensor works and accurately show battery percentage. Has to be some issue with my pysoma version, but unsure how to update that / why that isn't being update when I try to add the integration again?
