### ISSUE TITLE
New Zealand region list on CLA signing page is very wrong

### ISSUE THREAD

**Issue by mje-nz** [home-assistant/home-assistant.github.io#2764]
When I signed the CLA, I literally couldn't find anything in the region list that described anywhere in NZ I've ever lived. It seems to be a random assortment of small towns, with a few cities and regions thrown in. Is there any reason it's not just [the list from Wikipedia](https://en.wikipedia.org/wiki/Regions_of_New_Zealand#List_of_regions)?

**Comment by fabaff** [comment]
@robbiet480 can you please take a look?

**Comment by robbiet480** [comment]
The code for the countries list is [here](https://github.com/home-assistant/home-assistant.github.io/blob/d5e78476820cdf4c69e156a1bdc06a136a539109/source/developers/cla_sign.html#L94), should be pretty easy to modify. I won't have time anytime soon to work on this (nor do I have a good understanding of New Zealand heh). The reason it's not from Wikipedia is because I got the entire script from some source that provided all the data.

**Comment by mje-nz** [comment]
It's supposed to be the highest-level geographic division in each country, right?
