### ISSUE TITLE
Many mistakes in the documentaiton

### ISSUE THREAD

**Issue by laithsaid** [home-assistant/home-assistant.github.io#27736]
### Feedback

Some of the examples make no sense.

When the type is tcp, it does not make sense to configure the slave. The slave is needed only for rtu.
When the type is tcp, we shall configure the host and port, else it wont work.

### URL

https://www.home-assistant.io/integrations/modbus/

### Version

2023.6.1

**Comment by janiversen** [comment]
First of all pull requests are welcome.

Slave is also used for tcp, sometimes it is called unit. We document what you can configure, and you can configure slave.

You write "many" mistakes what are the others ?

**Comment by janiversen** [comment]
Closing issue, since we correctly describe what can be configured (in that sense it makes sense, even though the modbus documentation often use unit= for modbus tcp and slave= for serial, but those are the same).

If you look at the examples in the documentation for tcp, they list both host and port. Actually you do not need to specify port is has 502 (the default modbus port) as default.
