### ISSUE TITLE
Connected Drive not working on 20230608.1

### ISSUE THREAD

**Issue by t9x42** [home-assistant/home-assistant.github.io#27866]
### Feedback

I never got it to connect, anyone still suvessfully using this or did the BMW side of things change and disable this again?

### URL

https://www.home-assistant.io/integrations/bmw_connected_drive/

### Version

2023.6.2

**Comment by rikroe** [comment]
Your issue is with the custom component (https://github.com/bimmerconnected/ha_custom_component).

Please reopen the issue there or remove the custom component and use the component delivered with HA.

There is no functional difference.

If you cannot login, please try to login once via the MyBMW **website**, as it might ask you to change your password.

**Comment by rikroe** [comment]
@home-assistant close
