### ISSUE TITLE
Will this item work in version 2023.8.0

### ISSUE THREAD

**Issue by LukeMal** [home-assistant/home-assistant.github.io#27891]
### Feedback

Will this item work in version 2023.8.0? Configuring Command Line sensor using YAML has moved. But is still here on documentary.

### URL

https://www.home-assistant.io/integrations/systemmonitor/

### Version

2023.6.2

**Comment by klaasnicolaas** [comment]
`systemmonitor` is not the same as the `command_line` integration 😉

**Comment by LukeMal** [comment]
Then why am i getting this prompt? :-)
---------
_Command Line YAML configuration has moved
This item will stop working in version 2023.8.0. Fix it before upgrading.
Configuring Command Line sensor using YAML has moved.

Consult the documentation to move your YAML configuration to integration key and restart Home Assistant to fix this issue._
---------

**Comment by frenck** [comment]
> Then why am i getting this prompt? :-)

Because that prompt is from the command line integration, however, you submitted this feedback on the system monitoring integration. You are mixing up two integrations.

You can find the relevant configuration information regarding the command line integration here:

<https://home-assistant.io/integrations/command_line>

Please note, this change was also announced in the release note weblog of Home Assistant 2023.6, in the Breaking changes section.

../Frenck
