### ISSUE TITLE
Can't install on Python 3.11

### ISSUE THREAD

**Issue by fuzzznet** [home-assistant/home-assistant.github.io#27969]
### Feedback

Python throws an error when installing dependencies.
From August 3.10 will not be supported, I'm trying to put it on 3.11, but it doesn't work.

mz@mz:~$ sudo apt-get install -y python3 python3-dev python3-venv python3-pip bluez libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 libturbojpeg0-dev tzdata ffmpeg liblapack3 liblapack-dev libatlas-base-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
**E: Unable to locate package libtiff5**

### URL

https://www.home-assistant.io/installation/linux/

### Version

2023.6.3

### Additional information

Ubuntu 20.04, 23.04, Python 3.11.2, 3.11.4

**Comment by frenck** [comment]
That is possible, which is why the documentation has this warning listed above all these instructions:

![CleanShot 2023-06-26 at 13 45 42](https://github.com/home-assistant/home-assistant.io/assets/195327/79a3bbf7-72ea-4126-901b-1f90ca68461b)

If you had used, for example, Debian Bullseye, it would have worked: <https://packages.debian.org/bullseye/libtiff5>

../Frenck
