### ISSUE TITLE
Aqara M2 Hub and Home Assistant Matter Server integration 

### ISSUE THREAD

**Issue by amorris101** [home-assistant/home-assistant.github.io#28005]
### Feedback

Here's my experience thru June 28, 2023 with the Aqara M2 Hub and the Home Assistant Matter Server integration. 

On June 25, 2023 I paired an Aqara Door/Window Contact Sensor to the Aqara M2 hub (updated to firmware level 4.02_0010.0644) and I am able to see that sensor in Home Assistant via the HA Matter Integration. I'm able to see Open/Close Status and Battery level status.  The entities are:

binary_sensor.aqara_door_and_window_sensor_contact
sensor.aqara_door_and_window_sensor_battery

I am not able to see in Home Assistant via the Matter Server integration the Aqara Water Sensor and Aqara Cube and it would seem they are not Matter compatible.

On June 27 I updated the HA Matter Server Integration to 4.7.0 and the two entities mentioned above became unavailable.

A new entity named: binary_sensor.none_contact showed up and it accurately reports open/close status of the sensor.

Subsequent to this the Aqara M2 hub developed a problem (the USB connector used for power that is in the body of the M2 hub fell into the hub when I disconnected the USB "power cable" to power cycle the M2 Hub and I therefore do not have a working M2 hub to further test the HA Matter Server integration with the Aqara M2 hub). I am currently awaiting a replacement M2 hub from Aqara.

### URL

https://www.home-assistant.io/integrations/matter/

### Version

2023.6.3

**Comment by marcelveldt** [comment]
Hi,

Sharing experiences is probably better done in our discord channels or forum.
Create issue reports here only if discovered an issue in our documentation.
If you discovered a bug in the Matter integration, better create an issue report in our core repository.

Some of your experiences are due to the fact that this is all very early stage and both we and in this case Aqara are still making changes, for example to naming. Hence our recommendation to not use it in production yet.

I'm going to close this issue here but feel free to join our discord server (look for the matter channel) to talk about your experience and get help by the community. Thanks!
