### ISSUE TITLE
Add link to "Python struct" docs

### ISSUE THREAD

**Issue by soeffi** [home-assistant/home-assistant.github.io#28017]
### Feedback

Hope this is the correct way to make a suggestion:

For the Modbus "custom" data type and `structure` parameter: Being unfamiliar with Python, it took me some minutes, to figure out what exactly to look for and that "Python struct" refers to a standard Python functionality.

I'd suggest to add a link to Python docs here, i.e. make "See Python documentation" link to 
https://docs.python.org/3/library/struct.html#format-strings

Thanks!

### URL

https://www.home-assistant.io/integrations/modbus/

### Version

2023.6.3

**Comment by janiversen** [comment]
Pull requests are welcome.

**Comment by soeffi** [comment]
@janiversen, I'm new to all this, please give me a hint.

Did you close, because you reject that change in general, or because you want me to create a pull request instead of verbally asking for that change?

Asking, because creating a pull request that gets declined as well, makes not sense.

NB: I first need to learn how to make a pull request. Was hoping that someone knowledgeable could make this small change in no time.

**Comment by janiversen** [comment]
I wrote specifically that pull requests are welcome, Because this is FOSS so "doers" gets things implemented, but please do not ask others to do your work.

I am not in favor of such links be because where do we stop, a lot of people have problems writing yaml, some people configures without reading the device manual etc..... My preference is to concentrate on describing the integration. And just to be sure, we do not support all of struct features.
