### ISSUE TITLE
AEMET OpenData Integration

### ISSUE THREAD

**Issue by ivanower** [home-assistant/home-assistant.github.io#28176]
### Feedback

Hello, 

I have just installed the native integration of AEMET Open Data and realised there is no way to choose the forecast mode between Daily or Hourly, and it always comes as daily.

Could you include in the configuration explanation, how to switch between these two modes?

Thanks in advance!

### URL

https://www.home-assistant.io/integrations/aemet/

### Version

2023.7.1

**Comment by Noltari** [comment]
Hi @ivanower,

> I have just installed the native integration of AEMET Open Data and realised there is no way to choose the forecast mode between Daily or Hourly, and it always comes as daily.

This is not an issue but a new feature request, because it's not possible to do that.

> Could you include in the configuration explanation, how to switch between these two modes?

However, you can create template sensors with the attributes that you're interesed in and expose the hourly forecast values.
This is documented here: https://www.home-assistant.io/integrations/template/#configuration-variables

**Comment by Noltari** [comment]
@home-assistant close
