### ISSUE TITLE
Reolink B800

### ISSUE THREAD

**Issue by tobyworks** [home-assistant/home-assistant.github.io#28196]
### Feedback

I've tested and reolink B800 cameras work flawlessly with this integration aswell.

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2023.7.1

**Comment by starkillerOG** [comment]
@tobyworks thank you for the feedback!
Do you have the B800 connected directly to HomeAssistant or do you have it connected to a NVR and the NVR to HomeAssistant?

I was under the impression that the B800 could not work on its own.

Note that any camera connected to the NVR will always work in HomeAssistant since HomeAssistant does not talk to the camera but to the NVR and the NVR API is fully supported.

**Comment by starkillerOG** [comment]
If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).
