### ISSUE TITLE
A little move info please.

### ISSUE THREAD

**Issue by LoCoCrUzN** [home-assistant/home-assistant.github.io#28279]
### Feedback

A little move info please.

### URL

https://www.home-assistant.io/integrations/image/

### Version

2023.7.3

**Comment by diamant-x** [comment]
I would add the question. Why this 'integration' is not showing up in 'add device' menu in home assistant?
In the release notes it is mentioned that it is a 'simplified version of a camera for static images only' which greatly reduces the system resources. Does that mean that if I have a generic camera with only static_image link define, it is already using image? Otherwise, why not expose the Image integration just asking for a (templated) url to populate it either from a web resource or a local resource URI and let user have more efficient static images entities?.

Thanks.

EDIT: Just saw this is available in the 'Template' integration, so I guess it would just better be a UI config flow missing option, as the template image entity just has mainly 2 fields.
