### ISSUE TITLE
Personal Access Token Scopes incomplete

### ISSUE THREAD

**Issue by BobRed0965** [home-assistant/home-assistant.github.io#28433]
### Feedback

https://www.home-assistant.io/integrations/smartthings/#personal-access-token-pat
The list of scopes needed for the SmartThings personal access token is incomplete.  When following this list and then setting the personal access token in the Smartthings integration, I repeatedly get the dreaded "Unknown error occurred"  error message.

However, when I create a personal access token and grant it all access to every scope, applying the token to the integration works correctly.

### URL

https://www.home-assistant.io/integrations/smartthings/

### Version

2023.8.0

**Comment by andrewsayre** [comment]
The list of available scopes has expanded quite significantly since the integration was created, but I'm surprised the original set isn't minimally sufficient for the integration to function, as it doesn't leverage the new resources that the new scopes yield access to.

I need some more information to help update the documentation:
1. Please provide the logs when you receive the unknown error. It will contain the specific reason it didn't work, and if it was authorization related, we'll know what resource it wasn't able to access.
2. Please enumerate what "every scope" means. On the main [ST PAT page](https://account.smartthings.com/tokens), please paste in the permission string for a token created per the documentation (that you indicated dones't work) and one that does. These strings look something like, `r:locations:*,l:installedapps,r:scenes:*...`

FWIW, my own ST/HA integration uses a token I created years ago with the most minimal set of scopes and it continues to function.

**Comment by BobRed0965** [comment]
Andrew,

Please accept my apologies and thank you for your skepticism which made me try again.
Looking at the logs again I realized that it was location that was missing (I am horrible at reading logs unless I know what I’m looking for).  I must have made that omission 3 times in 3 separate attempts.

Thanks again!
Bob
