### ISSUE TITLE
Average electricity price of the day suggest only one value per day

### ISSUE THREAD

**Issue by jhuisstede** [home-assistant/home-assistant.github.io#28452]
### Feedback

It is unclear if this entity contains the hourly energy rates or not. 
On other sites it suggests it does, but from the description it is unclear. 
Furthermore its unclear which attributes it contains

### URL

https://www.home-assistant.io/integrations/energyzero/

### Version

2023.8.1

**Comment by klaasnicolaas** [comment]
The average entity has **no** attributes with the hourly energy rates, which you can find with other custom integrations via HACS. This question was asked very often in the beginning, which is why I have mentioned it extra in my [own blog](https://student-techlife.com/2023/01/11/energyzero-market-prices-with-new-integration-in-home-assistant/). 

> On other sites it suggests it does

Where?
