### ISSUE TITLE
Energy-distribution card animation

### ISSUE THREAD

**Issue by twassil** [home-assistant/home-assistant.github.io#28481]
### Feedback

Dear Home Assistant,
The energy dashboard card is awesome. The only problem is with the small dots running along the lines in the energy-distribution card animation. They are running following the values of kWh (or Wh), the direction and speed of the dot are based on energy values of the source and destination nodes. By this method, a dot will keep flowing from a node (that had been producing energy for some time)  not producing energy anymore. For example, in the night dot will still be flowing from solar panel (that was only producing energy during the day).
The dots must flow based on the changes of energy in the source and destination nodes, or in other words, based on current power coming from source node and power consumed by destination node.
Thank you for developing and sharing such a great works.

### URL

https://www.home-assistant.io/dashboards/energy/

### Version

2023.8.1

**Comment by dannytsang** [comment]
Not a replacement but an alternative is to use [Power Flow Card Plus](https://github.com/flixlix/power-flow-card-plus) which is based on power i.e current electricity being rather than over time like the Energy dashboard in Home Assistant.

If that is not what you want, then please raise this by going to New issue > Feature Request.

**Comment by klaasnicolaas** [comment]
This is more for the frontend repository and a feature request, not documentation feedback
