### ISSUE TITLE
Noobs

### ISSUE THREAD

**Issue by raiubreaksthings** [home-assistant/home-assistant.github.io#28536]
### Feedback

<img width="733" alt="image" src="https://github.com/home-assistant/home-assistant.io/assets/76890070/c754a7d3-8a3f-4262-b286-0bf5aa38c881">

Where would a new to this service user find said folder? Do I need to ssh? Is there a terminal? What is yamal. 

A screen shot that looks like the screen the user might actually be on or should be on would be helpful. 
What tab the users should be on?

<img width="701" alt="image" src="https://github.com/home-assistant/home-assistant.io/assets/76890070/ed9e25ef-3faa-4330-9904-736442d3addf">

### URL

https://www.home-assistant.io/integrations/downloader/

### Version

2023.8.1

**Comment by dannytsang** [comment]
Does this help with the configuration.yaml? https://www.home-assistant.io/docs/configuration/

The folder will be accessible via some of the tools mentioned in the configuration page above. Otherwise, yes via SSH if you install the add-on.

The bottom screenshot is called *Developer Tools*. It available as a menu item if you have **Advanced Mode** turned on in your profile. More details about the Developer Tools are [here](https://www.home-assistant.io/docs/tools/dev-tools/).

[YAML](https://en.wikipedia.org/wiki/YAML) is a markup language used by Home Assistant for storing things like configurations to automations.
