### ISSUE TITLE
Water Control Bluetooth

### ISSUE THREAD

**Issue by Des2323** [home-assistant/home-assistant.github.io#28545]
### Feedback

Thanks for this addon, I just bought one.
Mine is type [01889-29](https://www.gardena.com/hu/termekek/ontozes/ontozesvezerlok/ontozokomputer-bluetooth/970480501/), but it also works perfectly.
And yes, if I use the official Android App, the connection is lost, it only works after Factory Reset, turning off Bluetooth on the phone didn't help me.

Is there a way to make the connected soil moisture sensor ([1867-20](https://www.gardena.com/int/products/watering/sprinklersystem/soil-moisture-sensor/967926801/)) also work?
How can I help you with this?

Des

### URL

https://www.home-assistant.io/integrations/gardena_bluetooth/

### Version

2023.8.2

**Comment by elupus** [comment]
The soil sensor should be easy to add i think: we need to add entities for some of these characteristics: https://github.com/elupus/gardena-bluetooth/blob/c8475b8f72a4c0f4b84c96316a670b62952e6111/gardena_bluetooth/const.py#L76

They may need to condition their availability on connected_state attribute.

They should likely be added here: https://github.com/home-assistant/core/blob/4342a95be0bde6bcc7ac9471c9b01f4b41b8f96d/homeassistant/components/gardena_bluetooth/sensor.py#L37 

Ps. Since i don't have one, i'm hesitant to add this myself. Would be better if somebody with the sensor tried it first.

**Comment by Des2323** [comment]
That sounds good, I have one :)
I think the first 8 characters should be used for CharacteristicInt, something like 98bd0xxx if I'm correct.
How can I get this?

I'm not a programmer (I'm an administrator), I can only "read" program code, but I absolutely cannot program in Python.
But with minor or major help, I can run all kinds of programs if necessary :)
And then I'll be happy to try it

**Comment by elupus** [comment]
This is mostly a feature request, so i'll close it for now. I've opened up a pull request with sensor support here: https://github.com/home-assistant/core/pull/98282 if you can test that we might be able to merge it.

You can grab this directory: https://github.com/elupus/home-assistant/tree/gardena/moisture/homeassistant/components/gardena_bluetooth and add as a custom component or you can run the branch fully if you know how to do that.
