### ISSUE TITLE
Roborock integration doesn't work

### ISSUE THREAD

**Issue by kgiedrius** [home-assistant/home-assistant.github.io#28610]
### Feedback

After email confirmation from roborock I get an error:

<img width="1076" alt="image" src="https://github.com/home-assistant/home-assistant.io/assets/15670549/3e0b4611-4379-4506-803d-b3d127bd03e2">

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2023.8.2

**Comment by kgiedrius** [comment]
In Roborock app I have S7 Max assigned to my account and it works

**Comment by frenck** [comment]
Hi there @kgiedrius 👋 

It seems like you want to report an issue with a Home Assistant integration; however, you have submitted documentation feedback instead. There is no amount of documentation we can adjust to fix issues in integrations.

Please report your issue here instead: https://github.com/home-assistant/core/issues

Thanks 👍 

../Frenck
