### ISSUE TITLE
Energy dashboard

### ISSUE THREAD

**Issue by Melectro1** [home-assistant/home-assistant.github.io#28667]
### Feedback

Are you really sure that configuring the energy panel should use kWh (energy). I think it would be easier to understand if this configuration was based on "power" (kW). The integral while time is running will be the energy
![image](https://github.com/home-assistant/home-assistant.io/assets/84949550/c2feaa11-86cf-4397-9fd3-96290216b56d)

### URL

https://www.home-assistant.io/docs/energy/solar-panels/

### Version

2023.8.3

**Comment by dannytsang** [comment]
@Melectro1 I'm not sure I understand your question/feedback because you have answered it. It's an energy dashboard displaying energy values and Home Assistant treats [power and energy as two separate measurement (data) types](https://www.home-assistant.io/docs/energy/faq/#energy-vs-power).

If you want to build a power dashboard, I would suggest using something like the [Power Flow Card Plus](https://github.com/flixlix/power-flow-card-plus).

If I have misunderstood your question, can you clarify please.

**Comment by Melectro1** [comment]
@dannytsang , Thank you this was a better solution
