### ISSUE TITLE
Aranet4 Home vs Pro

### ISSUE THREAD

**Issue by curtailment** [home-assistant/home-assistant.github.io#28894]
### Feedback

Aranet make two versions of the Aranet4, the HOME and PRO versions. I'm not sure if this is a recent introduction.

https://aranet.com/products/aranet4/

The Home Assistant documentation is unclear which of these is supported (or both?)

Thanks

### URL

https://www.home-assistant.io/integrations/aranet/

### Version

2023.9.1

**Comment by aschmitz** [comment]
The integration was created for the Aranet4 HOME. The [Aranet4 datasheet](https://cdn.bfldr.com/FS48XT6B/at/k9b9wjnv8f455crkp7846j/Aranet4_datasheet_v25_WEB.pdf) (which covers both models) states that only the PRO has a long-distance radio, but doesn't make any similar comment about the Bluetooth details. If they both have Bluetooth, it's plausible that you can enable the "smart home integration" mode and still use it with Home Assistant. However, this integration does not provide support for the PRO base station.

I should put together a PR at some point that clarifies that the PRO base station is not supported, but in the interim hopefully this helps.

(I don't have an Aranet4 PRO, but if we can find someone who does, finding out whether it can be made    to work with the Home Assistant integration via Bluetooth would be useful. Given that the PRO's only real benefit over the HOME is the extra range, I assume Bluetooth users would only really care about the HOME since it's cheaper, but it would still be good to know and document it.)

**Comment by thecode** [comment]
According to the datasheet and the FCC approval at https://fccid.io/W9Z-ARANET4, the Aranet4 Pro was tested for Bluetooth and sub-giga communication on the same device so the hardware does contain Bluetooth.
The protocol specification for the BLE packet also contains the region of the device (sub giga communication requires 3 regions to fit worldwide) so I assume it will work. However, it doesn't guarantee 100% compatibility and even if the manufacture will approve it has similar BLE, it might still not work out of the box.
