### ISSUE TITLE
Plusieurs freebox dans HA Est ce Possible ? 

### ISSUE THREAD

**Issue by creaimmo** [home-assistant/home-assistant.github.io#28945]
### Feedback

Bonjour,

Est -il possible d'ajouter plusieurs freebox dans Home_assistant ? 

J'aimerai pouvoir le faire, car j'ai la gestion de plusieurs freebox de ma Famille et d'amis que je surveille a distance. Et J'aimerai donc me simplifier les choses et pouvoir les mettent tous sur Home Assistant pour pouvoir avoir un retour de chaque box  rapidement sur l'aperçu et ainsi savoir si tout est ok sur celle-ci. 

Car actuellement je peux insérer ma Freebox local, mais des que j'essais d'en mettre une nouvelles j'ai une erreur qui apparait.  

Cordialement

### URL

https://www.home-assistant.io/integrations/freebox/

### Version

2023.9.2

**Comment by Quentame** [comment]
Hi !

Yes, it has always been possible to add several Freeboxes to HA, but in fact there are errors for devices connecting to 2 boxes because they will have the same ID.
A fix is not yet planned, create an issue in the right repo to talk about it --> https://github.com/home-assistant/core

Other remarks:
- You must connect to the Freebox on the local network for the first authentication, even if used with a remote URL (I have 3 boxes configured on my development environment)
- It is not enough to say that there is an error, it must be reported
- We always speak English on official HA repos, or otherwise speak in French on @hacf-fr repos, like https://github.com/hacf-fr/freebox-api (but I am looking much more on official repos)
- Here we are on the HA documentation repo, not HA itself, you have to create it here: https://github.com/home-assistant/core

Thanks

---

Bonjour,

Oui, il a toujours été possible d'ajouté plusieurs Freebox à HA, mais en effet il y a des erreurs pour les appareils se connectant sur les 2 box car ils auront le même ID.
Un fix n'est pas encore prévu, créer une issue dans le bon repo pour en parler --> https://github.com/home-assistant/core

Autre remarques:
- Il faut se connecter à la Freebox sur le réseau local pour l'authentification la première fois, même si URL distante (j'ai 3 box paramétrées sur mon environnement de développement)
- Il ne suffit pas de dire qu'il y a une erreur, il faut la rapporter
- On parle toujours anglais sur les repos officiels HA, ou sinon parler en français sur les repos d' @hacf-fr, comme https://github.com/hacf-fr/freebox-api (mais je regarde bien plus les repos officiels)
- Ici on est sur le repo de la documentation d'HA, pas HA même, il faut la créer ici: https://github.com/home-assistant/core

Merci

**Comment by Quentame** [comment]
You can also join the @hacf-fr [Discord](https://discord.hacf.fr/) or [forum](https://forum.hacf.fr/) to talk about HA in French
