### ISSUE TITLE
Location of configuration.yaml misleading

### ISSUE THREAD

**Issue by eiabea** [home-assistant/home-assistant.github.io#29141]
### Feedback

The documentation states:
```
If you use Home Assistant Operating System, you can find configuration.yaml in the /config folder of the installation.
```
this information is kind of misleading, because on the host system the `configuration.yaml` can be found at `/mnt/data/supervisor/homeassistant/` and only in the `homeassistant` container the `configuration.yaml` is at the stated location `/config/configuration.yaml`

### URL

https://www.home-assistant.io/docs/configuration/

### Version

2023.9.3

**Comment by frenck** [comment]
`because on the host system`

The Host system is not the daily driver in the Home Assistant ecosystem, and is not even enabled for access but the majority.

The documentation in this case is correct and matches both Docker and HAOS setups, which cover around 96% of the installation types and use cases.

../Frenck
