### ISSUE TITLE
unsupporting for CGroup version v2 or maybe higher

### ISSUE THREAD

**Issue by timcfliu** [home-assistant/home-assistant.github.io#29200]
### Feedback

I started as fresh installation according to the installation guide this summer and I was being prompted about the "unsupported system - CGroup version"
I further checked the docker system info and found the version I have is version 2, which came with the installment of docker ce version.

Can you help to fix this false prompt? Thanks!

### URL

https://www.home-assistant.io/more-info/unsupported/cgroup_version/

### Version

2023.10.0

### Additional information

root@XXXXX:~# docker system info
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 17
  Running: 16
  Paused: 0
  Stopped: 1
 Images: 18
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-12-arm64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.699GiB
 Name: rpi4-20230612
 ID: c8df9f4c-407e-4faa-b6a4-9277542f3fa5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by frenck** [comment]
Hi there @timcfliu 👋 

It seems like you want to report an issue with the Home Assistant Supervisor; however, you have submitted documentation feedback instead.

Please report issues with the supervisor here:

<https://github.com/home-assistant/supervisor/issues>

Thanks 👍 

../Frenck

**Comment by hellbringer** [comment]
The message "System is unsupported because the wrong version of Docker CGroup is in use. Use the link to learn the correct version and how to fix this." Learn more links here.: https://www.home-assistant.io/more-info/unsupported/cgroup_version
Feedback on that article links here: https://github.com/home-assistant/home-assistant.github.io/issues/new?template=feedback.yml&url=https%3A%2F%2Fwww.home-assistant.io%2Fmore-info%2Funsupported%2Fcgroup_version%2F&version=2023.10.1&labels=current

systemd has switched to CGroup2 "systemd now defaults to the "unified" cgroup hierarchy (i.e. cgroupv2).  This change reflects the fact that cgroups2 support has matured substantially in both systemd and in the kernel."
I followed this guide on a new installation: https://github.com/home-assistant/supervised-installer 
and got the CGroup v2
So the statement "you will need to revert what you did" is incorrect.

The documentation a extra "check": "Please make sure you use CGroup v1 to check for this:

This is CGroup v2 (incorrect, default):
mount -l|grep cgroup2
cgroup2 on **/sys/fs/cgroup** type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)

This is CGroup v1 (correct):
mount -l|grep cgroup2
cgroup2 on **/sys/fs/cgroup/unified** type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)

To fix this on ArmBian 23 bookworm:
add this line to /boot/armbianEnv.txt
extraargs=systemd.unified_cgroup_hierarchy=0

In GRUB:
sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
or change/add in /boot/grub/grub.cfg or /etc/default/grub
GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"

See also:
https://forum.armbian.com/topic/21129-pull-request-bootenvrockchip-force-cgroup-v1-usage/
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=985446

**Comment by frenck** [comment]
Cool, but as per above.. this is not the right place....
