### ISSUE TITLE
Conditional card not behaving inside a horizontal stack

### ISSUE THREAD

**Issue by sdi72** [home-assistant/home-assistant.github.io#29282]
### Feedback

The conditional card documentation shows no hyphen before card
type: conditional
This does not work.
With a hyphen:
- type: conditional
works. However, see issue at this link:
https://community.home-assistant.io/t/conditional-cards-not-behaving-inside-horizontal-stack/620907/2

### URL

https://www.home-assistant.io/dashboards/conditional/

### Version

2023.10.1

**Comment by reedy** [comment]
Depending on where/how you're using it.. for example, in the Visual Editor, on an individual tab, it would be right to be used/shown as `type:` rather than `- type:`...

![Screenshot 2023-10-10 at 00 23 35](https://github.com/home-assistant/home-assistant.io/assets/67615/d3cb233f-bf41-4d1f-a822-4d307d04b3f4)
![Screenshot 2023-10-10 at 00 23 27](https://github.com/home-assistant/home-assistant.io/assets/67615/d271ca3b-fdc4-4e9f-9e02-b864c7960a41)
