### ISSUE TITLE
Expose zone heat demand, battery state, window state, etc

### ISSUE THREAD

**Issue by rkeijsers** [home-assistant/home-assistant.github.io#29369]
### Feedback

Is it possible or could you edit this integration with the possibility to see the heath demand of every group?

I now use a Ramses RF antenna and plugin to see those values, but this is not that accurate.
I can also see the status of the battery and if the "window open" feature is on or off.

It also shows me if the brd91's are open or close and what the relay demand of these bdr91's is.

This would be nice to see in this intergration.

### URL

https://www.home-assistant.io/integrations/evohome/

### Version

2023.10.3

### Additional information

![1](https://github.com/home-assistant/home-assistant.io/assets/96620390/53c26521-f934-4e5e-9325-66dfcc3e8d7e)
![2](https://github.com/home-assistant/home-assistant.io/assets/96620390/a1efd0ac-a653-4790-ba31-bb50873b578d)

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍

**Comment by zxdavb** [comment]
For the benefit of those who may find themselves here, and would like to know the answer.

> Is it possible [for] this integration to see the heat demand of every [zone]?

No. It is not - the vendor's API simply does not provide this information.

The same applies for battery state, window state, relay state, etc. 

> I now use a Ramses RF antenna and plugin to see [heat demand] values, but this is not that accurate.

Hmmm. I wrote both the (official) **evohome** and (custom) **ramses_cc** integrations. 

The heat demand available via **ramses_cc** (which uses **ramses_rf** library) _should_ be exactly match those in the evohome controller (with certain caveats due to convergence, etc.). If it is not - raise an issue on the **ramses_cc** repo.

**Comment by rkeijsers** [comment]
zxdavb thank you for the quick reply and information.
Is it possible to pm you?
I have some questions about the ramses cc.
