### ISSUE TITLE
This intragration is broke and is not being fixed

### ISSUE THREAD

**Issue by cr8tor456** [home-assistant/home-assistant.github.io#29540]
### Feedback

When reinstalling the integration does not fix it, its broke. Please fix it.

### URL

https://www.home-assistant.io/integrations/myq/

### Version

2023.10.5

### Additional information

After readding the integration i get the below error. Please resolve this.

Logger: pymyq.api
Source: components/myq/config_flow.py:37
First occurred: 10:30:50 AM (1 occurrences)
Last logged: 10:30:50 AM

Authentication failed: Error requesting data from https://partner-identity.myq-cloud.com/connect/token: 401 - Unauthorized

**Comment by Lash-L** [comment]
@home-assistant close

**Comment by Lash-L** [comment]
1) This is on the wrong repository - you should make issue request on the core repository, not the doc repository.
2) Always look for existing issues before you post
3) https://community.home-assistant.io/t/the-current-state-of-myq-from-the-codeowner/630623
4) If you want a github issue: https://github.com/home-assistant/core/issues/101912#issuecomment-1779665814

**Comment by cr8tor456** [comment]
Awesom since i clicked on the link in the app to do this. Love wasting time.

**Comment by Lash-L** [comment]
> Awesom since i clicked on the link in the app to do this. Love wasting time.

You must have clicked on the documentation link not the 'known issues' link. Keep in mind - I also don't love wasting time and when I waste time on unneeded issues I can't be working on integrations. Please try to keep your comments respectful

**Comment by cr8tor456** [comment]
I clicked on the feedback link. Thats why its labeled feedback in the post.

If you dont like feedback, dont ask for it. 

I realize you didnt directly ask for it.

And its not directly targeted at you.

I see you have put a lot of time into making this work despite MYQ openly saying they dont want it.

I appreciate your time. I do. I dont write code but im in IT and i get it.

Sorry to bitch at you. 

I do feel though that if MYQ doesnt want it, then it should not exist, then people can pressure them into providing proper api support.

Again, thank you for your time. In this case, i am removing the MYQ integration because its not worth the hassle.

**Comment by ujverm-cloud** [comment]
> I clicked on the feedback link. Thats why its labeled feedback in the post.
> 
> If you dont like feedback, dont ask for it.
> 
> I realize you didnt directly ask for it.
> 
> And its not directly targeted at you.
> 
> I see you have put a lot of time into making this work despite MYQ openly saying they dont want it.
> 
> I appreciate your time. I do. I dont write code but im in IT and i get it.
> 
> Sorry to bitch at you.
> 
> I do feel though that if MYQ doesnt want it, then it should not exist, then people can pressure them into providing proper api support.
> 
> Again, thank you for your time. In this case, i am removing the MYQ integration because its not worth the hassle.

A simple apology from you would have been perfect but seems you are hell bent on proving that you are an entitled fellow. Anyways, the feedback link you clicked on the documentation page clearly says that

**Help us to improve our documentation
Suggest an edit to this page, or provide/view feedback for this page.**

It means the feedback is regarding the documentation on the page and not the actual functionality. If we have any issues with the functionality we always browse the issues page to see if anyone else is facing the same issue. Leave alone HA that's how people try to solve issues with a simple light bulb instead of reaching out to GE or Philips in the first place.

Also, it's a community driven space which means either you take what is available or leave it. If you have to give feedback provide constructive feedback to improve the product without bickering. That's how we all use this community.

**Comment by cr8tor456** [comment]
I mean, what do you want at this point?
I provided feedback and was immediately shit upon.
More shits going to help?

May i suggest, as community driven space you take what is available or
leave it.
