### ISSUE TITLE
Be more precise which Ecoforest devices are covered

### ISSUE THREAD

**Issue by Greentreegarden** [home-assistant/home-assistant.github.io#29646]
### Feedback

Hi,

the page says "of local [Ecoforest](https://ecoforest.com/) fireplaces".

https://ecoforest.com/ does not talk about an app or remote controlling. (Their bad!)

https://play.google.com/store/apps/details?id=com.ecoforest.ecoforest&hl=en&gl=US mentions Pellet stoves and Pellet boilers.

Make more precise which Ecoforest products offer the remote features.

Thanks!

Best,
Armin

### URL

https://www.home-assistant.io/integrations/ecoforest/

### Version

2023.10.5

**Comment by pjanuario** [comment]
The integration documentation have a section with the supported models: https://www.home-assistant.io/integrations/ecoforest/#supported-models
At the moment the integration was only tested with that model (since is the only one I can be sure that is working), once other users share their models and particularities, the idea is to extend this to support the different models that offer a local connectivity.

I didn't found any documentation specifying API information from the different models. To my knowledge, until recently the models had a embed webserver with a website/CGI that allow to control the device remotely from a web browser using local connection or through the ecoforesthome (i guess they have some bridge, not clue how it was implemented, mine doesn't have internet access enabled).
More recently I saw a new ecoforest home website (that doesn't allow to access my device) and a mobile app, but I have no clue how they can be accessed.

Regarding your comment do you have any particular information that you think it should be part of the documentation? From the ticket wasn't clear to me what could be the concrete actions or information to add.

**Comment by Greentreegarden** [comment]
I should have used Google:

- https://ecoforest.com/wp-content/uploads/2022/01/Manual-ECOFOREST-EASYNET-V01_EN.pdf
- https://www.youtube.com/watch?v=Y3KnRVwYqww (2 weeks old!)

I propose to add the info that the Ecoforest devices span a Wifi, plus the 2 links above.

**Comment by pjanuario** [comment]
@Greentreegarden i believe that is part of the device installation process of the device, doesn't feel something that should be documented in the integration. If you feel the configuration process can be improved in here feel free to add additional information here and we can reopen the ticket.

**Comment by pjanuario** [comment]
@home-assistant close
