### ISSUE TITLE
Docs: Installing Hass.io

### ISSUE THREAD

**Issue by robinmalik** [home-assistant/home-assistant.github.io#2970]
Some suggested edits:
> Flash the downloaded image to an SD card

I believe could be:

> Flash the downloaded image to an SD card or USB stick

unless there is a reason why we can't do this from a USB stick?

> On the SD-card, edit the

I believe could be:

On the SD card / USB stick, edit the

> Insert SD card to Raspberry Pi

I believe could be:

> Insert SD card / USB stick to your Pi/NUC

I know these clarifications can probably be deduced, but clarity is never a bad thing :)

**Comment by Sparkboxx** [comment]
The documentation refers specifically to the SD card because this is by far the easiest way to start a raspberry pi with the image. Even tough you can theoretically boot the raspberri pi from a USB device as [explained here](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md) it seems to be an experimental feature. 

For a NUC this could be different. I personally have no experience with the NUCs. Do you have experience loading Hass on a NUC? If so we might have to split the docs for the NUCs in this case.

**Comment by Landrash** [comment]
In general the most likely new user will be a rPi owner so most of the documentation assumes this. Lets keep it as is and if the user base changes this can be changed then :smile:
