### ISSUE TITLE
The documentation should include a select_source service call

### ISSUE THREAD

**Issue by dzeltner** [home-assistant/home-assistant.github.io#29732]
### Feedback

I happened to find a posting where someone shows how to use the select_source service call to change the TV source through a button or automation.  It would have saved time if this important example was documented.  Here is an example that shows a tap action on a button:

tap_action:
  action: call-service
  service: media_player.select_source
  service_data:
    entity_id: media_player.lg_webos_smart_tv
    source: Hulu

### URL

https://www.home-assistant.io/integrations/webostv/

### Version

2023.11.1

**Comment by thecode** [comment]
This is documented on the base [Media player](https://www.home-assistant.io/integrations/media_player/) which is linked from the integration. If you look at it there are many services there.
However I am not against adding examples, feel free to make a PR to edit and add an example, but for now this issue is not specific to `webostv`.
