### ISSUE TITLE
Growatt server not connecting anymore to Home Assitant

### ISSUE THREAD

**Issue by gustavogberger** [home-assistant/home-assistant.github.io#29908]
### Feedback

Since the beggining of this year I lost access to Growatt integration.  Do you know what is going on?  I can not see my hme energy anymore

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.11.2

**Comment by dannytsang** [comment]
See [here](https://community.home-assistant.io/t/growatt-integration-roadmap/510221) for the conversation. I still advocate for the [Growatt Integration to be removed](https://community.home-assistant.io/t/growatt-integration-roadmap/510221/9?u=tuxinator94) from Home Assistant because of the attempts to block access by the vendor continues @frenck 

I'm afraid your options are:
1. Setup a "Man In The Middle (MITM)" service like [grott](https://github.com/johanmeijer/grott). I use this and works well.
2. Use [Solar Assistant](https://solar-assistant.io/).
3. Get a different, supported inverter.

**Comment by muppet3000** [comment]
I recommend taking a read of the link in the final comment on the long chat that happened around this a few weeks ago: https://github.com/home-assistant/core/issues/100874#issuecomment-1792347970
