### ISSUE TITLE
PrusaLink integration refers to "API key" which no longer exists

### ISSUE THREAD

**Issue by simtr** [home-assistant/home-assistant.github.io#29913]
### Feedback

The PrusaLink integration documentation states:

> To obtain the API key:
> - On your printer, navigate to Settings > Network > PrusaLink.
> - The API key is shown at the bottom of the screen.

However, at least on Prusa Firmware version 5.0.0 (I'm not exactly sure when this changed, in fact it could be unique to the MK4), the API key is no longer separate and is labelled as such in the printer's menus, it's instead labelled as "Password".

![PrusaLink](https://github.com/home-assistant/home-assistant.io/assets/163107/af43f6ac-5631-4f50-b11d-4969d0eb7810)

### URL

https://www.home-assistant.io/integrations/prusalink

### Version

2023.11.2

**Comment by SPooks753** [comment]
I read somewhere that the password is used as API key.
But what do you put in "host" ??

**Comment by c0ffeeca7** [comment]
Thank you for reaching out, @simtr.
I added a note to the docs and will also add a description in the UI.
I do not have a Prusa myself but from their documentation, it looks like the wording depends on the Model you have. Instead of API key, it may be called password. In the [Host](https://www.home-assistant.io/docs/glossary/#host) field, enter the IP address or hostname of your Prusa.
