### ISSUE TITLE
Chipolo One Spot not working for iBeacon

### ISSUE THREAD

**Issue by macj72x** [home-assistant/home-assistant.github.io#30084]
### Feedback

I'm seeing a lot of users buying this, including me, and no one seems to be able to get it to work with iBeacon.  Can you remove it from the compatible documentation or provide instructions on how to connect it?

### URL

https://www.home-assistant.io/integrations/ibeacon/

### Version

2023.11.3

**Comment by frytos** [comment]
Up :) 
I'm facing the same issue

**Comment by philbert** [comment]
I just bought a 4-pack expecting expecting them to work because they were listed as compatible, however I've pretty much lost all hope now.

Looking at the change to the documentation here: https://github.com/home-assistant/home-assistant.io/pull/25462,
this comment jumps out "The Chipolo One Spot ist supported as iBeacon Device. (See product Description at Chipolo)"

There is no mention of iBeacon in the production description at Chipolo. I have contacted their support to confirm this.

If they confirm it does not use the iBeacon protocol I will raise a PR to remove it from the compatibility list :(

**Comment by philbert** [comment]
Issue can be closed
