### ISSUE TITLE
Better visibility that custom integration directory must be the same name as DOMAIN

### ISSUE THREAD

**Issue by jamesonuk** [home-assistant/home-assistant.github.io#30144]
### Feedback

See https://community.home-assistant.io/t/config-flow-strings-json-not-working/504312
The code bug report was closed as won't do so I think there needs to be something more explicit in the dev docs.

If you name your custom component anything other than your domain then it all seems to work but it will not pick up strings / translations and there is no logging or feedback to highlight this.

It would be really helpful for new developers to add to a few pages that this is a mandatory thing 
https://developers.home-assistant.io/docs/creating_integration_file_structure just says that the example domain of `mobile_app` is in the `mobile_app` directory, it does not make it clear that things won't work unless it is in a directory of the same name.   I suspect this should also be included in the config flow and a few other places where translations are mentioned

### URL

https://developers.home-assistant.io/docs/config_entries_config_flow_handler/

**Comment by frenck** [comment]
This issue is created in the wrong repository. Nevertheless, the developer documentation lists this multiple times. As a matter of fact, it is the absolute first sentence of the integration structure page:

![CleanShot 2023-12-05 at 12 23 47@2x](https://github.com/home-assistant/home-assistant.io/assets/195327/9e6b7f8b-e988-413b-8a7f-36e3dc08b9fc)

An example is provided in that same paragraph again, to make it more visually concrete as well.

../Frenck
