### ISSUE TITLE
ESP32-S3-BOX* documentation ? 

### ISSUE THREAD

**Issue by bert269** [home-assistant/home-assistant.github.io#30343]
### Feedback

Just saw on the momnthly release from Home Asistant that Voice is not supported on S3-Boxes. Well, it does not work. I get a "No Wifi" message as after I connect to the S3-Box's wifi - it does not take me to a page to configure the wifi.
Flashed multiple times - no difference.

### URL

https://www.home-assistant.io/voice_control/thirteen-usd-voice-remote/

### Version

2023.12.3

### Additional information

your documentation doe not have anything for S3-BOX yet..really, bit it us avaialbe?

**Comment by c0ffeeca7** [comment]
From the link you provided, I suspect you may have followed the wrong instructions. The instructions you gave here are for the ATOM Echo.
There is a specific tutorial for the [S3 BOX](https://www.home-assistant.io/voice_control/s3_box_voice_assistant/)
Also, there is a [troubleshooting section](https://www.home-assistant.io/voice_control/troubleshooting_the_s3_box/) specifically for the S3-BOX

**Comment by bert269** [comment]
Yes, I did as it was the only link provided from the ESPhome.io/projects
page.
Also, is this the troubleshooting for only the S3BOX-6 or does it cover the
S3-BOX and S3-BOX-lite ?
(I guess not, as these all use different code)

**Comment by c0ffeeca7** [comment]
- The troubleshooting should work for all 3 product variants.


> Yes, I did as it was the only link provided from the ESPhome.io/projects

Are you saying, yes, I followed the instructions on the ATOM ECHO?

On the ESPHome website, you can pick your product variant
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/fbeac87f-d5ee-46ca-9f03-6153c78a0b61)

And in the docs, there is a specific [tutorial for the S3-BOX](https://www.home-assistant.io/voice_control/s3_box_voice_assistant/)
If you have the S3-BOX-3, you can install directly using the button there
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/97470f23-f169-48f7-b88a-ac05946a9eff)

**Comment by bert269** [comment]
Correct. I was trying to follow the link for the ATOM (as I could not find
anything for the S3-BOX. I still cannot.
The link you provided takes me to the S3-BOX-# instructions. Under projects
on the right, there is a link for S3-BOX, but it takes me directly back to
the same page for S3-BOX-3!

That is the point I am trying to get across. References to the S3-BOX and
S3-BOX-Lite support, but only troubleshooting and instructions for S3-BOX-3.

**Comment by c0ffeeca7** [comment]
Oh, right. Let me add a note to the docs.
The installation and troubleshooting steps are essentially the same for all 3 variants. The firmware is slightly different. That's why you need to select your specific variant there. I wrote the procedure with an S3-BOX.


So for the BOX and the BOX-light, you need to choose your version here:
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/8f016a09-b461-449b-917c-6cb16869f83d)

For the S3-BOX-3, you can just use the button from within the [tutorial](https://www.home-assistant.io/voice_control/s3_box_voice_assistant/):
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/1b8c8f62-5d4a-4fd6-941f-5eb7a881cdec)

**Comment by bert269** [comment]
Please let me know when the documentation is ready for S3-BOX and
S3-BOX-lite, as I want to try this out.

Thank you.

**Comment by c0ffeeca7** [comment]
The documentation is ready, under the links I provided above. You can follow these steps. The only thing I'm going to change is adding a note that the steps apply for all 3 variants.

**Comment by bert269** [comment]
Then I will follow the instructions of S3-BOX-3 for the S3-BOX and
S3-BOX-lite and report back.
Thanks

**Comment by bert269** [comment]
I follow the instructions for the **S3-BOX-Lite** from this pages above, flashed the firmware, it boots up, creates an ap for my phone to connect to, I receive a message on my phone that the device will not provide internet, click on it and nothing happens. It does not ask for the Wi-fi cerdentials,
Next moment the **S3-BOX-Lite** display a screen with "No WiFi"

**Comment by bert269** [comment]
When I go with the ESPHOME route ("prepare for first use" ) with the **S3-BOX-Lite** - at the end when I click on next, all I get is the message below. Same thing when I click on the three dots to the right and select "configure Wifi: I get:
<img width="292" alt="image" src="https://github.com/home-assistant/home-assistant.io/assets/18601216/af49d650-1a03-4c40-845a-1a011cc1715b">

Flashing the code from the github repository for **S3-BOX-lite**, creates a boot-loop and never get to any screen.

I do not know WHAT I am missing here. Also - the board type in the github code for S3-BOX-LITE shows S3-BOX-3 but HA reports it as board: esp32-s3-box-lite, so I wonder if anyone tested this code on S3-BOX-LITE ? If it was tested - I do not know why I am getting these issues. These devices (S3-BOX and S3-BOX-LITE) works fine as a Willow devices, running on the willow-inference-server as a voice-command device into HA- so it is not the hardware.

At least one would think that if the devices S3-BOX and S3-BOX-Lite are 'advertised' to be working, someone would have tested the code before these claims are made, correct? Or am I expecting to much from the open-community?

**Comment by kbx81** [comment]
> At least one would think that if the devices S3-BOX and S3-BOX-Lite are 'advertised' to be working, someone would have tested the code before these claims are made, correct? Or am I expecting to much from the open-community?

@bert269 yes, that's a reasonable expectation and I can personally confirm that the installation procedures and software have been tested by many individuals (including myself) and they do indeed work. I'm sorry you're having such a difficult time getting this going.

For sake of discussion here, I don't really care which version of the hardware you have/are using, as long as you are selecting the correct option when installing the VA onto it (and I'll call out that this selection is very important!). So, from now on, I'm just going to say "S3-Box" to refer to your hardware. If I need to distinguish a specific hardware version, I'll call it out accordingly.

Based on what I see above, it appears that you are able to connect to your S3-Box via your browser, so that's a good first step. I see you're familiar with the [ESPHome Projects page](https://esphome.io/projects/), as well -- if you go there and complete the VA installation onto your S3-Box, I'd like to know what happens after you see the "Installation complete! 🎉" modal and click its "Next" button.

It is at this point we expect you'll be presented with a "Configure Wi-Fi" flow in your browser; you can select your Wi-Fi network from the drop-down list and enter the passphrase necessary to connect to it.

If at this point you do **not** see this Wi-Fi configuration flow in your browser, try instead clicking "Logs & Console", wait a few seconds, then click "Back" and see if the option to configure Wi-Fi appears. You can also try using "Reset Device" as shown in the "Logs & Console" view to confirm the device is booting up as expected (you'll see a bunch of log messages roll here by as the ESP starts up).

**Notes:**
1. You do not need to use the captive portal on the ESP to configure Wi-Fi -- this configuration should be done via the browser immediately after the VA installation completes. I haven't used the on-device captive portal to configure Wi-Fi myself so I'm not going to try to speak to that process here now -- but you can try it again if you want to. (Personally, I highly recommend using the configuration via the serial connection to the ESP in your browser, though.)
2. Do not manually invoke (by way of the buttons on the left side of the S3-Box) the bootloader on the ESP. I know some folks like to do this but doing so will prevent the browser from configuring Wi-Fi after the software installation completes. (You can still accomplish this configuration, but you have to manually reset the ESP and then go through the whole connection (but not installation) process again via your browser, etc.)

I hope this is helpful. Let us know if you have any success or not.

**Comment by bert269** [comment]
Yes, this is still an issue, as this process is NOT working for the
ESP-BOX-S3 and S3-Lite. I have tried both, numerous times.

**Comment by bert269** [comment]
This is not working. Here are screen shots from the whole process on the S3-Lite.
I placed the device in download mode and connect it to the browser/web interface (using Chrome). And the installation starts:
![image](https://github.com/home-assistant/home-assistant.io/assets/18601216/5c6bd0e4-7656-4c4d-bdd6-ac374bdb16a3)

When it completes, I get the message "Wrapping up":
![image](https://github.com/home-assistant/home-assistant.io/assets/18601216/b70f4a8c-bca8-4066-989b-b0732a78b600)

Followed by "Installation Complete":
![image](https://github.com/home-assistant/home-assistant.io/assets/18601216/69cf5667-bf08-4f62-b2d2-94d8f6cbf578)

Clicking on "next", shows the screen is again, "Install VA" or "Logs and Consoles" - I never get the "Wifi credentials login":
![image](https://github.com/home-assistant/home-assistant.io/assets/18601216/27d02422-77c3-4870-be41-66c1e830ac04)


Even clicking on "Logs and console", wait a while (one minute) and "back" as you suggested, just takes me back to the  "Install VA" or "Logs and Consoles" screen - no wifi.
When I click on "Reset device" all I get is a "Waiting for download" and nothing happens. The device does not reset or reboot.
![image](https://github.com/home-assistant/home-assistant.io/assets/18601216/eb5ed0dc-d20a-48b4-955d-10a9f827df2d)

When I power cycle the device, I get the HA White icon, that latest changes to the unhappy face and the QR ciode.
![image](https://github.com/home-assistant/home-assistant.io/assets/18601216/fdd270d5-1c01-4ee9-a4b3-c8260b3a1e96)

I have tried to download the log file, from the "logs and consoles" screen, but it is empty, 0bytes long.

**Comment by kbx81** [comment]
It seems you did not read my full reply. You mention:

> I placed the device in download mode and connect it to the browser/web interface (using Chrome).

...but I specifically said:

> Do not manually invoke (by way of the buttons on the left side of the S3-Box) the bootloader on the ESP.

Please test _without_ invoking the bootloader ("download mode", as you say) and let us know what happens.

**Comment by bert269** [comment]
I do appologize. that made a HUGE difference and I am sorry that I missed that very important line!
Yes, not it worked - it installed, asked for the Wifi credentials but then something is off in HA.

ESPHOME picked up the device and asked to "adopt" it. I adopted it, and it went throught the whole compiling of the code, re-install the firmware onto the unit and now it cannot connect back to the wifi.

**Comment by kbx81** [comment]
> now it cannot connect back to the wifi.

If you rebuilt and reinstalled the config, the wifi credentials may have been lost. You should be able to configure it with Improv again or, as an alternative, just add the wifi credentials into your configuration (which should be available in the ESPHome dashboard now since you adopted it) before you build & install it onto your hardware.

To reconfigure via Improv serial, you can go to [ESPHome Web](https://web.esphome.io), click "Connect", select your serial interface from the list the browser presents, click the vertical ellipsis and then click "Configure Wi-Fi".

If you wish to add your wifi credentials into your configuration, see the [ESPHome Wi-Fi component documentation.](https://esphome.io/components/wifi)
