### ISSUE TITLE
Very very confusing tutorials. Too many options and alternatives described in the same document.

### ISSUE THREAD

**Issue by v1ncen72** [home-assistant/home-assistant.github.io#30360]
### Feedback

Very very confusing tutorials. Too many options and alternatives described in the same document.

Selectign the Linux install the. offers the option to download images (??)

[VirtualBox](https://github.com/home-assistant/operating-system/releases/download/11.2/haos_ova-11.2.vdi.zip) (.vdi)

[KVM](https://github.com/home-assistant/operating-system/releases/download/11.2/haos_ova-11.2.qcow2.xz) (.qcow2)

--> This is then not a linux install, but install on virtualized on top of Linux..... (I expect an apt or dpkg install for this category!!)

I am desperately looking for an easy way to install on native linux, or to set up HA in a VM, but I don't want an outdated vmdk.

It seems way many options are mixed in the same document making this very confusing.
 

### URL

https://www.home-assistant.io/installation/linux/

### Version

2023.12.3

**Comment by agners** [comment]
> --> This is then not a linux install, but install on virtualized on top of Linux..... (I expect an apt or dpkg install for this category!!)

The document lists installation types which on Linux, and virtual machine is one of them. I know what you mean, but this is currently how it is structured. We support different hypervisors on Linux vs. on Windows, so it kinda makes sense to have them sorted under the host OS.

We do not have integrations into Distributions package management systems (dpkg's etc). The reason is that we have a HUGE amount of Python dependencies, which not all can get packaged into a single package.

The closest to a native installation is probably the installation into a Python virtual environment ([Home Assistant Core](https://www.home-assistant.io/installation/linux/#install-home-assistant-core) installation). However, this puts some maintenance burden onto the user and doesn't allow the installation of add-ons.

If you want an easier start, I definitly recommend a virtual machine installation. On Linux KVM (e.g. via virt-manager) is well supported.

> I am desperately looking for an easy way to install on native linux, or to set up HA in a VM, but I don't want an outdated vmdk.

What makes you believe that the vmdk is outdated?

All virtualization disk images we offer (vmdk included) are built from our Home Assistant Operating System build system, and all of them get built with every release. When you download the vmdk from the link on the official documentation, you'll have the latest stable version of Home Assistant (with OS/Supervisor etc).

> It seems way many options are mixed in the same document making this very confusing.

We are working on overhauling the installation guides. Suggestions and ideas how to structure it less confusing are welcome.
