### ISSUE TITLE
More info should be added about Auto mode

### ISSUE THREAD

**Issue by and7ey** [home-assistant/home-assistant.github.io#30445]
### Feedback

It is not quite clear from the doc how `Use default theme` + `Auto` mode works. 
The following is unclear:
1. what is treated as "system settings"? If my OS setting is `dark`, but firefox/chrome setting is `light`? 
2. does it change the HA mode only when I choose the option? 
3. does it automatically refresh the HA page, when system mode is changed? (i.e. I have the HA page always opened on my wall-mounted iPad, then firefox addon changes the mode from light to dark - based on time, will HA page be refreshed automatically to dark in this case?)
4. does it change `<meta name="color-scheme" content="dark">` value?

### URL

https://www.home-assistant.io/integrations/frontend/

### Version

2023.12.3

**Comment by and7ey** [comment]
+

**Comment by piitaya** [comment]
Hello 👋

> 1. what is treated as "system settings"? If my OS setting is `dark`, but firefox/chrome setting is `light`?

It follows your browser settings. The term "system" is used because this setting is used on web app, mobile app and desktop app. In case of apps, there is no browser. Also, in most cases the browser follows the system settings.

> 2. does it change the HA mode only when I choose the option?

The `light` and `dark` variables will be used (see [dark mode support documentation](https://www.home-assistant.io/integrations/frontend/#dark-mode-support)). That's the case for the default theme but if your custom theme supports light and dark mode, it will work with `light`, `dark` and `auto` settings.

> 3. does it automatically refresh the HA page, when system mode is changed? (i.e. I have the HA page always opened on my wall-mounted iPad, then firefox addon changes the mode from light to dark - based on time, will HA page be refreshed automatically to dark in this case?)

Theme change dynamically. You don't have to refresh the page, the theme will be applied without reloading the page.

> 4. does it change `<meta name="color-scheme" content="dark">` value?

Yes
