### ISSUE TITLE
recurring public holidays

### ISSUE THREAD

**Issue by PC-Welt** [home-assistant/home-assistant.github.io#30519]
### Feedback

What I miss are recurring public holidays, such as January 1st.

### URL

https://www.home-assistant.io/integrations/workday/

### Version

2023.12.4

**Comment by gjohansson-ST** [comment]
I think you have to be more specific. Missing in what context?
Unless you removed it for most countries for all years that will be a holiday e.g. not a working day.

**Comment by PC-Welt** [comment]
Maybe I didn't understand the description right.  If i have a public holiday, each year. How can i set this?

**Comment by gjohansson-ST** [comment]
If you select your country and possibly region if applicable for your country it will automatically load all the public holidays for you and set those as non working day.
If you remove holidays from the exclusions and/or your manually remove holidays then obviously anything can happen.

There is a service you can use to check if a specific day is a holiday or not using the dev tools in HA. I suggest you try that and also read the documentation again on how this integration works.

There is btw also a new integration for `holiday` which adds a calendar with all the holidays so you might want to check that one.

Closing the issue here but please raise a new issue if you find there is specifically an issue or bug somewhere. Thanks 👍
