### ISSUE TITLE
Link broken on 'ESP32-S3-BOX voice assistant' page

### ISSUE THREAD

**Issue by nirnachmani** [home-assistant/home-assistant.github.io#30565]
### Feedback

[deleting the ESP32-S3-BOX configuration from ESPHome](https://www.home-assistant.io/voice_control/s3_box_voice_assistant/) just takes you to the same page. 

I have the problem described but am unable to follow the procedure because of the broken link. 

### URL

https://www.home-assistant.io/voice_control/s3_box_voice_assistant/

**Comment by c0ffeeca7** [comment]
related to #30580

**Comment by kbx81** [comment]
When the prompt appears asking for the ESP's connection settings (host and port) it means that auto-discovery of the ESPHome device failed. This can occur for a number of reasons, but the most common is generally because of your network/LAN configuration.
- You may ned to modify one or more settings on your home router/modem to permit mDNS broadcasts on your network:
  - Some routers block all such broadcast messages;
  - Other routers specifically prevent these broadcast messages from passing between Wi-Fi and wired networks.
- If you have configured VLANs on your network, it may be because the ESP was connected to one VLAN while HA is on another. Unless specifically configured, mDNS broadcasts generally won't cross VLAN boundaries, preventing HA from discovering your ESPHome device(s).

While I realize this isn't a specific solution to resolve this issue, I hope it sheds some light on what might be going on so you can work towards some resolution. Please comment back and let us know if this helps.

**Comment by c0ffeeca7** [comment]
Closing this issue as resolved by #30772
