### ISSUE TITLE
no information provided for deleting ESPHome node

### ISSUE THREAD

**Issue by eric10k93** [home-assistant/home-assistant.github.io#30580]
### Feedback

There is a link in the guide listed under "Close the dialog and perform the procedure on [deleting the ATOM Echo configuration from ESPHome](https://www.home-assistant.io/voice_control/thirteen-usd-voice-remote/)."

This link doesn't point to anything... I've never used ESPHome before, so there should be no possible way for anything to be configured, but I am getting the dialog prompting me to enter the connection settings of your ESPHome node.  So I believe there is something failing when following the guide... there shouldn't be anything for me to delete when I've never configured any ESPHome devices before...

### URL

https://www.home-assistant.io/voice_control/thirteen-usd-voice-remote/

### Version

2023.12.4

**Comment by kbx81** [comment]
When the prompt appears asking for the ESP's connection settings (host and port) it means that auto-discovery of the ESPHome device failed. This can occur for a number of reasons, but the most common is generally because of your network/LAN configuration.
- You may ned to modify one or more settings on your home router/modem to permit mDNS broadcasts on your network:
  - Some routers block all such broadcast messages;
  - Other routers specifically prevent these broadcast messages from passing between Wi-Fi and wired networks.
- If you have configured VLANs on your network, it may be because the ESP was connected to one VLAN while HA is on another. Unless specifically configured, mDNS broadcasts generally won't cross VLAN boundaries, preventing HA from discovering your ESPHome device(s).

While I realize this isn't a specific solution to resolve this issue, I hope it sheds some light on what might be going on so you can work towards some resolution. Please comment back and let us know if this helps.

**Comment by c0ffeeca7** [comment]
Closing this issue as resolved by #30772
