### ISSUE TITLE
AO Smith operation modes

### ISSUE THREAD

**Issue by shaunplee** [home-assistant/home-assistant.github.io#30652]
### Feedback

What strings can be supplied in automations to set the operating mode of the water heater? The const.py file suggests these are:

```
AOSMITH_MODE_ELECTRIC = "ELECTRIC"
AOSMITH_MODE_HEAT_PUMP = "HEAT_PUMP"
AOSMITH_MODE_HYBRID = "HYBRID"
AOSMITH_MODE_VACATION = "VACATION"
```
but this isn't clear from the documentation.

Thanks for writing this integration! We're excited to use it to set out water heater to electric mode when it's cold in the house (so it doesn't make the house even colder in heat pump mode).

### URL

https://www.home-assistant.io/integrations/aosmith/

### Version

2024.1.0

**Comment by bdr99** [comment]
Thanks! Glad to hear you're enjoying the integration. Out of curiosity, which water heater model do you have?

I didn't specifically list the mode strings in the documentation because they can be different for each model. To get the mode strings for your specific water heater, go to Developer tools > States, filter for your water heater entity, and look for the `operation_list`. `eco` corresponds with Hybrid, by the way. (It was the closest match among the operation modes supported by HA.)

![image](https://github.com/home-assistant/home-assistant.io/assets/2292715/5388a7dd-7949-4cf0-b7ab-1950a90f14d5)

**Comment by shaunplee** [comment]
Thanks for the quick response and for writing this integration! I have the HPTS-50.

Maybe it would be helpful to list these steps in the documentation so that other people can get the mode strings this way.

**Comment by bdr99** [comment]
I agree, the documentation should be clearer. I'll work on improving that

**Comment by shaunplee** [comment]
Another thought is that since it's possible to programmatically get a list of operation modes (as shown in the `operation_list`), can this list of modes be shown in a dropdown box in automations? (Or is Home Assistant not really architected in a way that makes that easy?)

**Comment by bdr99** [comment]
> Another thought is that since it's possible to programmatically get a list of operation modes (as shown in the `operation_list`), can this list of modes be shown in a dropdown box in automations? (Or is Home Assistant not really architected in a way that makes that easy?)

Unfortunately that is not something the integration can control, that would need to be changed in Home Assistant itself.
