### ISSUE TITLE
 Xiaomi BLE and support for Telink flasher

### ISSUE THREAD

**Issue by Jab2870** [home-assistant/home-assistant.github.io#30762]
### Feedback

I am not entirely sure if this is a bug with the core integration or something that should be clarified in documentation, but the integration page includes the following under Encryption:

> Set your own. The [Telink Flasher](https://atc1441.github.io/TelinkFlasher.html) allows you to generate new bindkeys for devices it supports. The new bind key will work with Home Assistant, but the Mi Home app will not recognize the sensor anymore once the device has been activated by the TeLink flasher application. To use the sensor again with the Xiaomi Mi Home app, the device needs to be removed and then re-added inside the Mi Home app.

My understanding from this was that flashing a device with the custom firmware was supported in HA, however after flashing the device, it is not picked up by the core integration. Reverting back to stock firmware and it is found as a new device to add.

If this is a bug with the integration, I'll create a new issue on the core repo.

### URL

https://www.home-assistant.io/integrations/xiaomi_ble/#encryption

### Version

2024.1.2

**Comment by Jc2k** [comment]
It sounds like there are 2 seperate things going on here.

First of all, the docs that you quoting are talking about using Telink Flasher to generate a bindkey with the **stock** firmware, **not** replacing the firmware with an alternative firmware. Re-reading it now, it seems correct. You can still use the Telink Flasher to generate bindkeys for supported devices.

It does not talk about using Telink Flasher to replace the firmware, which is what you are trying.

What you are trying to do should work, but it is outside the scope of this integration. Mostly because you need to choose an advertising format so that Home Assistant can see the broadcasts from the device, and the suggested advertising format is BTHome. That's handled by a different integration - https://www.home-assistant.io/integrations/bthome.

From https://bthome.io/:

> Use their [TelinkMiFlasher.html](https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html) tool to upgrade your device directly from your browser. Once installed, change the advertising type to "BTHome" and click "Send Config".

Hope that helps!

**Comment by Jab2870** [comment]
thanks very much. That is helpful. Would you agree that the documentation for the Xiaomi BLE integration should be updated to reflect that using the flasher to flash custom firmware isn't supported (at least not by this integration). Happy to create a PR if you want that clarifies that

**Comment by Jc2k** [comment]
Using the flasher to replace the firmware is supported (by core home assistant) though. It's just got nothing to do with this integration.
