### ISSUE TITLE
HA as Thread border router?

### ISSUE THREAD

**Issue by chronvas** [home-assistant/home-assistant.github.io#30822]
### Feedback

It is unclear if HA can be used as a TBR without having some of the other vendors TBRs first. If not, the documentation should state it clearly.

### URL

https://www.home-assistant.io/integrations/thread/
https://www.home-assistant.io/integrations/matter/

### Version

2024.1.3

**Comment by agners** [comment]
The Thread documentation receives a major update with #30913.

However, your particular question depends on the smart home protocol you are planning to use over Thread. Which TBR are supported is mostly dependent on (access to) the Thread credentials. And Thread credentials are required during on-boarding/commissioning, which is part of the smart home protocol.

I am assuming you are trying to add a Thread based Matter device. In that case, currently, the best supported TBRs are the Apple TBRs when you are using the iOS companion app, or the Google TBRs when you are using the Android companion. Currently the combination of OTBR and propitiatory TBRs seem to cause issues (see also the updated section in #30913). 

To use Home Assistant via OpenThread Border Router add-on (or Silicon Labs Multiprotocol add-on which includes an OpenThread Border Router) standalone, currently only works if you have an Android phone and *no* Google TBR yet (otherwise the Google TBR will be the preferred BR, and Android APIs do not allow to change that currently).

Do this information answer your questions?

I'll mark this issue for the Matter integration as this must be answered on the Matter integration documentation page.

**Comment by chronvas** [comment]
Hi @agners this is very helpful information 👍 

My usecase is to mainly use it within HA, not very interested in proprietary TBRs atm, so I have added my Thread based Matter device to HA via OpenThread Border Router add-on (using a SkyConnect device with the thread only firmware) by using the HA Android app. It works great atm, even tho I am unsure if I the device now has the capability of getting firmware updates with this setup. 

Do you recon that I will be able in the future to also add that to the Google Mini TBR and both HA and Google Home to work in parallel? Any tips on how would it look like would be greatly appreciated.
(feel free to close/ref/etc. this issue as you deem appropriate)

**Comment by agners** [comment]
> It works great atm, even tho I am unsure if I the device now has the capability of getting firmware updates with this setup.

I am assuming you mean firmware updates for the end devices? This is really device specific: The Matter protocol itself has an update capability. To use this, the Matter Controller requres support for firmware update. Our Python Matter Server does not have this capability yet.

Some device manufacturer also have their own update solution (e.g. Nanoleaf through their App via Bluetooth). 

But typically, firmware update should not be related to the Thread border router in use.

> Do you recon that I will be able in the future to also add that to the Google Mini TBR and both HA and Google Home to work in parallel? Any tips on how would it look like would be greatly appreciated.

Combine them to work on a single network, and being able to commission devices to it should be possible soon. It is already possible to combine the networks, but it leads to instabilities currently. We are trying to work these out. It is hard to give a timeline these type of issues.
