### ISSUE TITLE
The documentation page for Trend Helper makes no sense

### ISSUE THREAD

**Issue by patrickcollins12** [home-assistant/home-assistant.github.io#31068]
### Feedback

This trend sensor makes no sense and the documentation doesn't explain its use.

I've setup a trend sensor and it shows a binary outcome, Off or On. 

My expectation is that a trend would calculate the slope of the line.  So if my battery is charging the line slope is 1.5 or if it is discharging the line slope is -3.

Specifically, the documentation tells us the inputs, but it doesn't tell us the outputs. It also doesn't describe the use case of the sensor. 

As a result, it is effectively a useless helper and is the likely reason for only 300 active installations.

### URL

https://www.home-assistant.io/integrations/trend/

### Version

2024.1.5

**Comment by jpbede** [comment]
Take a look at the [statistics integration](https://www.home-assistant.io/integrations/statistics/ ) or the [history stats integration](https://www.home-assistant.io/integrations/history_stats/), these should be suitable for your needs, I think.

Sure the documentation may can be improved in terms of what can be expected.

**Comment by AlanGreene** [comment]
I also found the page a little unclear on first reading and had to create a sensor to understand what it does and whether it might be suitable for my needs. Having this information available in the docs would be really helpful.

The only hint on the page as to how it works is:
> Invert the result
Invert the result. A true value would mean descending rather than ascending.

Testing it out myself I see that the result is a binary sensor whose state is `on` by default when the trend is ascending, `off` when descending, and `unknown` if the minimum samples have not yet been collected.

I think an update to the description at the top of the page would be helpful to clarify this.
