### ISSUE TITLE
Article Completely Ignores The Supervised Method

### ISSUE THREAD

**Issue by o4bay** [home-assistant/home-assistant.github.io#31111]
### Feedback

1. If you use Home Assistant Container, you can find configuration.yaml in the config folder that you mounted in your container.

2 . If you use Home Assistant Operating System, you can find configuration.yaml in the /config folder of the installation.

3. If you use Home Assistant Core, you can find configuration.yaml in the config folder passed to the hass command (default is ~/.homeassistant).

4.  but if you're using the supervised method, well go search.. 

### URL

https://www.home-assistant.io/docs/configuration/

### Version

2024.1.5

**Comment by o4bay** [comment]
The issue was incorrect documentation. Has it been fixed? If not it's still relevant.

**Comment by AlanGreene** [comment]
As far as I understand it the Supervised method is more advanced and not recommended unless the user has a specific need not addressed by the other options. See for example: https://www.home-assistant.io/installation/linux#install-home-assistant-supervised

> Install Home Assistant Supervised

> [!WARNING]
> This way of running Home Assistant will require the most of you. It also has strict requirements you need to follow.
>
> Unless you really need this installation type, you should install Home Assistant OS (this can also be a [virtual machine](https://www.home-assistant.io/installation/linux#install-home-assistant-operating-system)), or [Home Assistant Container](https://www.home-assistant.io/installation/linux#install-home-assistant-container).

Step 3 of that section links to the installation instructions which include details of the default location for HA files as well as how the user can modify this if desired: https://github.com/home-assistant/supervised-installer?tab=readme-ov-file#configuration

> Configuration
> The default path for our $DATA_SHARE is /usr/share/hassio. This path is used to store all home assistant related things.
>
> You can reconfigure this path during installation with
> `DATA_SHARE=/my/own/homeassistant dpkg --force-confdef --force-confold -i homeassistant-supervised.deb`

Personally I think it's reasonable to omit detailed information related to the Supervised method since the maintainers do not want to encourage its use unless the user is already very familiar with the requirements etc.

**Comment by o4bay** [comment]
I guess I look at it differently. There are four methods but because one is complicated, don't document it.

"Unless you really need this type of installation", that's why this method exists because people really need this type of installation. 

Personally I have found most of the issues associated with this method is 100% the lack of documentation. And as you know the supervised method is the most flexible of the four methods. The other three either require a dedicated device or do not support the ADD on store.. so that's  A BIG DEAL!

 Home Assistant OS method CANT USE DEVICE FOR ANYTHING ELSE
 Home Assistant Container method NO ADDON STORE
 Home Assistant Core method  method NO ADDON STORE

I guess I have never understood the rational behind hiding or obscuring documentation.

**Comment by AlanGreene** [comment]
> CANT USE DEVICE FOR ANYTHING ELSE

I'm not sure where you got that idea from, is there some documentation you can point to that suggests this?

The installation instructions show how to install HA OS in a VM, you can install it "bare metal" if you wish, but the main approach described in the instructions is to install it in a VM. See for example https://www.home-assistant.io/installation/linux#install-home-assistant-operating-system

**Comment by o4bay** [comment]
[https://peyanski.com/how-to-install-home-assistant-supervised-official-way/](https://peyanski.com/how-to-install-home-assistant-supervised-official-way/ )
I found that it provided a better explanation than anything I from the official sources including the one you provided.

**Comment by AlanGreene** [comment]
From that link:
> Home Assistant OS comes in a form of a [ready to use images](https://www.home-assistant.io/hassio/installation/), that could be used on a Raspberry Pi, Intel-NUC, Odroid and so on. Or you can use this Home Assistant OS image to create a new Virtual Machine with VirtualBox or other similar software, exactly as I’m showing in this article 👇

He provides a link to another guide he wrote on how to do exactly that.

He does later say:
> As cons imagine the following scenario: If you boot the Home Assistant OS image let’s say on a Raspberry Pi or Odroid – you cannot use that device for almost anything else!

But that's only if you've installed it on bare-metal rather than going the VM route as he explained previously. So he doesn't claim that the only way to install HA OS means you can't use the device for anything else except in specific circumstances and even documents himself how to install it in a VM.

However, he continues to claim the bare-metal route as a con a few more times in the article which I think is unfair but everyone's entitled to their own opinion. 🤷 

With the Supervised option you're responsible for installing all the required dependency packages and maintaining their versions etc. It is quite easy to get into situations where different software installed on the device requires different versions of the packages and it's entirely up to the user in those situations to resolve any issues and ensure things still work. This is one reason it's considered the more advanced option.

Both the Container and Core options provide additional guarantees around the dependency versions, reducing the burden on the user, with the Container option being the most controlled of these. There's a reason containers as a technology are so popular in general, although they're not a solution to every problem.

HA OS goes a step further in managing versions, providing everything needed in one image, as well as a number of additional benefits including the add-ons if you want them.

There are many options for installation, some are better suited to different people's needs, so use what works as long as you understand the requirements and limitations.

---

Addressing the original point of this issue, the lack of information regarding the config location for Supervised installs, have you considered opening a pull request to update the documentation with the information you'd expect to find there?

I believe the relevant file is https://github.com/home-assistant/home-assistant.io/blob/current/source/_docs/configuration.markdown

Ultimately it's up to the maintainers to decide whether this should be included or whether the omission is intentional, but proposing a PR might be a good way to get their feedback.

**Comment by o4bay** [comment]
I'm not following. I searched for  bare-metal and it's not in his doc..
"But that's only if you've installed it on bare-metal rather than going the VM route as he explained previously. " 

I'm not sure where you are getting that information.

**Comment by AlanGreene** [comment]
bare-metal, i.e. directly on the physical device, not on top of another existing OS / without virtualisation

**Comment by o4bay** [comment]
I understand bare-metal. I was referring to your assertion that the claim the HA OS Method being dedicated only applied to bare-metal.  I think you might be saying that if you put the HA OS Method in a container than it's not dedicated. However if you put HA OS Method in a container you are really doing options 2 or 3 as they are just variations of containers? Like I mentioned earlier, I find the HA documentation lacking in clarity.
