### ISSUE TITLE
Add a note that Battery Powered Cameras don't work - like Argus 3

### ISSUE THREAD

**Issue by mikezwgr** [home-assistant/home-assistant.github.io#31305]
### Feedback

I tried to connect my cameras 2 Argus 3  (https://reolink.com/at/product/argus-3-pro/)- I tried a lot 
than I found this 
https://support.reolink.com/hc/en-us/articles/900004435763-How-to-Set-up-Reolink-Ports-Settings-via-Reolink-Client-New-Client-/ 

so please just for more clarity add the note "That battery/solar powerd cameras are not supported, due a lack of support from the vendor - no http-api "

Thanks a lot! 

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2024.2.0

**Comment by starkillerOG** [comment]
See https://www.home-assistant.io/integrations/reolink/#tested-models

**Battery-powered cameras are not yet supported.**

It is already in the docs and has been there since the beginning.

Luckily there is hope, Reolink has announced a "Home Hub" that will allow to connect battery cams to HomeAssistant through this Home Hub, but there is no ETA yet for the product release.
