### ISSUE TITLE
TAPO P100 Sockets, RSSI

### ISSUE THREAD

**Issue by richardmx5guys** [home-assistant/home-assistant.github.io#31314]
### Feedback

Love this intergration. Thank you.
1. I use TAPO P110 and P100, integration works very well with P100 too so it could be in the list of compatible devices on the website.
2. RSSI entity is missing, sensor.******_rssi is missing :-(
I used to, I am sure others did too, use RSSI value to monitor devices as to when online/offline and quality of connection. Can it be added?
Otherwise switch.******* entity can be used but it is a switch not for monitoring really.

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2024.2.0

**Comment by rytilahti** [comment]
Hi and thanks for your report, glad to hear they are working for you! :-)

We are currently working on exposing more features of these devices (you can subscribe to https://github.com/python-kasa/python-kasa/pull/741 if you want to follow the progress), so that information will be available in some future release. As this is a feature request (which rather belong to the community forums), I will close this issue now.
