### ISSUE TITLE
Realtime Import and Export power readings

### ISSUE THREAD

**Issue by Azimuth0r** [home-assistant/home-assistant.github.io#31426]
### Feedback

The biggest thing I miss from the HACS/DEV version of this integration is the real-time import/export sensors. also import/export energy entities for the energy dashboard. I have a full Encharge system and I've not seen any examples of custom templates that would work for a full Enphase with battery backup system.

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2024.2.1

**Comment by catsmanac** [comment]
Hi @Azimuth0r , this is actually work in progress. The library pyenphase that  is used by the HA integration has been updated for this. The Home Assistant update is in the works.

See also [#82879 ](https://github.com/home-assistant/core/issues/82879) and [#109891](https://github.com/home-assistant/core/issues/109891).

We use 82879 as that is the oldest request. So if you can add your ask over there than we can close this one.

**Comment by catsmanac** [comment]
Fixed in #110884 and documented in #31491.

**Comment by catsmanac** [comment]
@home-assistant close

**Comment by joergbattermann** [comment]
Hi @catsmanac quick Q: I just installed 2024.3 (I _think_ that this is included in, right?) and read [in the documentation](https://www.home-assistant.io/integrations/enphase_envoy#capabilities) that now "_Sensors for net production (grid export) and net consumption (grid import) if the consumption CT is a net-consumption CT._" should be available and while we do have CTs installed (our system is a System Controller 3 / Combiner 5/ 5P batteries and  solar setup), I don't see those *net grid import / export sensors, albeit local envoy reports _grid_ import/export wattages. The reason why I emphasize the _grid_ side of things is simply because the Envoy correctly reports the _grid_ side of import/export and does not include/mix-in what goes into/out of our batteries of the system production and consumption.

Basically I am just wondering which sensor(s) I should see or use that report the 'net' grid import/export values?

Pls ignore the exact values from the screenshots below as they were taken a few moments apart from each other, but the HA sensors section basically shows what I see, well.. in HA sensors wise vs what Enlighten & Envoy show:

![image](https://github.com/home-assistant/home-assistant.io/assets/828/f8bd3b3a-92b5-48a2-b158-f74777d6ce19)


or

![image](https://github.com/home-assistant/home-assistant.io/assets/828/61ce8dcc-1a0e-4867-aca6-45985dab2eb2)


![image](https://github.com/home-assistant/home-assistant.io/assets/828/dd9adf08-2e7c-41ca-9dbf-b4da1bc29812)


![image](https://github.com/home-assistant/home-assistant.io/assets/828/56c2508c-98a5-494b-9cce-68754c2699c3)

.. but don't see said net _grid_ import/export:

![image](https://github.com/home-assistant/home-assistant.io/assets/828/a41a25bc-e0c0-46f1-9e7e-df95950fc5cd)

![image](https://github.com/home-assistant/home-assistant.io/assets/828/d33ae2d7-b05d-43ed-ba4b-a996b837bc26)

**Comment by gyordanov** [comment]
@joergbattermann  exactly the same issue i'm having - i don't see the new sensors with 2024.3

**Comment by Azimuth0r** [comment]
@joergbattermann , @gyordanov , If you go to the enphase component, then click on entities and show disabled entities, it should be listed, you will need to enable the net consumption energy and power meters. (In the US we also have each phase as separate entities.)

**Comment by gyordanov** [comment]
@Azimuth0r i tried that before and just checked again - they don't show up for me , also  usually disabled entities  show in the Envoy "Device info" screen like in the screenshot above - "Metering status production CT" for example ..... i'm in the US and would love to get each phase as separate entities !

**Comment by Azimuth0r** [comment]
![Screenshot_20240306-213617](https://github.com/home-assistant/home-assistant.io/assets/47956735/63d3cf25-933f-4b16-a693-d401266f8ccc)
Make sure you're not looking at devices, you need to look at entities.
![Screenshot_20240306-214840](https://github.com/home-assistant/home-assistant.io/assets/47956735/71947a6f-8362-445e-bcdb-73724625afd0)

**Comment by gyordanov** [comment]
@Azimuth0r exactly where i was looking ... they don't show up for me :(
the only disabled entities i have left are the "last reported" attributes for my inverters ...

**Comment by joergbattermann** [comment]
@Azimuth0r : yeah I had checked that before already / see:

![image](https://github.com/home-assistant/home-assistant.io/assets/828/d341ab61-2728-4055-821f-9fe1c6e8ba51)

.. nothing with 'net'. Got 2 phase(s) but the HA integration mentions "only" _storage_ and _production_ CTs. The consumption monitoring side of things IS enabled however (see Enlighten Manager below). And hence me asking, because I'd have expected for this to be 'enough' for the HA integration.

![image](https://github.com/home-assistant/home-assistant.io/assets/828/8ec29487-3e0d-4b35-83e6-851e78f6e229)

![image](https://github.com/home-assistant/home-assistant.io/assets/828/8a091ab0-8327-49c1-91aa-901d3a72a28b)

![image](https://github.com/home-assistant/home-assistant.io/assets/828/81e8896d-53e3-475a-8976-304b33874a7a)

**Comment by catsmanac** [comment]
@joergbattermann, the issue is with the missing net-consumption CT, and a storage CT reported instead it seems. @gyordanov, is it in your case also reported as `storage CT`? @Azimuth0r, sounds like your is reporting a net-consumption CT? 

If these don't show it's because the  net-consumption CT is not reported by the Envoy. If there's no net-consumption CT reported there will not be net production and consumption entities. 

The question is if there's a net-consumption CT as well and the code inadvertently used the storage CT or there's no net-consumption CT at all. And if the storage CT can be used to deduct grid import/export would be another question.

If you download the diagnostic report of the Envoy device in HA you can check what is send by the Envoy.  Open it and look for /ivp/meters  and /ivp/meters/readings. The ivp/meters section reports which CT are installed, enabled and their setup, there should be at least 2 section, not sure if there will be 3 and if 3 sets of CT can be connected. The /ivp/meters/readings reports the actual data. 

```json
      "/ivp/meters": [
        {
          "eid": "123456000",
          "state": "enabled",
          "measurementType": "production",
          "phaseMode": "three",
          "phaseCount": 3,
          "meteringStatus": "normal",
          "statusFlags": []
        },
```
As you can note from your consumption CT position picture there's no reference to storage CT, so unless a consumption CT is reported as well, I'm not sure what it implies. Didn't realize there is a storage CT option as well, we can add that as input for the battery section energy dashboard in a next version. So if you can upload the diagnostic report here as file after remving anything you want to remove it can help with deducting what is going on and/or adding the `storage CT` as source for the battery usage.

Below my (new) simple view of the CT's. 
![afbeelding](https://github.com/home-assistant/home-assistant.io/assets/120491684/6422e43b-e153-4610-86f8-d5c48c68acac)

The `net-consumption CT` will measure anything to/from the grid and is referred to as load included and also includes anything the battery loads from the grid. The 'total-consumption CT` is the load only one.

I see that the IQ Combiner 5/5C comes with an `IQ Battery metering CT` and a `Consumption metering CT`. I see that CT are optional on system controller 3. Looks we need to complete the puzzle to get more details.

EDIT1: 
Did a bit more searching and Enphase tells:
![afbeelding](https://github.com/home-assistant/home-assistant.io/assets/120491684/4a2fbe18-8876-48f8-a019-8b5cbec1d7c0)
So that diagnostic information will be  interesting if all 3 are installed and configured.

**Comment by catsmanac** [comment]
Please open a separate new topic on this as it looks like @Azimuth0r original question is resolved and closed already, and this one deals with the storage CT situation.

**Comment by joergbattermann** [comment]
Will open a new topic in a few moments and reference this one, thanks @catsmanac
