### ISSUE TITLE
default config is terrible by design

### ISSUE THREAD

**Issue by FreezyExp** [home-assistant/home-assistant.github.io#31475]
### Feedback

please document a migration path away from relying on default_config
or a way to disable specific items from the defaults

### URL

https://www.home-assistant.io/integrations/default_config/

### Version

2024.2.2

### Additional information

default_config breaks existing setups by injecting new things that are not compatible, a migration path should be provided as well as (since version) to make it easier to understand when it changed.

**Comment by frenck** [comment]
> please document a migration path away from relying on default_config

You can remove it from your YAML if you like. Specific documentation on using every single integration it provided is documented on each of those pages. They are all listed here.

> or a way to disable specific items from the defaults

That doesn't exist at this point. We have been slimming default config down (it was almost cut in half in the 2024.2 release), and more will move out of it over time.

Otherwise, please use our community forums for requesting features 👍 

> default_config breaks existing setups by injecting new things that are not compatible

That should not be the case. If you run into such a thing, please raise an issue. The default config is designed to be always active (and is so by default). If that isn't possible, it should be reported in our Core issue tracker.

../Frenck
