### ISSUE TITLE
Support for ‎H7020

### ISSUE THREAD

**Issue by scrome1337** [home-assistant/home-assistant.github.io#31717]
### Feedback

Hi, i have the ‎H7020 outdoor lights. I used to have these integrated via homebridge into homekit. Is there a reason why these lights are currently not supported in this home assistant add-on?

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.2.5

**Comment by Galorhallen** [comment]
Hi @scrome1337,
 the integrations currently supports the devices listed on the Govee local APIs pages.
If the integration detect a device with the APIs enabled that is not currently support it will print a message in the logs and the user can open an issue on the library [issue tracker](https://github.com/Galorhallen/govee-local-api/issues) (The link is printed in the logs).
For your specific device, a request has already been opened. I can't give you an ETA on when the device will be added, since I try to batch a few requests/issues before releasing a new version.

Galo

**Comment by Galorhallen** [comment]
@home-assistant close
