### ISSUE TITLE
More describing the using af address

### ISSUE THREAD

**Issue by thoath2** [home-assistant/home-assistant.github.io#31760]
### Feedback

In the Desciption of modbus-integration there i find by the topic "address" only "address integer Required: Address of coil/register"
I don't know: is it 
- the alias-address, for example 30847 or 
- the absolute address, for example 847?
Is there an offset, according of function?
Is the value of address
- decimal, for example 0x34f  or
- hexadecimal, for example 847

What is allowed?
Can you please expand the description, also with some examples, because this is the hardest point for me in using this integration.
Thank you, for Your job.

### URL

https://www.home-assistant.io/integrations/modbus/

### Version

2024.2.5

**Comment by janiversen** [comment]
It is not possible to expand on this, since it depends on the device you are using. Different devices have very different ways of doing addressing.....the modbus integration simple sends what address you configure to the device, without knowing if its offset, backwards or .....

 In order to obtain the correct addressing you need to read your device manual.
