### ISSUE TITLE
Default polling time?

### ISSUE THREAD

**Issue by paull27** [home-assistant/home-assistant.github.io#32382]
### Feedback

The page describes how to implement custom polling interval, but it does not tell what the default interval is and I cannot find it anywhere.

### URL

https://www.home-assistant.io/integrations/waze_travel_time/

### Version

2024.4.3

**Comment by eifinger** [comment]
The polling interval might need to change due to various technical reasons and also is a technical detail. It might also be throttled if a rate limit is reached etc. I am against including a technical detail in the documentation which would also mean more maintenance cost to keep it up to date.

For users which are interested in the exact rate the instructions on how to control it directly are enough.

**Comment by paull27** [comment]
alright, thanks.
