### ISSUE TITLE
Please clarify the relation between the two 'assist_microphone' add-ons

### ISSUE THREAD

**Issue by ReinhardPrix** [home-assistant/home-assistant.github.io#32391]
### Feedback

There are two non-identical add-ons with the same name 'assist_microphone', and same stated purpose 
- one in home-assistant core, at version 1.2.0: https://github.com/home-assistant/addons/tree/master/assist_microphone  ("Home Assistant add-on that uses a local USB microphone to control")
- and one in 'rhasspy', at version 2.2.3: https://github.com/rhasspy/hassio-addons/tree/master/assist_microphone ("Use Assist voice control with a USB microphone.")

However, neither one seems to explain or discuss anywhere what the relation is or which one to use when etc.

This is very confusing, and at least the respective README's and add-on 'Documentation' should add some explanation about which one to use in what case etc.

### URL

https://github.com/home-assistant/addons/tree/master/assist_microphone#readme

**Comment by ReinhardPrix** [comment]
Also reported here https://github.com/rhasspy/hassio-addons/issues/60 for symmetry.

**Comment by synesthesiam** [comment]
The old Assist Microphone add-on (in the Rhasspy repo) used the websocket API to run voice pipelines. This works fine, but didn't allow for assigning an area to the voice satellite because it wasn't a proper device. There are no plans right now to continue development.

The newer (official) Assist Microphone add-on uses the Wyoming satellite infrastructure, which is a proper HA device. Development will continue with this add-on.
