### ISSUE TITLE
Manual Google Assistant integration doesn't work

### ISSUE THREAD

**Issue by garnbleiche** [home-assistant/home-assistant.github.io#32471]
### Feedback

When I try to set up the Google Assistant (Manual Setup) as described in the instructions on the website [https://www.home-assistant.io/integrations/google_assistant/](url) I get the following error message after creating the Google Action project:

![chrome_m0GpiKnuwE](https://github.com/home-assistant/home-assistant.io/assets/28215618/2f54fbdb-7e26-40a4-82a2-aeb19dfae2b8)

### URL

https://www.home-assistant.io/integrations/google_assistant/#manual-setup-if-you-dont-have-home-assistant-cloud

### Version

2024.4.4

**Comment by agners** [comment]
Not sure we can do much about it here... Probably best to report to Google.

**Comment by garnbleiche** [comment]
I tried to create an Google Action Project several Times - now Google says: "You're 3 projects away from the project limit."

![chrome_L0xmsVeyot](https://github.com/home-assistant/home-assistant.io/assets/28215618/f927f1be-1459-4cdd-b4aa-1f52b5f81101)

Is there any other way to manual setup the Google Assistant integration?

I also reported this error to Google.

**Comment by garnbleiche** [comment]
I have just tried again to create an "Action" project at Google, it still does not work. Also from Google I have not received an answer regarding this problem so far.
According to some YouTube comments, this problem has been around for several weeks.

![chrome_BIAFq1rvuP](https://github.com/home-assistant/home-assistant.io/assets/28215618/f07a6fa1-6821-4747-bf89-5132d637d2b3)

**Comment by nvram93** [comment]
problem still exists, no fix available until now. google is letting us down. it seems that the projects can be seen in google cloud. is there any way to setup the home assistant sync with google cloud interface instead of "actions on google"-interface?

edit: i dug a little deeper and found this error in the logs, maybe this is whats preventing us to see our projects on the "actions on google" dashboard?
![image](https://github.com/home-assistant/home-assistant.io/assets/13992986/6beae2e3-1f38-4d78-8cba-80c007e9ec2d)

it's kinda weird, since we accepted firebase tos when we create a project. 
![image](https://github.com/home-assistant/home-assistant.io/assets/13992986/0db15391-3e77-485d-be2c-17572ddd810d)

maybe there is another way to confirm these tos for a project or the whole account?

edit2: i just checked again, i created a new project and it definitly fails after "trying to add firebase resources". i also tried to add firebase to one of the already created projects but didn't make it appear on the "actions on google" dashboard. ( https://console.firebase.google.com/ )
