### ISSUE TITLE
More than one Pi ? 

### ISSUE THREAD

**Issue by mcintoi** [home-assistant/home-assistant.github.io#32585]
### Feedback

this integration  only provides support for one Raspberry Pi., am sure  lots of us have more than one ?   well i do

### URL

https://www.home-assistant.io/integrations/rpi_power/

### Version

2024.5.1

### Additional information

only supports one PI

**Comment by swetoast** [comment]
@mcintoi,

Let’s try this again:

https://github.com/swetoast/Raspberry-Pi-Power-Usage-Monitor

Please check that out.

Please don’t create more support tickets, since you don’t seem to reply in those.

The Raspberry Pi power checker is intended for one device only, not several. It was never designed for that. However, the other one is a standalone program that can be incorporated into Home Assistant with error codes and cost analysis.

It should fit your needs.

**Comment by swetoast** [comment]
the raspberry pi power checker is intended for one  device only not several it was never designed for that
