### ISSUE TITLE
HA integration with carwings has stopped working

### ISSUE THREAD

**Issue by gitand71** [home-assistant/home-assistant.github.io#32861]
### Feedback

About 5 days ago my HA entities for carwings started showing up as unavailable.  HA is up to date and the Nissan official app still works fine.

These are the errors from HA below.  Many thanks.

Logger: homeassistant.components.nissan_leaf
Source: components/nissan_leaf/__init__.py:164
integration: Nissan Leaf (documentation, issues)
First occurred: 13:31:00 (1 occurrences)
Last logged: 13:31:00

An unknown error occurred while connecting to Nissan: <class 'pycarwings2.pycarwings2.CarwingsError'>

Logger: pycarwings2.pycarwings2
Source: components/nissan_leaf/__init__.py:156
First occurred: 13:31:00 (1 occurrences)
Last logged: 13:31:00

Invalid JSON returned

### URL

https://www.home-assistant.io/integrations/nissan_leaf/

### Version

2024.5.4

**Comment by arundalep** [comment]
I have the same issue. After home assistant restarted on the 17th May it hasn’t  connected successfully since.
I get the following errors 

Logger: pycarwings2.pycarwings2
Source: components/nissan_leaf/__init__.py:156
First occurred: 17:56:29 (1 occurrences)
Last logged: 17:56:29

Invalid JSON returned


And 

Logger: homeassistant.components.nissan_leaf
Source: components/nissan_leaf/__init__.py:164
integration: Nissan Leaf (documentation, issues)
First occurred: 17:56:29 (1 occurrences)
Last logged: 17:56:29

An unknown error occurred while connecting to Nissan: <class 'pycarwings2.pycarwings2.CarwingsError'>

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
