### ISSUE TITLE
Not Supported by Evohome

### ISSUE THREAD

**Issue by SiddyHq** [home-assistant/home-assistant.github.io#32882]
### Feedback

Getting errors that Evohome is not supporting these now, all my TRV's have errors. Evohome home itself on the web still online but not via HA.
Any advice?

### URL

https://www.home-assistant.io/integrations/evohome/

### Version

2024.5.4

**Comment by zxdavb** [comment]
I am sorry, but:
 - this is not a helpful issue - you need to provide a lot more information
 - in any case, I believe your problem is not with the docs - perhaps you meant to raise an issue against the integration?
 
Also see: home-assistant/core/issues/117916

I am closing this issue.

If you choose to submit another issue, please provide the exact error message you are getting.
