### ISSUE TITLE
What to call service on unclear. 

### ISSUE THREAD

**Issue by leblancexplores** [home-assistant/home-assistant.github.io#32894]
### Feedback

What entity to call the update entity service for custom automation seems unclear, would I run it on all three download/upload/ping entities? something else? Also reenabling the update polling doesn’t seem to reintroduce 1hr polls as described by default. 

### URL

https://www.home-assistant.io/integrations/speedtestdotnet/

### Version

2024.5.4

**Comment by glibg10b** [comment]
I only tested this once so it might be wrong, but it my case calling it on the ping entity works. However, for some reason the entities show "Unavailable" minutes after measurements have been made:

![image](https://github.com/home-assistant/home-assistant.io/assets/56197853/7079a4c1-b524-4f4d-ab07-fe5cb06a8aaf)

Note that some of the gaps in the graph may be due to my PC being offline.
