### ISSUE TITLE
Consistency with units

### ISSUE THREAD

**Issue by theukedge** [home-assistant/home-assistant.github.io#32983]
### Feedback

I'm not sure what the issue is here, but it's one of two things:
1. The integration uses metres in the Tolerance calculation, regardless of the user's native distance units, or
2. The integration uses the user's native distance units for the Tolerance calculation and the documentation is wrong.

The documentation also describes what the tolerance distance is, but I think it could be made clearer. I offer the following:
> When adding the **Proximity** integration, you are prompted to define the **Tolerance Distance**. Because GPS is imperfect and the location is adjusting slightly all the time, the tolerance distance helps to filter out insignificant movements. Once the device/person has moved in excess of the tolerance distance, a change in the Direction of Travel is calculated.

### URL

https://www.home-assistant.io/integrations/proximity/

### Version

2024.5.5

### Additional information

Note that the Markdown is not respected in the Note callout

**Comment by mib1185** [comment]
Hi @theukedge 

in the backend all calculations are done in meters and later converted based on the selected unit system in HA (_see [setup basic information](https://www.home-assistant.io/docs/configuration/basic/)_). Therefore the tolerance needs to be provided in meters and is used to filter out small GPS changes due to inaccuracies of GPS.
I agree that the current hint is somehow unclear formulated, will fix this soon
