### ISSUE TITLE
guide not working for me, install with ESP32-S3-BOX3 in chrome but no wi-fi

### ISSUE THREAD

**Issue by starschild86** [home-assistant/home-assistant.github.io#33039]
### Feedback

i followed the guide multiple times last week and again today.
i am always able to install voice assistant into my esp32 but never asks me for wifi input, then esp32 boots and it says no wi-fi.
i've tried to change port, change cable, reset pc, all with no luck.
a similar process for my two everything presence one esp32 devices worked yesterday (from this link) https://everythingsmarthome.github.io/everything-presence-one/updating.html
so i'm guessing my pc/ usb/ cable are ok?

### URL

https://www.home-assistant.io/voice_control/s3_box_voice_assistant/

### Version

2024.5.5

**Comment by c0ffeeca7** [comment]
Have you tried the troubleshooting steps? https://www.home-assistant.io/voice_control/troubleshooting_the_s3_box/

**Comment by kbx81** [comment]
We've identified and fixed the issue in the PR linked above; a patch has been released and the updated binaries will be available on the projects page in about a day or so.

**Comment by btreinders** [comment]
So link will not work yet?  It still is not asking to setup wifi after installation.  Thank you.

**Comment by kbx81** [comment]
Sorry about that -- the updated image is available on the site now. I tried it with my Box-3 and Box-Lite and it worked, although I did have to reset the Box-3 once manually after installing. Let us know if it works for you.

**Comment by btreinders** [comment]
The first time I went to the website and connected it asked to setup wifi right away without a fresh install.  It then asked to add to Home Assistant and that failed so I reset it manually like you had to and then it went to the No wifi sad face with bar code.  I installed again since this time there was only install and logs options again.  It finished installing and is just like before, never goes to wifi setup.  Thank you.

________________________________

**Comment by btreinders** [comment]
I tried some more and finally did get it to work.  Seems like there is still something there that isn't quite right but at least I am up an running!  Thank you!
________________________________

**Comment by Yeahoover** [comment]
Hello, I have the same issue. I used two different data cables (as described in the "The Wi-Fi dialog never shows after the installation"), but it does not work.

**Comment by bturrie** [comment]
I'm also having the issue, WIFI dialog never appears. The Next button just takes me back to the Install box. The screen gos blank for a long time afterwards but did show the "no wifi" screen eventually on at least one occusaion.

**Comment by kbx81** [comment]
Make sure you do not _manually_ force the S3 into boot loader mode before attempting to flash. If you are holding the "boot" button down while tapping the reset button, then you are manually invoking the bootloader. Don't do this, as it will, with absolutely certainty, prevent the Wi-Fi dialog from appearing after the installation completes. This happens because the S3 cannot be reset via the USB connection when it is manually forced into its bootloader mode. This is not something we can fix/have any control over -- it's just how the S3 works.

Manually invoking the bootloader is only necessary after performing a full erase on the S3, which you would need to be doing from the command line/terminal with `esptool`.

**Comment by bturrie** [comment]
Perhaps I'm stuck in bootloader mode or maybe not. I tried powering down and holding boot when I plugged the power in. Nothing happens the power light doesn't even come on. Is there something I should try or is it just dead?
    On Saturday, July 27, 2024 at 05:32:30 PM CDT, Keith Burzinski ***@***.***> wrote:  
 
 


Make sure you do not manually force the S3 into boot loader mode before attempting to flash. If you are holding the "boot" button down while tapping the reset button, then you are manually invoking the bootloader. Don't do this, as it will, with absolutely certainty, prevent the Wi-Fi dialog from appearing after the installation completes. This happens because the S3 cannot be reset via the USB connection when it is manually forced into its bootloader mode. This is not something we can fix/have any control over -- it's just how the S3 works.

Manually invoking the bootloader is only necessary after performing a full erase on the S3, which you would need to be doing from the command line/terminal with esptool.

**Comment by kbx81** [comment]
@bturrie holding the "boot" button down as you connect the USB cable also counts as manually invoking the bootloader. Doing so will result in the same behavior (the Wi-Fi dialog will not appear). As I mentioned above, unless you have manually erased the device using `esptool` from the command line/terminal, there is really no need to do this.

I am not sure why you don't even get a power light when you connect your S3-Box to USB. I might suspect you are using a bad cable, bad port, or a USB hub that isn't providing sufficient/correct power.
