### ISSUE TITLE
Websockets Support enabled for nginx

### ISSUE THREAD

**Issue by GreborB** [home-assistant/home-assistant.github.io#33074]
### Feedback

For reverse proxy to work from Nginx you need to enable Websockets Support, I had to dig deep to find someone who gave that solution.

### URL

https://www.home-assistant.io/integrations/http/

### Version

2024.5.5

**Comment by dannytsang** [comment]
The documentation describes Home Assistant's configuration with reverse proxies rather than the reverse proxy itself so I don't think it makes sense to add it to this page.

It might be suited somewhere else and looking at pages like https://www.home-assistant.io/docs/configuration/securing/#remote-access it doesn't go into detail. Any other ideas?
