### ISSUE TITLE
Cgroup version on debian for supervised installation

### ISSUE THREAD

**Issue by akrigator** [home-assistant/home-assistant.github.io#33169]
### Feedback

 I'm try to setup virtual Debian machine for running supervisor dev container. 
[Docker non-root instruction](https://docs.docker.com/engine/security/rootless/#known-limitations) suggest to set cgroup to v2, in this case then start of supervisor is failed with:
```
Startup dbus
unix:path=/run/dbus/system_bus_socket,guid=e5e117a740cba574462b619b6663edf6
Startup udev
Failed to set receive buffer size for device monitor, ignoring: Operation not permitted
Starting systemd-udevd version 252.22-1~deb12u1
LNXSYSTM:00: Failed to write 'change' to '/sys/devices/LNXSYSTM:00/uevent': Permission denied
LNXSYBUS:00: Failed to write 'change' to '/sys/devices/LNXSYSTM:00/LNXSYBUS:00/uevent': Permission denied
ACPI0007:00: Failed to write 'change' to '/sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0007:00/uevent': Permission denied
```
Home assistant suggest use cgroup v1, then getting:
```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to apply cgroup configuration: mkdir /sys/fs/cgroup/cpuset/docker/02335aab98195dec4f1c85690d9658a58ad22e501bdea5e23ccef18abdbbb8f3: permission denied: unknown.
```

so which should be used finally?

### URL

https://www.home-assistant.io/more-info/unsupported/cgroup_version/

### Version

2024.6.1

**Comment by frostworx** [comment]
I think this is getting important very soon!

Systemd cgroupsv1 has been deprecated and you need to forcefully enable it since systemd [v256-rc3](https://github.com/systemd/systemd/releases/tag/v256-rc3) by setting the kernel cmdline `SYSTEMD_CGROUP_ENABLE_LEGACY_FORCE=1`.
This enables cgroupsv1 for now, but will delay the boot process for 30 seconds _(see [here](https://github.com/systemd/systemd/issues/32998) for an upstream discussion)_

Are there any active plans to switch to cgroupsv2 for supervisor?

Edit: I also opened thread [here](https://community.home-assistant.io/t/cgroupsv1-no-longer-supported-by-systemd/742098), surprisingly this does not seem to be discussed anywhere yet

**Comment by frenck** [comment]
> [Docker non-root instruction](https://docs.docker.com/engine/security/rootless/#known-limitations)

The Home Assistant project doesn't running as non-root, which is most likely the cause of your issue.

../Frenck

**Comment by frostworx** [comment]
I use Arch linux and docker is running with root priviledges, so the more generic issue I reported apparently is a different one.
Just updated the [corresponding community thread](https://community.home-assistant.io/t/cgroupsv1-no-longer-supported-by-systemd/742098) accordingly

**Comment by akrigator** [comment]
> > [Docker non-root instruction](https://docs.docker.com/engine/security/rootless/#known-limitations)
> 
> The Home Assistant project doesn't running as non-root, which is most likely the cause of your issue.
> 
> ../Frenck

Thanks @frenck, yes the problem was in this. Just don't remember why i've decide to use non-root when have got an error to run devcontainer if there another option to add user into docker group.
