### ISSUE TITLE
auto create elements based on project file

### ISSUE THREAD

**Issue by hgehrts** [home-assistant/home-assistant.github.io#33177]
### Feedback

It's my first days of using Home Assistant... been a long iobroker user before. The KNX Integration went smooth without any issues - great work! Even with Multicast Adressing. What I'm missing is a way to control the objects from that KNX Tree right away like I'm used to in iobroker (for testing for example). But also a automatic generation of the group adresses and elements would be helpful, even if it's only semi-complete. I'm not a big fan of fiddling around with yaml on the cli myself, IMO yaml is a pita and too error prone. So: anything that could help here is highly welcome. 

### URL

https://www.home-assistant.io/integrations/knx/

### Version

2024.6.1

**Comment by farmio** [comment]
Hi 👋! 
Please be aware that issues in this repository target problems with the documentation of Home Assistant. For feature requests and support questions please head to the [HA community forums](https://community.home-assistant.io).

That said, there probably won't be any "auto entity creation from a project file" in the foreseeable future, since a knx project file just doesn't have enough semantic information to do that reliably. There are however efforts to move the configuration to the UI. 
See https://github.com/home-assistant/core/pull/104079 and https://github.com/XKNX/knx-frontend/pull/112
And the discussion here https://github.com/XKNX/knx-frontend/discussions/50
Any help with that is highly welcome 😉
