### ISSUE TITLE
docker-compose.yaml modernization

### ISSUE THREAD

**Issue by robd003** [home-assistant/home-assistant.github.io#33259]
### Feedback

docker-compose.yaml no long has a `version: 3` header.

Why exactly is privileged mode needed?

One other thing, is it **required** to run home assistant in network=host mode? What about using a docker bridge and forwarding ports?

### URL

https://www.home-assistant.io/installation/linux/

### Version

2024.6.2

**Comment by frenck** [comment]
> Why exactly is privileged mode needed?

> One other thing, is it required to run home assistant in network=host mode? 

Because Home Assistant integrations use many different privileges, for example, to use certain ports, it also sniffs traffic (e.g., DHCP traffic) for device discovery. Additionally, the extendable nature of Home Assistant means there are integrations that can require other things we do not know up front.

Don't get me wrong, Home Assistant is open source. You can run it any way you like, but if you run things differently, you might run into unexpected issues that are yours to solve.

../Frenck

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @robd003. Closing this as fixed by #33343
