### ISSUE TITLE
No Bi-Directional Voice Communication

### ISSUE THREAD

**Issue by barthel-eu** [home-assistant/home-assistant.github.io#33286]
### Feedback

Based on the positive sound of the Reolink integration, local push, I ordered the E1 Outdoor Pro. While the setup on Reolink side was a hurdle (App didn't work, needed to use the old-style "client software". Quite contrary, the recognition in Home Assistant was a blast. Quick, recognized, all good. Added a Picture Glance with panning. As a newbie to HA will sure find out how to add zoom, though in general I expect not much use on the door. But. ...

Oops. Where is the bi-directional voice communication needed to use it as a door cam?
Does it need additional workaround?
Latest Home Assistant, updated Reolink Firmware.

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2024.6.2

**Comment by starkillerOG** [comment]
@barthel-eu thanks for the feedback.
There is a number entity available that controls the zoom of the E1 Outdoor Pro, so you can control the zoom of the camera in HomeAssistant quite easily.
Go to settings->devices&services->Reolink-> click the "1 device" in blue under the name of the E1 Outdoor Pro.
That will bring you to the device page that lists all the entities for that camera. you can have a look around there for all the possibilities to control the E1 Outdoor Pro.

Unfortunately 2 way audio is not (yet) implemented in HomeAssistant.
Audio is available (if you turn on the audio recording switch) in the video stream, but you can not talk back.

The siren enties are available, so you can sound the siren.

Talking back is only available in the Reolink app itself, not yet in HomeAssistant. sorry.

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).

**Comment by barthel-eu** [comment]
Okeh... Second failure for a Door Camera in Home Assistant. The bi-directional communication is only available in their Windows client in a lousy quality. From first sight it looks like you implemented everything in the web interface.
May I kindly ask if you by chance know of a full scale camera (not a doorbell-camera) with bi-directional communication that works in Home Assistant?
First attempt was Bosch (good press), but camera + Yale Linus door opener work neither well together in Bosch Smart Home App, nor at all in the Bosch Camera App, and sure also not in Home Assistant.
So for the door opener to react faster I found a way to trigger an electric door opener with a Shelly. But I need a camera. And prefer a high-resolution ceiling cam over one of those doorbell-crutches like Ring. And local over (slow) cloud. Reolink sounded just like it.
Learning curve. Recommendation(s) appreciated.
Best - Juergen

**Comment by barthel-eu** [comment]
May I (strongly) recommend to also add such shortcomings to the product integration pages? It's my second (expensive and excessively time consuming) learning curve just on cameras, after the mess-up with Bosch (the camera is _**not**_ supported in Home Assistant), where here the bi-directional communication is _**not**_ supported in Reolink.

Not everyone bothers just about "surveillance", I look for a smart, instant working door camera with two way communication, which becomes a common use case to do better than i.e. Ring.? Smart means, it should integrate with the door opening, which camera provider apps nor door opening apps bother about really, so Home Assistant would have a USP.

edit: Typo corrected

**Comment by starkillerOG** [comment]
I don't know of any cam that works with bi-direction audio in HomeAssistant.
However I do no that some Reolink cameras can be made to work with bi-direction audio in HomeAssistant using custom integration and cards (maybe the frigate card, I don't remember). So it is possible, but not with the build-in reolink integration.

There is a pretty extensive documentation here: https://www.home-assistant.io/integrations/reolink/ which lists all the supported features of the Reolink integration. Bi-direction audio is not listed there (since it is not supported).
It is a bit silly to go list all the things not possible with reolink camera's since that list can always be as long as you want.

You will see that Reolink cameras are amoung the most tighely integrated in Home Assistant and already provide a lot of control over the camera from Home Assistant. Bi-direction audio is just not one of the features. Probably I will add it at some point.
But I have limited free spare time.....
