### ISSUE TITLE
There is no "advanced" link after I got message "Google hasn’t verified this app"

### ISSUE THREAD

**Issue by gmrvos2** [home-assistant/home-assistant.github.io#33289]
### Feedback

This is new screen. Please advice how to procide 
![Screenshot 2024-06-16 155733](https://github.com/home-assistant/home-assistant.io/assets/28431873/1e30d450-6e0b-4da9-85d2-84a1aebda9f6)

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2024.6.3

**Comment by allenporter** [comment]
Hello. See the [Troubleshooting](https://www.home-assistant.io/integrations/nest/#troubleshooting) section of the nest integration documentation for the error "Error 403: access_denied" which tells you the configuration steps missed for the *Configure OAuth Consent screen" step.  Closing since this should answer the question, and happy to have you take further support questions the community forums.
