### ISSUE TITLE
Hue vs ZBT / Skyconnect

### ISSUE THREAD

**Issue by MattB95** [home-assistant/home-assistant.github.io#33359]
### Feedback

This documentation appears to say that an external Hue hub is essential. Likewise the Hue page.

As a result I nearly went and bought a Hue hub, frustrated that I’d bothered with this project and also spent on a SkyConnect dongle… wondering what the point of the latter was.

Would be much better if both pages pointed to the skyconnect / ZbT page as an option. Thanks!

### URL

https://www.home-assistant.io/integrations/emulated_hue/

### Version

2024.6.4

**Comment by Hedda** [comment]
> Would be much better if both pages pointed to the skyconnect / ZbT page as an option. Thanks!

What other page/pages are you referring to?

Do you mean that it should also make reference to the ZHA (Zigbee Home Automation) integration as an alternative solution or?

- https://www.home-assistant.io/integrations/zha

As I understand they serve two very different purposes:

* Emulated Hue integration is meant to allow you to present non-Hue products already added to Home Assistant by other means as native Philips Hue devices to other ecosystems like Google Home and Amazon Alexa via emulating Philips Hue API.

* ZHA (Zigbee Home Automation) integration is for connecting Philips Hue lights and other Zigbee devices to Home Assistant, (e.g. it acts as a Zigbee gateway host application for conneting and integrating native Zigbee devices into Home Assistant).

PS: Off-topic but check out this indirecty related community guide and forum discussion thread about adding/moving Philips Hue light products to the ZHA (Zigbee Home Automation) by using SkyConnect/ZBT-1 radio dongle instead of a Philips Hue Bridge:

- https://community.home-assistant.io/t/migrating-from-a-philips-hue-bridge-to-the-zha-zigbee-home-automation-integration/620862

**Comment by MattB95** [comment]
Hi all,

Many thanks for the rapid response!

Yes, in the end I worked out that ZHA existed and was what I needed; and
what Emulated Hue is for in distinction 👍

All I was saying is that this was “in the end” and that along the way it
was somehow difficult to find the ZHA page (or realise this was what I
needed). On the way I encountered 2 pages that *seemed* to say I needed a
Hue hub. So much so that I nearly pulled the trigger on a new Hue hub that
I didn’t actually want.

A one-liner linking to ZHA as in “you may be looking for this” would have
been super helpful to this new user 👍

As it is I managed to read the intro to the Hue Emulation page as saying a
Hue hub was obligatory for Zigbee.

This may seem crazy to someone who knows what “Hue Emulation” means, but to
a new user who is looking for HA to replace (emulate?) the function of a
hue hub* such clarification early in the did would be super useful.

Many thanks!

Matt

* mine is the old obsolete one, hasn’t worked for years, was buying into HA
to replace it!
