### ISSUE TITLE
input_text  not editable on mobile

### ISSUE THREAD

**Issue by dimagoltsman** [home-assistant/home-assistant.github.io#3342]
Tested with LG v20 - chrome browser.
A tap on the field opens the history window instead edit window.

my settings:

input_text:
  boiler_time_mins:
    name: Boiler Time
    pattern: '[0-9]*'
    min: 1
    max: 3
    initial: 30
    icon: mdi:camera-timer

**Comment by frenck** [comment]
I'm closing your issue since it looks misplaced. This is the issue tracker for the Home Assistant Documentation & Homepage. 

Please report technical Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration, and usage.

Thanks!
