### ISSUE TITLE
delete removed devices in fibaro integration

### ISSUE THREAD

**Issue by pblacky** [home-assistant/home-assistant.github.io#33467]
### Feedback

I had to remove several devices from my Fibaro HC2 and re-learn them.
These are still present in the HomeCenter with the old IDs!
I managed to delete the corresponding entities, but the associated device cannot be deleted because there is no function for this

### URL

https://www.home-assistant.io/integrations/fibaro/

### Version

2024.6.4

**Comment by rappenze** [comment]
Thanks for your report. That's true, currently the fibaro integration does not support to remove devices and also does not remove them automatically. So the only option you have is to remove the integration and add it again (since the fibaro integration uses unique ids for the entities and devices you should not loose your configuration by doing this, but I didn't try it myself since quite a long time so i'm not 100% sure if this is still the case). I will have a look if this feature can be implemented easily. 

Be aware that you are reporting in the wrong location, this is the home assistant documentation repository and you should only report documentation isssues here. Use https://github.com/home-assistant/core instead to report bugs in home-assistant server.

**Comment by pblacky** [comment]
Sorry for posting in the wrong area!

Unfortunately I don't know the structure of Github, this was my first time here!

I hope it's OK to answer here, because it looks to me like you assigned the topic correctly @rappenze!?

I removed the integration for testing and reinstalled it. It looks like you're right, at first glance no connections in the dashboards have been lost!

However, I had to assign all of my 98 devices to a room again MANUALLY, that was a bit of work ;-(
But now it looks neat again.....

Is it possible to compare the rooms from the Fibaro HC2 with those of the Home Assistant when installing the integration?

Then you wouldn't have to assign them manually! Just an idea ;-)

**Comment by pblacky** [comment]
Sollte es eine neue Version zum Testen geben, kann ich mir das gerne mal ansehen ....
Liebe Grüße in die Schweiz ;-)

**Comment by rappenze** [comment]
Let's close this issue here as it is the wrong place.

For reference, most probably the function to remove device will be added: https://github.com/home-assistant/core/pull/121427

**Comment by rappenze** [comment]
@home-assistant close
