### ISSUE TITLE
customization icon attribute

### ISSUE THREAD

**Issue by vinojv96** [home-assistant/home-assistant.github.io#3350]
I found a Bug on HA v0.53 
while editing icon attribute on customization dashboard not changes the icon.Because it saves the icon attribute as 
**icon: 'icon_name'** mdi not included in **customize.yaml** entry
![customize_bug](https://user-images.githubusercontent.com/15646153/30266494-2a4386fc-96fd-11e7-8ecd-573ff02a9caf.JPG)

I fixed this by manually included **icon: mdi:'icon_name'** manually in **customize.yaml** file
Or including **mdi:** with icon name as shown below
![customize_bug_fix](https://user-images.githubusercontent.com/15646153/30266749-f55563a6-96fd-11e7-9a4a-25247704e23c.JPG)
Fix this bug on next update!
Thank You!

**Comment by frenck** [comment]
I'm closing your issue since it looks misplaced. This is the issue tracker for the Home Assistant Documentation & Homepage. 

Please report technical Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration, and usage.

Thanks!
