### ISSUE TITLE
After update to 0.53.0, Homematic does not load.

### ISSUE THREAD

**Issue by LeonVos** [home-assistant/home-assistant.github.io#3355]
Hi, after the new update 0.53.0 the Homematic gives a "config" config error. Configuration worked perfect before the update (from 0.52.1)

How can i down grade to 0.52.1 (or fix this problem)

 install homeassistant==0.52.1  (with putty) gives a question back with
   -c      Just copy (default)
        -d      Create directories
        -D      Create leading target directories
        -s      Strip symbol table
        -p      Preserve date
        -o USER Set ownership
        -g GRP  Set group ownership
        -m MODE Set permissions
        -t DIR  Install to DIR
THX Leon vos

**Comment by frenck** [comment]
I'm closing your issue since it looks misplaced. This is the issue tracker for the Home Assistant Documentation & Homepage. 

Please report technical Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration, and usage.

Thanks!
