### ISSUE TITLE
The backup page doesn't show how to configure backups? Where are they stored to?

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [home-assistant/home-assistant.github.io#33564]
### Feedback

Should provide a link at least, I'm using a docker container to run HA.

### URL

https://www.home-assistant.io/integrations/backup/

### Version

2024.7.0

**Comment by j4n-e4t** [comment]
@h0jeZvgoxFepBQ2C The documentation actually does say where the backups are stored: It's in the `backups` directory in your `configuration directory`. However since this is only mentioned under the _Restore_ section, I've opened a PR (#33637 ) to make this more clear.

**Comment by h0jeZvgoxFepBQ2C** [comment]
True, you are right, sorry. 

Could you also imporve if this backup also includes recordings (which I have in postgres right now)? Is this included? 
Its only written some ambigious "...some metadata"?

**Comment by j4n-e4t** [comment]
There is no reason to apologise. 

As for the history recordings: I did some investigation and as you can see in the attached screenshot, it doesn't seem as if they were part of the backup when using an external DB such as Postgres. It's just a dump of the configuration directory. Since the `data/.storage` folder is contained in the backup, I assume that the history is backed up, when using the internal recoding system. For Postgres, I'd recommend to do a manual backup, just to be safe.

And the _metadata_ is this JSON file:

```json
{
  "slug": "3184cbda",
  "name": "Core 2024.8.0.dev0",
  "date": "2024-07-08T15:04:09.430509+02:00",
  "type": "partial",
  "folders": ["homeassistant"],
  "homeassistant": { "version": "2024.8.0.dev0" },
  "compressed": true
}
```
<img width="1144" alt="Screenshot 2024-07-08 at 17 29 42" src="https://github.com/home-assistant/home-assistant.io/assets/130256240/e60af9f4-8a37-46ff-b530-ecfa1da40a6c">

**Comment by h0jeZvgoxFepBQ2C** [comment]
Great, I see, thank you so much!

**Comment by j4n-e4t** [comment]
No problem 😉
