### ISSUE TITLE
Blog post content jitter-y when scrolling on Android

### ISSUE THREAD

**Issue by tetele** [home-assistant/home-assistant.github.io#34181]
### Feedback

Using Chrome on Android, when there is an image at the bottom of the viewport and i'm slowly sliding my finger to scroll down, the viewport "jumps" to keep the image in place. Sliding quickly to move the image completely into the viewport stops the jitter.

I've not been able to reproduce the issue on Chrome on Windows.

### URL

https://www.home-assistant.io/blog/2024/08/07/release-20248/

### Additional information

https://github.com/user-attachments/assets/1b797268-2e39-4729-ba26-59d765dcec7b

**Comment by GSzabados** [comment]
@frenck, @Madelena there are already 5 issues logged regarding the scroll on the new webpage design. Can those issues being looked at? 
Also there are also some accessibility issues logged regarding font size and scrollability, which in the 21st century should be a priority, due to it is a form of discrimination.
