### ISSUE TITLE
Provode step by step instruction how to use virtual buttons.

### ISSUE THREAD

**Issue by NoUsername10** [home-assistant/home-assistant.github.io#34287]
### Feedback

Hi!
Great integration, use it every day.

Could we get a step by step instruction (explain to me like I'm 5 years old type) on how to add a Shelly virtual device (component) and how to make a scene with them?

I have some Shelly WallDisplays so this instruction would be for that, now that the integration support is extended.

Thank you!

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2024.8.1

**Comment by bieniu** [comment]
This is a documentation repository, this is not the right place to ask for support, especially if you want step-by-step instructions. Open a thread on the community and tag me and I'll show you some examples.

**Comment by NoUsername10** [comment]
Hello @bieniu 
Thank you for your reply and your offer to help, that is very kind of you!

Perhaps i was not clear in my post.
I read in the changelog 2024.8 .1 of HA that the Shelly integration was extended and wanted to know more, but could not find it or understand how to do it on the integrations page.
I pressed the "HELP US IMPROVE OUR DOCUMENTATION" link on your integrations page and ended up here.

I was not asking for help in coding or instructions.
Only to say that it would be helpful with some guidance in the integrations documentation, (Shelly Wall display with viritual components in this case)
I understand that not everything can be covered, but something like a "Hello world" or similar would go a long way to understand the way to do it for users, so we can use all the work you have put in to make the integration great.

There is always a "gap" between having a great integration (not at all limited to Shelly) with so may possibilities, but its almost impossible to use them, for "normal" people :-) without a little help.

Best Regards and keep up the good work!

**Comment by bieniu** [comment]
You need to remember that virtual components are a feature of Shelly, not Home Assistant. Home Assistant since version 2028.0 supports these components, this means, if you create them on the Shelly side, they will be reflected on the Home Assistant side. That's why I think you should look for information on how to create and use virtual components in Shelly documentation or support. You can start [here](https://shelly-api-docs.shelly.cloud/gen2/DynamicComponents/Virtual/) and [here](https://community.shelly.cloud/forum/147-virtual-components/). As a WallDisplay user, you may find this [video](https://www.youtube.com/watch?v=48066yblVGU) helpful (you need also such [automation](https://gist.github.com/bieniu/fd9b1191b6be7294e8dc2cf7245149bb)).
Besides, virtual component support in HA is a feature that opens up a lot of possibilities and we ourselves don't fully know how users will use it. If you have a use case, I encourage you to open a PR and share it with the community.

**Comment by NoUsername10** [comment]
Hi again, yes i understand what you are saying.
And thank you for the links, I have looked at the Shelly API before, but perhaps I'm not technical enough to "get it" as for me at least the "step by step" instructions are needed to get started, then after that hurdle its a little bit less complicated.

Even with AI (tested many of them) none of them get it right, there is always something missing / wrong / guesses that are made.

So after some days of struggle, I have  made some Shelly VD scripts that gets the current Sonos song and Album image from Home Assistant and shows them in the shelly app.

I could share it, but i don't know where to share it, as i don't know where to open a PR (Pull request?) in the correct place.
Jesus, i feel like such a noob with this and i have programmed Crestron systems... 😂

**Comment by bieniu** [comment]
I think the easiest way to share your solution is to use [Share your Projects](https://community.home-assistant.io/c/projects/9) or [Community Guides](https://community.home-assistant.io/c/community-guides/51) sections in the community. In my opinion this option is definitely better if your solution is based on Shelly scripts.

If the solution is based on virtual components and Home Assistant automation, you can add the solution description to the Shelly integration documentation. You should open a PR targeting the `current` branch. Please take a look [here](https://developers.home-assistant.io/docs/documenting/).
