### ISSUE TITLE
WeatherFlow Cloud not accepting my personal API key...

### ISSUE THREAD

**Issue by codemonkey2k5** [home-assistant/home-assistant.github.io#34317]
### Feedback

I am attempting to add the WeatherFlow Cloud integration to HomeAssistant.  In doing so I am challenged for my Personal API key.

So I created one and entered it in to the field.  No matter how I try it always reports:  API KEY INVALID or Unknown error occurred.
I tried it with and without the dashes.  

Any assistance with this would be greatly appreciated.

### URL

https://www.home-assistant.io/integrations/weatherflow_cloud/

### Version

2024.8.1

**Comment by frenck** [comment]
Hi there @codemonkey2k5 👋 

It sounds like you are in need of support. For that you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places. If it turns out we can improve our documentation based on your findings, we are happy to learn about those.

Thanks! 👍

../Frenck
