### ISSUE TITLE
Clarify which devices the Linkplay integration supports

### ISSUE THREAD

**Issue by clavius11** [home-assistant/home-assistant.github.io#34369]
### Feedback

Not all devices under the LinkPlay brand are supported by this integration.  It would be helpful to specify which devices are supported (or which are not).  For example, WiiM streamers are NOT yet supported.

### URL

https://www.home-assistant.io/integrations/linkplay/

### Version

2024.8.2

**Comment by txitxo0** [comment]
I don't know if it is a lack of documentation or not. My behavior is that I can no longer use the HACS integration because it is not working, and the new integration says the connection fails on setting up. My device is an Arylic H50, and it is right connected to my network.

I had found some other related comments in a closed topic (wrong located issue):
@josephnfoley [josephnfoley](https://github.com/josephnfoley)
_Same issue here. I was using a the hacs linkplay integration which I modified to better suit the Wiim however now this no longer works and the new native integration fails to connect.

I have removed the old integration folders from custom_components and i have removed the reference to it in my configuration yaml. I can now see the new integration in the add integration window in settings - integrations however when i select it and input the ip address for my Wiim Pro i receive the "Failed to Connect" error.

I believe I read somewhere that the Wiim Pro needs https to connect however I can no longer find that post and I can't find any solutions. Help Please._

@greeferd [greeferd](https://github.com/greeferd)
_Feedback
I tried to add my Wiim Pro to home assistant with new linkpay integration. After typing the ip address of my device I get "Failed to connection" .

URL
https://www.home-assistant.io/integrations/linkplay/_

**Comment by silamon** [comment]
Support has been added in the meantime.
