### ISSUE TITLE
Tested this integration with a Dragino LHT65 and external reedcontact (external interupt mode): the integration is too slow..

### ISSUE THREAD

**Issue by askmurphy** [home-assistant/home-assistant.github.io#34403]
### Feedback

Tested this integration with a Dragino LHT65 and external reedcontact (external interupt mode): the integration is too slow..
Using the LoRa sensor for a letterbox: the integration doesn't see the changed status. Seems to be the polling time is too large.
With the normal MQTT it's working perfect: I use the an MQTT Nodered now for this.

### URL

https://www.home-assistant.io/integrations/thethingsnetwork/

### Version

2024.8.2

### Additional information

Maybe not the right place for this bug-report, sorry.

**Comment by angelnu** [comment]
Thanks for the feedback @askmurphy.

indeed, the current implementation uses polling mode only which is limited by the polling time. I have prepared it to implement pysh mode as well: https://github.com/angelnu/thethingsnetwork_python_client/issues/8

Beyond being slow to get updates do you get the sensors updates eventually?

Btw: since this is not a documentation issue then it would better fit into the core repository where the integration code is checked in.

**Comment by askmurphy** [comment]
> Thanks for the feedback @askmurphy.
> 
> 
> 
> indeed, the current implementation uses polling mode only which is limited by the polling time. I have prepared it to implement pysh mode as well: https://github.com/angelnu/thethingsnetwork_python_client/issues/8
> 
> 
> 
> Beyond being slow to get updates do you get the sensors updates eventually?
> 
Yes, i get some updates but much too late. Useless updates 😀

Maybe in your future update, will use nodered mqtt node for it for now 😀

Keep on the good work, really appreciated!!
