### ISSUE TITLE
ZHA Global Options are missing from documentation

### ISSUE THREAD

**Issue by wbyoung** [home-assistant/home-assistant.github.io#34668]
### Feedback

As reported on the [community site](https://community.home-assistant.io/t/what-do-the-toggle-settings-in-zha-configuration-actually-do/729861):

> I can’t seem to find the answer to this anywhere. There are toggles in the ZHA configuration page with no details and nobody seems to know exactly what they do. What exactly do these settings do?
> 
> 1. Enable enhanced light color/temperature transition from an off-state
> 1. Enable enhanced brightness slider during light transition
> 1. Always prefer XY color mode
> 1. Group members assume state of group

If we can get some clarity around these, I'm happy to open a PR to include them in the docs.

### URL

https://www.home-assistant.io/integrations/zha/

### Version

2024.9.1

**Comment by TheJulianJES** [comment]
1. Enable enhanced light color/temperature transition from an off-state:
For older non Zigbee 3.0 lights, this still allows a proper transition from an off-state to a new color (without seeing the old color). (recommended: off)

2. Enable enhanced brightness slider during light transition:
This avoids seeing intermediary brightness state when turning on lights with a transition. (recommended: on)

3. Always prefer XY color mode:
This forces ZHA to always send colors in XY, never HS. (recommended: on)
This option might be removed in the future, as there aren't any upsides to using HS on Zigbee lights.

4. Group members assume state of group:
When using ZHA groups, turning on a ZHA group light makes the ZHA group members optimistically change their state to "on", instead of waiting and polling the lights when off. (recommended: on)
We could also think about removing this option in the future (and also leave it "on" in the background), since this is how Hue and Z2M behave by default and there are few reasons to disable this.

The recommendations are also the defaults.

**Comment by wbyoung** [comment]
Thanks, a PR has been created at #34670.

**Comment by wbyoung** [comment]
Dearest bot,

It's probably still an issue until the PR that addresses it gets merged. Thanks for your understanding.

😜
