### ISSUE TITLE
authentication is not possible

### ISSUE THREAD

**Issue by tvergov** [home-assistant/home-assistant.github.io#34789]
### Feedback

Hello guys,

I'm using LR4 and it seems doesnt work with this addon. I dont see it's specified what products are supported or tested with it.
I cannot even authenticate so maybe its totally outdated.
On other places like IFTTT i can authenticate but LR4 is not supported only LR3.

### URL

https://www.home-assistant.io/integrations/litterrobot/

### Version

2024.9.2

**Comment by natekspencer** [comment]
@tvergov, this is the wrong repo (documentation) to post issues with integrations. You should use home-assistant/core instead. 

That being said, I just tested logging in again and it worked, albeit slow. This integration is reverse engineered, so it's always possible it can break if whisker makes changes, but is otherwise functional. Please try logging in again and give it time, as well as enabling debug logging to be able to better help. If you still have an issue after that, open an issue in the core repository and post the relevant logs.

**Comment by natekspencer** [comment]
@home-assistant close
