### ISSUE TITLE
missing sensor name in proximity

### ISSUE THREAD

**Issue by phsdv** [home-assistant/home-assistant.github.io#34863]
### Feedback

In proximity documentation the states of the sensor are shown however I am missing how the sensor itself is named.

### URL

https://www.home-assistant.io/integrations/proximity/

### Version

2024.9.2

**Comment by mib1185** [comment]
I'm not sure what you're missing here - each sensor has its own sub-section int the [sensors section](https://www.home-assistant.io/integrations/proximity/#sensors) in the docs. The section title is the common name of the sensor, but the entity id (_`sensor.*`_) is based on your local language because of translation.
