### ISSUE TITLE
Local calendar documentation does not provide any useful information

### ISSUE THREAD

**Issue by RockDuster** [home-assistant/home-assistant.github.io#34928]
### Feedback

This isn't even documentation. There's no information on how to use the integration or configure it. It doesn't show any examples of YAML configuration. There's nothing whatsoever in the HA UI for configuring it. How the actual hell do you even use this? Does it even work?

### URL

https://www.home-assistant.io/integrations/local_calendar/

### Version

2024.9.3

**Comment by allenporter** [comment]
Hi. Local calendar is one type of calendar integration similar to others like Google Calendar, Todoist, etc.  You can see the primary Calendar integration documentation for information that applies to all calendar integrations here https://www.home-assistant.io/integrations/calendar/ -- in particular i think you are looking for the information under "Viewing and managing calendars" which described the UI for editing calendar events, and later on the page there are automation examples. The integration is configured from the UI and does not have yaml configuration since there is nothing to configure.
