### ISSUE TITLE
Position of blinds in HA is opposite of blinds in real

### ISSUE THREAD

**Issue by toktoktokt** [home-assistant/home-assistant.github.io#35116]
### Feedback

Hello,
thank you very much for the integration of Warema-stuff, I really appreciate it and am happy to have it the "natural way" as core integration.
I have one topic that came up immediately after having started to set up the cards on my dashboard:
The Position of all blinds is in HA exactly opposite of the position of the "real" blinds / covers.
Do I have to configure something in addition to put it upside down?
Thank you and best regards,
tok

### URL

https://www.home-assistant.io/integrations/wmspro/

### Version

2024.10.1

**Comment by mback2k** [comment]
Good point, for normal covers the position would need to be inverted in the integration, but for awnings I decided not to, because an awning is technically considered open if is driven out and closed if is driven into the cassette/storage, right?

At least that is the general concept I am aware of and that also Warema uses. The visuals and percentages in Home Assistant don't match this at the moment, because I think this is the first awning integration.

What type of covers do you have?

**Comment by toktoktokt** [comment]
Thank you for the quick response!

We have these vertical awnings:

https://www.warema.com/de-de/markisen/fenster-system-markise-fsm-mit-easyzip-fuehrung/

**Comment by mback2k** [comment]
Ah, okay. These act basically like normal covers, but identify as awnings. I guess I will need to talk to some core developers how to handle this situation.

**Comment by toktoktokt** [comment]
Thanks for taking care!

**Comment by mback2k** [comment]
See existing discussion here: https://github.com/home-assistant/architecture/discussions/979#discussioncomment-10884489

**Comment by toktoktokt** [comment]
... ok, seems to be a bigger and general discussion, as far as I understand as non-dev. Try to follow the topic nevertheless over there. Thank you!

**Comment by mback2k** [comment]
I guess in the meantime I will just invert the positioning and treat everything like a normal cover.

**Comment by toktoktokt** [comment]
... that would be great! Looking forward to seeing the big new "cover"-architecture, even though the discussion in this topic seems not be quite lively at the moment.

**Comment by frenck** [comment]
Hi there @toktoktokt 👋 

Oh and thanks, @mback2k for jumping in here as well. However, I will go ahead and close this issue.

The reason is you submitted documentation feedback, and there is no amount of documentation we can adjust to change this for you.

Additionally, this is doubtful an issue but, at best, a feature request. Home Assistant currently does not have such features. As per the above, architectural discussions are ongoing, but there are also open feature requests in our community forums (which is the place where we collect that kind of thing).

When you are unsure on where to go; please see <https://www.home-assistant.io/help> for guidance.

../Frenck

**Comment by toktoktokt** [comment]
@mback2k Hello Marc, thank you for taking care and for the fix for Warema-implementation, thanks for your work!

**Comment by toktoktokt** [comment]
@mback2k Hello Marc, thank you for taking care and for the fix for Warema-implementation, thanks for your work!
