### ISSUE TITLE
APsystems integration on HAssOS strains SSD

### ISSUE THREAD

**Issue by hubbty** [home-assistant/home-assistant.github.io#35171]
### Feedback

I have recently installed HAssOS on a Raspberry PI 4 8GB solely in order tu use the APsystems integration. It runs from a SSD. The LED of this SSD indicates that Homassistant is keeping it very busy all the time. To me this feels unnecessary. To give you an impression of what I mean, I've uploaded a short videoclip to [https://nowtransfer.de/f86d97e81a63](https://nowtransfer.de/f86d97e81a63) . It will be available there for 8 weeks.
Apart from the APsystems integration there is only 1 Gosund SP1 plug connected with 1 automated switches per day.

- Is this constant reading/writing to the SSD normal? 
- Is there a way to set an interval for how often data from the inverter are to be retrieved?

### URL

https://www.home-assistant.io/integrations/apsystems/

### Version

2024.10.1

### Additional information

Core 2024.10.1
Supervisor 2024.10.0
Operating System 13.1
Frontend 20241002.2

**Comment by mawoka-myblock** [comment]
Thanks for bringing that up. A quick tip regarding creating issues in general: You should be able to attach the video directly to the issue here on GitHub instead of linking to a more or less random website. That out of the way, here are my thoughts on that:

- If it's a problem with the APsystems integration, try disabling it temporarily or check when the inverter is offline.
- Absolute numbers help to put the numbers into perspective, so I'd appreciate you somehow finding some exact numbers regarding the disk IO.
- I doubt it's either a flaw in home Assistant or even less, a flaw in the APsystems integration.

Here's my Home Assistant OS disk IO measured by proxmox:
![image](https://github.com/user-attachments/assets/1dec42bc-674b-4a8c-856c-96085dffdfa2)


My Home Assistant installation is quite big in the sense of connected devices feeding data into it.


Please verify that it's a problem of the APsystems integration, otherwise I won't be able to help you as that'd be out of my scope regarding time, skill and motivation.

**Comment by hubbty** [comment]
Thank you!  This time my new video seems to have been accepted here:
https://github.com/user-attachments/assets/2b2d19a9-7d6a-42b9-901c-be7f49c10d40

I have no idea, how I might get the numbers you asked for. The LED does blink now less frequently after APsystems integration as well as its history and the Gosund plug too are disabled.

Could writing the history of the inverter be the cause for that intense usage of the SSD? Is there a way to write the history only e.g. every 5 minutes?
