### ISSUE TITLE
Missing special Characterst for Reolink Passwords

### ISSUE THREAD

**Issue by DumpName** [home-assistant/home-assistant.github.io#35302]
### Feedback

I recently set up a new Reolink camera. I noticed during the integration process that the set of special charaters differs from the character set that is allowed by reolink.
Reolink allows the following characters in addition to alphanumeric characters:
```!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~``` and space.
The current implementation that allows only `@$*~_-+=!?.,:;'()[]` as special characters is therefor outdated.

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2024.10.3

**Comment by reedy** [comment]
Noting this is for the HA documentation...

https://github.com/starkillerOG/reolink_aio/blob/fa2b834424952a25fb10c0f3b61195906bb92706/reolink_aio/api.py#L114-L116

```
# not all chars in a password can be used in the URLS of for instance the FLV stream
ALLOWED_SPECIAL_CHARS = r"@$*~_-+=!?.,:;'()[]"
ALLOWED_CHARS = set(r"abcdefghijklmnopqrstuvwxyz" "ABCDEFGHIJKLMNOPQRSTUVWXYZ" "0123456789" + ALLOWED_SPECIAL_CHARS)
FORBIDEN_CHARS = set(r"""#&% ^`"\/|{}<>""")
```

It would look like the list needs updating over at https://github.com/starkillerOG/reolink_aio, a release tagging and that pulling into HA and hten the docs can be updated to match...

**Comment by starkillerOG** [comment]
See my explanation here: https://github.com/home-assistant/core/issues/123302#issuecomment-2274337355
Closing this issue since it is a duplicate.

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).
