### ISSUE TITLE
Documentation not displaying correctly on my Motorola mobile

### ISSUE THREAD

**Issue by steveuk23** [home-assistant/home-assistant.github.io#35301]
### Feedback

I was looking through various documentations on my mobile (Motorola ) and quite a few don't load correctly they are really narrow and do not fill the page.

https://github.com/user-attachments/assets/84e6efcb-3c84-47af-9a18-8cfe2a19e94d

### URL

https://www.home-assistant.io/integrations/google_generative_ai_conversation/

### Version

2024.10.3

**Comment by tronikos** [comment]
I can fix it locally in my browser developer tools with this CSS: `word-break: break-all;`

With it:

<img width="400" alt="image" src="https://github.com/user-attachments/assets/d3649b15-cf96-47b0-817e-f77934094094">

Without it:

<img width="399" alt="image" src="https://github.com/user-attachments/assets/908dcb1d-770e-4a87-88bd-ecfaf9bae217">


But since this applies to many pages I don't feel comfortable making such a change
