### ISSUE TITLE
Support for NFC and fingerprint on G4 Pro door bell

### ISSUE THREAD

**Issue by robertwebbe** [home-assistant/home-assistant.github.io#35626]
### Feedback

Yesterday UniFi Protect 5.1.34 was released as EA. One of the new features is support for NFC and fingerprint.
Can you look into whether this can be supported in the Protect integration?

https://community.ui.com/releases/UniFi-Protect-Application-5-1-34/b50f7e9d-55c9-4b80-8386-d982d88856ac

### URL

https://www.home-assistant.io/integrations/unifiprotect/

### Version

2024.11.0

**Comment by DarthDestroyer** [comment]
I would like to join the request.

this is pretty sweet =>https://www.reddit.com/r/Ubiquiti/comments/1godpuz/ubiquiti_home_assistant_elevenlabs/

**Comment by bachp** [comment]
This just got merged https://github.com/home-assistant/core/pull/130840, will be in 2024.12

**Comment by danktankk** [comment]
> This just got merged [home-assistant/core#130840](https://github.com/home-assistant/core/pull/130840), will be in 2024.12

Awesome that this was handled so quickly.  Thank you for that!  

I just installed the latest update for protect and it does have NFC and fingerprint entities, however the fingerprint entity doesn't seem to trigger when I try it in an automation.  Im not sure if it is just me or maybe something else.  Thanks again for adding this.

**Comment by DarthDestroyer** [comment]
> > This just got merged [home-assistant/core#130840](https://github.com/home-assistant/core/pull/130840), will be in 2024.12
> 
> Awesome that this was handled so quickly. Thank you for that!
> 
> I just installed the latest update for protect and it does have NFC and fingerprint entities, however the fingerprint entity doesn't seem to trigger when I try it in an automation. Im not sure if it is just me or maybe something else. Thanks again for adding this.

just check => https://www.home-assistant.io/integrations/unifiprotect/#fingerprint-identified-event

;)

**Comment by danktankk** [comment]
I used the template, but it doesn't appear to work for me.  The if condition always goes to false and doesnt continue.  Thanks anyway though.

**Comment by DarthDestroyer** [comment]
@danktankk yes, it will always be false - you have to set your id in the condition!

easy way: remove the last "AND id in [xxx]" and it will send your own id via message, when you try it out... repeat it and add these keys into the brackets when you add the last AND back into Condition

**Comment by danktankk** [comment]
Sorry for the delayed reply.  I should have read a bit more when I first was setting this up.   This works without any issue now.  Thank you for your help!

**Comment by Sawtaytoes** [comment]
I have these working in my integration, but I was wondering if there's a way to know if the NFC scan was valid like how you can check if a fingerprint is valid.

UniFi Protect allows using any card (including a credit card) for NFC scanning, and it validates your card at the doorbell and even plays a sound indicating if it was valid or invalid including blinking green or red.

Because UniFi Protect knows that user, I think it'd be good to get that validation in Home Assistant rather than trying to check that information myself.

Also, your event has `ulp_id` for fingerprints, but that's missing for NFC scans. UniFi tells you who scanned their card (when valid).

---

Ideally, you'd store all access information in Home Assistant and the Doorbell would validate against that info, but that's just not how it works.
