### ISSUE TITLE
Get maps dont found anymore??

### ISSUE THREAD

**Issue by JuhaFIN1** [home-assistant/home-assistant.github.io#35928]
### Feedback

From Deve tools i cannot find "roborock.get_maps" And if i manually add: 
action: roborock.get_maps
target:
  entity_id: vacuum.roborock_q7_max
i get answer: Action roborock.get_maps not found.

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2024.11.3

**Comment by frenck** [comment]
Hi there @JuhaFIN1 👋 

It seems like you want to report an issue with an Home Assistant integration; however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by JuhaFIN1** [comment]
Ai undestand but I presswd button from this webpage where is wrong data

https://www.home-assistant.io/integrations/roborock/

**Comment by frenck** [comment]
The documentation on this page seems to be correct.

../Frenck

**Comment by JuhaFIN1** [comment]
Not for this get.map thing because it doesn’t work

**Comment by Lash-L** [comment]
@JuhaFIN1 if you are unable to call it, either a) your home assistant is up to date enough or b) your Roborock integration isn't loaded or c) you have the custom component version of Roborock instead of the built in home assistant version

Regardless, Frenck is right and this is not the right issue board for this problem.
