### ISSUE TITLE
Password restriction is not in-line with Reolink

### ISSUE THREAD

**Issue by neketu** [home-assistant/home-assistant.github.io#36193]
### Feedback

I tried adding my 3rd camera to HA this morning but discovered my secure password was too secure for the integration by using what is considered 'incompatible special characters'. I particularly despise this wording and 'flipping the script' on what is an inherent flaw in the HA code, not Reolink or user password selection. I encourage the developer to rethink this and fix their flaw in lack of support for special characters, in essence forcing users to be LESS secure for a device that very much needs the highest level of security due to the nature of what it does. If REOLINK (and other 3rd party tools and NVR devices) support my password, there is no reason why HA integration should not as well.

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2024.12.0

**Comment by starkillerOG** [comment]
See my explanation here: https://github.com/home-assistant/core/issues/123302#issuecomment-2274337355
Closing this issue since it is a duplicate.

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).
