### ISSUE TITLE
Unexpected error when trying to add my Freebox

### ISSUE THREAD

**Issue by julien969a** [home-assistant/home-assistant.github.io#36239]
### Feedback

Hello,

I'm trying to add my Freebox Pop but I got an "Unexpected error" message as soon as I click on "Valider" button.
![image](https://github.com/user-attachments/assets/0f6a5b82-6fea-4a5a-8b10-d473445755ac)

I've set the router as told :
Enable the option “Permettre les nouvelles demandes d’associations” and check that the option “Accès à distance sécurisé à Freebox OS” is active in “Gestion des ports” > “Connexions entrantes”.
But sitll the same problem.

Do you know this error ?

Thank you for your support !
Julies

### URL

https://www.home-assistant.io/integrations/freebox/

### Version

2024.12.1

**Comment by looping40** [comment]
Same version, same config... same error

**Comment by Chartreusito** [comment]
Same here, after a Freebox change, autodiscovery worked but i get the same "unkwown error"

**Comment by git-greatguy** [comment]
Same here with already configured freebox v8.
Sensors became unavailable. Tried to del / readd it, "unknown error".

http request (irrevelant ?) 
`{
    "type": "form",
    "flow_id": "01JEWZ5VAYBP0XY8QK8DJ8A5E5",
    "handler": "freebox",
    "data_schema": [],
    "errors": {
        "base": "unknown"
    },
    "description_placeholders": null,
    "last_step": null,
    "preview": null,
    "step_id": "link"
}`

freebox api version
`"api_version":"12.2","device_type":"FreeboxServer8,1"`

**Comment by voyagers21** [comment]
idem

**Comment by sPioT** [comment]
I face the same problem. Here is what I've found in the log (host and port have been hidden ;) ):

`File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1118, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host *******.fbxos.fr:***** ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Missing Authority Key Identifier (_ssl.c:1020)')]`

**Comment by radouanel** [comment]
I have the same issue but a fix by the integration maintainer seems to be underway https://github.com/home-assistant/core/pull/133455 waiting for it to be merged and released soon 🤞 😄

**Comment by Quentame** [comment]
Created in the wrong repo, you are on the documentation repo

Issue on the right repo: https://github.com/home-assistant/core/issues/132333

Closing because of duplicates, and fixed now, only waiting for the release.

Thanks

----

Pour ceux qui comprennent mal l'anglais:

L'issue créée ici est dans le mauvais repo, ici c'est la documentation d'HA, il faut aller dans core pour le code d'HA/des intégrations.

Lien de l'issue dans le bon repo: https://github.com/home-assistant/core/issues/132333

Je ferme l'issue car dupliqué l'original, en plus elle est corrigée maintenant, en attendant la prochaine livraison.

Merci
