### ISSUE TITLE
Min/Max documentation, low on details

### ISSUE THREAD

**Issue by breeegz** [home-assistant/home-assistant.github.io#36544]
### Feedback

I'm implementing a helper of combined sensors and I attempted to round to the nearest whole number.  My guess, to set  of `Precision` to 0 did not give me a whole number.   
`type = sum`
`name = num_requests`
`Precision = 0` - Gives me 1234.0, I expected I would get a whole number.  If there's a less obvious way to display a whole number I think it needs to be an example in the documentation.  I tried a few different values without getting it to display a whole number.

I am not very strong in HA, but I dabble enough that I think I did it right and the documentation does not tell me otherwise. 

### URL

https://www.home-assistant.io/integrations/min_max/

### Version

2024.12.5

**Comment by gjohansson-ST** [comment]
It returns a float anyhow, precision is just about how many decimals will be handled in the result.
It might not be a bad idea as a feature request that a `0` precision should result in an integer instead but it's out of scope for this issue.

the only way I can imagine is to apply a template sensor on top which is converting your float to an integer and then you can use that.
Secondly you should use group sensor instead of `min_max` as it's more developed --> Feel free to open an issue for it to have an int result.

Closing this from here.
