### ISSUE TITLE
Tradfri component failing to setup

### ISSUE THREAD

**Issue by Zrgisa** [home-assistant/home-assistant.github.io#3855]
Hi all,

When setting up the tradfri component for lights it always fails. Turning on the debug mode revealed that it is constantly getting a 404 Not Found on the setup API call (turned on the debug logger - the component itself seems to be setup ok, I've inserted the security key).

Visiting the IP address via browser gives a response code 470 (I think... it requires auth), from the looks of it, I'd say it is hitting the gateway.

Have you seen this happen before? Any advice on what to do?

Thank you!

P.S. Running this on raspberry pi stretch

**Comment by ferdydek** [comment]
I think you've added issue in wrong repository, this one is for the https://home-assistant.io/ website only. You wanted the `home-assistant` and not `home-assistant.github.io`
Please check if https://github.com/home-assistant/home-assistant/issues/10252 matches your issue or create new one in https://github.com/home-assistant/home-assistant/issues/ .
Please close your issue here.
Thank you

**Comment by Zrgisa** [comment]
Yes, you're right. I'm very sorry about this.

Thank you for pointing me in the right direction!
