### ISSUE TITLE
[Roadmap] Update installation guideline

### ISSUE THREAD

**Issue by c727** [home-assistant/home-assistant.github.io#3929]
**Background**
* discussion on Discord and GitHub #3918 
* https://www.youtube.com/watch?v=s5_dtRoFYyU&feature=youtu.be&t=368

**Tag to use for your PR**
[Install]

* Remove unnecessary stuff
* lead new users to Hass.io, if they reach limitations they should check the alternatives

Todo
- [ ] restructure navigation bar/ sidebar
- [ ] what are the limitations of hass.io, what isn't working

**Comment by DubhAd** [comment]
Rather than directing people just to HassIO, I'm strongly in favour of guiding and informing. Let people know about the "top 3" install methods (HassIO, Hassbian, VENV) and why they might want to chose them (as per Ryan's [draft here](https://github.com/home-assistant/home-assistant.github.io/pull/3918), but more complete).

If we just go "Use HassIO" then there's a strong risk we'll lose the mid ground, only retaining those who just want a Wink/SmartThings/etc replacement, and those who're Docker developers.

**Comment by c727** [comment]
@DubhAd 
The Hassbian docs need some rework before we can add it :stuck_out_tongue_closed_eyes:
