### ISSUE TITLE
"Newest Configuration directions assume Hass.io install, and disregard other platforms

### ISSUE THREAD

**Issue by eldorel** [home-assistant/home-assistant.github.io#4244]
Apparently, 3 days ago, someone edited: 
https://home-assistant.io/getting-started/configuration/

The result of this change is that the initial configuration wizard on a freshly installed (not hass.io) home assistant install is directing users to configurations directions that WILL NOT WORK on that platform. 
```

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        Hello, and welcome to Home Assistant!

        We'll hope that we can make all your dreams come true.

        Here are some resources to get started:

         - Configuring Home Assistant:
           https://home-assistant.io/getting-started/configuration/

~~~~~~~~
```

Specifically, I was using the direct Python install, and these new directions state that there should be a Hass.io menu option that does not exist. 

Considering that 90% of the available installation options on https://home-assistant.io/docs/installation/ do NOT use hass.io, this is going to cause a lot of frustration and confused users.

**Comment by frenck** [comment]
@eldorel Thank you for your feedback, nevertheless, we are working on making Hass.io the default installation method. This to support the more non-tech users for the future.

Nevertheless, other installation methods are offered for people who do have a more technical background.

**Comment by kwlayman** [comment]
Well I just spent a half a day installing/updating debian9 and python3, only to run into the same issue and spend another couple of hours trying to figure out why or how my install failed as it was not showing the specified menu to install addons.

Not a good start. Since now I'm apparently running a soon-to-be discarded version should I even bother to track down the correct instructions?

**Comment by mf-social** [comment]
Having hass.io as the default method is fine, but sabotaging the documentation to make it difficult to do it any other way seems a bit odd tbh.

**Comment by mf-social** [comment]
To clarify my above post before anyone takes it wrong, there's a big difference between whether somebody is a newbie or whether they need to use a different installation method. The two are not necessarily related in any way.

An experienced user will find the right documentation if needed (or work it out from experience), but there will be many users who are new to homeassistant but cannot use hass.io for one reason or another. 

Simple reason might be needing to run something else on the pi for example. 

Another one that I can relate to is that you can't use a razberry Zwave board and Bluetooth tracking at the moment in hass.io as it requires using a USB dongle because the onboard Bluetooth must be disabled to use the razberry. 

Someone may do a lot of research in the forums, decide on a razberry board and Bluetooth dongle approach, and decide to install homeassistant the old fashioned way, this does not make them an advanced user, they are still new to the platform and require decent (easy to follow)  instructions to get started.

It's not as easy as "noobs install hass.io" unfortunately.

**Comment by eldorel** [comment]
@frenck  Regarding the label you added to this issue: This wasn't a question, this was a notification that this IS an issue for potential users.

Even if Hass.io is planned to be the recommended "new default", a new set of directions or moving the existing documentation and changing the "go here to get directions" links in the welcome message would be a much better way to handle that until it's feature set actually IS on par with HA.  

To be clear, I am currently holding off on switching to HA because of this.  
As mf-social said above 'It's not as easy as "noobs install hass.io"' 

I'm far from a "noob" when it comes to automation, linux, or system integration.  I am new to Home assistant however, and have been experimenting with the software for several months while deciding whether or not I can reliably migrate my existing configuration. 

I already have redundant hardware and a dedicated virtualization stack running my automation, so I have no desire to use a Pi, Nuc, or docker instance.
I also have several devices that Hass.io doesn't currently support due to required hardware access.  
So Hass.io is not currently an option for me.

Finding the Hass.io documentation has begun to replace (not augment or displace) the existing documentation was a massive issue for me.  Having the documentation for this "alternative/advanced" install disappear while I'm implementing it is not a problem I plan to deal with.  

Honestly, I've found that this type of disregard for 'legacy' documentation usually implies that the dev doesn't really care about maintaining the existing systems or userbase and that there will be massive system-breaking changes that render future restore/recovery procedures useless.  

Instead, I plan to sit back and see how you handle the transition and then reassess whether or not I want to rely on your software for something as vital as my home security and automation.

**Comment by frenck** [comment]
Ooh my, those replies contain pretty strong expressions.

Every change comes with pro and cons, as an result there will always happy and less happy people. The issue at hand, we have a lot of new "less technical" users in our fast growing user base, we need to support.

@eldorel You are right, the URL is wrong. I labeled the issue as an question because of two thing.

1. You do not seem to be able to find the appropriate documentation, which is a question imho. Let me help you on this one: https://home-assistant.io/docs/configuration/

1. The URL is wrong the first time you'll start. I will look into a fix for this. To support this, I've also added the bug label.

Does this satisfy your intents?

I you guys find anything that needs to be corrected, feel free to contribute and place a pull request.

**Comment by mf-social** [comment]
^That was my first thought, I could probably add a line here or there to try and clear things up.  I've edited a few pages before for clarity and written guides and stuff, it's nice to give something back (especially when you don't understand python so can't help out with components and bugs and stuff). 

The reason I didn't is because it kinda looks like the getting started section is in the middle of some kind of transition and I didn't want to get in the way. 

Is there like a todo list somewhere so I can see where the documentation is heading towards so I don't waste ages putting paragraphs here and there that will be irrelevant in a week when somebody else who is clued up with the plan moves the pages to a separate section?

Or is there no real plan other than the drive towards orienting Getting Started towards hass.io, and that's how we ended up here?
