### ISSUE TITLE
USPS Component listed but broken

### ISSUE THREAD

**Issue by vidvisionify** [home-assistant/home-assistant.github.io#4260]
https://community.home-assistant.io/t/usps-authentication-failed/30720

This component has been broken for over a month, shouldn't there be some sort of warning on the component pages?

**Comment by fabaff** [comment]
We should only add a warning/note if there is no workaround/solution available. It look like that people are working to resolve the issue and start tracking it in the docs in addition to the issue tracker would add extra work.

**Comment by frenck** [comment]
I'm closing your issue since it looks misplaced. This is the issue tracker for the Home Assistant Documentation & Homepage. The documentation reflects the code base, which is still accurate.

Please report technical Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration, and usage.

Thanks!
