### ISSUE TITLE
Fritz! presence detection requires password for firmware 6.87

### ISSUE THREAD

**Issue by swhaat** [home-assistant/home-assistant.github.io#4388]
I used the FRITZ! presence detection with the defaults (no password) system for some time without a problem.
I updated my FRITZ!Box router from firmware 6.85 to 6.87 and the presence detection stopped working.. I added username: admin and my password to the configuration file and presence detection worked again.
It seems the FRITZ! component does not work by without credentials anymore.
Maybe a note on the component page would be required if this is indeed the case.

**Comment by frenck** [comment]
I'm closing your issue since it looks misplaced. This is the issue tracker for the Home Assistant Documentation & Homepage. 

Please report technical Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration, and usage.

Thanks!
