### ISSUE TITLE
Xiaomi Gatway light can't be turned on from app if turned off from HA last

### ISSUE THREAD

**Issue by AbFarid** [home-assistant/home-assistant.github.io#4416]
If the Gateway light is turned off using HA, it's impossible to turn it back on any other way (from app, wireless switches and not event with its own button on top), until it's turned back on using HA (or plugged off/on), then it can be turned off and on using other methods.

**Steps to replicate:**
1. From HA: turn ON the light
2. From HA: turn OFF the light
3. Using the button on top, a wireless switch or from phone: try to turn ON the light

A little more investigation showed that if the brightness is changed from the app, the light will turn on again.

**Comment by frenck** [comment]
I'm closing your issue since it looks misplaced. This is the issue tracker for the Home Assistant Documentation & Homepage. 

Please report technical Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration, and usage.

Thanks!
