### ISSUE TITLE
Avahi Support

### ISSUE THREAD

**Issue by sam-wright** [home-assistant/home-assistant.github.io#4419]
I just finished writing a handful of media_component automations and really was missing the ability to use the avahi naming, rather than the full ip when pointing towards my local media. I've had the same thought other places, such as pointing towards my zoneminder instances, etc... 

In short, it would be nice to say:
`  media_content_id: http://vault.local/local/Fireplace.mp3`
and
`zoneminder:`   
`   host: zoneminder.local`

rather than:
`  media_content_id: http://192.168.1.150:8123/local/Fireplace.mp3`
and
`zoneminder:`
 `  host: 192.168.1.175`

Most of my computers have static IPs, but its still annoying to have to remember them and type them out.

Just a thought

**Comment by frenck** [comment]
I'm closing your issue since it looks misplaced. This is the issue tracker for the Home Assistant Documentation & Homepage. 

Please report technical Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration, and usage.

Thanks!
