### ISSUE TITLE
Google Assistant Guide is outdated

### ISSUE THREAD

**Issue by lal12** [home-assistant/home-assistant.github.io#4824]
Hello,

I was able to create a test app without creating the project.json and uploading it with gactions. 
Now it is possible to create a Smart Home Project directly, as you can read here: https://developers.google.com/actions/smarthome/create-app

**Comment by c727** [comment]
What about you edit the docs?

**Comment by lal12** [comment]
Planned on doing so, just wanted to hear if there is some reason, for not doing so. E.g. less customizability. At least I didn't encounter any.

**Comment by c727** [comment]
I think nobody noticed it so far^^

**Comment by cogneato** [comment]
I walked through the new directions and everything works as before. I had two minor suggestions to make for #4853 which I submitted. Also, the page has changed since PR #4853 was made to account for [#12959](https://github.com/home-assistant/home-assistant/pull/12959) and [#13030](https://github.com/home-assistant/home-assistant/pull/13030)

**Comment by cogneato** [comment]
Noticing this wasn't closed. Page has been updated with new instructions. Thanks, @lal12!
