### ISSUE TITLE
Add "AntiFeatures" categories to component listings

### ISSUE THREAD

**Issue by arthurlutz** [home-assistant/home-assistant.github.io#6402]
First off : kudos to home-assistant and it's brilliant ecosystem. I'm a big fan. 

Second : I know this might be a controversial feature request for the web site, I am hoping that this will be a constructive discussion on how we can provide useful information to existing and potential users of home-assistant. 

My feature request is the following : it would be awesome to have some way of categorising and listing components according to the following question "does the component use an external non-free service?" "does the component rely on closed source hardware?" "does the component download and use non-free software to work?"

The closest type of approach I can think of (thus the title of the issue) is the categories provided by fdroid https://f-droid.org/ (a FLOSS alternative to Google Play for android)  https://f-droid.org/wiki/page/Antifeatures

I think the following "flags" can get us starting the discussion : 

* Non-free Network Services 
* Non free Dependencies
* Tracking 
* FLOSS web services needed (possibility of self-hosting) 

As a side note : maybe there could be a "flag" such as "Requires registration of a web service". 

One example : network speed probing : 

* fast.com : Non-free Network Services 
* speedtest.net : Non-free Network Services 
* iperf3 : FLOSS web service

I can think of a bunch more examples, but I'll stop there for conciseness.

**Comment by timmo001** [comment]
I guess this could be done with labels similar to how GitHub works.

Not sure if this is a definite, but I know there is a PR for migrating the site to Hugo. #5744 

From that, Hugo has a feature known as [taxonomies](https://gohugo.io/content-management/taxonomies/) which are essentially tags. We could probably throw in a bunch of tags for each component like `non-free`, `3rd-party`, `self-hosted`, `diy` etc.

**Comment by fabaff** [comment]
This topic was coming up a few times in the past but was never implemented. The reasons are manifold. The biggest blocker is that there are no resources to perform reviews to categorized existing  integrations and check it for new ones. Even if we limit it to everything that is communicating at the moment with a third-party web service (sensors and notifications) are we talking about approx. 100 integrations (I'm guessing). There will be only value for the users if the coverage over the integrations is large. I doubt that a lot of users care about a "Non-free Network Services" as long as the usage is free. And those who cares will probably be capable to figure out an alternative.

Also, for contributors it must be super easy to determine if the integrations is a match for the particular flag. This means that "Non free Dependencies" and "Tracking" are not really practicable because it would require that a license review is performed and the network traffic analysed in detail.

I see `3rd-party`, `self-hosted` and `requires-registration` as additional categories. `diy` is already there. 

The technical aspect to do it is not an issue as we are doing it already for the overview grouping.

**Comment by arthurlutz** [comment]
I intend to work on this at some point.

**Comment by arthurlutz** [comment]
dear @stale I'm going to work on this.

**Comment by arthurlutz** [comment]
Am looking into using icons from font awesome : 

* opensource https://fontawesome.com/icons/osi?style=brands
* cloud https://fontawesome.com/icons/cloud?style=solid
* registration-required https://fontawesome.com/icons/sign-in-alt?style=solid
* proprietary https://fontawesome.com/icons/door-closed?style=solid

**Comment by frenck** [comment]
@arthurlutz I've responded on your PR and thinking about closing the PR. Please see: https://github.com/home-assistant/home-assistant.io/pull/8498#issuecomment-462722672

**Comment by balloob** [comment]
https://github.com/home-assistant/home-assistant.io/pull/8498#issuecomment-462849329
