### ISSUE TITLE
New thermostat lovelace card doesn't play well with themes

### ISSUE THREAD

**Issue by marciogranzotto** [home-assistant/home-assistant.github.io#7290]
The new thermostat card on lovelace is awesome. But it doesn't play well with dark themes.
I'm including an image of the cards with the default theme and other with the dark theme that I use.

<img width="448" alt="screen shot 2018-10-31 at 02 06 30" src="https://user-images.githubusercontent.com/11080704/47767297-bd6a9100-dcb1-11e8-9de5-a0938838d3ff.png">
<img width="446" alt="screen shot 2018-10-31 at 02 06 14" src="https://user-images.githubusercontent.com/11080704/47767298-bd6a9100-dcb1-11e8-9203-b5300c90ed27.png">

**Comment by HadiHassaoui** [comment]
I have a small glitch in the thermostat card. When the background of the card has transparency (ex: rgba(0, 0, 0, 0.6), since the "diamond" that mask the bottom part of the gauge use the same color in the theme file "paper-card-background-color", the result is not pretty.

See the PNG attached for what I'm saying....
![capture d ecran 2018-11-13 00 07 12](https://user-images.githubusercontent.com/27429281/48392704-6bc2fd00-e6da-11e8-8a62-de31d282c7bc.png)

**Comment by frenck** [comment]
@HadiHassaoui Thanks for your response, but as listed above, this issue has been moved.
Please respond on the correct issue.
