### ISSUE TITLE
Default Media Control Next Track Google Home issue

### ISSUE THREAD

**Issue by dustins1983** [home-assistant/home-assistant.github.io#7802]
When using google home and listening to pandora the pause button works, but I cannot use the next track button to change songs. It calls the service but nothing happens

**Comment by frenck** [comment]
I'm closing your issue since it looks misplaced. This is the issue tracker for the Home Assistant Documentation & Homepage. 

Please report technical Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration, and usage.

Thanks!
