### ISSUE TITLE
Update privacy policy to mention Google Analytics, Algolia, Cloudflare and JSDelivr

### ISSUE THREAD

**Issue by arthurzenika** [home-assistant/home-assistant.github.io#8577]
The current version of the documentation uses a number of third parties to serve assets or services. I think these services should be mentioned in the privacy policy.

![screenshot from 2019-02-14 18-58-47](https://user-images.githubusercontent.com/445200/52807478-dd209c00-308b-11e9-8474-90eae0b8252a.png)

Services used : 

* Google Analytics
* Algolia
* Cloudflare
* jsdelivr
* netlify

**Comment by arthurlutz** [comment]
ping

**Comment by arthurlutz** [comment]
this is still an issue

**Comment by frenck** [comment]
The privacy policy has been reviewed and adjusted where needed.

**Comment by arthurlogilab** [comment]
Great news. @frenck thanks for taking a look at this issue and fixing some things. 

I now find mention of "Google Analytics" in the https://www.home-assistant.io/privacy/ document. A few things are still missing from my point of view : mention of the other services used, for example links to https://www.algolia.com/policies/privacy/ and https://www.netlify.com/privacy/

Another note : it's a shame that the changelog doesn't mention a recent change. (since this is in git we could even imagine a link to the merge request which serves as a great way to show transparency on those issues).

**Comment by arthurlutz** [comment]
Great news. @frenck thanks for taking a look at this issue and fixing some things. 

I now find mention of "Google Analytics" in the https://www.home-assistant.io/privacy/ document. A few things are still missing from my point of view : mention of the other services used, for example links to https://www.algolia.com/policies/privacy/ and https://www.netlify.com/privacy/

Another note : it's a shame that the changelog doesn't mention a recent change. (since this is in git we could even imagine a link to the merge request which serves as a great way to show transparency on those issues).

**Comment by frenck** [comment]
@arthurlogilab First of all, I did not update it. I merely closing the issue as an effort to keep things clear in the issue tracker.

It was reviewed and adjusted to what was needed.

The changelog mentions it, this is git, commits are our changelog (for docs & website). Secondly, a link to the merge request is in this issue request as well.
