### ISSUE TITLE
Links broken in components pages.

### ISSUE THREAD

**Issue by eliseomartelli** [home-assistant/home-assistant.github.io#8619]
The links are broken on the components pages.

Some examples:
https://www.home-assistant.io/components/media_player.emby/
points at:
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/emby/media_player.py
but it should be:
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/media_player/emby.py

**Comment by fabaff** [comment]
I think that @frenck knows the current state of the changes to make the links work again.

**Comment by klaasnicolaas** [comment]
This is something that is being worked on, more people have opened that same type of issue.

**Comment by klaasnicolaas** [comment]
let's use this issue for discussion, I notice that many people are going to open issues that are about the same. You can better respond to this issue.

**Comment by peternijssen** [comment]
Just noticed the same thing in the following pages:
https://www.home-assistant.io/components/sensor.buienradar/
https://www.home-assistant.io/components/weather.buienradar/

**Comment by hmmbob** [comment]
> Just noticed the same thing in the following pages:
> https://www.home-assistant.io/components/sensor.buienradar/
> https://www.home-assistant.io/components/weather.buienradar/

Lol, that's how I came into this issue - noticed the same while I was fixing a key error for the buienradar sensor

**Comment by nikolak** [comment]
Note that also (all?) binary sensors have invalid links:

For example

https://www.home-assistant.io/components/binary_sensor.template/

https://www.home-assistant.io/components/binary_sensor.trend/

https://www.home-assistant.io/components/binary_sensor.bayesian/

https://www.home-assistant.io/components/binary_sensor.iss/

The docs structure points to e.g:

`/components/trend/binary_sensor.py`

While the real path is in [`/components/binary_sensor/`](https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/binary_sensor)`filename.py`

In general there seems to be a lot of broken links, should I write a quick script to find them all, or is this something that's already known or otherwise unecessary?

Since this is being worked on I'm assuming that there is some work done, or are contribtions still welcome?

**Comment by frenck** [comment]
## ⚠️ Please DO NOT add all the broken links you can find to this issue.

The links are generated and currently we know which links break and why.
The breakage is caused by [The Great Migration](https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html) in our code base.

I've added a couple of fixes to make them work in around 80% of the cases.

**Comment by frenck** [comment]
The great migration on the code-base has been finished, this means all links now work as expected (including all listed above).

🎉
