### ISSUE TITLE
Updated documentation for Daikin

### ISSUE THREAD

**Issue by fredrike** [home-assistant/home-assistant.github.io#9133]
The PRs #9033 should have reached the documentation of 0.91.

**Comment by frenck** [comment]
@fredrike According to Git the following PR's are currently on `current`: #9100 #9040.
So regarding those 2, I'm not sure what is wrong with them?

#9033 is indeed not on current, which is weird. I'm looking into why this happened.
Instead of making the PR #9134 against `current`, shouldn't we just cherry-pick #9033 to `current`?

**Comment by fredrike** [comment]
> Instead of making the PR #9134 against current, shouldn't we just cherry-pick #9033 to current?

Yes but there are merge conflicts for #9033, the #9134 outdates #9033.

**Comment by frenck** [comment]
#9033 is already merged, so #9134 would inevitably create a merge conflict when syncing our main branches...

**Comment by fredrike** [comment]
Could the #9033 be cherry picked into the `current` branch and I'll rebase #9134 against that (as you can see, I changed quite some text in that pr).

**Comment by fredrike** [comment]
What is the status on this?

**Comment by fredrike** [comment]
Closed by #9134
