### ISSUE TITLE
Strange navigation experience  /docs/ and /lovelace/

### ISSUE THREAD

**Issue by nickma82** [home-assistant/home-assistant.github.io#9443]
For me as a HA beginner it was hard to realize the difference between the "[*lovelace docs*](https://www.home-assistant.io/lovelace/)" and "[*all the other docs*](https://www.home-assistant.io/docs/)". 

What confused me:
* the changing (right) navigation menu when one switches between the "*lovelace docs*" and "*all the other docs*"
  * No link in both of the navigation menus to easily switch over
* the only link to the "*lovelace docs*" I found was right at the [docs root page](https://www.home-assistant.io/docs/) (took me quite a while to memorize the place)

**Comment by frenck** [comment]
I agree this part of the navigation could be improved significantly.

Thanks for you suggestion.

**Comment by bschatzow** [comment]
I am also a fairly new user of Hassio / home-Assistant and am also have been confused with the documentation and lack of consistency. An example is how code is entered in the raw UI vs a manual card.  
I have seen conflicts between documents (install vs the help docs, MQTT for example).  I see this as another reason why you have switched to Lovelace.yaml as this keeps you at one document type.  I'm not there yet.

It would be helpful if when a new method or update is released (automation for example) some documentation is released or links to the necessary method is added.  For example there is no place showing how to enter time.  For new users, easy stuff should be easy.   I understand all of this is searchable, but it could be a lot easier.  Automations is a key component to most peoples HA and this needs a lot of help to make it easier for new users.

As a retired EE (owned an Aerospace Power company) I am very familiar with methods and I am willing to help.  

I very much understand this is an open source community and documentation is sometimes very slow, but some easy fixes would be to implement document dates and a revision system.  This way a user can see which is the latest documentation and follow it.  Also a methods sheet should be created so that all the contributors follow the same method in creating documents.  This way once you understand one document and how it is presented, new documents will not have a large learning curve.

**Comment by frenck** [comment]
We have started some restructuring to address this. More docs will be put into their own section (like lovelace). Right now installation has moved like that.

Additionally, we've extended the menu to get around easier:

![image](https://user-images.githubusercontent.com/195327/107765683-8e697380-6d32-11eb-8891-b68c4562fe97.png)
