### ISSUE TITLE
Could the Sense HAT documentation be updated for Hass.io

### ISSUE THREAD

**Issue by menant** [home-assistant/home-assistant.github.io#9691]
Could the documentation page for Sense Hat ([https://www.home-assistant.io/components/sensehat/ ](url)) be updated for Hass.io?

I installed Hass.io on top or Raspbian following this documentation [(https://github.com/home-assistant/hassio-installer)](url) and I'm missing important steps. Troubleshooting has been unsuccessful due to my limited knownledge of Hass.io internals and its permission system...

**Comment by frenck** [comment]
@menant I do agree on improvements can be made here. Nevertheless, we as maintainers don't know everything as well since integrations and documentation is contributed. For example, I don't use the sensehat and have no clue what it is.

To me, it sounds like a bug in the first place.

Please file an issue on https://github.com/home-assistant/home-assistant/issues

Thanks!

../Frenck
