### ISSUE TITLE
Documenation Update - Apple TV Component tvOS13

### ISSUE THREAD

**Issue by SauRoNZA** [home-assistant/home-assistant.github.io#9898]
Just a request that someone with access please update the https://www.home-assistant.io/components/apple_tv/ page to make a big bold note that this no longer works on tvOS13.

**Comment by frenck** [comment]
Everybody has access. Feel free to open up a pull request! 👍

**Comment by SauRoNZA** [comment]
> Everybody has access. Feel free to open up a pull request! 👍

Okay, let's see if my n00b ass can figure that out.

THanks.

**Comment by SauRoNZA** [comment]
Nah, not going to happen, I've got no idea how this is meant to work.

A simple edit page here would have been nice. :)

Github maybe not the best place for those of us who can document, but not code.

**Comment by frenck** [comment]
There is an edit button on every single page on the top. There is no coding experience required to use GitHub.

**Comment by SauRoNZA** [comment]
> There is an edit button on every single page on the top. There is no coding experience required to use GitHub.

The only edit button I have is an "edit in fork" one which I'm sure isn't the right thing?

**Comment by SeanPM5** [comment]
At the top of each page on the Home Assistant website you'll see an "Edit this page on GitHub" link.

Click that and it will take you to the `apple_tv.markdown` page on Github.

Then you will want to click the "Pencil" icon / edit in fork.

You'll see a blue box at the top which says something like "You’re editing a file in a project you don’t have write access to. Submitting a change to this file will write it to a new branch in your fork SauRoNZA/home-assistant.io, so you can send a pull request." 

That is the part that I think confuses or scares most people off. But don't worry about that message and make the changes you want to the file - you can preview it etc. Very similar process if you've ever edited a Wiki before.

At the bottom of this page you'll see a `Propose file change` section, which again works similar to if you've edited Wiki's before. It just wants you to put a very brief edit summary of what you've changed. In this example you'd put something like "Adding note that AppleTV integration is incompatible with tvOS13" .

Hit the green "Propose File Change" button.

Now you'll be on a "Comparing changes" screen where you can see what you've done. Deletions will be highlighted in red and additions/changes will be highlighted in green. If you missed something you can go back and fix it, but otherwise if this looks good, hit the green "Create pull request" button at the top. (Don't worry about the dropdown menu stuff above it, the default settings of `base: current` should be fine).

After you hit the "Create pull request" button you'll get the summary screen one last time where you can preview your changes etc. Submit it and that's it, you're done. Someone with write access will review your changes and approve it usually within a few days.

Hope this helps. It's not as hard as it seems at first, and helping with documentation is a great way to contribute to the project.

**Comment by frenck** [comment]
Closing this issue, since we have introduced Home Assistant alerts that integrate with the Documentation.

For tvOS13 an alert has been issued.
